### ISSUE TITLE
Enhance i3wm.org py3status page

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#1010]
https://i3wm.org/docs/user-contributed/py3status.html

- doc links are wrong
- we could use an animated GIF
- we can do better

**Comment by lasers** [comment]
I finished this. I'd like to know what you mean by `we can do better`.
I cleaned up everything, added the animated GIFs... and a pink font.
I'm not sure what else we should add. Let me know. Thx.

[lasers-html.zip](https://github.com/ultrabug/py3status/files/1272084/lasers-html.zip)

**Comment by ultrabug** [comment]
closing here, we now have an open PR for this
