### ISSUE TITLE
Profiling py3status

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#1038]
While looking at py3status performance I found I needed a tool to help so I created https://github.com/tobes/py3status-profiler

Currently it's a little clunky but it does the job for me.

Having it separate from py3staus allows testing of old versions etc.

This issue is just to let people know of its existence.

**Comment by lasers** [comment]
```
# pprofile
Running tests for 10 minutes.     
[██████████] 100.00%  10:00  (22.12)   
user 21.41s
system 0.71s
total 22.12s
```
```
# vmprof
Running tests for 10 minutes.     
[██████████] 100.00%  10:00  (2.10)
user 1.77s
system 0.33s
total 2.1s
```
```
# cprofile
Test terminated.
```
