### ISSUE TITLE
New module - static_string

### ISSUE THREAD

**Issue by frimdo** [ultrabug/py3status#105]
Extremely simple [module](https://gist.github.com/frimdo/4020e56d9ac08b2bf6c3) solving problems with not finished formatting of output of modules and multicoloring output. :-)

**Comment by ultrabug** [comment]
Thanks @frimdo, could you please fork and make a proper pull request for both your proposals ?

This would allow me to comment on the code for review and also have you listed as a contributor of py3status !

Cheers

**Comment by ultrabug** [comment]
this module was added in your PR, closing
