### ISSUE TITLE
mpd_status creates a new socket connection every second

### ISSUE THREAD

**Issue by girst** [ultrabug/py3status#1090]
I'm not sure if this should be a bug report or a feature request, but I've been bitten by this, erm, _feature_: I use `mopidy` (mpd with spotify integration) and that gets confused when a request comes in from `mpd_status` while it processes a mpd-command-block. 

This also keeps a lot of abandoned connections in `TIME_WAIT` state - 60 currently at my system. 

I've had a quick look at the code for this module, and the connection i s esatablished in `current_track()`. I do not know if it is possible, but the best apporach (IMHO) would be to `connect()` once and keep the socket alive until `py3status` gets reloaded.

**Comment by tobes** [comment]
@girst it's not a module I use, but if you have a patch that fixes this that would be great

**Comment by girst** [comment]
my python is very rusty. I've made some progress, but then broke it again somehow. do you have any idea why i could get the following error (when launching the `mpd_status.py` manually)?

```
response should be a dict (TypeError) module.py line 763.
Traceback
TypeError: response should be a dict
  File "/usr/lib/python3.6/site-packages/py3status/module.py", line 763, in run
    raise TypeError('response should be a dict')
```

I've found no way to attach a patch, so there it is:

```
diff --git a/py3status/modules/mpd_status.py b/py3status/modules/mpd_status.py
index 65af95b..264f4c1 100644
--- a/py3status/modules/mpd_status.py
+++ b/py3status/modules/mpd_status.py
@@ -110,6 +110,20 @@ class Py3status:
     state_play = '[play]'
     state_stop = '[stop]'
 
+    c = None
+
+    def mpdc(self):
+        if self.c is None:
+            self.c = MPDClient()
+            self.c.connect(host=self.host, port=self.port)
+            if self.password:
+                self.c.password(self.password)
+        return self.c
+
+    def mpd_disconnect(self):
+        self.mpdc().disconnect()
+        self.c = None
+
     def post_config_hook(self):
         # Convert from %placeholder% to {placeholder}
         # This is not perfect but should be good enough
@@ -128,12 +142,7 @@ class Py3status:
 
     def current_track(self):
         try:
-            c = MPDClient()
-            c.connect(host=self.host, port=self.port)
-            if self.password:
-                c.password(self.password)
-
-            status = c.status()
+            status = self.mpdc().status()
             song = int(status.get('song', 0))
             next_song = int(status.get('nextsong', 0))
 
@@ -144,7 +153,7 @@ class Py3status:
                 text = ''
 
             else:
-                playlist_info = c.playlistinfo()
+                playlist_info = self.mpdc().playlistinfo()
                 try:
                     song = playlist_info[song]
                 except IndexError:
@@ -170,9 +179,10 @@ class Py3status:
         except CommandError:
             text = "Failed to authenticate to mpd!"
             state = None
-            c.disconnect()
-        else:
-            c.disconnect()
+            #c.disconnect()
+            self.mpd_disconnect()
+        ##else:
+            #c.disconnect()
 
         if len(text) > self.max_width:
             text = u'{}...'.format(text[:self.max_width - 3])

```

**Comment by lasers** [comment]
```
     def current_track(self):
```
... it should be `def mpd(self):`... 
```
+    def mpd_disconnect(self):
+    def mpdc(self):
```
... it should be `def _mpd_disconnect(self):`... 
... it should be `def _mpdc(self):`... 

We allow one method for the loop... and that method can be named anything... In this case, `current_track` is being used here in the loop. Other methods need to start with `_` except for few special methods: `post_config_hook`, `kill`, `on_click`.

I think ideally, we should name the method after the module... is which why I said... it should be `def mpd(self):` above... then just add the missing starting underscore for any methods you want to make.

Scroll down a bit. Look for special methods. http://py3status.readthedocs.io/en/3.6/writing_modules.html#module-methods

**Comment by girst** [comment]
so, it's 5:13 here. I've fixed the underscore issue (the hell!?!). I have __NOT__ done any testing yet, but I'll post my patch, since I don't  want to lose it. 

when run either directly or with `python3 -m py3status.__init__` it opens one connection and keeps using that one (assuming mpd/mopidy/etc is already running -- again, no testing yet)

```
diff --git a/py3status/modules/mpd_status.py b/py3status/modules/mpd_status.py
index 65af95b..d479521 100644
--- a/py3status/modules/mpd_status.py
+++ b/py3status/modules/mpd_status.py
@@ -110,6 +110,20 @@ class Py3status:
     state_play = '[play]'
     state_stop = '[stop]'
 
+    c = None
+
+    def _mpdc(self):
+        if self.c is None:
+            self.c = MPDClient()
+            self.c.connect(host=self.host, port=self.port)
+            if self.password:
+                self.c.password(self.password)
+        return self.c
+
+    def _mpd_disconnect(self):
+        self._mpdc().disconnect()
+        self.c = None
+
     def post_config_hook(self):
         # Convert from %placeholder% to {placeholder}
         # This is not perfect but should be good enough
@@ -128,12 +142,7 @@ class Py3status:
 
     def current_track(self):
         try:
-            c = MPDClient()
-            c.connect(host=self.host, port=self.port)
-            if self.password:
-                c.password(self.password)
-
-            status = c.status()
+            status = self._mpdc().status()
             song = int(status.get('song', 0))
             next_song = int(status.get('nextsong', 0))
 
@@ -144,7 +153,7 @@ class Py3status:
                 text = ''
 
             else:
-                playlist_info = c.playlistinfo()
+                playlist_info = self._mpdc().playlistinfo()
                 try:
                     song = playlist_info[song]
                 except IndexError:
@@ -170,9 +179,7 @@ class Py3status:
         except CommandError:
             text = "Failed to authenticate to mpd!"
             state = None
-            c.disconnect()
-        else:
-            c.disconnect()
+            self._mpd_disconnect()
 
         if len(text) > self.max_width:
             text = u'{}...'.format(text[:self.max_width - 3])
```

**Comment by lasers** [comment]
`def kill()` can be useful for disconnecting socket too. My computer is dirty. Can't initialize `mpd` without getting errors, assertions, etc. I could go through #856 again when #1005 get merged... along with your socket patch.

**Comment by girst** [comment]
"good" morning. was rudely awaken by the landlord. 

Progress: bugs seem good so far, on a slightly improved version. However...

I found another bug in the current/old `mpd_status` implementation. if you only have this module active, it doesn't refresh. On the other hand, if you've got e.g. `tztime`(clock) active, which fires more often than mpd_status should, mpd_status fires every second.    
@lasers -- you've got an idea?

also, what do you mean by "`def kill()` can be useful?" Do you mean, a method inside the class named `kill()` will be called on exit?

**Comment by lasers** [comment]
>I found another bug in the current/old mpd_status implementation. if you only have this module active, it doesn't refresh. On the other hand, if you've got e.g. tztime(clock) active, which fires more often than mpd_status should, mpd_status fires every second.

You described this better than my vague _"Hey. Something's wrong with this"_. I'm pretty sure that's https://github.com/ultrabug/py3status/issues/1023 and had nothing to do with `mpd_status`. If you find something more, share it there.

>also, what do you mean by "def kill() can be useful?" Do you mean, a method inside the class named kill() will be called on exit?

Yup. I wonder if we want to have a thread here to keep socket alive too.

**Comment by tobes** [comment]
With the refresh issue it may be worth waiting for some PRs like #1030 that may end up fixing things.

**Comment by girst** [comment]
ok then; i'll submit a pull request shortly. it'll only include 
 * keeping the socket alive (`mpdc()`)
 * closing the socket in `kill()`

**Comment by girst** [comment]
https://github.com/ultrabug/py3status/pull/1093

comments please!
