### ISSUE TITLE
Add CACHE_FOREVER option for cache_timeout

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1115]
Add `CACHE_FOREVER` option for cache_timeout

```
    cache_timeout = CACHE_FOREVER
    cache_timeout = -1
```

Modules should have this option to run once as I think it is not nice  if we keep `CACHE_FOREVER` exclusive to the code. The alternative is to use a larger number, eg `3600` (an hour)... which is something many users sometimes will use as there is no choice.... Some users even may incorrectly use `0` too thinking it mean `None` or `once`.

Some users may be content with... or prefer to... run something once and this could be good for performance since we don't have to `% 1` the rest... so maybe less modules to check for.

Good candidates... air_quality, diskdata, aws_bill, bitcoin_price, coin_balance, coin_market, etc. Excellent candidiates... external_script, get_json, randr, xrandr_rotate, etc.

In the future, I may want `keyboard_locks` to have `CACHE_FOREVER` too and have the other module to update `keyboard_locks` instead.

**Comment by tobes** [comment]
This issue is actually about the timeout on errors.  It is a good example of a badly worded issue.

maybe adding the option to the config would be an option but it is difficult to do well I think.

**Comment by tobes** [comment]
Sorry was confused.  This might be hard as `setting = something` I believe gets interpreted as  `setting = "something"` by the parser.

I'll have a look at some point as I want to see weather we can enable re-writing of the config file for deprecated options etc.

**Comment by lasers** [comment]
>enable re-writing of the config file for deprecated options etc.

Also, consider something like `getjson: use post_config_hook` where you described `self.py3.missing_config(['url'])`... but for the old placeholders... If it's caught, it can notify the user to update the format for the module in question... because https://github.com/ultrabug/py3status/pull/878 consists of 1/5 turning into the new format, 1/5 parsing the json, 1/5 supporting the old deprecation, and 1/5 supporting time conversion and 1/5 color stuffs that can be deprecated.

**Comment by lasers** [comment]
Fixed by https://github.com/ultrabug/py3status/pull/1260. This is great. Thanks. :hourglass:
