### ISSUE TITLE
Travis CI to plead temporary insanity

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1128]
... for breaking #1014, #1075, and #1026... and more if I were to keep going.

**Comment by tobes** [comment]
yeah travis can be a pain sometimes

it should be sorted in a day or two

**Comment by ultrabug** [comment]
Sorry I don't understand what you guys mean here?

**Comment by lasers** [comment]
Travis is failing everyone in the class.

https://github.com/ultrabug/py3status/pull/961: add new module: gcal
https://github.com/ultrabug/py3status/pull/1014: add new module: void_updates
https://github.com/ultrabug/py3status/pull/1026: rate_counter: rename, merge formats, add buttons, optimize, cleanup
https://github.com/ultrabug/py3status/pull/1068: added google calendar module
https://github.com/ultrabug/py3status/pull/1088: Clear clipboard onclick and optional log (xsel)
https://github.com/ultrabug/py3status/pull/1107: taskwarrior: new module made from scratch
https://github.com/ultrabug/py3status/pull/1116: apt_updates: new module made from scratch
https://github.com/ultrabug/py3status/pull/1117: net_iplist: new module made from scratch
https://github.com/ultrabug/py3status/pull/1126: github: remove the trailing slashes
https://github.com/ultrabug/py3status/pull/1127: volume_status: check the binaries
https://github.com/ultrabug/py3status/pull/1129: bitcoin_price: use helpers
https://github.com/ultrabug/py3status/pull/1130: process_status: use post_config_hook
https://github.com/ultrabug/py3status/pull/1131: process_status: clean up the docs
https://github.com/ultrabug/py3status/pull/1132: keyboard_locks: merge formats

**Comment by JohnAZoidberg** [comment]
They all fail because of the same thing. Flake8 introduced some new warnings/errors `E722 do not use bare except`. These all have to be resolved before any test will pass again.
