### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by Artlant** [ultrabug/py3status#1141]
hi!
I found two errors. I do not know if they are connected. because I will publish in one issue

my OS
`Linux 4.13.9-1-ARCH`
ver pyi
`local/py3status 3.6-1`

description of the problem:
1) I'm using my own `deadbeef` output script, since I'm listening to radio stations and I need to cut out text in square quotes (example:
 `regex [*]$`).
I wanted to process the standard output (example `output | awk)` but it did not work.
The essence of the error is that the output color of this block is always red. Override by `color =` does not work
![screenshot from 2017-10-31 20-42-27](https://user-images.githubusercontent.com/13064767/32242741-3ee3d818-be7c-11e7-8fcb-3c49d407290a.png)

2)
There is another script. It prints `xprop WM_CLASS` instead of the standard one where `window_title` is displayed.
If to output through a file (`script_path =`) that it is deduced
If through `command=` that is deduced but sometimes at absence of windows the warning from which I can not get rid is deduced.
![screenshot from 2017-10-31 20-41-43](https://user-images.githubusercontent.com/13064767/32242782-54eeeed6-be7c-11e7-9f49-caa70e4ebdef.png)

The question is why the 2 script is not executed and the first color does not change?

Also there are certain problems with the processing of commands there is a symbol ` (tilda)

ps 
[conf.zip](https://github.com/ultrabug/py3status/files/1431899/conf.zip)

**Comment by lasers** [comment]
My findings...

1) I can't tell what you're trying to do here. Too many `deadbeef` modules.

    a) `deadbeef {}`
    b) `i3block deadbeef {}`
    c) `external_script deadbeef {}`

   If you can tell how to reproduce `py3status`-issued `deadbeef` radio station along with URL, etc...  I could look into why it's printing red... as I looked at the code and can't see how it can happen... I think it may had nothing to do with our `deadbeef` and more to do with your `deadbeef.sh` in `external_script`. That and `deadbeef` can be funny with error codes sometimes. Read our `deadbeeef` code to find this.
    ```
            # Starting deadbeef may generate lot of startup noises either
            # with or without error codes. Running command below may sometimes
            # change how things behaves onscreen. We use subprocess to ignore
            # error codes. We use pgrep and hidden placeholders to dictate
            # how status output and color should look... mainly to stay
            # consistency between versions.
    ```
    Try `color_bad = #ffffff` in `external_script deadbeef` and report back. Also, we might not want to have `self.py3.error()` here in `external_script` if it is to switch over to `CACHE_FOREVER`. 

2) `py3status` is reporting an error with `i3block command`.

   Time to look at the `command`. Run this in the terminal then focus on empty workspace.
   ```
   $ sleep 5 ; xprop -id $(xprop -root _NET_ACTIVE_WINDOW) | cut -d\  -f5) WM_CLASS | cut -f4 -d '"'
   xprop: error: Invalid window id format: 0x0.
   ```
   No error code here. We remove `| cut | cut` things.
   ```
   $ sleep 5 ; xprop -id $(xprop -root _NET_ACTIVE_WINDOW)
   xprop: error: Invalid window id format: _NET_ACTIVE_WINDOW(WINDOW):.
   ```
   It returns error code `1` here on empty workspaces.

Let me know the results. Thanks. 👍

**Comment by Artlant** [comment]
@lasers 
Sorry my English to bad
Many thanks to the addition in general color_bad = '#FFFFFF' really helped

but here's a strange moment
if called
`
i3block deadbeef {
    interval = 3
    script_path = "~/.config/i3/i3blocks/deadbeef.sh"
}
`
then nothing happens
with the fact that when you call from the console - everything is correct (I think the problem is that the two lines)
![screenshot from 2017-10-31 22-47-30](https://user-images.githubusercontent.com/13064767/32248195-8450754e-be8d-11e7-820f-c0328834b3f7.png)

I wanted to initially do something like
`format = " {output} | sed 's/\[[^]]*\]//g'"` where `{output}` === `{artist} - {title}`
but of course this did not work
Here is the radio station itself 
` http://relay.radio.obozrevatel.com:8000/main_stream_rock128.mp3`

and as you can see in the _title_ field there is a constant  ` [Мейнстрим рок]` essentially [a-z]$ which I wanted to remove
![screenshot from 2017-10-31 22-52-15](https://user-images.githubusercontent.com/13064767/32248426-56975ebe-be8e-11e7-8932-5a2e615b01a5.png)
I know it's silly but I do not know how you can throw the standard {output} to another file for processing and then output it to `format = "{_new__output}"`


I understand that I'm probably involved in garbage but I really do not have enough work with the standard output modules and their transfer to external scripts.

also it is not clear why
```
external_script deadbeef {
    color = "#FFF"
}
```
has a lower priority than
```
general {
    colors = true
    color = '#FFFFFF'
    color_bad = '#FFFFFF'
}
```
**SORYY
replacing `i3block` to `external_script`  the error with the output warn disappeared**

Many thanks for the answer! and remembered why I used i3block func_name instead of external_script func_name
The possibility of using command instead of script_path. But as you can see, `i3block` is much more sensitive to `exit 1` (error output) than `external_script`

and I also forgot that `i3block` does not have a `script_path` parameter because _"~ /.config /i3/i3blocks/deadbeef.sh"_ does nothing and has not

I'm dumb. Аnd thanks again for having responded!!

**Comment by lasers** [comment]
>has a lower priority than

`color ` only works if the modules does not return `color`. In `external_script`, it uses  `color` _only_ when the command/script came back with a `error code`, so you will want to use `color_bad`.

Using `dpms` as an example...
```
order += "dpms"
dpms {
    color = "#ffccff"
}
```
... is not possible... as `dpms.py` is always returning `color` in the module.

> also it is not clear why
> ...
> has a lower priority than

>...
>external_script deadbeef {
>    color = "#FFF"
>}

This should work fine. Maybe try `#caf` and `echo @lasers` to see it more clearly... as `echo` wouldn't return error code. As before, `deadbeef` is funny with error codes so you have to use `color_bad` here.

>Аnd thanks again for having responded!!

No problem. :-)

**Comment by lasers** [comment]
@Artlant Can you try this? [deadbeef-scrub/deadbeef.py](https://github.com/lasers/py3status/blob/deadbeef-scrub/py3status/modules/deadbeef.py)

**Comment by lasers** [comment]
@Artlant Pinging again. Maybe you didn't notice the message above. Does this make things easier for you if `deadbeef` supports the new `scrub` option?

**Comment by Artlant** [comment]
@lasers 
I noticed and tested your modified module. And of course it completely works. 

![screenshot from 2017-11-02 22-25-58](https://user-images.githubusercontent.com/13064767/32348571-d9e927ea-c01c-11e7-9b1b-87ce40081e16.png)

Nevertheless, I thought that you will have problems with the support of additional functionality except me and no one needs. And it was logical to assume that you provided it as an example of work.
That in turn should show me (you see how to do it ;) ). And should not take the time of developers forcing them to solve my specific requirements

**Comment by Artlant** [comment]
@lasers 
frankly. The only two goals that I wanted to tell you:
1) I thought that I can not change the red color of the output deadbeef is a bug,
2) to convey the idea (or understand) about how you can use `$output` to output/change for example to apply regex or another bash function.
Here's an example of how your windows_title module displays not only the name of the program/process a and the path to the file the file name and other (for me) useless information. And I wanted to how to handle them with third-party scripts in a better simple bash function.
But now I understand that it's much more logical to just create your own module based on yours.
But I am pushed off by the possibility that sooner or later you will change api and I will have to understand this. Simply speaking, I might be lazy at the time. Forgive me for such frankness.

**Comment by Artlant** [comment]
@lasers 
you helped me very much by writing (improving) my py3status / py3status / modules / deadbeef.py. Unfortunately, I myself got enough of my mind to upgrade it so much. For me, it's easier to work with the provided module with the ready-made output and then change it.
Understand your not always possible (me) python simply and there code is relatively easy to digest. But I better not go there where you can break something. Badly understanding the question. Rather, these are my personal prejudices.

**Comment by lasers** [comment]
An issue is an issue. Open them all and we'll try to address them all. ;-)

>1. I thought that I can not change the red color of the output deadbeef is a bug,

It does not print `color` in the module, but probably something to do with `self.py3.CommandError` as I am not familiar with what that one does. I assumed it gave you `bad` color.

>2. to convey the idea (or understand) about how you can use $output to output/change for example to apply regex or another bash function.

I suppose @tobes can explain this part here. Maybe we assume the output is mostly nice and/or is wanted as-is. This could be more of an issue with `deadbeef` lacking `scrub` option rather than the `$OUTPUT` + `regex` + etc`... See what he have to say.

Also, `spotify` have something similar to what you're trying to accomplish in their code. Also, it was not too long ago that `deadbeef` was completely unknowingly broken for `{unknown_long_period}` so it is _nice_ to see somebody already using the working`deadbeef` in the wild.

@tobes I think we should make `self.py3.scrub` helper for all modules.
* `gcal`... contains `remove` + `ignore` functions to scrub something.
* `google_calendar`... contains `blacklist_event` to scrub something.
* all song players, eg `clementine`, `mpd`, `gpmdp`, etc... can use this to scrub something.
* others not listed here and/or others in need of this `scrub` feature.

>Here's an example of how your windows_title module displays not only the name of the program/process a and the path to the file the file name and other (for me) useless information. And I wanted to how to handle them with third-party scripts in a better simple bash function.
But now I understand that it's much more logical to just create your own module based on yours.

Ideally, you should try to add _New!_ `{class}` placeholder for `window_title` rather than depending on third-party scripts.. then you can make a pull request here... then others will appreciate you for adding this feature... Jump in. Have fun a bit with python.

> But I am pushed off by the possibility that sooner or later you will change api and I will have to understand this. Simply speaking, I might be lazy at the time. Forgive me for such frankness.

I don't think that'll happen... The changes are utterly slow around here. 

>But I better not go there where you can break something.

I had my shares of breaking codes in `py3status`. It's something that is going to happen when you're working on `py3status` or any other code. That's life... And we can't learn without breaking something sometimes.

You're welcome to make pull requests to make modules more better. I can review your code. Others can review your code too. We need more testers here too. Feel free to test things if you prefer to take a cautious approach instead. :-)

**Comment by lasers** [comment]
Can you rename this to `deadbeef: output error` and make a list of feature requests? 👍

**Comment by Artlant** [comment]
@lasers Many thanks for the detailed answer

> Ideally, you should try to add New! {class} placeholder for window_title rather than depending on third-party scripts.. then you can make a pull request here... then others will appreciate you for adding this feature... Jump in. Have fun a bit with python.

I'm afraid I can not write a class. For this you need not only to write a simple code but also be able to design a module. And my attempts to write something useful is enough - filth. It is enough to look at this.
https://github.com/Artlant/gmail-check/blob/master/gmail.py

> and make a list of feature requests?

I'm sorry, but I do not know how. Can you explain what you want, fill in some fields here? Maybe I should give you access to my git-account, what would you fill?

**Comment by lasers** [comment]
>And my attempts to write something useful is enough - filth. It is enough to look at this. [gmail.py]

*[shudders in horror]* - You can try `imap` here if you hadn't. It checks every 60 seconds.

>I'm sorry, but I do not know how. Can you explain what you want, fill in some fields here? Maybe I should give you access to my git-account, what would you fill?

Open a new issue (like this one) with a list of feature requests you want to see. Make a list... then we can try and tackle them all. Revisit the modules you're currently using. When we help you, we help others too with the new features.

**Comment by Artlant** [comment]
> [shudders in horror] - You can try imap here if you hadn't. It checks every 60 seconds.

I know ((( is an alternative to RSS imap. The truth is, what advantages I myself can not answer

> Open a new issue (like this one) with a list of feature requests you want to see. Make a list... then we can try and tackle them all. Revisit the modules you're currently using. When we help you, we help others too with the new features.

oh it's now clear. (language barrier). Thank you
