### ISSUE TITLE
add deadbeef мodule Format placeholders {file_name}

### ISSUE THREAD

**Issue by Artlant** [ultrabug/py3status#1155]
Hi!
Sometimes it happens that the file has no `title / artist` tags and then it makes sense to print out the file name. This is for example when downloading the `.m4a` file from _youtube_.
 for the `deadbeef` command looks like this. 
`deadbeef --nowplaying "%f"`

Just maybe it makes sense also to cut out the file extension and leaving only the name.
`deadbeef --nowplaying "%f"` | regex (.\w{2,4}$)

But it's convenient to design a kind
`format = '[{output} == null ] | {file_name}'`

**Comment by lasers** [comment]
Hi @Artlant, do you mean `{filename}` ?
```
    For more placeholders, see title formatting 2.0 in 'deadbeef --help'
    or http://github.com/Alexey-Yakovenko/deadbeef/wiki/Title-formatting-2.0
    Not all of Foobar2000 remapped metadata fields will work with deadbeef and
    a quick reminder about using {placeholders} here instead of %placeholder%.
```
http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.25filename.25

I don't see why we can't add `{filename}` to the default format. :+1:

**Comment by Artlant** [comment]
`%f filename without path` in 
https://github.com/DeaDBeeF-Player/deadbeef/wiki/Title-formatting

**Comment by lasers** [comment]
```
   --nowplaying FMT   Print formatted track name to stdout
                      FMT %-syntax: [a]rtist, [t]itle, al[b]um,
                      [l]ength, track[n]umber, [y]ear, [c]omment,
                      copy[r]ight, [e]lapsed
                      example: --nowplaying "%a - %t" should print "artist - title"
                      for more info, see http://github.com/Alexey-Yakovenko/deadbeef/wiki/Title-formatting
                      NOTE: --nowplaying is deprecated.
   --nowplaying-tf FMT  Print formatted track name to stdout, using the new title formatting
                      FMT syntax: http://github.com/Alexey-Yakovenko/deadbeef/wiki/Title-formatting-2.0
                      example: --nowplaying-tf "%artist% - %title%" should print "artist - title"
```
NOTE: `--nowplaying` is deprecated. We use ` --nowplaying-tf FMT`. Please try `{filename}`.

**Comment by Artlant** [comment]
![screenshot from 2017-11-09 20-33-38](https://user-images.githubusercontent.com/13064767/32622953-5139a336-c58d-11e7-8bae-9fef8247bc68.png)

**Comment by lasers** [comment]
Click on `CONFIG ERROR`. What does it say?

**Comment by Artlant** [comment]
![screenshot from 2017-11-09 20-37-06](https://user-images.githubusercontent.com/13064767/32623128-c5ce463e-c58d-11e7-8916-ac0e7e3ac33f.png)

**Comment by Artlant** [comment]
![screenshot from 2017-11-09 20-37-52](https://user-images.githubusercontent.com/13064767/32623165-e0f2cdfe-c58d-11e7-85d9-e60ae81c6ee8.png)

**Comment by lasers** [comment]
What's on line 26 position 23?

**Comment by Artlant** [comment]
Sorry, I used the local module and edited the global module. Idiot

**Comment by lasers** [comment]
It is fine. Drop in any time. :+1: 

>This is for example when downloading the .m4a file from youtube.

If you can give me a link to download that `m4a` file, I can add `filename` to default format. It should be something like `format = '[{artist} - ][{title}]|{filename}'.

**Comment by Artlant** [comment]
I combine format to scrub

`  scrub = "{'title': '\[.*\]$'}|{filename}"`

but I wonder why `format` only works with parentheses and the `scrub
![screenshot from 2017-11-09 20-49-21](https://user-images.githubusercontent.com/13064767/32623625-7d565d54-c58f-11e7-93a8-010d1ae01d89.png)
` can do without them

**Comment by Artlant** [comment]
![screenshot from 2017-11-09 20-49-21](https://user-images.githubusercontent.com/13064767/32623667-98c13654-c58f-11e7-81bf-c1a8e741ca47.png)

**Comment by Artlant** [comment]
`scrub = "{'title': '\[.*\]$'}|{filename}" `
 how to make a working combination?

**Comment by lasers** [comment]
```
format = '[{artist}][\?soft  - ][{title}]|{filename}'
scrub = {'title': '\[.*\]$'}
```
I think...

**Comment by Artlant** [comment]
this is genius! 
I thought that `format` is incompatible with `scrub`

**Comment by Artlant** [comment]
Well, because `scrub` works without the parameter `format`

**Comment by lasers** [comment]
>But it's convenient to design a kind
format = '[{output} == null ] | {file_name}'

This is what you're asking. Same thing. :+1: 

`scrub` just scrub the placeholder. You can scrub `title`, `filename`, or any other placeholders.
```
scrub = {'filename': something_here'}
```

**Comment by Artlant** [comment]
not this is absolutely brilliant. `Scrub` is a very powerful tool. In the past, I was concerned about the inability to process `{output}`. But if I read carefully the manual then there were no such stupid questions.
**Scrub - it's brilliant.** You need a separation guide for this parameter. So powerful it is

**Comment by Artlant** [comment]
but what do these square brackets do?
`format = '[\?max_length=50 {class}]|\u2665'`

**Comment by lasers** [comment]
I made simple `scrub` for you. I do think we should make universal `scrub` to work with all modules. Things to figure out...  Do we want to `scrub` the format itself... or to `scrub` the placeholders's values because of the loop? Maybe just both... 

Square brackets either hide things or break up things. You can use `format = '\?max_length=50 {class}|\u2665' just fine.... but if things starts to get too complicated, then we need square brackets to break up colors, lengths, formatting stuffs, etc...

Also... `'{class}|\u2665'` will work fine... If no `{class}`, then we use `\u2665`.
If just `{class}` and no value, then it may show either `{class}` or `''` or `None`.

**Comment by lasers** [comment]
@Artlant Hi. How can I reproduce this behavior? I'm trying to understand your `deadbeef` flow especially with the Internet links... Are you using some script? Got a `m4a` link? I tried `easytag` to scrub the title/artist. and deadbeef just put the filename (w/o extension) in the title.

**Comment by Artlant** [comment]
I listen to internet radio. And if I like the song, then click the mouse and the search window opens on YouTube (or any other site). After the most convenient for me is simply copying the link into the telegram (this is im where except for the bot-processors there is nothing interesting. Well, unless you are interested in communication with a bunch of Russian and Iranians). Bot link https://t.me/YTAudioBot
And he gives me a file to listen to. Then if I like the song, I can save it on the disc. But sometimes there are no tags and here I am writing an issue and begin praying for help from you.

.pyi3status.conf:
```
deadbeef2 {
    format = '[{artist}][\?soft  - ][{title}]|{filename}'
    scrub = {'title': '\[.*\]$'}
    color_good = '#FFFFFF'
    color_degraded = "#4D4D4D"
    color_bad = "#ff7a00"
    on_click 1 = 'exec echo $OUTPUT | exec xclip -selection c; exec notify-send "Copied to clipboard" "$OUTPUT"'
    on_click 3 = 'exec chromium "\youtube.com/results?search_query=$OUTPUT"'
}
```

**Comment by Artlant** [comment]
[radio.pls.zip](https://github.com/ultrabug/py3status/files/1462779/radio.pls.zip)
bot saves the file in this format 
`Aero Chord _ Anuka - Incomplete (T-Mass Remix) - vXTrSJRJTYY.m4a`.


the radio playlist itself is also attached. But I have a bad musical taste

**Comment by Artlant** [comment]
The bot work itself is simple.
a link to a video or request he suggests download - yes and the entire file is uploaded. Minus the telegram lack of stream playback (not yet before the end of the downloaded file)
![screenshot from 2017-11-10 23-37-26](https://user-images.githubusercontent.com/13064767/32679795-6d2794f2-c670-11e7-82c8-e187e59f8ff8.png)

**Comment by lasers** [comment]
Ah I see. I didn't try to reproduce what you explained above... as I'd have to download songs. I tried the radio playlist and do not see title until 20~ seconds later... which is useless with `{filename}` here. Anyhow, this does not seem too big of a deal to add `{filename}` to the default format.

Seeing how people are listening and/or downloading songs from online nowadays, we could add it anyway just to make `deadbeef` behave a little better. I dunno. I leave this to others as I don't use `deadbeef`. Thanks for sharing your scenario. Drop in any time with new feature requests. :+1:
