### ISSUE TITLE
event latency

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#1169]
We have several issues here mainly effecting scroll wheel events due to the rapid nature of their arrival

* events can trigger a module to be run several times concurrently we probably only want it running the update once - this is fairly easy to solve

* events are all handled in the same thread, when a event occurs it wants to be processed in it's own thread so that it doe not delay other events. - this need some more work but we should be able to do this fairly easily using the Runner class and then ignore any events till we can process new ones

**Comment by lasers** [comment]
#1256 breaks `hueshift` module. See https://github.com/ultrabug/py3status/pull/1142#issuecomment-359504684.

**Comment by tobes** [comment]
closing as we now run events in threads.

> #1256 breaks hueshift module. See #1142 (comment).

this should be in the #1256 hueshift module or a new issue
