### ISSUE TITLE
After upgrade from 2.4 to 2.5 the status bar is empty

### ISSUE THREAD

**Issue by ndalliard** [ultrabug/py3status#117]
Hello,

after the upgrade from 2.4 to 2.5 my status bar is empty. I am using Arch Linux.

My i3status config:
```` 
general {
         output_format = "i3bar"
         colors = true
         interval = 1
 }
 
 order += "0connection"
 order += "10netdata"
 order += "20sys"
 order += "70uname"
 order += "80volume"
 order += "99clock"
````
This line is from the i3 config file:

````
status_command py3status -s
````
And the python files are located in the py3status folder.

**Comment by Horgix** [comment]
Hi,

I'm maintaining the Arch package for py3status and running 2.5 version without any trouble. Same for some friends of mine. I'll take a look into that tomorrow anyway :)

Is that intented to have number before modules names in "order += ..." part ?

**Comment by ndalliard** [comment]
That is intended. I tried to remove the numbers but still an empty status bar. Thanks for looking into that. Here is a link to the modules, maybe that helps: https://github.com/ndalliard/dotfiles/tree/master/.i3/py3status

**Comment by ultrabug** [comment]
I'll have a look too tomorrow mate !

**Comment by Horgix** [comment]
https://github.com/ndalliard/dotfiles/blob/master/.i3/py3status/0connection.py#L25

Any reason to return a tuple with `return (0, response)` ? What I'm returning in my modules is simply a dictionnary. Try returning only "response" maybe. @ultrabug : can you confirm that ? Didn't look that much in how py3status handles modules answers.

**Comment by Horgix** [comment]
And indeed the example modules only returns a dictionnary : https://github.com/ultrabug/py3status/blob/master/doc/example_module.py#L105 , not a tuple (int, dictionnary)

**Comment by ultrabug** [comment]
@Horgix : yes old school modules did provide a (position, response) tuple before which has been obsoleted by the order += mechanism.

I think I was a bit hasty in dropping the support of such response for compatibility reasons obviously !

I'll implement it back

**Comment by Horgix** [comment]
@ultrabug : ok, at least we know where it comes from now :)

**Comment by Horgix** [comment]
@ndalliard : either :
* downgrade py3status to before 2.5 (dropped support for the (<pos>, <dict>) answer format)
* update your modules with only "return response"
* wait for @ultrabug to revert the format drop

**Comment by ultrabug** [comment]
@ndalliard : if you can, I would greatly appreciate you install py3status by hand from the `fix/cli_available_modules_detection` branch and report if it fixes all your problems ?

Thanks !

**Comment by ndalliard** [comment]
@ultrabug : The branch `fix/cli_available_modules_detection` fixes all problems. 
Works like before. Thanks a lot!

**Comment by ultrabug** [comment]
Cool @ndalliard thanks ! I'm glad to say that version 2.6 is now out !

Btw, looking at your own modules you may be interested to know that most of them are already proposed in py3status official modules:
- 0connection -> whatismyip or online_status module
- 10netdata -> netdata module
- 20sys -> sysdata module
- 70uname -> uname module ;) thx to you

See the `py3status modules list` command and `py3status modules details` for more info, new modules are configurable directly from your i3status.conf just like any other i3status module !

I also took the liberty to create a new `uname` module for everyone which is inspired by yours : https://github.com/ultrabug/py3status/commit/c531065d7c171adadd15456db44dad45899b676c
