### ISSUE TITLE
semicolon in on_click does not work

### ISSUE THREAD

**Issue by Artlant** [ultrabug/py3status#1181]
Hello! 
It's me again (the guy asking idiotic questions related to Deadbeef), although I doubt that someone remembers me. And about a miracle, today it is not connected with the player, but indirectly.

суть в том что параметр вида:
`on_click 1 = 'exec echo $OUTPUT | xclip -selection c; notify-send "Copied to clipboard" "$OUTPUT"'`
does not work. But if you replace the semicolon `;` of a symbol `&&` then everything is fine
on_click 1 = 'exec echo $OUTPUT | xclip -selection c **&&** notify-send "Copied to clipboard" "$OUTPUT"'

The question is why? And how then can I run several commands, regardless of the result of the previous one. I came up with this option `command1 | command2` but this is some kind of garbage.
In general `;;;;;` exception or interruption in the code and should not ... probably ... I hope

**Comment by lasers** [comment]
```
[~]$ i3-msg exec 'echo $OUTPUT | xclip -selection c ; notify-send "Copied to clipboard'
ERROR: Your command: exec echo $OUTPUT | xclip -selection c ; notify-send "Copied to clipboard
ERROR:                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'mode', 'bar', 'gaps'
[{"success":true},{"success":false,"parse_error":true,"error":"Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'mode', 'bar', 'gaps'","input":"exec echo $OUTPUT | xclip -selection c ; notify-send \"Copied to clipboard","errorposition":"                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"}]
```
```
[~]$ i3-msg exec 'echo $OUTPUT | xclip -selection c && notify-send "Copied to clipboard'
[{"success":true}]
```
```
[~]$ i3-msg exec 'echo $OUTPUT | xclip -selection c ; exec notify-send "Copied to clipboard'
[{"success":true},{"success":true}]
```
>The question is why?

You need `exec` to start an application. https://i3wm.org/docs/userguide.html#exec

>And how then can I run several commands, regardless of the result of the previous one.

You need `exec` too. :-)

**Comment by Artlant** [comment]
@lasers thank you, i thought `|` `;` `&&` `||` belong to the same group of consecutive calls. But apparently the interpreter breaks them. I'm one step closer to enlightenment

**Comment by ultrabug** [comment]
Impressive @lasers!

Thanks guys and happy enlightenment @Artlant :)
