### ISSUE TITLE
readthedocs

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#1191]
version 3.7 broke the doc build.

I've changed the default https://py3status.readthedocs.io to point to latest so we have docs showing, but we have no documentation for version 3.7.

I think we should create a 3.7.1 branch with the documentation fix 744d14d47f6 (maybe wait a week for any other bugs) and then do a release of 3.7.1

I'll also look at making the doc build more robust so that a similar error will not break the doc build.

**Comment by lasers** [comment]
We could release `3.8` in time for holidays? Multiple PRs ready to be merged.
