### ISSUE TITLE
make new method: on_urgent

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1201]
I am currently trying Solus. Either I hadn't been paying attention to `solus_updates` module or Solus released all of that updates at same time. I said this because I apparently had 70 updates to do.

I didn't know which one was it, but I wish to add `urgent` for `solus_updates` so it can tell me about a large number of pending packages rather than me noticing it just now.

The solution could be to implement this in the module directly. The better solution could be to see if we can do this without touching the module. I'm visualizing something like this.

An example using `solus_updates`.
```
solus_updates {
    format = 'UPD {update}'
    on_urgent = [
        ('format', 'update', >=50), # urgent. you got 50 updates. c'mon bro.
        ('format', 'security', >0), # urgent. security update. in fedora.
        ('format', 'security', True), # urgent. security update. fake example.
    ]
}
```

An example using `air_quality`.
```
air_quality {
    format = 'UPD {update}'
    on_urgent = [
        ('format', 'aqi', >=200),  # urgent. very unhealthy today.
    ]
}
```

An example using `imap`.
```
imap {
    allow_urgent = False  # we should omit allow_urgent in `imap` along with
                          # an example to turn it on, but would break
                          # existing configs.

                          # users who receive some emails everyday will love this.
                          # users who receive ton of emails everyday will hate this.

    format = 'Mail: {unseen}'
    on_urgent = [
        ('format', 'unseen', >=15),  # urgent. check your fucking mail.
                                     # you're fucking lazy today....
    ]
}
```

**Comment by maximbaz** [comment]
`on_urgent` means to me "do something when module became urgent", but I think what you want is the other way around, thus I suggest to rename to `urgent_on`.

**Comment by tobes** [comment]
this would maybe work well as part of the neglected issue  #934

**Comment by lasers** [comment]
I'm not sure if it's a good idea to implement this. Maybe #934 too. I think with a little more work in the `formatter`, this could be superseded by the `format` alone due to basic conditions... and that we could always add more conditions to the `format` later. The replacements probably looks like this and may be more practical than a separate config.
```python
solus_updates {
    format = 'UPD {update}'
    format += '[\?if=update>=50&urgent]
    format += '[\?if=security&urgent]    
}
```

```python
air_quality {
    format = 'UPD {update}'
    format += '[\?if=aqi>=200&urgent]
}
```

```python
imap {
    format = 'Mail: {unseen}'
    format += '[\?if=unseen>=15&urgent]
}
```
When an `urgent` gets activated inside a block, it should be activated anywhere anyway.
