### ISSUE TITLE
weather_owm not listed in modules

### ISSUE THREAD

**Issue by alexoneill** [ultrabug/py3status#1213]
I recently added `weather_owm`, and it is not listed in `py3status/modules/README.md`.

Is there an automated process to do this, or should I manually transcribe the docs from the module?

**Comment by tobes** [comment]
Really we should replace that file and direct people to https://py3status.readthedocs.io/en/latest/modules.html

I want to do some cleaning up of the docs for the next release

**Comment by lasers** [comment]
I tried my hand at this stuff. Thoughts? Should I make a PR for this?
Preview: https://github.com/lasers/py3status/tree/readthedocs

**Comment by tobes** [comment]
> I tried my hand at this stuff. Thoughts?

Things can be improved.  But imho on the main readme.rst I want an overview/install instructions etc.  I do not just want to be directed to the documentation.

Removing the stale documentation (and the generator etc) is really the way forwards.  I have a branch that cleans the modules docstrings etc and it is probably best to do this cleanup as part of that.

**Comment by ultrabug** [comment]
This README is obsolete, now we have readthedocs

I updated the readme to say so, closing
