### ISSUE TITLE
external_script functionality to support multiple scripts

### ISSUE THREAD

**Issue by erpadmin** [ultrabug/py3status#1215]
i'm new to [i3|py3]status, but is it possible to add support for the module name to be arbitrary (unique) and use external_script as a definition that replaces script_path?

example:
```
order += arbitrary_script

arbitrary_script {
        color = "#8ba9af"
        format = "FUN:${output}  "
        external_script = "/home/user/bin/fun.py"
}
````

bad idea?

**Comment by tobes** [comment]
What is it that you are trying to achieve?
If you want two external script modules you can do like this

```
order += 'external_script hello'
order += 'external_script goodbye'

external_script hello {
        format = "Hello: {output}"
        script_path = "hello.py"
}

external_script goodbye {
        format = "Goodbye: {output}"
        script_path = "goodbye.py"
}
```

**Comment by erpadmin** [comment]
Exactly what you have written,  thanks for the feedback.
