### ISSUE TITLE
[wifi] Device detection is not working anymore

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1231]
Creating an issue for tracking purposes, see https://github.com/ultrabug/py3status/pull/1157#issuecomment-357518637.

/cc @lasers 🙂

**Comment by lasers** [comment]
Repasting the issue.

>:rotating_light: this PR broke detection of wlan device name, because self.iw_dev_id_link = [iw, 'dev', self.device, 'link'] is now set before self.device has a chance to be overridden with the detected device name.

Thx for the /cc. :blush: Can you share the the `wifi` config? Meantime, I will look at this.

**Comment by maximbaz** [comment]
Just a default config, nothing special. I noticed that after an upgrade py3status started executing `iw dev wlan0 link`, but my only device is actually called `wlp2s0`, so it should have been executing `iw dev wlp2s0 link`.

**Comment by lasers** [comment]
@maximbaz Please try https://github.com/lasers/py3status/tree/wifi-set-loc

**Comment by maximbaz** [comment]
That fixes the issue, thanks for looking 🙂

**Comment by lasers** [comment]
No problem. I remember I moved it up to "clean" and "make things nice".... Ugh. Thx for testing. I will put this out now. Cheers. :+1:
