### ISSUE TITLE
Spotify - "Paused" logic

### ISSUE THREAD

**Issue by fam4r** [ultrabug/py3status#1244]
Hi,

it seems that Spotify module is not correctly handling Play/Pause/Stop PlaybackStatus controls.

Let me explain:
If I force a "Stop" event (see commands below), PlaybackStatus still returns "Paused" string when queried.

```bash
# Sending "Stop" request to player
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop

# Getting response
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'
method return time=1516302438.396819 sender=:1.28 -> destination=:1.118 serial=3656 reply_serial=2
   variant       string "Paused"
```

In that way, py3status Spotify module is not going to show the "format_stopped" parameter content, but it is "only" [changing color](https://github.com/ultrabug/py3status/blob/master/py3status/modules/spotify.py#L132).

Since it seems that spotify it's handling "Stop" and "Pause" in the same way (thus flow reaches the "else" block) (if I'm right!), is there a way to manage that?
Something like
```py
# code...
                if playback_status.strip() == 'Playing':
                    color = self.py3.COLOR_PLAYING or self.py3.COLOR_GOOD
                else:
                    color = self.py3.COLOR_PAUSED or self.py3.COLOR_DEGRADED
                    format = self.format_stopped
# code...
```

Glad to contribute!
Thank you

**Comment by lasers** [comment]
Try this https://github.com/lasers/py3status/tree/newmodule-spotify

**Comment by fam4r** [comment]
Works fine, thank you!

**Comment by lasers** [comment]
@fam4r You're welcome. This, I think, at least need a formatter `contains` condition to be made / merged first before I should put out a `newmodule-spotify` pull request. Happy pausing. :-)

**Comment by fam4r** [comment]
That's ok, I'll include it manually until it will be merged 👍

**Comment by fam4r** [comment]
Hi @lasers,

any update?
Has it been merged?

Thanks

**Comment by lasers** [comment]
Nothing changed. Too much changes in my spotify PR. I guess you should keep using this. If you hadn't, py3status have a `--include INCLUDE_PATHS` argument that you can use for `spotify` and `lm_sensors`.

The bug is that spotify does not have `format_paused` config. I made spotify from scratch that puts everything in one `format`... and will just break people's spotify configs. You also could try `mpris` as an alternative.

**Comment by fam4r** [comment]
> You also could try mpris as an alternative.

No, thank you. I just automatized everything downloading both modules with `wget` and including them with `--include` option when calling `py3status` from `i3bar`.

I think you can close the issue.

Thank you so much for your support!

**Comment by fam4r** [comment]
I assume I can close.
Thank you again, @lasers
