### ISSUE TITLE
py3status in Debian

### ISSUE THREAD

**Issue by sdelafond** [ultrabug/py3status#1253]
Heya,

wasn't sure how to reach out to you about this, but I've been packaging py3status in Debian for a little while now (it's also been picked up by Ubuntu since the latest stable):

  https://tracker.debian.org/pkg/py3status

Maybe it'd be worth mentioning in the README, so Debian users don't have go through pip ? If you think that's a good idea, but you'd rather I draft a PR instead of having you edit it yourself, please let me know :)

Cheers,

--Seb

**Comment by lasers** [comment]
Hi. I'm only a contributor here. I gather you should make a PR right away to touch `doc/intro.rst` as `README.rst` is deprecated and should be removed eventually. 👍

**Comment by sdelafond** [comment]
I can and will do that, but README.rst is still the info displayed on the 1st page at this point, right ? So I'm assuming any potential Debian user would start with a "pip install..." only to maybe discover later that py3status was apt-get'able ?

**Comment by lasers** [comment]
Although it's on the first page, `README` hadn't been touched since `Fri Apr 7`.
See what @tobes has to say... And he have a branch to deal with this too.

>@tobes Removing the stale documentation (and the generator etc) is really the way forwards. I have a branch that cleans the modules docstrings etc and it is probably best to do this cleanup as part of that.

We are in serious need of a documentation rewritten / overhaul too... as there are several hidden features and/or formatters that hadn't been documented for months.

**Comment by tobes** [comment]
> README.rst 

This will still remain as it is a useful on github especially.  The one in `/modules` is the one that needs to die (or at least be very different)

@sdelafond 
Thanks for you work packaging py3status.  If you need any assistance please get in touch with us

**Comment by tobes** [comment]
I'm going to leave this open as I think we need details of debian/ubuntu install on the root README.rst
