### ISSUE TITLE
Run `on_click` handler in a separate thread

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1270]
I have a long-running `external_script`, so I made `on_click` print the last result, like so:

```
cache_timeout = 600
script_path = 'mylongrunningscript'
on_click 1 = 'exec notify-send "my cached results" "`cat ~/.cache/mylastrunresults.txt`"'
```

This works perfectly, except when the script is running, onclick is not doing anything. I think it is happening because onclick is handled in the same thread that is running my script.

**Comment by tobes** [comment]
Yes that makes sense as we currently stop the same module running twice.  So here once is the long running script and twice is the on_click.

As it is not actually the script running the on_click as it is external the logic should be fixed.

**Comment by lasers** [comment]
@ultrabug Close this.
