### ISSUE TITLE
gevent monkey patching breaks mpris

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1271]
Using `--gevent`, @cyrinux ran into an issue with `mpris`. https://github.com/ultrabug/py3status/pull/1250#issuecomment-359168769.

**Comment by tobes** [comment]
I wonder if this is the `gobject` stuff.

**Comment by lasers** [comment]
It is. The log stopped there and I was able to run it without `gobject` + thread. Slowly, but surely.

**Comment by lasers** [comment]
@girst If you want to do something, see if you can solve this issue. Threading is involved.
