### ISSUE TITLE
wanted features for thresholds

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1281]
Hi. Opening a dialogue about this issue... I think `thresholds` could use some rewritten.

To start off... 

First, it is already useful to make thresholds based on placeholder.
* We already do this for `int` and `float`.
* Not `string`... as threshold gives them `color_bad`.
* And an exception on `None`.

With that in mind, I propose we add the following features...

**Feature 0**: Skip on None.
* No color. Not supposed to happen, but sometimes it can... via loop or such.

**Feature 1**: Support strings.

Some modules minimally could use string thresholds too. The working solution is to (internally) assign a number and run with it.

* Example 1: (String values) `cmus / moc / others`: playback --> stopped, playing, paused

    ```python
    format = '\?color=playback ...'
    thresholds = {
        'playback':[
            ('stopped', 'bad'), ('paused', 'degraded'), ('playing', 'good')
        ]
    }
    ```

* Example 2: (String values) `pomodoro`: state --> stopped, running, break
    ```python
    format = '\?color=state...'
    thresholds = {
        'state':[
            ('stopped', 'bad'), ('break', 'degraded'), ('running', 'good')
        ]
    }
    ```
    * IS MAYBE BETTER THAN THIS WORKING SOLUTION...

    Example 3: (Internal numbers) `pomodoro`: state --> stopped, running, break
    ```python
    format = '\?color=state...'
    thresholds = {
        'state':[
            (0, 'bad'), (1, 'degraded'), (2, 'good')
        ]
    }
    ```

**Feature 2**: A solution for internal thresholds.

Sometimes it is useful to make custom thresholds based on data.

This is for @raspbeguy's `gazelle`. I likely can do this in `nvidia_smi` too with NVIDIA GPU `{memory.used}` and `{memory.total}` properties... and for the other finished module I made (not available in pull requests).

The internal threshold will not change much, but can change sometime so maybe cache the string after `get_color`. Also, not always for same thing, eg One card have 8GB and next card have 4GB. Anyhow, caching the strings shouldn't have any problem w/ this. The threshold for this could be named: `thresholds = {'auto': True}` (if auto).

I used this. This works for me, but is inefficient.

```diff
diff --git a/py3status/py3.py b/py3status/py3.py
index 15ed85e0..ce998678 100644
--- a/py3status/py3.py
+++ b/py3status/py3.py
@@ -1028,7 +1028,7 @@ class Py3:
             self._audio.kill()
             self._audio = None

-    def threshold_get_color(self, value, name=None):
+    def threshold_get_color(self, value, name=None, auto=None):
         """
         Obtain color for a value using thresholds.

@@ -1055,7 +1055,11 @@ class Py3:
         name_used = name
         if name_used not in self._thresholds:
             name_used = None
-        thresholds = self._thresholds.get(name_used)
+        # custom/auto threshold
+        if auto:
+            thresholds = [(x[0], self._get_color(x[1])) for x in auto]
+        else:
+            thresholds = self._thresholds.get(name_used)
         if color is None and thresholds:
             # if gradients are enabled then we use them
             if self._get_config_setting('gradients'):

```

I'm not sure if this is the best solution as this approach is not fully customizable.  To make it fully customizable, we need to support parsing things more in `self.thresholds`, eg

Convert from internal `auto`... `thresholds = {'auto': True}` to...
```python
thresholds = {'auto':
    [
        (0, 'good'),
        ('{max}', 'orange'),
        ('{crit}', 'bad')
    ]
}`
```

* If I want to add another threshold? For `nvidia_smi` and the other module, I supposedly add -10% warning threshold before the max or total value... Then I do this...

```python
thresholds = {'auto':
    [
        (0, 'good'),
        ('{max}' - '{max}' / 100 * 10, 'degraded'),  # custom
        ('{max}', 'orange'),
        ('{crit}', 'bad')
    ]
}
```

Maybe this is a bit silly. Just ranting. This kind of thing, I think, requires us to differentiate between (string) values / (int/float) placeholders... I thought about testing booleans for thresholds too... but I'm not sure if that's a good idea or even if we need one right now... as one could just do `self.py3.threshold_get_color(int(value), 'value')` instead... And having the last `True` priority in the list would imply the helper to use this last color... Anyhow, that's why I didn't make this **Feature 3** because I hadn't noticed any real needs / purposes for this.

We stop printing `color_bad` / `color_error` for wrong strings too.

**Comment by raspbeguy** [comment]
I'll review those propositions in detail later tonight but seems to have some good ideas.

**Comment by lasers** [comment]
- [x] **Feature 0**: Skip on None, 78fb3aa28facdaea57bc436d94f7f9b9e5507a35, (Mar 10)
- [x] **Feature 2**: A solution for internal thresholds, 068c67a0caac689d2ea40cb434f34352251e4c8a (Aug 17)
- [x] **Feature 1**: Support strings, 068c67a0caac689d2ea40cb434f34352251e4c8a (Oct 10)
- [x] **Feature 3**: Support booleans, _Supported via int_, (Oct 21)

I think we can close this now... Thanks. :game_die:
