### ISSUE TITLE
[question] Best prictice for injecting default attributes

### ISSUE THREAD

**Issue by Anon1234** [ultrabug/py3status#133]
I am not quiet get how the per-block attributes from i3status.conf (like align, min_width, separator etc) are being injected in py3status module response. Do i need to do it manually? If so, what is the best way to do it?

**Comment by ultrabug** [comment]
Hi, are you talking about the i3status `general` configuration block ? if so, it is passed as the second argument to every modules' methods (i3s_config) so you can use it as you please.

**Comment by Anon1234** [comment]
No, i mean this stuff: https://i3wm.org/i3status/manpage.html#_universal_module_options
For example, i have this block in i3status.conf:
```
my_py3status_module {
    #  py3status module parameters
    format  = ...
    ...
    # universal module options
    align = "center"
    min_width = 100
    ...
}
```
Will the "universal options" be included in the my_py3status_module output dictionary without any code in my module?

**Comment by ultrabug** [comment]
Oh ok.

No they will be available in your `my_py3status_module` as class attributes : self.align / self.min_width etc..

**Comment by Anon1234** [comment]
Thank you for the explanation. I come up with this code and have spotted that a boolean values from ```i3status.conf``` are not being parsed at all. I created PR #134 to fix this problem.
```python
    def window_title(self, i3s_output_list, i3s_config):
        resp = {
            'full_text': self.title_format.format(title=self.title),
            'cache_timeout': 1,  # update ASAP
        }

        for option in ('min_width', 'align', 'separator'):
            try:
                resp[option] = getattr(self, option)
            except AttributeError:
                continue

        return resp
```
