### ISSUE TITLE
sysdata - all cpu cores utilization

### ISSUE THREAD

**Issue by fam4r** [ultrabug/py3status#1336]
Hi,

is there a way to get all cores cpu utilization in `sysdata` module?

Thanks :)

**Comment by su8** [comment]
Skip parsing the first cpu row

```bash
cpu  1363194 10160 209260 3269639 38912 0 2847 0 0 0
cpu0 447009 3346 72632 1096772 13624 0 49 0 0 0
cpu1 460223 3324 67454 1089434 12746 0 78 0 0 0
cpu2 455961 3489 69173 1083432 12540 0 2719 0 0 0
```

```c
#define IDLE_NUM 3
#define LOOP_ITERZ 10
// z is the number that "cpuNUM" matches

  for (x = 0; x < z; x++) {
    for (y = 0; y < LOOP_ITERZ; y++) {
      total[x] += core_active[x][y];
    }

    diff_total[x]     = total[x] - previous_total[x];
    diff_idle[x]      = core_active[x][IDLE_NUM] - previous_idle[x];

    // static variables
    previous_total[x] = total[x];
    previous_idle[x]  = core_active[x][IDLE_NUM];

    percent[x]        = 0;
    if (0 != diff_total[x]) {
      percent[x]      = ((uintmax_t)100 * (diff_total[x] - diff_idle[x]))
                            / diff_total[x];
    }

    printf("%d%% ", percent[x]);
  }
```

**Comment by lasers** [comment]
@fam4r If you want a solution today, you can use [pinkybar](https://github.com/su8/pinky-bar). Look under `extra/py3status` for a module to use. You will want to specify `--coresload` in your `~/.pinky` config. That should be just it.

**Comment by fam4r** [comment]
@lasers Thank you.

Currently trying indicated module, works fine, even though I prefer to not install other programs.

**Comment by lasers** [comment]
Try https://github.com/lasers/py3status/tree/sysdata-add-per_cpu_used_percents

**Comment by fam4r** [comment]
@lasers thank you! Works great :smile:

Is there any difference in measuring temperature with that module or with `lm_sensors` module?

**Comment by lasers** [comment]
`sysdata` parses the command `sensor` for only the first cpu temperature.  `lm_sensors` parses the raw command `sensors -u` for literally everything. There shouldn't be any differences in measuring because we're getting the numbers from output... and not measuring the sensors ourselves.

**Comment by fam4r** [comment]
Ok, awesome.
The module is working good. Thank you.

@lasers if you want, you can close the issue.

**Comment by lasers** [comment]
@ultrabug Do you want to close this? (ie forgo a feature)

**Comment by ultrabug** [comment]
since @fam4r says so, yes closing thanks!
