### ISSUE TITLE
vpn - hiding placeholder

### ISSUE THREAD

**Issue by fam4r** [ultrabug/py3status#1338]
Hi,

currently playing with `vpn_status` module.

What I want to get: green "VPN" label when I'm connected to a VPN, no label when I am not using a VPN.

I can reproduce wanted result only with following configuration: `format = "VPN {name}|"`.
If i remove `{name}` placeholder (`VPN|`), module doesn't work properly: it gives me no output.

So i tested with (`VPN|aaa`) and prints green output with `aaa` label.
But this is the label for a disconnected VPN. And it should be red.

Currently using `check_pid` at `True` and `pidfile` set to `/sys/class/net/tun0/dev_id`.

py3status version:
```
py3status -v
py3status version 3.8 (python 3.6.5)
```

Running OpenVPN (if useful information).

**Comment by lasers** [comment]
`format = '\?if=name VPN'` should give you what you want.

**Comment by ultrabug** [comment]
I think so too, the formatter really needs some better documentation I'm afraid :(

**Comment by fam4r** [comment]
@lasers it works, thank you!
@ultrabug np.

So `\?if` works in all modules? For all configuration parameters? What other statements are available?

Thank you! :grinning:

**Comment by lasers** [comment]
>So \?if works in all modules?

Almost all. The modules need to be addressed.

>For all configuration parameters?

Only the configuration parameters with `format_*` prefix.

>What other statements are available?

[tests/test_formatter.py](https://github.com/ultrabug/py3status/blob/master/tests/test_formatter.py)

>Thank you! :grinning: 

Thank @tobes. He made this.

**Comment by fam4r** [comment]
@lasers Great!

I'll try them. You can close the issue.

Thank you guys.

**Comment by lasers** [comment]
@ultrabug Close this?

**Comment by ultrabug** [comment]
Thanks guys
