### ISSUE TITLE
diskdata not displaying disk data correctly

### ISSUE THREAD

**Issue by kozross** [ultrabug/py3status#1341]
I have the following block in my conf file:

```
diskdata {
    disk = sdb2
    format = "Disk:{used} GB/{total_space} GB"
}
```

However, what I see looks like this:

```
Disk:   0.0 GB/     0.0 GB
```

Which is clearly not right. ``/dev/sdb2`` is definitely my root partition. Am I missing something here?

**Comment by lasers** [comment]
Looks like the module is looking for lines starting with `sdb2` or `/dev/sdb2/` in command `df`. Can you paste `$ \df` output? Pinging author @guiniol.

**Comment by kozross** [comment]
I've figured out the issue - for some reason, ``df`` only displays ``/dev/root`` for me. When I changed it to that, it worked fine.
