### ISSUE TITLE
How to switch keyboard layout like in gnome 3?

### ISSUE THREAD

**Issue by alisianoi** [ultrabug/py3status#1352]
Hi,

My Arch Linux has *three* keyboard layouts that I keep switching between. By default, the layouts are being cycled in a loop, one after the other. However, most of the time I need to switch back and forth between just two layouts. A couple years ago (maybe now too) gnome would let you achieve it like this:
say your layouts are `en`, `ru` and `de`. You begin with `en` active. Let's say you're coding. Now you get a message from a friend in `ru`, you press `Shift+Alt` (or whatever combo you have) and reply in `ru`. When done, you press `Shift+Alt` again which gives you back `en` and you go back to coding. So, single `Shift+Alt` presses swap `en` and `ru` for you, and you can happily code and chat.

Now, let's say you go to an online language course in `de`. You type the address in the address bar in `en` and go to the website. Soon after you realize you need `de`, so you press `Shift+Alt` which gives you `ru` (because you were talking to a `ru` friend earlier). This is not the layout that you want, so you press `Shift+Alt` again, which gives you `de`. In my opinion that worked nicely:

1. `Shift + Alt` followed by some buttons followed by `Shift + Alt` would switch you between just *two* layouts.
2. `Shift + Alt` immediately followed by `Shift + Alt` would cycle through the list of layouts that you have, setting a new pair of active layouts (the previously active one and the one you eventually stop. You stop cycling when you begin to type in that layout).

So, I wanted to implement something similar with an `py3status` module, so I've been reading these:

1. [Introduction to writing modules][1]
2. An issue about [keyboard layout switching][2]
3. Some [pull request of keyboard_layout][3] and the source code of that module.

Could you please tell me who and how could pass the "the user is pressing some buttons" and "the user is pressing the switch layout button" events into the `keyboard_layout` module? If this is outside the scope of that module, I could also implement the layout switching logic somewhere else.

[1]: https://py3status.readthedocs.io/en/latest/writing_modules.html
[2]: https://github.com/ultrabug/py3status/issues/1179
[3]: https://github.com/ultrabug/py3status/pull/1192

**Comment by lasers** [comment]
>**alisianoi** ... passing  the "the user is pressing some buttons" and "the user is pressing the switch layout button" events into the keyboard_layout module.

AFAIK out of the scope. The [click-events](https://py3status.readthedocs.io/en/latest/writing_modules.html#example-3-click-events) docs mentions:
>You should only receive events for the module clicked on, so generally we only care about the button.


Maybe it is possible to implement layout switching logic using time... Something like this:
* Config option: `seconds = 3`
* Under `3` seconds? Switch to the new layout. Repeat to go through the list.
* Over `3` seconds? Get current layout. Switch back to last layout. Assign current layout as
new last layout.
* keyboard_layout refreshes at user-defined 10s or such so we deal with that too. Can see `xrandr_rotate.py` module for `self.scrolling` lines to see how the module could differentiate between module querying versus users clicking+module querying.

Can ask @tobes for second opinion as he might have something better.
