### ISSUE TITLE
keyboard_layout: show variant only

### ISSUE THREAD

**Issue by cyrinux** [ultrabug/py3status#1360]
Hi, 
i just comment https://github.com/ultrabug/py3status/pull/1335
@lasers Maybe i don't understand something?

**Comment by lasers** [comment]
@cyrinux Looks like you should ~~rewrite this module from scra...~~ erm, I mean... improve this by adding new placeholders / options / features, etc. This could be easy. Also, I don't use this module.

**Comment by cyrinux** [comment]
Lol ok, I note, will take a look ;)

**Comment by lasers** [comment]
@cyrinux What's the status of this issue? Do you have an issue with `keyboard_layout`?

**Comment by cyrinux** [comment]
Hi @lasers, the goals was to have placeholders for main mapping and variant

**Comment by lasers** [comment]
Closed via #1492.
