### ISSUE TITLE
add format_pause, format_stop and format_play to mpd_status

### ISSUE THREAD

**Issue by L0ric0** [ultrabug/py3status#1364]
Add  format_pause, format_stop and format_play to mpd_status to format the output depending on the state of the mpd.

**Comment by L0ric0** [comment]
found a way to do this with the formater, just use for example:
` [\?if=state=[stop] ... ]`

**Comment by ultrabug** [comment]
You're getting very good with the formatter and it obviously lacks documentation

@L0ric0 it would be very appreciated and welcome to have contributions to the formatter documentation !

**Comment by L0ric0** [comment]
Will do.
