### ISSUE TITLE
Disk read/write stats in diskdata isn't computed correctly when a disk is specified

### ISSUE THREAD

**Issue by scotte** [ultrabug/py3status#1373]
When a disk is specified, a logic error in _get_io_stats() results in statistics for all drives being summed, rather than just the selected drive.

Additionally, the filtering is a simple string match, so specifying "sda" or "/dev/sda" will sum stats for "sda", "sda1", "sda2", etc resulting in incorrect values.

Pull request is incoming momentarily to fix both of these issues.

**Comment by scotte** [comment]
In addition to fix PEP8 lint failure that was my fault, I updated the pull request with a better way to match the disk name - we have to parse the line at some point, so do that first and then just use the discrete field for the disk.

**Comment by ultrabug** [comment]
Thanks mate!
