### ISSUE TITLE
ValueError in i3status.py caused by race condition during timezone calculation

### ISSUE THREAD

**Issue by girst** [ultrabug/py3status#1375]
(this is an oldish bug report I've typed up and forgot about -- it is still valid, even though it is probably very-low-priority)

## ValueError in i3status.py caused by race condition during timezone calculation

**tl;dr**: Timezone calculation relies on parsing `i3status`' output and comparing it to `datetime.utcnow()`. Race conditions ensue when the computer is suspended during this time.

Last week I've got the following exception (yes, at 3 in the morning).

```
2018-03-16 15:32:22 INFO Module `imap 3`: updated.
2018-03-19 03:05:38 WARNING Runner (ValueError) i3status.py line 189.
2018-03-19 03:05:38 INFO Traceback
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
  File "/home/t/projects/py3status/py3status/core.py", line 59, in run
    self.module.run()
  File "/home/t/projects/py3status/py3status/i3status.py", line 132, in run
    if self.update_time_value():
  File "/home/t/projects/py3status/py3status/i3status.py", line 189, in update_time_value
    date = datetime.now(self.tz)

2018-03-19 03:05:38 ERROR py3status: Runner (ValueError) i3status.py line 189. Please try to fix this and reload i3wm (Mod+Shift+R)
```

As you can see by the INFO preceding the traceback, I've had my computer suspended for multiple days, and as soon as I turned it back on the exception happened.

I've dug around a bit, and here's what I've got: 
 * line 189 in i3status.py tries to get the current date+time from within a certain timezone.
 * the error message `offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).` occurs only once, [in datetime.py -> `class timezone(...)`](https://github.com/python/cpython/blob/3.6/Lib/datetime.py#L1965).  (do not confuse it with a very similar one at L258)
 * the `_minoffset` and `_maxoffset` values are defined [here](https://github.com/python/cpython/blob/3.6/Lib/datetime.py#L2045-L2046) (and are 1 minute less than the error message indicates...), and
 * looking at the offending if clause, `if not cls._minoffset <= offset <= cls._maxoffset:`, the problem has to be the `offset`, which - back to i3status.py - gets calcuated in [`set_time_zone()` line 226](https://github.com/ultrabug/py3status/blob/master/py3status/i3status.py#L226), before it is passed to py3's `Tz` class, which is then given to the function call that `ValueError`d. 

The error is here:
```python
        date = datetime.strptime(i3s_datetime, TIME_FORMAT) # i3s_datetime is a string passed into this function and read from i3status.
        # calculate the time delta
        utcnow = datetime.utcnow()
        delta = (                                                                                        
            datetime(date.year, date.month, date.day, date.hour, date.minute) -                          
            datetime(utcnow.year, utcnow.month, utcnow.day, utcnow.hour,                                 
                     utcnow.minute))
```

`date` looks like to be read out from a string (supplied by the i3status binary maybe?) and `utcnow` is generated a line before with `datetime.utcnow()`. 

I believe this is a race condition that showed up in the following way: 
 * on 2018-03-16, `i3status` generated a time string, that was passed to `update_from_item()`. 
 * the clock jumps to 2018-03-19
 * from there, `set_time_zone()` was called (probably due to the sudden jump in time).
 * `utcnow` gets set, and `delta` computed. `delta` is now ~3days instead of <24h.
 * when `.now()` is called, the `self.tz` gets casted into a `timezone` object and an exception with the above error message is thrown. 

Why is the timezone calculated in this roundabout way? Is it because i3status allows you to set the timezone in the config and we can't get at that value otherwise?

Anyhow; this issue has popped up once and I don't think it warrants much attention at this time, but I wanted to mention it in case someone else runs into that.

[modeline]: vim: syntax=markdown

**Comment by tobes** [comment]
> Why is the timezone calculated in this roundabout way? 

mainly because it's hard to do this without having `pytz` as a dependency without this guessing game. now we could maybe be more sensible if we have `pytz` but it'd still be good to fix this for people without it.

Thanks for your analysis

**Comment by tobes** [comment]
> I think depending on pytz shouldn't be that much of a problem

part of the py3status dream is minimal dependencies

can you see if the issue is resolved in master

**Comment by girst** [comment]
I've pulled the changes in; this isn't a nicely reproducible bug (hard to trigger race condition), so all I can do is see if the problem manifests itself again. (I'll reopen it then)

It does feel more like a workaround than a fix to me, though. :/ Thanks for the patch!
