### ISSUE TITLE
Better handling of transient interfaces in net_rate

### ISSUE THREAD

**Issue by scotte** [ultrabug/py3status#1377]
I use net_rate for a couple of tun interfaces that are transient depending on VPN connections. It would be nice if net_rate had some additional configuration on what to do for non-existent interfaces. Currently, the hardcoded text "net_rate" shows up, where ideally I'd just have no output from net_rate.

I saw "format_no_connection" - it doesn't help with this case but seems like a potential candidate to tie in to this (where no connection and no device are arguably similar).

I'll look into implementing this, but figured I'd park the feature request here for now.

**Comment by scotte** [comment]
Ah! So it's actually a bug, I think:

```
ValueError: max() arg is an empty sequence
  File "/usr/lib/python3/dist-packages/py3status/module.py", line 729, in run
    response = method()
  File "/usr/lib/python3/dist-packages/py3status/modules/net_rate.py", line 143, in currentSpeed
    interface = max(deltas, key=lambda x: deltas[x]['total'])
```

This is good, because it shouldn't be too hard to fix. Working on a solution now...

**Comment by lasers** [comment]
First, welcome to py3status. :-)

>Currently, the hardcoded text "net_rate" shows up

Not hardcoded. That can be custom error or exception being handled in i3bar instead of former annoying `i3-nagbar`. You can left-click to toggle/view the message and right-click to dismiss the module. This shows that maybe errors should be more obvious, eg always display the error messages.

**Comment by scotte** [comment]
Sorry, "hardcoded" was a poor choice of words - placeholder due to bad data. I actually didn't know that it was clickable for a message, nice!

Thanks for the welcome - I looked at py3status several years ago (2014 per #43) when it was fairly new - I never got around to revisiting it until now and am really happy to have finally been able to throw away my hacked-in conky-emitting-json statusbar. Great to see where it is today - should have done this a long time ago. :-) Thanks!
