### ISSUE TITLE
whatismyip not working

### ISSUE THREAD

**Issue by leachim** [ultrabug/py3status#1401]
I get this error when running python whatismyip.py, with the current version of that file (from the master branch, py3status version 3.11). 

> 'NoneType' object has no attribute 'get' (AttributeError) module.py line 732.
> Traceback
> AttributeError: 'NoneType' object has no attribute 'get'
>   File "/home/user/.anaconda3/lib/python3.6/site-packages/py3status/module.py", line 732, in run
>     response = method()
>   File "whatismyip.py", line 135, in whatismyip
>     info = self._get_my_ip_info()
>   File "whatismyip.py", line 127, in _get_my_ip_info
>     info[old] = info.get(new)

Configuration file: 
whatismyip {
format = "{ip} ({country})"
hide_when_offline = True
color_good = '#e89393'
color_bad = '#e89393'
color_degraded = '#e89393'
}

I am running python 3.6.6, ananconda build. 
I can run `curl https://ifconfig.co/json` successfully.

Any idea, what might cause this behavior? Any changes in the py3status structure, specifically the self.py3.request part?

**Comment by lasers** [comment]
Most likely related to https://github.com/ultrabug/py3status/pull/1398 because this returns `None` instead of a (dict) data.

**Comment by ultrabug** [comment]
Fixed by #1406 thanks!

Will be available in 3.12

**Comment by nylocx** [comment]
I know that this issue should be closed, but I get an almost identical stacktracke every 1 to 3 Minutes:
```
2020-07-01 19:22:13 WARNING Instance `whatismyip`, user method `whatismyip` failed (AttributeError) whatismyip.py line 116.
2020-07-01 19:22:13 INFO Traceback
AttributeError: 'NoneType' object has no attribute 'get'
  File "/usr/lib/python3.8/site-packages/py3status/module.py", line 940, in run
    response = method()
  File "/usr/lib/python3.8/site-packages/py3status/modules/whatismyip.py", line 138, in whatismyip
    info = self.ip_data = self._get_my_ip_info()
  File "/usr/lib/python3.8/site-packages/py3status/modules/whatismyip.py", line 116, in _get_my_ip_info
    info[old] = info.get(new)
```
Should I open a new issue or do you want to reopen this one?

I have to say that the IP renewal works half of the time, so it is nothing that happens in every call.

**Comment by ultrabug** [comment]
@nylocx thanks

I'm reopening since indeed we did not fix this properly.

I traced down the source of the problem now. I just need to understand/remember why the py3status.request handler do not want to raise an HTTP exception when something like a 500 is returned... for now it returns a json = None which is why this error happens.

I shall fix this quick now; thanks for your patience

**Comment by ultrabug** [comment]
@nylocx this should be fixed. In case you can test master, I'd be happy to get your confirmation

FYI when this happens, modules will not crash but placeholders won't be replaced in the format

**Comment by nylocx** [comment]
@ultrabug Thanks for the quick fix, I'am running on "3.28.r7.g12c02739" (latest master) since this morning and did not have an error case yet.
So for me it looks like this is fixed.

**Comment by ultrabug** [comment]
@nylocx thanks for your feedback

I'm still asking myself about this logic of py3.requests silently returning an empty response on HTTP errors..
I see three options:
- it is good as-is, do nothing
- we should raise it and let every module decide what do to when remote servers return non 200 code
- we could abort the module update on the core altogether and display the "last successful refresh value" (maybe color given modules as degraded to alert user?)

Would you have an opinion on this?

**Comment by nylocx** [comment]
Personally I would go with a mixture of 1 and 2. Because going to 2 directly would probably break some compatibility with existing modules. For near future I would make it an optional parameter of the request, like `raise_error` and default to `False` to silently return nothing as it currently is. But if a module is interested in the info of failed requests it could easily handle it in a try catch and set `raise_error=True`.
In the next major release you could deprecate the default, than move to default to `True` and finally remove the option again if everybody is happy with it.

**Comment by ultrabug** [comment]
The problem with that IMHO is still that modules do get an empty response, so they store it as if it was real and users can see their format output variables not being replaced

Wouldn't we prefer not to update the module's output in that case instead? That's option 3.

**Comment by nylocx** [comment]
Yeah that would be a better option, I was thinking that this is what is happening but as if too poof me wrong I just got an `{ip}` output on my bar :).
So yes going for 3 on the do not raise case would be better.

**Comment by ultrabug** [comment]
@nylocx I tried implementing this but I'm unhappy with the result as the current logic of py3status is not meant to handle that kind of case

I'll add this point to the 4.0 RFC instead
