### ISSUE TITLE
window_title_async stopped working after python updated to 3.7.0

### ISSUE THREAD

**Issue by mrpewpew** [ultrabug/py3status#1405]
After python updated to 3.7.0, I had to recompile py3status arch package for it to work again. Everything seems OK except for window_title_async. I suppose it is linked to the python update. 
Anyone experiencing the same issue ?

**Comment by lasers** [comment]
`scratchpad_async` is broken too because it also uses `i3ipc`. Try [aur/i3ipc-python-git](https://aur.archlinux.org/packages/i3ipc-python-git/).

**Comment by maximbaz** [comment]
[aur/i3ipc-python](https://aur.archlinux.org/packages/i3ipc-python) works as well, but if you are using this one, you had to recompile it after python 3.7.0 was released. In fact, you have to rebuild a lot of packages, a good rule of thumb is to rebuld all packages in `/usr/lib/python3.6/site-packages/` until this folder becomes empty.

**Comment by mrpewpew** [comment]
Yes your solution works, @maximbaz . Thanks !
