### ISSUE TITLE
Bitcoin charts not reloading when waking up from sleep

### ISSUE THREAD

**Issue by fxleblanc** [ultrabug/py3status#141]
To view the data again, I had to reload i3 itself. Is there a way to reload specifically the bitcoin price plugin?

**Comment by ultrabug** [comment]
Hi @fxleblanc,

Do you mean to refresh the data ? If so, the default "force refresh" behaviour is to middle click on the module you want :)

**Comment by fxleblanc** [comment]
Sorry, I wasn't clear enough. What happens is that when I lose my internet connection, say when I go in sleep mode and go away from a wifi hotspot, the ui prints that Bitcoincharts is unreachable when I come back from sleep and connect to a new wifi hotspot . I'll try to click next time and I'll give feedback.

**Comment by fxleblanc** [comment]
The middle-click worked. It just takes some time. I was thrown off at first because of the message. Thanks for your patience.

**Comment by ultrabug** [comment]
@fxleblanc about the time it takes, if you're using the latest py3status 2.7 it should be instant unless the bitcoin server used takes time to connect/response ;)

Have fun, closing !
