### ISSUE TITLE
Module weather_owm broken, timezoneapi not available in some area

### ISSUE THREAD

**Issue by PetrusZ** [ultrabug/py3status#1433]
https://timezoneapi.io/ return error code 503 in part of China, HK, JP and etc for a while(couples of days). It make weather_owm not functional.

**Comment by lasers** [comment]
@alexoneill

**Comment by tobes** [comment]
#1460 addresses this issue @PetrusZ if you could confirm this fixes your problem that would be great

**Comment by PetrusZ** [comment]
@tobes Both city and location param work perfect, thank you.

**Comment by ultrabug** [comment]
merged, thanks for reporting @PetrusZ !
