### ISSUE TITLE
Wanda makes a lot of noises in the log

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1479]
Hi friends. I adore `wanda_the_fish` too much. I am a horrible father for abandoning `wanda_the_fish` everytime I collaborate on py3status. I'd like an option to adjust log verbosity or to simply turn off the logs. Exceptions should always be kept in the logs too.

I also think it'd be great if we could default `wanda_the_fish` with no logs.

I'm thinking about a per-module/global option too... that can tune out the noises in other modules without turning them off... by redirecting attention toward this module only... rather than to keep working and/or grepping through all the noises.

Here's a list of some modules that already make lot of noises.

* `backlight.py`:    cache_timeout = 10
* `dpms.py`:    cache_timeout = 15
* `file_status.py`:    cache_timeout = 10
* `gpmdp.py`:    cache_timeout = 5
* `keyboard_layout.py`:    cache_timeout = 10
* `keyboard_locks.py`:    cache_timeout = 1
* `lm_sensors.py`:    cache_timeout = 10
* `loadavg.py`:    cache_timeout = 5
* `pomodoro.py`: cache_timeout = 0
* `spotify.py`:    cache_timeout = 5
* `timewarrior.py`:            self.cache_timeout = 0
* `wanda_the_fish.py`:    cache_timeout = 0
* `window_title.py`:    cache_timeout = 0.5
* `xsel.py`:    cache_timeout = 0.5

It's not worth to list all modules that can refresh every `<= 20` seconds, but you get the idea.

**Comment by tobes** [comment]
maybe just turn of debug mode https://py3status.readthedocs.io/en/latest/intro.html#options

but yes per module debugging would be nice at some point.  It is generally too noisy so I never really have it turned on. but if it was more clean then I'd probably use it.  Even in core it would be good to have limits on what is logged in debug mode as in which chunks of the code, events, modules, formatter ... but for modules it'd be simple enough to implement.

Also talking of noise try to keep you comments succinct too :).

**Comment by tobes** [comment]
A feature request is a specific thing this is a ramble

**Comment by lasers** [comment]
Okay, I turned off debug. I'll see if I can get used to this. I often leave this on to identify or study module issues and/or behaviors better between intervals.

Feature is that I am looking for a way to filter out other modules, but still keep core, startup, exceptions, etc on... I often need this only when I'm working on a new module... or a new module from scratch. Maybe it's an non-issue with `debug` off and I can always try to grep things with `debug` off too.

I go ahead and close this feature request and/or ramble.
