### ISSUE TITLE
spotify.py

### ISSUE THREAD

**Issue by Kuchenm0nster** [ultrabug/py3status#148]
Hi, I'm new to github and this kind of stuff.
spotify.py does not recognize my spotify and tells me it is not running so i looked into the code and fixed it.
Maybe you can look into it and merge it?

**Comment by ultrabug** [comment]
Hi @Kuchenm0nster welcome and thank you, I'm always very happy when new comers start their contributions on py3status !

Let's discuss this on your PR #149 !
