### ISSUE TITLE
group: render only currently-visible module

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1501]
I noticed that even though only one element of a group is displayed, all of them are being rendered.

```
group test {
  external_script {
    cache_timeout = 5
    script_path = 'notify-send 1 1'
    format = '1'
  }

  external_script {
    cache_timeout = 5
    script_path = 'notify-send 2 2'
    format = '2'
  }
}
```

I was wondering, won't it make sense to save time and only render currently-visible module? Instead we could trigger refresh when elements in the group are being scrolled, this doesn't happen now.

**Comment by tobes** [comment]
It depends. Some notify me eg github. And change the group in this situation. But yeah many could sleep. I think we need to decide for each module. The question is do we tag modules that can sleep or one's that cannot?

**Comment by maximbaz** [comment]
Every module gets a boolean property `cache_hidden` similar to `cache_timeout`, default to `True`, that can be overridden by a user — would this work?

**Comment by tobes** [comment]
long term maybe this is good.

For now I'd just get the basic feature so that we know our suspend/restart modules is working great.   So for the simple ones. Then up the game.

But my main thing is to not have it user accessible to start with - which is why just the can stop ones is good.  Once we have the feature fully formed then make it user settable

**Comment by lasers** [comment]
@maximbaz See if #1183 works for you.

**Comment by maximbaz** [comment]
I don't have a command to run, so I don't think `switch` is a good fit for me... I explained my use-case in #1502, see the "what I want" part 🙂

**Comment by lasers** [comment]
Well, here... `switch` with `cache_timeout` literally is a perfect solution for your example above. :slightly_smiling_face: 
```python
group test {
  external_script {
    cache_timeout = 5
    script_path = 'notify-send 1 1'
    format = '1'
  }

  external_script {
    cache_timeout = 5
    script_path = 'notify-send 2 2'
    format = '2'
  }
}
```
```python
order += "switch notifications"
switch notifications {
    button_next = 4
    button_previous = 5
    cache_timeout = 5
    list = [
        ('\?color=#268BD2 1', 'notify-send 1 1'),
        ('\?color=#F75252 2', 'notify-send 2 2'),
    ]
}
```
For your "what I want" part, we'll keep the discussion going over there. :wink:

**Comment by maximbaz** [comment]
Oops, you are totally right, I completely forgot that I made a toy example based on `external_script` 🙂 

In reality my use-case is about `wifi` module 🙂

**Comment by tobes** [comment]
>  See if #1183 works for you.

This is not relevant to the subject of this issue which is about updates to hidden modules which is a real issue even if it can be avoided in this one instance
