### ISSUE TITLE
Allow formatter to switch between different outputs of the same module

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1502]
#### What I want

I found myself often wanting the same feature from different modules: toggle between short and descriptive output.

For example, #1501 is inspired by wanting to have `wifi` module just showing the icon (green icon means I have connection, red icon means I'm offline), but on click I want to see SSID next to the icon (and next time I click, I again want to see the icon alone).

With #1500 I want similar, by default have `sysdata` module just output usage of CPU and memory, but by clicking on the module I want to get more detailed description (most cpu-hungry and most memory-hungry process names).

`whatismyip` module also has this toggling functionality, which is hardcoded and cannot be turned off, and in this case it is a bit annoying because for `whatismyip` module I _don't_ want the toggling functionality.

#### How I currently achieve this

```
group wifi {
  wifi {
    # ... my configs
    format = 'ON|OFF'
  }

  wifi {
    # ... copy of my configs
    format = 'ON {ssid} ({signal_percent})|OFF'
  }
}
```

Problem is, it's quite verbose and leads to config duplication, and as mentioned in #1501 it doubles the load, py3status refreshes both `wifi` modules, not only the currently-visible one.

#### Ideas on how to better implement this

I was thinking we could introduce a counter of clicks, and base on it some conditional logic in the format string, but I'm not sure how exactly... Modulo won't work I think.

We could make `format` be a list instead of string, and internally in every module keep track of click counter and cycle through this list, but it feels like a not generic solution.

Any other ideas?

**Comment by tobes** [comment]
> Any other ideas?

yeah lots but the implementation is not the issue.  The issue is __only__ about how we do this in the config.  one option is a list of formats like the clock module has.  Maybe we make this universal.  The thing is it would bepend on some core click changes I plan to implement (if they are accepted)

**Comment by tobes** [comment]
> I think we should not only use this for format but for all options

Interesting idea but I think separate from this one as it has a different usecase.  It is also more complex as you'd need multiple instances of a module.  So we'd need to do a lot more work and needs #1501

**Comment by maximbaz** [comment]
I agree that if I had more options different, I would rather choose to use group + multiple instances of the same module, the configuration would look much more cleaner comparing to bundling everything in one place. And #1501 would help reducing the perf cost of using multiple instances 😉
