### ISSUE TITLE
3.12 release doesn't have latest commits

### ISSUE THREAD

**Issue by mhdali** [ultrabug/py3status#1505]
aur-py3status package https://aur.archlinux.org/packages/py3status/ is failing on installing.

it's giving me this error
```
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools.command.easy_install import _to_ascii, ScriptWriter
ImportError: cannot import name '_to_ascii' from 'setuptools.command.easy_install' (/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py)
```

Looking at the package source code, seems we removed the dependency on Jul 9, however the AUR uses 3.12 release which has been released on Aug 9 (which is a month later).
But the 3.12 release dosen't contain the fix.

I already fix my local by using master branch and build the package from there.

But to fix `aur-py3status`, it's better to release new release and we just install the tarball ;)

Thanks for awesome tool.
Cheers

**Comment by lasers** [comment]
Closed via #1508.
