### ISSUE TITLE
Parisian question, bike sharing 🚲 

### ISSUE THREAD

**Issue by cyrinux** [ultrabug/py3status#1512]
@ultrabug @tobes do you take velib ? ;)

I'm doing another module for velib for bike sharing.

I have find a good python but python2 only project which make me dream for few minutes...

My main goal was to make a bike sharing for velib but if I can make one more generic this would be wonderfull.

The cool  stucked? project is https://github.com/eskerda/pybikes/pull/284

I have also find blog post about api which are bad.
I have started and get working a embryonic  module which give me informations for my velib station with using an undocumented api, which one used on the default velib metropole map... 

 https://www.velib-metropole.fr/webapi/map/details?gpsTopLatitude=48.87170154444531&gpsTopLongitude=2.3671030998229985&gpsBotLatitude=48.863938392400414&gpsBotLongitude=2.346911430358887&zoomLevel=16

General question, before go further, what  would you do? Wait for a real api? Wait for pybikes move about python3?
Use an opendata which less info like  https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_status.json (how to get my station id?)

That the point, would like to do something but in a good way, if you have advise, I take.

sources:
https://github.com/eskerda/pybikes/issues/299
https://github.com/nipil/velib-metropole-stats/blob/master/vms.py
sqlite dump of station...
https://pub.phyks.me/datasets/velib/
in french
https://nipil.org/2018/02/17/api-velib-metropole-manque-de-fiabilite.html

**Comment by cyrinux** [comment]
Same thing for me but seems be OK now. Was sad.
The goal will be to have info about station, would be happy if i can get my user stats too but ...
Also, pybikes guy reply me, the project will maybe progress.
I will do first version without it. And if one day I can use pybikes i will do. Hope we will be able to merge the version without pybikes first ;)

Here a demo a my velib metropole, will work on code before do a PR.
![velib_metropole](https://user-images.githubusercontent.com/519083/45390010-f8d7d000-b61d-11e8-8756-3e151a33167f.gif)

Green counter are not electrical bike and blue electrical :)

**Comment by tobes** [comment]
> Here a demo a my velib metropole

I think starting with velib and then seeing about other schemes would be nice (or wait for pybike I voted for the python 3 changes)

**Comment by lasers** [comment]
With #515 merged, it seems like we should close this now unless otherwise stated.
