### ISSUE TITLE
Composite index strings are not always strings 

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1516]
I ran into a functionally blocking user facing bug for `? from scratch`.

The bug is that the [composite](https://py3status.readthedocs.io/en/latest/writing_modules.html?highlight=composite) documentation says this...
>Supplied index values should be strings. If no index is given then it will have an integer value indicating its position in the composite.

When I pass in `str(int)` value, I get an `int` instead of `str(int)`.

* Gave `format(123456789)`
* Expected `'123456789'`
* Got `123456789`

Options:
1) Modules that passes `int` alone must find alternative solutions such as giving `str(float(value))` then `int(float(str))` later or to use prefix, eg `timewarrior/22`, to be split up later.
2) Keep `str(int)` as-is. Same for `int`. It's done by prefixing `int:` and `str:`. [int-vs-str](https://github.com/ultrabug/py3status/tree/int-vs-str). This sometimes can produce ugly logs.
3) Don't give numbered `index`. Use `index` only when we give them.

This probably broke `timewarrior` too with `isinstance` and I didn't notice it.
https://github.com/ultrabug/py3status/blob/d395f2e57b95b1307eeed1c44d0bbc50825e7c3b/py3status/modules/timewarrior.py#L325-L330

Let me know what you would like to do here.

**Comment by tobes** [comment]
This is a limitation due to i3bar. It sounds like you are trying to abuse things.

Better documentation is the solution and in your module either you care about the index which is int or give it a proper name.

Simplicity is the best option. If you are passing '2' as an index you are doing it wrong for at least one reason

**Comment by lasers** [comment]
Me abusing things? No way... :blush: 

* Yes on `time_index` (on a list of time intervals) for `timewarrior`.
* Could had gave `device_id` for `usbguard`.
* Container ID for `scratchpad` which looks like `123456789`.

This probably broke `google_calendar` too.
https://github.com/ultrabug/py3status/blob/d395f2e57b95b1307eeed1c44d0bbc50825e7c3b/py3status/modules/google_calendar.py#L382
https://github.com/ultrabug/py3status/blob/d395f2e57b95b1307eeed1c44d0bbc50825e7c3b/py3status/modules/google_calendar.py#L441-L442

I'll go with `split` thing. Make this nice for `py3-cmd --index` too.

**Comment by lasers** [comment]
I assume `google_calendar` still can break (ie open wrong event URL) based on number of composites. This code does not look trivial to fix so I will leave this as-is. I wrote documentation and made a pull request to address `timewarrior`.

It's only `timewarrior` and `google_calendar` that uses `composite_update` right now so we would have seen this bug sooner or later as we're adding more and more modules that uses `composite_update` + `index`... such as `usbguard`, `xrandr_tweaks`, `modules from scratch`, etc.

We should be good here.

P.S.  Can you fix so `index` numbers does not print with leading spaces too? Thx.

**Comment by lasers** [comment]
> * `index` - The index of the output. Allows composite output to identify which component of their output had an event triggered.

>The index key in the response is used to identify the individual block and when the modules on_click() method is called the event will include this. Supplied index values should be strings. If no index is given then it will have an integer value indicating its position in the composite.  [source](https://py3status.readthedocs.io/en/latest/writing_modules.html?highlight=composite%20index#composites)

I supplied the string meant to be utilized in a command parameter according to the individual block... instead of using the string to identify the individual block. As mentioned, it can be misused (i.e. I pass in i3wm container id for `scratchpad` to raise... or device id for `usbguard` to accept/block/reject. 

There are many different and rather easy ways to overcome this so I'm not concerned about this at all. Splitting `index` off `instance` is nice and all. I suppose one could make `literal` that would be anything inside a string... then use `ast.literal_eval()` to give us more than just an int / string.

>**lasers**
Close or merge `#1518`. At most, it's a minimal inconvenience. The odds of having new modules in the future that relies on composite index and happens to be passing along numerical strings too is pretty low. The workaround is also trivial enough to make a decision on writing this down or not.

>**ultrabug**
>Ok, as per `#1589` I think that if that's not something we want to push for, no need to document it as the probability of use cases is low

Utterly ridiculous to find a solution for something so trivial. Use Option 1 above if needed. Closing.
