### ISSUE TITLE
py3status, logo proposal

### ISSUE THREAD

**Issue by cyrinux** [ultrabug/py3status#1528]
Hi guys,

I have ask to my gf is she can make one for us. 

I have explain her what our project do and use, i3, i3bar, python etc and she make this.

Here the first draft.
Do you like? Do you have comment? 

![draftlogo](https://user-images.githubusercontent.com/519083/45928302-b24d7400-bf41-11e8-9396-68260990c5a2.png)

Thanks :)

**Comment by tobes** [comment]
It's fun - and it scales nicely even at tiny sizes.

**Comment by ultrabug** [comment]
Thanks a lot @cyrinux I've been willing to have a logo for so long...!

I like the idea of the logo tho I find it a bit "fat" compared to the i3wm one:

![image](https://user-images.githubusercontent.com/474389/46194895-ff936200-c302-11e8-9c5f-05e960259bda.png)

Maybe it's me and it's okay to not have the logo close to i3wm, but I always wanted to have something that shows they're bound together

On the color side, I'd be for diverging from official python colors and maybe get closer to i3wm colors as well

Thanks again!

**Comment by tobes** [comment]
i3wm logo is kind of ugly

**Comment by ultrabug** [comment]
@tobes that's why we can do better with :snake: !

**Comment by cyrinux** [comment]
Thanks for your replies, gf will try to do another proposal.

**Comment by cyrinux** [comment]
Will reping my gf to see if she can find time for another try. Before this, do you have remark, you want someting special, change on the first version?

**Comment by lasers** [comment]
@cyrinux Have you asked your lamb to work on this? If not, I can ask somebody else.

**Comment by lasers** [comment]
@Tobaloidee

**Comment by Tobaloidee** [comment]
Hi @lasers  I can be of help here 👍

**Comment by Tobaloidee** [comment]
will post here the design that I am going to came up with 💯

**Comment by Tobaloidee** [comment]
Here's what i came up with...I hope you like it..still open for suggestions.

-the logo design is minimal and clean..visible in small scales
![py3status pres-02](https://user-images.githubusercontent.com/36028424/55671404-44a3dc80-58c2-11e9-9128-56b4408468d3.png)

**Comment by lasers** [comment]
@Tobaloidee Very nice! Can we play with more things? I wonder how it would look like if it have more colors similar to `Denver Nuggets` logos and I also wonder how it would look like in non-Python colors (i.e. mockup violet color above).

Other thing. I wonder how it would look if we fill a partially filled square with a different color filler (i.e. darkblue) and still keep outer color square alone? Or add different color stroke/border? 2 vs 3 colors.

P.S. I like logo 2.

**Comment by Tobaloidee** [comment]
Surely! will try some color combinations 👍

**Comment by Tobaloidee** [comment]
here
line 1 are the first draft
line 2 are 3 colored with shadow  (denver nuggets 2A) 
line 3 are outlines
line 4 are gradients
![py3status-03](https://user-images.githubusercontent.com/36028424/55672565-01039f80-58cf-11e9-9419-988236924e74.png)

**Comment by maximbaz** [comment]
Very, very nice job 👍 I like 1A the best, but regardless of the chosen colors, the concept is awesome!

**Comment by lasers** [comment]
I didn't notice this before. The edges are wavy. I think it would look better straight and clean cut. Also, try B3 with inner yellow like A2 (and maybe add some white in there somehow). I like first line, C2 and denver nugget A2. Gradient A4 looks nice too. Not sure what color @ultrabug want to go with.

**Comment by Tobaloidee** [comment]
So glad that you liked it @maximbaz 😃

**Comment by Tobaloidee** [comment]
@lasers I have updated the display of the icons and made a straighten up version of the inner yellow that you said... It looks visually wavy but it is not..haha

**Comment by lasers** [comment]
>Also, try B3 with inner yellow like A2 (and maybe add some white in there somehow).

Sorry if I wasn't clear enough. See Sample 2. I made Sample 1 too. Sample 3 is yours.

![2019-04-06](https://user-images.githubusercontent.com/852504/55673329-5eb2d000-586c-11e9-9fdb-f5e30a3e424b.png)

>I'll wait for the final choice of @ultrabug to finalize it earliest tom!

I agree. Thank you for doing this! :smiley:

**Comment by ultrabug** [comment]
Wow @Tobaloidee I'm speechless, the concept is just exactly what I had in mind and the result is stunning!

First of all, **thank you so much**!

I'm a big fan of both 1A and 2A, I just see them as two different declensions:
- 1A would be the basic / default one, the kind you can have a favicon out of
To take github as example, it's like having:
![GitHub-Mark](https://user-images.githubusercontent.com/474389/55674475-998d2600-58b5-11e9-87ed-da4491166320.png)

- 1B would be the colored one, the kind you can have your own variants of and play with
To take github as example again, would be like:
![Octocat](https://user-images.githubusercontent.com/474389/55674481-ac9ff600-58b5-11e9-9f7b-9b5981dd5a2c.png)

Does it make sense?

Thanks again!

**Comment by josefson** [comment]
I really liked 4a or 1a, i like purple  better than blue, but the concept dwarfs the importance of the color from my perspective.

**Comment by Tobaloidee** [comment]
I finalized the files and uploaded & updated the readme file with this PR #1768 
Also, you can download all the chosen (liked) versions of the logo [HERE](https://drive.google.com/drive/u/1/folders/1y0AqDYOIEOoY0phZPXNkA1cmPIepCbSH)

 if ever you want to use different color versions. I am glad to be of help to you guys! Whenever you need logo design just mention me in the future. :) Cheers! 

Thanks and best regards! 
-Tobaloidee

**Comment by ultrabug** [comment]
Thanks a lot @Tobaloidee 

Do you confirm all these versions are straighten ones? some of them look so to me while some others not... might be a visual effect tho

**Comment by lasers** [comment]
Request a version of all logos rotated like A5 in case we don't like the visual effect / rotation / etc.

**Comment by Tobaloidee** [comment]
Its all straighten up..i will upload to my drive  the squared versions 👍 earliest tom @ultrabug @lasers

**Comment by ultrabug** [comment]
Cheers @Tobaloidee will copy again when you confirm. Thanks again for your amazing work and reactivity :)

**Comment by Tobaloidee** [comment]
I updated my [DRIVE](https://drive.google.com/drive/u/1/folders/1y0AqDYOIEOoY0phZPXNkA1cmPIepCbSH) for the rotated versions @ultrabug  👍

**Comment by ultrabug** [comment]
Thanks!

**Comment by ultrabug** [comment]
@Tobaloidee hi, I forgot to ask you about the license you'd like the logo to be used upon please?

**Comment by Tobaloidee** [comment]
It's <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.  😃

**Comment by ultrabug** [comment]
Thanks a lot @Tobaloidee :+1:

**Comment by Tobaloidee** [comment]
I am just a mention away if you need help with logos in the future 👍👍👍😃
