### ISSUE TITLE
cannot install with apt-get on Ubuntu 16.04

### ISSUE THREAD

**Issue by fmv1992** [ultrabug/py3status#1529]
I cannot install as stated in the [documentation](https://py3status.readthedocs.io/en/latest/intro.html#installation):

    # apt-get install py3status
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    E: Unable to locate package py3status
    # uname -a && lsb_release -a
    Linux xxxx 4.15.18-041518-generic #201804190330 SMP Thu Apr 19 07:34:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.5 LTS
    Release:	16.04
    Codename:	xenial

Could you please help me?

**Comment by tobes** [comment]
looks like it's just in 17.10+ https://packages.ubuntu.com/search?keywords=py3status

you should be able to install via pypi

**Comment by fmv1992** [comment]
Indeed. It worked perfectly with `pip` install. I asked because such procedure was disencouraged somewhere in the docs. Thanks for the software!
