### ISSUE TITLE
200th star wish

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#153]
Hi @eivindj !

You're the 200th star of `py3status` thank you very much and congratulations :)

As being the one, I came up with the idea of asking you about the module of your dream you would wish to see available in py3status ? I'll be glad to make it happen for you !

Cheers :+1:

**Comment by eivindj** [comment]
Hi .

That's a tough question, I recently started looking into i3status setups
again :)

I'll get back to you when I can think of something

On Tue, Dec 22, 2015 at 6:41 PM, Ultrabug <notifications@github.com> wrote:

> Hi @eivindj <https://github.com/eivindj> !
>
> You're the 200th star of py3status thank you very much and
> congratulations :)
>
> As being the one, I came up with the idea of asking you about the module
> of your dream you would wish to see available in py3status ? I'll be glad
> to make it happen for you !
>
> Cheers [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ultrabug/py3status/issues/153>.
>



-- 
Best regards,
Eivind Josten
Infrastructure Engineer
Kahoot!

**Comment by ultrabug** [comment]
We'll be reaching the 300th soon, I'll close this issue and please feel free to reopen whenever a need of yours arise :)

**Comment by eivindj** [comment]
Alright, sorry! Thankful for the offer :)
