### ISSUE TITLE
Strange problem with tray_output

### ISSUE THREAD

**Issue by EvilMegaDroid** [ultrabug/py3status#1530]
Lately I've been having this weird problem with my tray output icons.
They kind of start swapping places or icons. Here's a pic to explain it better.
https://i.imgur.com/vJPSPmC.png
I'm running a dual monitor setup and this happens on both monitors

**Comment by lasers** [comment]
Nothing to do with py3status. See https://github.com/i3/i3/issues/3414.

**Comment by EvilMegaDroid** [comment]
Damnn as I though. Thanks
