### ISSUE TITLE
Improve notifications in `battery_level` module

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1531]
I think the way notifications are implemented in PR #1439 (here: https://github.com/ultrabug/py3status/pull/1439/commits/c6a1c2146294ed1c90ba7153df3c9fb41d130fe9) is awesome, I think it makes sense to re-use this pattern in `battery_level` module.

Currently `battery_level` has a bunch of properties to control notifications:

- format_notify_charging
- format_notify_discharging
- notification
- notify_low_level

All of this could be replaced with a single `notifications` parameter of a dict type.

This would additionally allow to set different title and icons, which would have otherwise required many more new parameters.

In case there will be more changes, let's see #1439 merged first, then improve `battery_level` by example.

**Comment by maximbaz** [comment]
I looked into it and I'm really not sure how much we can generalize, it sounds like every module will show notifications at completely different times and even on the same event (on click) modules may choose to show different messages to a user.

For example, in `external_script` or `update` I need to show notification on click, i.e. `notifications = {'click': {'msg': '{output_full}'}}`

In battery, it will already be different based on threshold, i.e. 

```
notifications = {
  'click_charging': {'msg': 'Charging: {percent}'},
  'click_discharging': {'msg': 'Discharging: {percent}'},
  'threshold_degraded': {'msg': 'Battery running low: {percent}'},
  'threshold_bad': {'msg': 'Battery critically low: {percent}'},
}
```

There are also modules which show notifications at completely random times, `github` shows them on error (sounds weird to me), `pomodoro` shows when timer reaches `0`, etc.

So there are some common patterns (show notification on click) and some different patterns, but even common patterns might generate different notifications based on some internal state of the module.

Have a look when you get a moment, maybe you'll have some idea how this can be generalized.

**Comment by ultrabug** [comment]
As I said on IRC, I wouldn't know how to begin with #1439 since it's so huge and full of comments.

Maybe we try to do too much things there and we should just add the feature you want as simply as possible for your use case and that's good enough.

It would be easy to reason with first. Then keep it in mind for later?

**Comment by maximbaz** [comment]
Well to be fair all I really wanted is implemented in the first two commits: https://github.com/ultrabug/py3status/pull/1439/files/e007e2795fcdb2fa8c0030bba9872260f7479691

The rest is attempts to address @lasers' feedback and making it more generic 🙂

**Comment by lasers** [comment]
>As I said on IRC, I wouldn't know how to begin with #1439 since it's so huge and full of comments.

That one is done in `external_script`. I said I'd give it a shot to move them to `py3`. Here it is...

https://github.com/ultrabug/py3status/compare/master...lasers:py3-notifications

If I understand this right, this should be similar to `thresholds`. If users want to add notifications, they should have to add `notifications_set(data)` and/or `notifications_set(data, 'click')` in the wanted modules and create a minimal or full-fledged `notifications` config. I tested only `external_script`.

As for `states`, we can create them in `py3`. I'm thinking we retain the common states... eg, `changed` for 99% of the module's scenarios... and `click` to make a particular somebody happy. We likely don't need `current`, but seeing how `current` is `current`, we should keep it anyway.

My trivial concern is that `notifications` config does not look friendly. I'm all for suggestions such as a list of (str, dict) tuples or anything you have in mind. Other than that, I think this is "good enough".

**Comment by ultrabug** [comment]
## click & refresh

TBH now that we have click modifiers support I'd be more inclined to change the default of click = refresh to something like CTRL+click or SHIFT+click instead

I was never happy of this auto-refresh thing anyway...

This would give more power to click buttons without forcing us to create a workaround mess around click+prevent refresh etc

## notifications rework

Maybe add it to 4.0 milestone?

**Comment by maximbaz** [comment]
Agreed! Please add both points to `4.0` ticket.

**Comment by lasers** [comment]
@maximbaz https://github.com/ultrabug/py3status/tree/shift%2Bmiddleclick to solve **`click & refresh`**. Using `Mod?` instead of `Shift` is consistent with i3wm's `Mod1-5`. This reduce workaround mess around click+prevent refresh, etc.

**Comment by maximbaz** [comment]
Since we are rethinking this approach anyway, I'd like to propose to stay away from middle click — y'all probably use mouse and don't know the pain, but I only use touchpad and I hate middle click (which for me is touch with 3 fingers at once), I never know if I successfully triggered refresh or not.

As to Shift vs Mod1-5, especially if refresh becomes `Mod?+leftclick`, I feel it's a bit impractical to reserve all modifiers for refresh. But don't know, depends on whether we decide to expose modifiers for modules, so that modules themselves can have different behaviors on leftclick vs shift+leftclick vs ctrl+leftclick vs etc. If not, then I guess `Mod1-5 + left click = refresh` is fine.

**Comment by lasers** [comment]
>... y'all probably use mouse and don't know the pain, but I only use touchpad and I hate middle click (which for me is touch with 3 fingers at once), I never know if I successfully triggered refresh or not.

>... whether we decide to expose modifiers for modules, so that modules themselves can have different behaviors on leftclick vs shift+leftclick vs ctrl+leftclick vs etc.

@maximbaz  I think you would like https://github.com/lasers/py3status/tree/on_refresh for your touchpad. You can have different behaviors too similar to `on_click`, but for `refresh`. :blush:

I think if we were to try consolidating `on_click` and `on_refresh` together into `on_event`, then we might be able to specify event options better to address known click limitations #1264 including the ability to disable `refresh` for your external scripts.
