### ISSUE TITLE
travis tests very noisy on python 2.7

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#1534]
travis tests for python 2.7 create a lot of noise in the logs during flake8 test

```
/home/travis/build/ultrabug/py3status/.tox/py27/lib/python2.7/site-packages/flake8/options/config.py:69: DeprecationWarning: You passed a bytestring as `filenames`. This will not work on Python 3. Use `cp.read_file()` or switch to using Unicode strings across the board.
  found_files.extend(config.read(filename))
```

it would be nice if we could silence these to make the test results more friendly and readable

**Comment by lasers** [comment]
Duplicate #1230 (?)

**Comment by tobes** [comment]
It's different this is flake8 making the noise. The other is our tests making it

**Comment by ultrabug** [comment]
I would like to drop flake8 tests altogether since they are now mostly useless with black

Only test I'd like to keep is useless imports and unused variables, I didn't check how to only look for specific errors on flake8 (only know of to ignore some) and their corresponding codes

**Comment by tobes** [comment]
#1560 fixes this
