### ISSUE TITLE
Group vanishes when scrolling on a group with a module that has no output

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#1537]
Reproduce:

- two or more modules in a group
- one of them has no (blank) output (meaning, do not display anything)
- scroll on the group until the black output "displays"
- group vanishes

We should detect this and display a dummy default character instead

**Comment by lasers** [comment]
I can't reproduce this. Explicit descriptions / modules might help. Is it just two or more than two? If it is just two, then it is possible that both modules does not display anything for you to get this. I see we have code to get next module at least two times before giving up for 5 seconds.
     
>We should detect this and display a dummy default character instead

You can try `format = '{output}|(G)'`.

**Comment by ultrabug** [comment]
You are right @lasers it happens only when the output changes to "empty" while it is being displayed in the group. Not when scrolling to an empty output module.

**Comment by lasers** [comment]
Possibly a better defaults to use... 
```python
group {
    format = '[{output} ]{button}'
    click_mode = 'button'
}
```
 This changes the scrolling behavior from anywhere to `{button}` and would allow interactive modules to work correctly too... as we slowly get more and more of those.

To change modules, scroll on `-` or `+`. Additionally, we could kill `click_mode` config too in favor of checking format` instead... and maybe to kill some more configs too.

This also exposes a toggling behavior many `group` users might not know about.

**Comment by ultrabug** [comment]
Closing, couldn't really reproduce anyway, thank you
