### ISSUE TITLE
Module "weather_yahoo" : 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by roghnin** [ultrabug/py3status#1538]
Hi,

I got this error message from module "weather_yahoo" : 'NoneType' object is not subscriptable
and it stopped working. Can you reproduce this error?

Thanks!

**Comment by ultrabug** [comment]
Hi @roghnin 

Looks like YAHOO changed something or their policy on their weather API

This is an example query for Paris weather: `https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid=%22615702%22%20and%20u=%22c%22&format=json&env=store://datatables.org/alltableswithkeys`

If you open it, and look at the headers we can now see:

```
referrer-policy | strict-origin-when-cross-origin
-- | --
server | ATS
strict-transport-security | max-age=31536000
via | http/1.1 a71.ue.bf1.yahoo.net (ApacheTrafficServer [cMsSf ])
x-content-type-options | nosniff
x-frame-options | DENY
x-xss-protection | 1; mode=block
```

We need to investigate more. And look for any recent announcement maybe? All help is welcome :+1:

**Comment by roghnin** [comment]
Well it seems to be working right now -- I'll follow up if it crashes again.
Thanks for the attention.

**Comment by ultrabug** [comment]
Indeed, mine got back up... Yahoo must have deployed some bug :)

Thanks for reporting @roghnin ! closing.
