### ISSUE TITLE
battery_level: IndexError for battery_level.py line 231 when docked

### ISSUE THREAD

**Issue by eddie-dunn** [ultrabug/py3status#1561]
The error `Instance 'battery_level', user method 'battery_level' failed (IndexError) battery_level.py line 231.` is reported when I dock my laptop.

```
$ acpi -bi
Battery 0: Full, 100%
Battery 0: design capacity 6842 mAh, last full capacity 6002 mAh = 87%
Battery 1: Discharging, 0%, rate information unavailable
Battery 2: Discharging, 0%, rate information unavailable
```

```python
# battery_level:230-231
battery["capacity"] = int(findall("(?<= )(\d+)(?= mAh)",
                                  acpi_battery_lines[1])[1])
```
It appears the string 'rate information unavailable' is not handled gracefully when trying to extract the capacity from `acpi -bi`.

Unless someone objects (or beats me to it), I can submit a patch that resolves this issue.

Also, going through the code I think that it needs some general refactoring love. Are you guys open to such endeavours?

**Comment by tobes** [comment]
> Unless someone objects (or beats me to it), I can submit a patch that resolves this issue.

patches welcome

> Also, going through the code I think that it needs some general refactoring love. Are you guys open to such endeavours?

Yeah this module has been around for quite a while and had bits added over time, so it is probably due some love.

**Comment by eddie-dunn** [comment]
After looking into this a bit more, the reason we get this issue is that I was running `battery_level` in its default ACPI mode, with two battery driven devices connected (Battery 1 and 2 in the `acpi -bi` output quoted above). In my case it was my wireless mouse and keyboard.

With the setting `measurement_mode = "sys"` enabled, `battery_level` no longer crashes.

Also, I did some digging in the source code and the way acpi mode is implemented is super fragile, and relies on regexes and that the user gets their output in English which may not always be the case. As such, I will not work on solving this bug, since acpi mode is not worth the effort.

This leads me to the following questions:

1. Why isn't 'sys' the default mode if `acpi` is installed?
1. Can it be set to always be the default?
1. Can we deprecate/remove 'acpi' mode?
1. Checking `/sys/class/power_supply` is actually quite powerful; we can get battery information also for e.g., HID devices. I can look into expanding the use case for `battery_level` to report information for other things found there as well. Would that be of interest to you?

**Comment by maximbaz** [comment]
So `acpi` method is default because `sys` was implemented later. Since `sys` seem to be more stable, I see no reason not to make it default and deprecate `acpi` mode.

**Comment by ultrabug** [comment]
@eddie-dunn thanks for digging.

Yes indeed, it makes also sense to me to default to using the more reliable kernel sys.

2. propose a PR for this please?
3. why not, but if it's no the default, I see no reason to deprecate it
4. I think it can be done later, in a separate PR

thanks!

**Comment by eddie-dunn** [comment]
@ultrabug np.

The reason for removal/deprecation is to make the source code easier to read and maintain. Also, since the `acpi` code is error prone I see no point in keeping it. But it's your decision of course :)

A PR is up.

**Comment by ultrabug** [comment]
Merged, thanks again
