### ISSUE TITLE
Gathering usage statistics

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1571]
Would be very useful to gather some anonymous statistics on which modules are used. Throw in your ideas on how we can implement this.

-----

My thoughts.

#### What to share

* At the very least we should see the list of modules.
* If we could get the entire `.i3status.conf`, that would allow us to understand which features of certain modules are never used.
    * But `.i3status.conf` can contain some secrets, we should be extremely careful here.

#### How to share

1. Automated upload when py3status process starts

    - pros: users have nothing to configure, we gather the most complete stats
    - cons: might be seen as hostile invasive behavior

1. Implement new flags `py3status --share-stats` or `--share-detailed-stats`

    - pros: simple to enable, yet not invasive
    - cons: unless we find a good way to notify users, very few will know about this flag

#### How to notify people

On py3status startup we should show some notification, similar to the one that shows up when you have an i3 misconfiguration, or simply desktop notification.

#### How to avoid duplicates

- Generate some uuid locally
- Store info locally when last upload succeeded
- Once a week reupload using the same uuid

------

I propose this:

- Implement `--share-stats` and `--share-detailed-stats`.
- If `py3status` starts with at least one of these flags, it uploads statistics once a week.
- If `py3status` starts with none of these flags, it checks if file `~/.config/py3status/willnotsharestats` exists:
    - If it exists, it proceeds as today: no sharing, no notification.
    - If the file doesn't exist, py3status emits a visible user notification:

        > Please help developers improve the app by sharing your anonymized usage details by running py3status with either --share-stats or --share-detailed-stats flags. If you want to opt-out, execute `touch ~/.config/py3status/willnotsharestats`

**Comment by cyrinux** [comment]
Should add a prompt for reviewing and confirm what will be send. Fwupd/fwmgr have a such system for example.

**Comment by tobes** [comment]
Once there was a discussion of a module that would do this and in return you would see some usage stats

Whatever we decide for me the following conditions must be met.

* It __must__ be opt in, not defaulted or assumed

* The data should be minimal and reviewable

* Data should be anonymised as much as possible and kept in a time limited way

* Comply with current legislation, GDPR etc

**Comment by ultrabug** [comment]
Nothing moved on this for a while, won't do for now, closing
