### ISSUE TITLE
100% CPU usage when setting CACHE_FOREVER in wifi module

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1576]
.i3status.conf:

```
order += 'wifi'

wifi {
  cache_timeout = -1
}
```

Restart i3.

CPU usage is peaking. Why? I don't see anything out of the ordinary in code 🤔

**Comment by lasers** [comment]
Closed via #1577.

**Comment by tobes** [comment]
@maximbaz can you confirm this fixes this issue

**Comment by maximbaz** [comment]
Yes it does, thanks to both of you for the fast fix & merge 😉
