### ISSUE TITLE
How to use python 3.4+

### ISSUE THREAD

**Issue by matjazmav** [ultrabug/py3status#1588]
I want to use i3pystatus, but i3pystatus requires python 3.4+. How can I do that?

I have installed python 3 but it is named as python3, I can create an alias, but it doesn't work. Probably it is called with a full path. Also, I don't want to mess with symlinks.

**Comment by lasers** [comment]
Try changing first line in `which i3pystatus` to `python3`.

**Comment by matjazmav** [comment]
@lasers Tried but it doesn't work. I'm getting error now.

```
$ cat /usr/local/bin/py3status
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from py3status import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())


$ py3status
Traceback (most recent call last):
  File "/usr/local/bin/py3status", line 7, in <module>
    from py3status import main
ModuleNotFoundError: No module named 'py3status'
```

**Comment by lasers** [comment]
@matjazmav I don't know what to do next as my py3status installation is different (for developing). How is `py3status` installed and what distro? It seems like you're having path-related issue. @tobes might be able to help you out with this.

I searched online. Maybe you have `py3status.py or `py3status/__init__.py` in that directory?

**Comment by matjazmav** [comment]
@lasers I installed it via `apt` command.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic


$ py3status --version
py3status version 3.14 (python 2.7.15rc1)
```

In what directory should I look for this files?

**Comment by lasers** [comment]
I looked through `py3status.deb`. The file should be `/usr/bin/py3status` for you to change. What is `/usr/local/bin/py3status`? You put it there? Also, this might be unrelated, but do you have `*.py` files in home? If you looked up your error, it is a path issue.

**Comment by matjazmav** [comment]
@lasers  Ah, I installed it via `pip`.

```
$ which py3status
/usr/local/bin/py3status
$ ls -al ~/ | grep *.py
$ 
```

**Comment by lasers** [comment]
After looking it up some more, what's the pip version (`pip -V`)? You might be on `python 2.7` and may have to install `sudo apt-get install python3-pip` and use `pip3 py3status` to get python3 modules.

**Comment by matjazmav** [comment]
@lasers Yes that was it, thank you. Maybe we need to update documentation for this i3pystatus module.

**Comment by lasers** [comment]
Sounds good. Please make a PR. We may drop Python2.7 support in the future too.

**Comment by ultrabug** [comment]
Thanks guys. @matjazmav feel free to contribute a PR plz!

Closing.
