### ISSUE TITLE
mpd_status module disappears and reappears after i3lock unlocks

### ISSUE THREAD

**Issue by Minda1975** [ultrabug/py3status#1594]
Hello. Thank for development team for this wonderful replacement of i3status. I use Debian Sid and I installed py3status from official Debian repo (v3.13-1). i3 version is 4.16 (2018-11-04). After configuring to match my liking i noticed such an unpleasant thing. Mpd_status module disappears and reappears after i3lock unlocks session. Also it happens when i watch full-screen video with Smplayer. It does not matter if the mpd is playing or not, but when screen is locked or video is in full-screen mpd show mesage 

> can't connect to mpd

but after few seconds it connecting and everything is working normally again. As a temporary solution, in configuration parameters i use `hide_on_error = 'True'`. I understand that this is just a temporary solution, so I would like to know if this if this error can be corrected in the version I use.

**Comment by lasers** [comment]
You can try my branch in https://github.com/ultrabug/py3status/issues/1542 or keep using `hide_on_error = True`. 

>Mpd_status module disappears and reappears after i3lock unlocks session. Also it happens when i watch full-screen video with Smplayer. It does not matter if the mpd is playing or not, but when screen is locked or video is in full-screen mpd show mesage

An excerpt from https://i3wm.org/docs/userguide.html#_display_mode
>The hide mode maximizes screen space that can be used for actual windows. Also, i3bar sends the SIGSTOP and SIGCONT signals to the statusline process to save battery power.

This may be same for i3lock. Easy fix might be to default the module with `hide_on_error = True`.

**Comment by Minda1975** [comment]
Hello. 

> hide_on_error = True

 I already use this method. 

Maybe in future i will try this method https://i3wm.org/docs/userguide.html#_display_mode. 

For now, i will close this issue. Good luck.
