### ISSUE TITLE
Allow the use of a specific i3status binary

### ISSUE THREAD

**Issue by Dettorer** [ultrabug/py3status#1600]
Hello,

I'd like to implement a commandline parameter that allows the user to specify a custom i3status binary for py3status to use instead of the current environment's one.

Something like `--i3status FILE`, FILE typically being the path to a user compiled version of i3status.

Would such a feature be interesting in your opinion?

**Comment by ultrabug** [comment]
Hey @Dettorer 

If the option is interesting to you and you're gonna use it then yes it's worth proposing a PR mate :)

Cheers!

**Comment by lasers** [comment]
@Dettorer That's a great idea. Are you working on this? I was wondering about making a link to `/usr/local/bin/i3status` as an easy alternative.

**Comment by Dettorer** [comment]
Hi! I didn't have the time to work on it yet but I'm planning on it yes.

I'm not sure I understand what you mean by the symlink, are you suggesting that py3status creates that symlink upon installation?

**Comment by lasers** [comment]
I don't know what you aim to do, but it seems like `i3status.py` just run `i3status -c <config>`. I'm suggesting that you try `ln -sf ~/your-compiled-i3status /usr/local/bin/i3status` and see if it will do what you want instead of using `py3status --i3status ~/your-compiled-i3status`.

**Comment by Dettorer** [comment]
Oh, yes that temporarily solves my problem, that's more or less what I'm doing until (and if) the feature I suggest gets merged.

**Comment by ultrabug** [comment]
Merged! Will be on 3.16 @Dettorer !

**Comment by Dettorer** [comment]
Thanks!
