### ISSUE TITLE
[Battery Level Module] Problem with on-click notifications

### ISSUE THREAD

**Issue by FlorentDancy** [ultrabug/py3status#161]
Hi,

I activated the notification parameter in the battery_level module, but when I click on the bar this is what I get (/var/log/everything/current) :

```
Jan 13 13:10:06 [/py3status] on_click failed with ('Py3status' object has no attribute 'time_remaining') for event ({'instance': '', 'name': 'battery_level', 'x': 2890, 'button': 1, 'y': 6})
```

Any idea of where it comes from?

Thanks in advance!

Flo

**Comment by ultrabug** [comment]
It's a typo in the module's onclick function yes, I'll check out why this happened thanks

**Comment by ultrabug** [comment]
@FlorentDancy would you care testing with the battery_level from master ? You just have to copy it over to your `~/.i3/py3status/` folder

**Comment by FlorentDancy** [comment]
@ultrabug Thanks, it works perfectly fine now!

@Shir0kamii is gonna do a pull request soo to still display a notification even when the laptop is in charge.

**Comment by ultrabug** [comment]
Thanks, FU as per #162
