### ISSUE TITLE
Ability to have custom graphical output, such as a small PNG

### ISSUE THREAD

**Issue by aioobe** [ultrabug/py3status#1610]
I don't even know if this is the right place to post such RFE. Perhaps it should be directed to i3status, or i3bar. anyways...

I'd love to be able to show custom graphics. Primarily to be able to have something like the [gnome shell system monitor applet](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet).

I think one would even be able to stick with the text based interface and use base64 encoded png files. We're talking &lt;few pixels&gt; &times; &lt;few pixels&gt; images anyway.

Please let me know if this is something doable, or if I should direct my efforts elsewhere.

Cheers

**Comment by aioobe** [comment]
Cool! Thans for the info! "py3status core is only responsible for outputing i3bar compatible JSON" was an aha-moment. Makes sense!

Filed this over at the i3 project: https://github.com/i3/i3/issues/3578

**Comment by ultrabug** [comment]
Thanks @aioobe I've subscribed to the i3 issue.

I've also found back @tobes code about popups that allowed to do something similar... I'll have a chat about this with him.

**Comment by anarcat** [comment]
i don't think this will be doable within the framework of i3status, as explained in i3/i3#3578
