### ISSUE TITLE
arch_updates says "None" rather than a figure

### ISSUE THREAD

**Issue by milkmiruku** [ultrabug/py3status#1617]
I'm using sway rather than i3, though that appears to be supported. I've got both `cower` and `yay` installed. I have aur updates pending.

Anything I could do to help test/debug why this is happening?

**Comment by lasers** [comment]
`cower` is deprecated. What's in your `arch_updates`? I can look into this.

**Comment by milkmiruku** [comment]
Ah, it was having `cower` installed that was causing the problem! Removed, refreshed sway, and the number came up correctly. Thanks :)
