### ISSUE TITLE
Double error messages for modules with validation errors

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1619]
We can get double error messages with this.
```python
order += "wanda_the_fish test3"
wanda_the_fish test3 {
    align = 'xxx'
    min_width = 10
}
```

81d4afb530db5c7b572e7941e348e60735dc1ee5 is the first bad commit
```
Author: lasers <lasers@users.noreply.github.com>
Date:   Sun Dec 30 14:53:04 2018 -0600

    modules: don't set module options on failed modules (#1608)
```

**Comment by lasers** [comment]
Reverting 4d3e0dfdc4ad367be3c21bc1c0a23489fe745b4f works okay. The better solution would be to reuse the method somehow. :man_shrugging:

**Comment by lasers** [comment]
>The better solution would be to reuse the method somehow. man_shrugging

Here you go. Make a PR? https://github.com/ultrabug/py3status/pull/new/module-not-disabled

**Comment by lasers** [comment]
@ultrabug You like this fix?

**Comment by ultrabug** [comment]
@lasers yes I do

**Comment by ultrabug** [comment]
Thanks
