### ISSUE TITLE
The events on_click aren't received on ``tztime local``

### ISSUE THREAD

**Issue by btall** [ultrabug/py3status#165]
I've a weird comportment on the events ``on_click`` in the block 
```
tztime local {
        format = "%Y-%m-%d %H:%M:%S"
        on_click 1 = "exec --no-startup-id gksudo notify-send -t 1000 'Hello'"
        on_click 3 = "exec --no-startup-id gksudo notify-send -t 1000 'Bye'"
}
```

When I click on the clock, I've this error message
```
Jan 18 17:49:26 mymachine py3status: trying to dispatch event to module "tztime"
```
But it works, when I use on the block ``time`` instead of ``tztime local``.

**Comment by ultrabug** [comment]
I can't reproduce this so far... will keep trying !

**Comment by ultrabug** [comment]
As debugged with you, it's not related to py3status but to your i3status version. Old versions of i3status does not pass the "instance" value of the time and tztime modules !
