### ISSUE TITLE
spotify module generates errors in /var/log/messages

### ISSUE THREAD

**Issue by UmBsublime** [ultrabug/py3status#166]
Errors in my /var/log/messages: py3status: 
```
user method getText failed (getText() takes exactly 2 arguments (3 given))
```
Here is my config for the module

```
order += "spotify"

spotify {
  format = "{title} by {artist} -> {time}"
}

```

And my py3status version

```
py3status --version
py3status version 2.8 (python 2.7.9)
```

I'm not sure, but I think this is because the method getText should be renamed _getText. 

When doing this locally the error dispersals.

**Comment by pydsigner** [comment]
Good catch.

**Comment by UmBsublime** [comment]
Awesome !
