### ISSUE TITLE
xrandr: set primary display

### ISSUE THREAD

**Issue by jdkbx** [ultrabug/py3status#1663]
When i switch displays my systray usually gets lost or is randomly assigned to a screen. To fix it to one screen, I set i"tray_output primary" and set the primary attribute to the corresponding screen. I would like to do this with the xrandr module somehow, so that when I use the dynamic configuration the primary attribute can be assigned to a specific screen.

**Comment by lasers** [comment]
Do you want to make a PR?

**Comment by lasers** [comment]
Closed via #1665.
