### ISSUE TITLE
[feature request] keyboard_layout and variants

### ISSUE THREAD

**Issue by ecks** [ultrabug/py3status#1668]
I really enjoy using keyboard_layout module, especially since I often switch between us and dvorak variants in the middle of typing. I have some some feature that I hacked together in my personal script, and would love to see included in the main branch.

1. When displaying *variant*, allow for boolean configuration parameter where if xkblayout-state returns the variant as empty (nothing), then display the variant as the same as the layout. This allows quickly to switch between the main language and variant (us and dvorak in my case) while having only one format identifier. The way it is currently, it would switch between empty string and "dvorak" if I have format = "{variant}" set.

2. Currently, there is no way to direct the module to set a variant using the *layout* user-defined array. The only way is to set it externally. Would be nice to have something like *layout = [us, (us, dvorak), ru]*, so that if an element is a tuple, to figure out that the second is the variant of the lang in the first. That might require *setxkbmap* to use the *-variant* flag in addition to *-layout*. 

For 1, it shouldn't be an issue to implement and shouldn't affect the main functionality of the module, if the feature is useful I'll make a pull request. For 2, it would be more complex and would need some feedback.

I also found out that you can set dvorak directly using *setxkbmap -layout dvorak* (as described in the example at the beginning of the module), however that leads to inconsistencies between what setxkbmap and xkblayout-state displays. It looks like there are some weird rules in linux when treating "dvorak" variant. *setxkbmap -layout us -variant dvorak* or *setxkbmap -layout us,dvorak* fixes that though.

**Comment by lasers** [comment]
1) I don't use this module so I can't confirm anything. I think setting `format` to something like `'{layout}[ {variant}]'` or `'[\?if!=variant {variant}|{layout}]'` might do what you want.

2) PRs welcome.

**Comment by ecks** [comment]
Hey,

Thanks for that, I did not realize the format string was so customizable! I guess I shoulda read the docs more. For [1] I was able to achieve exactly what I wanted using 

[\?if=variant [\?color=#00ff1e&show {variant}] | {layout}]

Then later I could define color_us = "#0038ff". I haven't been able to figure out how to define a var that will specify the color of the variant (if we want it to be different color from the lang, if not then it all works), so that's why need to add \?color specifier.

Just curious, are there other useful command you can put after **&** besides **show**, **color** and **if**?

**Comment by lasers** [comment]
I think this does same thing -- Simplifying... `'[\?color=#00ff1e {variant}|{layout}]'`.

To print different colors... `'[\?color=red {layout}][\?soft  ][\?color=#00ff1e {variant}]'`...

Your example might looks like this: `[\?if=variant [\?color=#00ff1e&show {variant}] |\?color=degraded {layout}]`... which might be a bit too much, but is not wrong.

Simplifying it to... `[\?color=#00ff1e {variant}|\?color=degraded {layout}]`... I think.

`[\?soft  ]` should have two spaces or you see both placeholders without a space.

>Just curious, are there other useful command you can put after & besides show, color and if?

You can look at #752. We got #1584 that ought to replace the current formatter with f-string formatter.

**Comment by ecks** [comment]
@lasers hey thanks! that actually works fine for me.

I am not sure why I didn't try that, but it also works if you want to set a variant for another language (for instance russian with phonetic).

I'm closing this issue then since it can do it all without needing any code changes. Thanks again!
