### ISSUE TITLE
air_quality: a little bug

### ISSUE THREAD

**Issue by cyrinux** [ultrabug/py3status#1669]
I think there is a little fix to do somewhere, due to a network, unresponding api maybe
![2019-01-25_13-45](https://user-images.githubusercontent.com/519083/51747879-ff398680-20aa-11e9-8bed-09cda5b6fdb7.png)

**Comment by lasers** [comment]
Can you log the data? What does it look like? Maybe `data['aqi']` need to be casted.

**Comment by cyrinux** [comment]
Yes @lasers will try, this was the first time I get it

**Comment by lasers** [comment]
@cyrinux Thoughts on closing this? Maybe you ran into a different status code at that time.

**Comment by cyrinux** [comment]
@lasers you can close, i dont reproduce the problem for the moment. Will do a PR if this come again.
