### ISSUE TITLE
weather_owm: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jimpriest** [ultrabug/py3status#1670]
Trying to get weather_owm setup and having issues.

Ubuntu 18.04,  py3status version 3.7 (python 3.6.7)

Got an API key and just dumped in the example from the docs:

```
order += "spotify"
order += "weather_owm"
order += "apt_updates"

weather_owm {
  api_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  location = (2.3548, 48.9342)  # Saint-Denis
}
```
But all I see in my bar is 'weather_owm'.  If I click that I see 'argument of type 'NoneType' is not iterable'

Not sure what I'm missing?  Reading through the docs it seems like the API key is the only thing required.

**Comment by lasers** [comment]
Seems like your `location` is off. It should be `4992` or `3098`, whatever you like better. The latter seems to be closer to your geographic coordinates.
```json
{
    "status": "ok",
    "data": [
        {
            "uid": 4992,
            "aqi": "13",
            "time": {
                "tz": "+0100",
                "stime": "2019-01-25 17:00:00",
                "vtime": 1548432000
            },
            "station": {
                "name": "Saint-Denis d'Anjou, la Mayenne, Loire, France",
                "geo": [
                    47.7883,
                    -0.444706
                ],
                "url": "france/loire/la-mayenne/saint-denis-danjou"
            }
        },
        {
            "uid": 3098,
            "aqi": "68",
            "time": {
                "tz": "+01:00",
                "stime": "2019-01-25 17:00:00",
                "vtime": 1548432000
            },
            "station": {
                "name": "Autoroute A1 - Saint-denis, Paris",
                "geo": [
                    48.9251,
                    2.35654
                ],
                "url": "france/paris/autoroute-a1-saint-denis"
            }
        }
    ]
}
```

**Comment by lasers** [comment]
@jimpriest Can you try the latest `weather_owm`? I think the problem could be that you're on older `weather_owm` module right now (i.e. `py3status 3.7` and the `(lat, long)` might be fixed / added in `py3status 3.13`.

You can click `Raw` button. [modules/weather_own.py](https://github.com/ultrabug/py3status/blob/master/py3status/modules/weather_owm.py)

**Comment by jimpriest** [comment]
Thanks!  Let me see if I can find where that's installed and update.

**Comment by jimpriest** [comment]
Updated weather_own.py file... Now I get an "API Error" so we're making progress :)

```
weather_owm {
  api_key = xxxxxxxxxxxxxxxxxxxxxxxxxxx
  location = 4992
}

or 

weather_owm {
  api_key = xxxxxxxxxxxxxxxxxxxxxxxxxxx
  city = "London"
  country = "UK"
}
```

My API key seems to work - I can call a request via the URL and get a JSON string back:
http://api.openweathermap.org/data/2.5/weather?q=London,uk&appid=xxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by lasers** [comment]
This works okay on my side.
```python
weather_owm {
    api_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    city = "London"
    country = "UK"
}
```
```python
weather_owm {
    api_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    location = (2.3548, 48.9342)  # Saint-Denis
}
```
`API Error` is vague + hardcoded so I can't tell from here specifically what your error was... Maybe we can with this.
```diff
diff --git a/py3status/modules/weather_owm.py b/py3status/modules/weather_owm.py
index 5ed5453..cfd8a2f 100644
--- a/py3status/modules/weather_owm.py
+++ b/py3status/modules/weather_owm.py
@@ -439,7 +439,7 @@ class Py3status:
         if req.status_code != 200:
             data = req.json()
             raise OWMException(
-                data["message"] if (data and "message" in data) else "API Error"
+                data["message"] if (data and "message" in data) else str(data)
             )
 
         return req.json()
```
I would tell you to upgrade to `py3status 3.16` because we added agent header to `self.py3.request()` 6 months ago and maybe that had something to do with it.

**Comment by lasers** [comment]
I checked out `3.7` with `3.16`'s `weather_owm`. Both works okay. Maybe it's an error relating to your API. Bad API token? I'll see if I can find a better diff.

**Comment by jimpriest** [comment]
FIXED!  I was cutting and pasting and somewhere along the way lost the quotes around my API key.

Added that and it works!  Thanks for all the help!!!!!!!!
