### ISSUE TITLE
[RFC] version 3.17

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#1676]
This is me writing down my wishes (and dreams) for version 3.17 and I hope I won't hurt anyone in doing so because I'm a rather drastic person...

As always, I'd love your ideas too. I'll edit this post if something else comes into my mind.

## man page
- https://github.com/ultrabug/py3status/issues/325 - you can try my branch. maybe start from there.

## i3wm page
- https://github.com/ultrabug/py3status/issues/1010 - you can try my zip. maybe start from there.

## logo page
- https://github.com/ultrabug/py3status/issues/1528 - you can try the logo i made. maybe start from there.

## tobes page
- bring him back.
- we need to know what he want to do with some open issues + pull requests.
- i believe he have some branches that he want to implement.
- No.1 Collaborator, enuff said.

## formatters
- because of issues, wishes (and dreams) around formatters, what do we want to do with #1542?
- address remaining open issues and pull requests relating to formatters such as #1563.
## group
- https://github.com/ultrabug/py3status/issues/890 - you can try my branch. maybe start from there.

## one page
- we reduced number of open issues and pull requests down to one page each. try to keep it that way.

**Comment by ultrabug** [comment]
I released 3.17

I will open a PR to update i3wm py3status page

3.18 man page maybe?
