### ISSUE TITLE
Spotify unable to get playback status

### ISSUE THREAD

**Issue by AnwariasEu** [ultrabug/py3status#168]
Hey, is any other other distro beside arch running spotify 1.0.19 having problems retrieving the playback status? If so a fix for that query is needed.
In case it is arch specific please confirm so a patch for the arch package can be submitted.

**Comment by pydsigner** [comment]
Possible duplicate of https://github.com/ultrabug/py3status/issues/166?

**Comment by pydsigner** [comment]
Take a look at that issue and check if you are having similar errors show up in your py3status logs.

**Comment by AnwariasEu** [comment]
It seems the problem is the implementation of the dbus api by spotify.
The following command does not return anything and results in a timeout.
dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'
When 'PlaybackStatus' is replaced by 'Metadata' the metadata is porperly returned.

**Comment by ultrabug** [comment]
Reminds me of #149 :(

As I'm no spotify user, I must admit I can't think of anything better. What you wanna do with this issue @AnwariasEu ?

**Comment by AnwariasEu** [comment]
Seemes like the same problems as in #149
I have submitted two pullrequests both are only workarounds.
If other distros don't have any problems i will submit them to the arch package.

**Comment by ultrabug** [comment]
Thx, closing here and will discuss on the PRs.
