### ISSUE TITLE
module archlinux updates: cower deprecated

### ISSUE THREAD

**Issue by rissson** [ultrabug/py3status#1716]
`cower` has been deprecated and is no longer in the AUR available for install. Use something like `pikaur` with `pikaur -Qua` to get the number of outdated packages.
Will try to submit a PR if I have time.

**Comment by maximbaz** [comment]
By the way `arch_updates` module already supports `auracle` and `yay` besides `cower`, but I agree that the current design is not really sustainable as others want to use their own AUR helper. Maybe one day (in `4.0`) we can return to an idea of the generic extensible `updates` module that can replace all `_updates`... 😉

**Comment by rissson** [comment]
`auracle` is not mentionned in the doc then x)

**Comment by lasers** [comment]
Mentions of `cower` are removed in the docs. `cower` is moved to end of the list putting `yay` higher in the list. We can remove all trace of `cower` sometime next year.

`auracle` is mentioned in the documentation. Adding `pikaur` can be done separately/later if you want `pikaur` to be supported too. I hope this is more than enough to close this `cower deprecated` issue.
