### ISSUE TITLE
Compatibility problems with sway

### ISSUE THREAD

**Issue by boucman** [ultrabug/py3status#1717]
Hello
I am using the sway compositor with py3status, and it works well, mostly. 
the one thing that doesn't work is on_click. it calls directly the command i3-msg which is not available with sway.

would it be possible to add a configuration option to change the message sending command ? sway has its own "swaymsg" commands that works just like i3-msg and could do the trick

thx
Jeremy

**Comment by duffydack** [comment]
I'm using sway more and with the stable 1.0 around the corner, unlikely I'll be going back to xorg/i3, so I'd like this supported more too.  That said, I have no problem having i3 installed as well if this is a 'wont fix', as things work still.  I guess it's more atheistic for me.

**Comment by maximbaz** [comment]
I think sooner or later many of us will switch to sway, and it would be nice to continue using py3status. Would love to hear what @ultrabug has to say on the matter of supporting sway 😉

**Comment by lasers** [comment]
If you want to, see if this works fine. Temporary sway fix.
```diff
diff --git a/py3status/events.py b/py3status/events.py
index 0a85ddf..c5a2707 100644
--- a/py3status/events.py
+++ b/py3status/events.py
@@ -160,7 +160,7 @@ class Events(Thread):
         """
         Execute the given i3 message and log its output.
         """
-        i3_msg_pipe = Popen(["i3-msg", command], stdout=PIPE)
+        i3_msg_pipe = Popen(["swaymsg", command], stdout=PIPE)
         self.py3_wrapper.log(
             'i3-msg module="{}" command="{}" stdout={}'.format(
                 module_name, command, i3_msg_pipe.stdout.read()
```
Ought to extend this support to modules using `i3-msg` too.
```python
window_title.py:        tree = loads(self.py3.command_output("i3-msg -t get_tree"))
xrandr.py:                    cmd = 'i3-msg workspace "{}"'.format(workspace)
xrandr.py:                    cmd = 'i3-msg move workspace to output "{}"'.format(output)
scratchpad_counter.py:        tree = loads(self.py3.command_output("i3-msg -t get_tree"))
google_calendar.py:            self.py3.command_run("i3-msg restart")
```

**Comment by boucman** [comment]
on a side note, I think there are also references to i3-nag to be replaced by swaynag, but I havn't figured out what triggers those...

**Comment by ultrabug** [comment]
OMG it's in, thanks a lot guys!

As I said, this warrants a release I guess

**Comment by rouja** [comment]
Hi,

I think a simpler way in our situation to fix this issue (before the code evolves) is to make a symlink : 

```
sudo ln -s /usr/bin/swaymsg /usr/bin/i3-msg
```
