### ISSUE TITLE
Square Brackets Break Pango Markup

### ISSUE THREAD

**Issue by alliefitter** [ultrabug/py3status#1719]
When configuring the format of a module using `[]` breaks pango markup. Instead of rendering the markup properly, the tags are displayed in plain text. 

```
sysdata {
	format = "<span fgcolor='#005faf' bgcolor='#00afff'>\ue0b8</span><span bgcolor='#00afff'>[\?color=cpu \uf233 {cpu_used_percent}%] [\?color=mem \uf2db {mem_used}/{mem_total} {mem_unit}] </span>"
	markup = "pango"
}
```
![screenshot from 2019-02-19 23-23-46](https://user-images.githubusercontent.com/13684558/53068254-70e3d500-349d-11e9-85c4-59a7ac6f24fa.png)

If you remove the brackets, the markdown renders properly, but both the cpu percentage and memory usage are color according to the state of the memory.

```
sysdata {
	format = "<span fgcolor='#005faf' bgcolor='#00afff'>\ue0b8</span><span bgcolor='#00afff'>\?color=cpu \uf233 {cpu_used_percent}% \?color=mem \uf2db {mem_used}/{mem_total} {mem_unit} </span>"
	markup = "pango"
}
```
![screenshot from 2019-02-19 23-27-54](https://user-images.githubusercontent.com/13684558/53068433-14cd8080-349e-11e9-8e6c-aa8ae866a497.png)

I've also tried placing the markdown inside of the square brackets which has mixed results.
```
sysdata {
	format = "<span fgcolor='#005faf' bgcolor='#00afff'>\ue0b8</span>[\?color=cpu <span bgcolor='#00afff'>\uf233 {cpu_used_percent}%</span>] [\?color=mem <span bgcolor='#00afff'>\uf2db {mem_used}/{mem_total} {mem_unit}</span>]"
	markup = "pango"
}
```
![screenshot from 2019-02-19 23-35-56](https://user-images.githubusercontent.com/13684558/53068741-206d7700-349f-11e9-94aa-b109a94c04ba.png)

Is there another way to specify color for a section of the format without using square brackets?

**Comment by lasers** [comment]
Can you try this?
```python
sysdata {
    format = "\?color=#005faf \ue0b8 [\?color=cpu \uf233 {cpu_used_percent}%] "
    format += "[\?color=mem \uf2db {mem_used}/{mem_total} {mem_unit}]"
    background = "#00afff"
}
```

**Comment by alliefitter** [comment]
Those meet the basic constraints of the issue, but the problem I run into using the `background` attribute of a module is that it colors the entire height of the bar. This is purely aesthetic, but I'm delimiting each module using a symbol from [powerline-extra-symbols](https://github.com/ryanoasis/powerline-extra-symbols). (Note: I'm not using a separator. The symbol I'm using to delimit each module is the first character of each module's `format` attribute.) The character doesn't fill the full height of the bar. 

![screenshot from 2019-02-20 01-32-43](https://user-images.githubusercontent.com/13684558/53112311-8e985500-3504-11e9-8e14-8c894b359d59.png)


I found that AirBlader made a [patch](https://www.reddit.com/r/i3wm/comments/47hktd/remove_a_border_around_i3bar/) to remove the borders from the top and bottom of the bar, but I'm not really interested in patching i3 myself. I haven't written nearly enough C to be confident in even applying a patch and compiling it. Building i3-gaps is about as far as I want to go.

I did find a workaround for this though. I defined two `sysdata` blocks. This way I can avoid using square brackets and set the threshold colors.

```
sysdata cpu {
	format = "<span fgcolor='#005faf' bgcolor='#00afff'>\ue0b8</span><span bgcolor='#00afff'>\?color=cpu \uf233 {cpu_used_percent}%</span>"
	markup = "pango"
	thresholds = [
	    (0, "#0087d7"),
	    (70, "#005faf"),
	    (90, "#ff0000")
	]
}
sysdata memory {
	format = "<span fgcolor='#005f5f' bgcolor='#00afff'>\ue0bf</span><span bgcolor='#00afff'> \?color=mem \uf2db {mem_used}/{mem_total} {mem_unit}</span>"
	markup = "pango"
	thresholds = [
	    (0, "#0087d7"),
	    (70, "#005faf"),
	    (90, "#ff0000")
	]
}
```

![screenshot from 2019-02-20 01-38-04](https://user-images.githubusercontent.com/13684558/53112647-56dddd00-3505-11e9-8260-ca6d954bdb4c.png)
![screenshot from 2019-02-20 11-50-11](https://user-images.githubusercontent.com/13684558/53112842-d4095200-3505-11e9-86b2-c3744aa9445d.png)
![screenshot from 2019-02-20 11-50-54](https://user-images.githubusercontent.com/13684558/53112848-d79cd900-3505-11e9-9b3f-a33355031ea9.png)

Btw, a tip for anyone who wants to test the threshold colors for memory: Just open multiple tabs in Chrome and go to gmail. Gmail uses ~300MB of RAM.

**Comment by lasers** [comment]
>but the problem I run into using the `background` attribute of a module is that it colors the entire height of the bar

>made a patch to remove the borders from the top and bottom of the bar,

This may have same effect. I don't know your background color, so red it is. 
```python
py3status {
    border = "red" 
    background = "#00afff"
    border_top = 2
    border_bottom = 2
}
```

**Comment by lasers** [comment]
Closed via #1723.

**Comment by lasers** [comment]
Opened via 72ce48f.

**Comment by ultrabug** [comment]
I recently added some fixes on pango markup, if this is not fixed, plz reopen
