### ISSUE TITLE
Wireless onClick not wirking

### ISSUE THREAD

**Issue by Cilenco** [ultrabug/py3status#173]
I use the default i3 plugin wireless _first_ to display my wlan connection. The _first_ is replaced automaticly by i3 with the first network interface name which is found on the device. I have added:

on_click 1 = "exec --no-startup-id nm-connection-editor"

to the module but it does not work. If I replace _first_ with my network interface name it works great. I think py3status registers a click listener to wireless _first_ and later the name is changed so it can not find the module. Would be great if someone can fix this so we do not need to hardcode the interface name.

**Comment by ultrabug** [comment]
Hi @Cilenco, would you mind telling me what version of py3status you're running ?

**Comment by Cilenco** [comment]
I'm using py3Status version 2.6 with python 3.5.1

**Comment by ultrabug** [comment]
Then please update to at least 2.7, it was a bug that's been fixed since then mate :)

https://github.com/ultrabug/py3status/blob/master/CHANGELOG#L16

**Comment by Cilenco** [comment]
Okay thank you for that and sorry for the inconvenience!

**Comment by ultrabug** [comment]
np mate, happy to help
