### ISSUE TITLE
Feature request: significant figures option for battery percentage

### ISSUE THREAD

**Issue by mxmilkb** [ultrabug/py3status#1734]
E.g. instead of "52.36%" it could be "52%", thus shaving 50% of characters used.

(Possibly this idea could be extended to other percentages?)

**Comment by lasers** [comment]
Can you try `{percent:d}` or `{percent:.0f}` in your `format`?

**Comment by mxmilkb** [comment]
Tried both (like `format = " %status:{percent:d}"`) and it just prints `UNK:{percent:d}` in the bar.

**Comment by lasers** [comment]
Oh that `battery` module... Sorry. You would have to take it up with [i3/i3status](https://github.com/i3/i3status), but before you do that, see the man page first. `man i3status` mentioned this in their `Battery` section. Try that?
>If you want the battery percentage to be shown without decimals, add                   
>integer_battery_capacity = true.


Using `:d` or `:.0f` ought to work fine on py3status's `battery_level` module (hence the mistake).

**Comment by mxmilkb** [comment]
A-ha! Thanks very much for the clarification :)
