### ISSUE TITLE
Can't fetch color if variable isn't used ?

### ISSUE THREAD

**Issue by GreyXor** [ultrabug/py3status#1743]
I checked the documentation but I think it's more of a bug or lack of functionality.

**Version**
```
py3status version 3.16 (python 3.7.2) on sway
Linux carbon 5.0.0-arch1-1-ARCH #1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019 x86_64 GNU/Linux
```
**Problem**
I'm using [sysdata](https://py3status.readthedocs.io/en/latest/modules.html#sysdata) module to show CPU usage, i don't need to display CPU percentage, only color of it.

The next line isn't working (That's what I need)
`format = "[\?color=cpu_used_percent CPU]" `

The next line is working (But it shows the percentage I don't want)
`format = "[\?color=cpu_used_percent {cpu_used_percent}% CPU]" `

I don't need to display the percentage of the CPU, only to use the color value of the percent. How can I display only the color on the text without using the percentage ?

**Comment by lasers** [comment]
If users do not use `{cpu_used_percent}` placeholder, then it's likely that they would not use `color=cpu_used_percent` too. This is true for most placeholders + colors.

In `sysdata`'s `post_config_hook`, we can get a list of placeholders and a list of colors. The lists are kept separately. We could consolidate them together if necessary... for all modules.

This should work. 
```python
sysdata {
    # add "cpu_used_percent" placeholder (turns False if percent is zero)
    format = '\?if=cpu_used_percent&color=cpu_used_percent CPU'
}
```
```python
sysdata {
    # empty is a made up placeholder (always False)
    format = "[\?if=empty {cpu_used_percent}]"
    format += "[\?color=cpu_used_percent&show CPU]"
}
```

**Comment by lasers** [comment]
You can't go wrong with first or third example. The second example is blah.

This is an non-issue, but if/when https://github.com/ultrabug/py3status/pull/1472#issuecomment-417209391 gets addressed, then this could be a thing of a past then you could have your `"[\?color=cpu_used_percent CPU]"`. For now, the lists are kept separate.

The comment (above) should solve your issue. Cheers.

**Comment by lasers** [comment]
(Fyi) https://github.com/ultrabug/py3status/pull/1798 consolidated the lists. `"\?color=cpu_used_percent CPU"` works okay.
