### ISSUE TITLE
How to install latest version

### ISSUE THREAD

**Issue by matjazmav** [ultrabug/py3status#1767]
I'm trying to install latest version (3.18). If I install it via pip3 or apt I get version 3.7. I couldn't find any instructions how to get latest release, can you give me some directions?

**Comment by lasers** [comment]
You can try `pip3 install git+https://github.com/ultrabug/py3status.git` (untested)

Alternatively, you can set up https://py3status.readthedocs.io/en/latest/contributing.html#setting-up-a-development-environment and run `git pull` monthly to catch up... and make new modules.

If you have `3.7`, then I think you installed it via `apt`. Currently available on `18.04 LTS`.

**Comment by matjazmav** [comment]
Yes I installed via apt on 18.04. Thanks I have successfully installed latest version now :) Didn't know that I can install directly from git.
