### ISSUE TITLE
pomodoro sounds play for less than 0.2 seconds

### ISSUE THREAD

**Issue by ertwro** [ultrabug/py3status#1769]
I wanna play a sound that is 3.5 seconds with sound_pomodoro_end and 1.2 seconds long for sound_pomodoro_start. Unfortunately, no matter what I do it only plays for less than 0.2 seconds in both cases.

**Comment by lasers** [comment]
I recall `paplay` doesn't support many filetypes. Not sure about `play`.

Can you see if this old PR https://github.com/ultrabug/py3status/pull/1313 works fine? Make sure `ffplay` is installed too.

**Comment by lasers** [comment]
@ertwro I put out a PR. Can you try #1770? Thx.

**Comment by ertwro** [comment]
@laser tested #1770 several times with different formats. Just perfect!!!

**Comment by ultrabug** [comment]
Thanks guys
