### ISSUE TITLE
Support for format_time in tztime module

### ISSUE THREAD

**Issue by cornerman** [ultrabug/py3status#177]
The tztime module from i3status introduced another ```format_time``` option to enable pango markup: https://i3wm.org/i3status/manpage.html#_tztime

As py3status handles the tztime module, this new option needs to be taken into account when parsing the time's format. Currently, when using ```format_time```, the time stops updating and adds the ```%Y,%m,%d``` formatstrings to the time (see [here](https://github.com/ultrabug/py3status/blob/master/py3status/__init__.py#L413)).

**Comment by ultrabug** [comment]
thx @cornerman for testing, it's fixed and merged :)

**Comment by cornerman** [comment]
There seems to be some kind of regression on the current master. When I use this block in my config:
```
tztime local {
    format_time = "%H:%M:%S"
    format = "<b>%time</b>"
}
```
Then I get an error:

```ValueError: time data 'Y-m-d H:M:S' does not match format '%Y-%m-%d %H:%M:%S'```

**Comment by cornerman** [comment]
I have bisected the last commits and found that ```e11ac996f529095c1b17925bfe87682c5989020f``` is the first bad commit.
