### ISSUE TITLE
"Unit Multiplier prefix" to override default {unit}

### ISSUE THREAD

**Issue by alan12345678** [ultrabug/py3status#1775]
It's a question/feature request not a bug.

Have configured the 'net speed' module. I'd like to have it calculate and display my bandwidth in either kB/s or Mb/s rather than the default - particularly as this leads to more spacing issues.

The docs say

`unit unit to use. If the unit contains a multiplier prefix, only this exact unit will ever be used (default “B/s”)`

but I can find NOWHERE where it explains how to format a prefix. I've tried experimenting... but no luck.

Is there a simple way/notation to change this unit from default?

**Comment by lasers** [comment]
Here is information about `unit` in question. You can view other lines too to read more.

https://github.com/ultrabug/py3status/blob/65a609261095f7502fc2814e9a6feb478845a69c/py3status/py3.py#L348-L351 

The problem might be related to rounding. Can you try this config?
```python
order += "net_rate"
net_rate {
    # unit = "kB/s"
    unit = "MB/s"
    format_value = "[\?min_length=11 {value} {unit}]"
}
```

**Comment by alan12345678** [comment]
ooh nice.

The two letters that worked for me were

"unit = M" or "unit = MB"

and

"unit = Kb"

It did indeed do some converting. Using the "M" it rounds to the nearest 0.1, which with low internet speeds is a bit unappealing.

I'm pleased that I have found a way to change this, so thank you.

I realise there's a difference between "bites per second" and "bytes per second". Although your reply helped me make an improvement, I also note that running a speed test (at www.speedof.me) gave me a figure saying my download was "2.43 Mbp/s" Using the most responsive multiplier for my module, it told me "237 Kb/s" or thereabouts - my point being that there's still a mismatch between what it's calculated as, what it's shown as, and what it's reported as externally.

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----

**Comment by ultrabug** [comment]
@alan12345678 please see the linked PR, this should help on your issue :) if not, please reopen

This will be part of 3.19

Thanks!
