### ISSUE TITLE
Import Error, No Module.. (in path)

### ISSUE THREAD

**Issue by alan12345678** [ultrabug/py3status#1776]
Decided to modify one of the included modules from this git (`mpris`). Rather than edit the original, I copied it locally and changed it.

After a few config issues etc. (py3status nagbar error messages) everything is now fine EXCEPT that I get this message as a placeholder for the module, set in `degraded` colour:

`Import Error, No module name 'py3status.modules.my_mpris'`

I thought this was system-wide, so I modified the Python3.7 system paths to include my `/home/<user>.i3/scripts` directory, but since the message is still there, I'm guessing that py3status does it's own run time checking?

Since I'm likely to be writing a few simple further modules, is there an easy 'non-hacky' way of updating the config so that my modules will run?

**Comment by lasers** [comment]
By default, py3status looks for module directories in the following order:

- ``~/.config/py3status/modules`` (or ``$XDG_CONFIG_HOME/py3status/modules`` if set)
- ``~/.config/i3status/py3status`` (or ``$XDG_CONFIG_HOME/i3status/py3status`` if set)
- ``~/.config/i3/py3status`` (or ``$XDG_CONFIG_HOME/i3/py3status`` if set)
- ``~/.i3/py3status``

**Comment by lasers** [comment]
Added in 3.18: `py3status` have its own config directory.

* Custom modules can go in `~/.config/py3status/modules`
* Single bar config can be `~/.config/py3status/config`

Then you can use this without specifying anything.
```
bar {
    status_command py3status
}
```
Or keep using `~/.i3`, then in that case, put custom modules in dir `~/.i3/py3status`.

Also, there is `py3status --include` which you can specify the module directory too. Cheers.

**Comment by alan12345678** [comment]
Thank you EVER SO much :)

Yes, I had read ALL the docs - was aware of the various search paths.

In order to help I provide this further info.

I'm using i3 with py3status (and blocks) on the Community Edition of Manjaro i3. As a complete .iso I installed and ran it - it 'hand holds' through the first bits and thus provides a lot of already prepared configs.

Whether your file paths are based on Arch I don't know, but I can tell you that on my system there are `py3status` installation directories anywhere in my $HOME path.

I therefore had to test out all of the options you suggested, most of which threw errors in py3status.

The one that has successfully worked is:

manually add ~/.config/py3status/modules/

and copy my modified file into it. Now it starts up and runs without any errors!

Thanks :)

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----

**Comment by lasers** [comment]
> I therefore had to test out all of the options you suggested, most of which threw errors in py3status.

The code say if you have `-i`, `--include`, that'll be used instead of the directories. Maybe that's it? 

I tested `~/.i3/py3status/` (the last one on the list) and it worked okay. I'll go ahead and close this. :-)
