### ISSUE TITLE
RFC : module_group / scroll_group

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#178]
**Dear py3status users, tell us what you think !**

As discussed in PR #155 with @tjaartvdwalt and @pydsigner.

A `scroll_group` or `module_group` whatever the name handled by py3status would allow users to **group multiple modules together** and switch between them using the mouse scroll buttons (4 and 5) !

This way users could still benefit from click events on mouse buttons 1, 2 and 3 on each module. My first idea would give something like this on i3status.conf for your use case (I need to use two different module instance _first_ and wlan0 to get them work on the same i3status output) :

````
wireless _first_ {
	format_down = "W"
	format_up = "%ip"
	scroll_group = 1
}

wireless wlan0 {
	format_down = "W"
	format_up = "%essid"
	scroll_group = 1
}
````

This would make py3status group the two outputs together and display one or the other on mouse scroll automatically.

What's interesting with this is that this would work with every module available and users could then group and *toggle* whatever modules they want together with a single line config.

Of course, the scroll_group itself would be configurable (we could even want it to scroll each module automatically at a given interval !)

**Comment by shrimpza** [comment]
The only thing I think is weird, might be the requirement for unique module names, and the `_first_` work-around for that (I presume there must be unique `<module> [param]` combinations within a single config). If a user is at this point of customisation of their configuration, is backward compatibility with a default i3status config still a requirement?

Could a configuration something like this perhaps work better:

```
...
order += "group wifi"
...

group wifi {
    scroll_interval = "30s"

    wireless wlan0 {
        format_down = "W"
        format_up = "%ip"
    }

    wireless wlan0 {
        format_down = "W"
        format_up = "%essid"
    }
}
```

py3status could then "flatten" the group internally and orchestrate scroll events, intervals, clicking, etc.

It's more work, but I think the above may be more flexible and readable, plus allows for the mixing of different modules within a group (for example, combine `disk "/var"` and `disk "/home"`, or combine `sysdata` and `load` into one group, etc.).

**Comment by UmBsublime** [comment]
Hi,

Kenneth's config solutions would be really nice to make this really simple
to setup !!!

**Comment by ultrabug** [comment]
Okay guys, but I really don't get how py3status is supposed to *flatten* those two configurations together ? Because one way or another, it has to execute i3status to get its output and i3status doesn't accept such dual module definition :(

An idea @shrimpza ?

**Comment by pydsigner** [comment]
Another thing to consider with this: a volume meter will probably want to use the scrollwheel to adjust the volume.
