### ISSUE TITLE
weather_owm: Bad Request 400 when using just API key and location.

### ISSUE THREAD

**Issue by fxdgear** [ultrabug/py3status#1781]
Just setting up a new computer and transferring all my configs over from one machine. 

I am getting errors that say `Bad Request 400`. 

I'm not sure what broke. :( 

I tried logging to a tmp log and tailing the log but I'm not getting any useful information fromthat log.

**Comment by ultrabug** [comment]
Hey mate,

I guess you may be using the default IP location resolution instead of having configured a city?

If so, I see that the API for IP location is now returning 40x errors :/
`IP_ENDPOINT = "https://timezoneapi.io/api/ip"`

Could you configure your city and test that way?

Cheers

**Comment by ultrabug** [comment]
Yep.. looks like they switched to a token based auth : https://timezoneapi.io/plans

I guess we'll have to remove the "guess my city from my ip" feature from the module don't you think?

**Comment by fxdgear** [comment]
I’m using a geo location. (Lat,long)

**Comment by ultrabug** [comment]
Mind sharing your config please?

**Comment by fxdgear** [comment]
```
weather_owm {
    api_key = "balah”
    location = (long,lat )
}
```

**Comment by ultrabug** [comment]
Alright, so nothing fancy...

I can't reproduce here on my side. Here is what I tested for Paris, and it works good:

```
weather_owm {
    api_key = "balah”
    location = (2.349014, 48.864716)
}
```

What py3status version are you using? Git commits show that there was en error about coordinates on this module that got fixed in 3.17.

**Comment by fxdgear** [comment]
I'm on
```
py3status version 3.18 (python 3.7.3) on i3
```

Is there a way I can find out what the response of the 400 is so i can give you more info?

**Comment by lasers** [comment]
>... there was an error about coordinates on this module that got fixed in 3.17.

@fxdgear Hey, you didn't reply to this. I fixed https://github.com/ultrabug/py3status/issues/1728. Please confirm you tried ~~(long, lat)~~ (lat, long).

Unrelated: You might want to change your Gmail password. And maybe some other things too.

**Comment by fxdgear** [comment]
Ugh. Thank you.

**Comment by fxdgear** [comment]
@lasers ahh yes your patch was what fixed it. i just swaped from lng,lat to lat,lng and we're working now. 

I'd been moving my dotfiles to a new computer and I guess I gotan updated version of py3status in the process. 

also thanks for the heads up.
