### ISSUE TITLE
py3status lost ability to use pango markup in non-composite modules

### ISSUE THREAD

**Issue by ya-isakov** [ultrabug/py3status#1783]
Hello! I've updated to py3status to 3.18 and found that my modules, which are using pango markup, now are missing 'markup' key in py3status output, so swaybar is not rendering them properly. I found that 'markup' key is now set not in `i3bar_module_options` (which guarantees that it will be in output as well), but in `py3status_module_options`, where it is seen only by `process_composite`. Please, fix it.

**Comment by lasers** [comment]
@ya-isakov  I put out a PR. Can you try #1784? Thx.

**Comment by ya-isakov** [comment]
This PR fixed this problem, thank you!

**Comment by ultrabug** [comment]
Thanks guys
