### ISSUE TITLE
signal_percent in wifi module isn't a float

### ISSUE THREAD

**Issue by clarfon** [ultrabug/py3status#1789]
So I can't actually adjust the precision that's printed. Would be nice if I could do that.

Downside is it removes the % from the format string and you have to add it in yourself. I don't really consider this a downside, though.

**Comment by lasers** [comment]
Yup. `%`, `dBm`, `MBit/s` shouldn't be hardcoded in `{signal_percent}`, `{signal_dbm}`, `{bitrate}`. 

More downside ahead: Users can't use thresholds with hardcoded placeholders like this.

**Comment by lasers** [comment]
Closed via #1791.
