### ISSUE TITLE
reloading swaywm gives error bar with "Runtime error (RuntimeError) core.py line 983."

### ISSUE THREAD

**Issue by mxmilkb** [ultrabug/py3status#1796]
`py3status: Runtime error (RuntimeError) core.py line 983. Please try to fix this and reload i3wm (Mod+Shift+R).`

**Comment by lasers** [comment]
2018 - py3status 3.7 (python 3.5)
```bash
2018-03-13 11:57:13 WARNING Runtime error (RuntimeError) core.py line 996.
2018-03-13 11:57:13 INFO Traceback
RuntimeError: release unlocked lock
  File "py3status/py3status/__init__.py", line 55, in main
    py3.run()
  File "py3status/py3status/core.py", line 996, in run
    if self.update_request.wait(timeout=update_due):
  File "/usr/lib/python3.5/threading.py", line 550, in wait
    return signaled
  File "/usr/lib/python3.5/threading.py", line 241, in __exit__
    return self._lock.__exit__(*args)
```

2019 - py3status 3.17 (python 3.7) on i3.
```bash
2019-03-29 02:55:17 WARNING Runtime error (RuntimeError) core.py line 977.
2019-03-29 02:55:17 INFO Traceback
RuntimeError: release unlocked lock
  File "py3status/py3status/__init__.py", line 59, in main
    py3.run()
  File "py3status/py3status/core.py", line 977, in run
    if self.update_request.wait(timeout=update_due):
  File "/usr/lib/python3.7/threading.py", line 553, in wait
    return signaled
  File "/usr/lib/python3.7/threading.py", line 244, in __exit__
    return self._lock.__exit__(*args)

2019-03-29 02:55:17 ERROR py3status: Runtime error (RuntimeError) core.py line 977.
    Please try to fix this and reload i3wm (Mod+Shift+R)
2019-03-29 02:55:17 INFO lock set, exiting
```

**Comment by ultrabug** [comment]
@mxmilkb which version of py3status are you running?

**Comment by mxmilkb** [comment]
Aah, maybe my AUR helper didn't properly check all --devel packages before, but now I'm on a97f73e6 and it appears sorted. Thanks!

**Comment by nwg-piotr** [comment]
Same happens to me while running **more than one instance** (top + bottom bar) of py3status on (almost) each Sway reload. Experimentally I added a 3rd one on the secondary display, and the message appeared twice. Reopen the issue, please.

**Comment by lasers** [comment]
Hey. I recently set up a fresh sway + 4 bars of py3status on a single screen (laptop) and can't reproduce this. Is this still an issue today (3 months since the last comment)? Thx.

**Comment by nwg-piotr** [comment]
It was 11 day ago, before I went on vacation. Not very annoying, but it
happens every several reloads. I'll confirm as I'm back home.

Czw., 15 sie 2019, 11:46 użytkownik lasers <notifications@github.com>
napisał:

**Comment by nwg-piotr** [comment]
On py3status 3.19 (-git package from AUR) it used to report error in core.py line 54, and sometimes in 980:

![screenshot_2019-08-16_20-47-19_017038722](https://user-images.githubusercontent.com/20579136/63191467-d7bb0300-c068-11e9-9a16-4bca5776a58c.png)

After updating to 3.20, those are lines 58 and occasionally 1027:

![screenshot_2019-08-16_20-55-42_813986575](https://user-images.githubusercontent.com/20579136/63191535-0e911900-c069-11e9-843e-c188bb2a2d1b.png)

The error seems **not to happen** on Void Linux.

**Comment by nwg-piotr** [comment]
After updating sway to 1.2 (1.2_rc2-1 Arch package), the problem seems to have disappeared on my machine.
