### ISSUE TITLE
volume_status should be able to detect change in default device

### ISSUE THREAD

**Issue by jose1711** [ultrabug/py3status#1799]
currently `volume_status` module does not detect a change in a default device - say after connecting to bluetooth speaker. i3 reload may be used as a workaround but a more friendly approach is preferred.

**Comment by lasers** [comment]
Does it change after a `cache_timeout` ... which can be roughly 10 seconds after connecting to a new device? Also, you can try https://github.com/ultrabug/py3status/pull/1765 which should resolve your issue as it would query more than before.

**Comment by jose1711** [comment]
thank you, waiting a bit longer helps indeed. closing.
