### ISSUE TITLE
RfE: xrandr module to support displaying icons instead of output names

### ISSUE THREAD

**Issue by jose1711** [ultrabug/py3status#1800]
it would be nice if xrandr module allows to define a custom map that would make things like this possible:
💻+🖥️ instead of eDP-1+DP-1
📺 instead of HDMI-0
etc

**Comment by ultrabug** [comment]
Hey @jose1711 you'll be happy to know that it has been implemented!

It will be part of version 3.20

Thanks for sharing your idea

**Comment by jose1711** [comment]
@ultrabug thank you - i am using the code from your branch for a few weeks already :-)
