### ISSUE TITLE
[sway] window_title_async module crashes on opening new window / closing a window

### ISSUE THREAD

**Issue by nwg-piotr** [ultrabug/py3status#1808]
Note: I only tested on sway wm.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/piotr/PycharmProjects/py3status/py3status/modules/window_title_async.py", line 124, in _loop
    conn.main()  # run the event loop
  File "/usr/lib/python3.7/site-packages/i3ipc/i3ipc.py", line 716, in main
    while not self.event_socket_poll():
  File "/usr/lib/python3.7/site-packages/i3ipc/i3ipc.py", line 696, in event_socket_poll
    event = BindingEvent(data)
  File "/usr/lib/python3.7/site-packages/i3ipc/i3ipc.py", line 264, in __init__
    self.binding = BindingInfo(data['binding'])
  File "/usr/lib/python3.7/site-packages/i3ipc/i3ipc.py", line 255, in __init__
    self.mods = data['mods']
KeyError: 'mods'
```
Commenting out line 122 prevents the module from crashing, and it seems to behave well.

```
        # listens for events which can trigger the title update
        conn.on("window::title", update_title)
        conn.on("window::focus", update_title)
        # conn.on("binding", update_title)
```

Could deletion of this line be considered?

**Comment by lasers** [comment]
Untested. This should work okay. Also, https://github.com/acrisci/i3ipc-python/issues/98. 
```diff
diff --git a/py3status/modules/window_title_async.py b/py3status/modules/window_title_async.py
index 6eea2e6..b89bb45 100644
--- a/py3status/modules/window_title_async.py
+++ b/py3status/modules/window_title_async.py
@@ -119,7 +119,8 @@ class Py3status:
         # listens for events which can trigger the title update
         conn.on("window::title", update_title)
         conn.on("window::focus", update_title)
-        conn.on("binding", update_title)
+        if self.py3.get_wm_msg() == "i3-msg"
+            conn.on("binding", update_title)
 
         conn.main()  # run the event loop
 
````

**Comment by nwg-piotr** [comment]
This works well on i3. Can't check on sway while at the office. :)

**Comment by lasers** [comment]
Solution might be to wait for this. https://github.com/acrisci/i3ipc-python/pull/105. Could do `try/except KeyError` instead.

**Comment by nwg-piotr** [comment]
The decision is up to you. I fixed it locally for personal use.

**Comment by lasers** [comment]
Can you try again? That issue has been addressed.

**Comment by nwg-piotr** [comment]
Seems to work very well. 

BTW: the i3ipc-python-git AUR package seems to introduce the python-xblib dependency, which is not mentioned in PKGBUILD.

**Comment by lasers** [comment]
>Seems to work very well.

Ah good. We didn't have to do anything here. Not a py3status bug.

>BTW: the i3ipc-python-git AUR package seems to introduce the (new?) python-xblib dependency, which is not mentioned in PKGBUILD.

You can mention this at ~~https://aur.archlinux.org/packages/i3ipc-python-git/~~. Pinned comment say:
>Issues and pull requests at https://github.com/nfnty/pkgbuilds

Thanks for the ~~bug~~ report. :+1:

**Comment by nwg-piotr** [comment]
> Ah good. We didn't have to do anything here. Not a py3status bug.

I kept an eye out on their PR #105, and you were who pushed things forward. :)
