### ISSUE TITLE
weather_owm: location provider doesn't work anymore

### ISSUE THREAD

**Issue by steinex** [ultrabug/py3status#1818]
The API of the location provider used by weather_owm is not free anymore and is throwing a 401.

weather_owm should switch to another location provider, ip-api.com looks like a reasonable alternative.

**Comment by lasers** [comment]
1) Before this got merged, 57564750b0eb58c19dffd6f5dac86428d54e2a70 changed from `ip-api.com` to `timezoneapi.io`.
2) `ip-api.com` may be using third-party scripts to obtain IP addresses.
* Do we have any concerns about spyware/privacy issue? May be in some adblock/host filters.
3) Remove this feature and have users enter their `location` instead. (Also a reasonable alt.)
4) Add the url to the error message too so we know which url gave 401 + message.

**Comment by steinex** [comment]
Just my 2 cent on option 3: as a user, I would really like if this feature would be kept / restored. When traveling, the configured location wouldn't help much.

**Comment by steinex** [comment]
Another option would be using GeoClue if available. This way the module wouldn't need to ask an external provider by itself. Another benefit would be that GPS could be used, which most laptops with integrated 4G modems have anyway.

**Comment by ultrabug** [comment]
Hi mates

As I'm getting a bit fed up with those closing down APIs, I'm going to just host one myself

I'm going to adapt the module to use it

Please note that I will have to remove TZ offset calculation as I don't have offsets on my side easily

**Comment by ultrabug** [comment]
PR up

**Comment by lasers** [comment]
@steinex Please give https://github.com/ultrabug/py3status/issues/1818 a try. :-)

**Comment by steinex** [comment]
Works fine, thanks!

I have just one minor nitpick: city names with umlauts in them get their umlauts stripped. Is this something easy to fix?
