### ISSUE TITLE
Add possibility to register modules via entry points

### ISSUE THREAD

**Issue by obestwalter** [ultrabug/py3status#1822]
As an additional way of adding modules to py3status we can use entry points to find modules that are installed in the same host interpreter like documented [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins).

Advantages of this approach: 
* a py3status module can be a real package installable via pip and bring its own dependencies. 
* the modules does not need to be contained in one file and does not need to be copied into one of the configuration directories and be free of dependencies
* modules can be developed independently of py3status with a different life cycle from py3status itself

**Comment by ultrabug** [comment]
That's an awesome feature that would help the project to not overgrow the number of modules available while benefiting users for ease-of-use !

Thanks mate :)
