### ISSUE TITLE
Keyboard layout in Sway

### ISSUE THREAD

**Issue by javiertury** [ultrabug/py3status#1825]
I made a module to display the keyboard layout in sway [keyboard_layout_sway](https://github.com/javiertury/keyboard_layout_sway). Each keyboard may have different layouts active, and all of them can be displayed at the same time.

Notice:
- Cannot change keyboard layout from interface. There is no `setxkbmap` for sway.
- Before each keyboard is formatted, `color_layout` is overwritten with the color associated to the layout of the current keyboard.

SAMPLE OUTPUT

```
# Ignore colors
'⌨ ext us, int es'

# With colors
[{'full_text': '⌨ ext ', 'separator': False, 'separator_block_width': 0}, {'full_text': 'us', 'color': '#0000ff', 'separator': False, 'separator_block_width': 0}, {'full_text': ', int ', 'separator': False, 'separator_block_width': 0}, {'full_text': 'es', 'color': '#f0c674', 'separator': False, 'separator_block_width': 0}]
```

**Comment by ultrabug** [comment]
Hey @javiertury !

Thanks for letting us know about that. Did you try looking at the recently added `xkb_layouts.py` ?

Maybe it could be modified to support sway as well?

**Comment by javiertury** [comment]
I see two issues:

* The module for sway must support multiple keyboards, each with its own layout.
* Available information and functionality for sway is much poorer (only layout). Most of the placeholders would be empty.

**Comment by lasers** [comment]
@javiertury I'm looking into this again. How can I get different layouts in sway? I haz several `English (US)`, but I'm not able to get anything else in `swaymsg --raw --type get_inputs`. I used `setxkbmap -layout "us,fr"`.

**Comment by javiertury** [comment]
@lasers, I am afraid you cannot use `setxkbmap` in sway. Take a look at the official documentation [here](https://github.com/swaywm/sway/wiki#keyboard-layout). In sway you have to configure each individual keyboard in `~/.config/sway`. For instance:

```
input "1234:56789:USB_KEYBOARD" {
    xkb_layout us,es,de
    xkb_options grp:win_space_toggle
    repeat_delay 250
    repeat_rate 50
}
```

The configuration above allows to switch between the layouts `us`, `es` and `de` by pressing `windows key + space`.

**Comment by lasers** [comment]
@javiertury Check out the same link above. It's still wip, but let's see if you like it and if it's better now. This supports pointers too. If you want something or I'm missing something, let me know. Give me your feedback on everything. I hadn't tried the example input above yet.

**Comment by javiertury** [comment]
@lasers, finally I had time this weekend for a review.

I've tested your branch and everything works fine in sway. The structured of your solution seems robust. You have filled any gap with respect to the xkb commands and gone the extra mile with `libinput`. I've learned many things reading your code.

Just some minor documentation fixes and suggestions.
https://github.com/lasers/py3status/pull/7

For instance, using `{xkb_layout_names}` in the format template breaks the output of py3status. The reason is that it's an array and not a string. Perhaps you were thinking about `{xkb_active_layout_name}`.

**Comment by lasers** [comment]
>You have filled any gap with respect to the xkb commands

One thing is that I want to find a (better?) solution. I don't know about using `/usr/share/X11/xkb/symbols/` or making our own mapping config to grow... since having switchers mean having to deal with them print slightly different things such as `English` and `English (US)`. This mean not having to add more thresholds of same language too.

I think if we can turn `English` and others to `English (US)`, then maybe that's slightly less code for one-char placeholders in switchers since each switcher have different code to get it.

>For instance, using {xkb_layout_names} in the format template breaks the output of py3status

Gotcha. It's practically 99% done. The thing to do now is to clean up any missed gotchas.

I'll  merge your fixes and suggestions. Thanks for them. Also, thanks for testing.

>gone the extra mile with libinput

I don't know if users will need or care for this, but I'm glad to make this possible already. :-)

**Comment by javiertury** [comment]
Do you mean to use `/usr/share/X11/xkb/symbols/` in order to reverse map names to layout symbols(e.g. English US to `us`)?

Perhaps we can use `/usr/share/X11/xkb/base.lst` as described [here](https://unix.stackexchange.com/questions/43976/list-all-valid-kbd-layouts-variants-and-toggle-options-to-use-with-setxkbmap/356782#356782). It's a single file, and has a nicer format. We just need to load the layout and variants information in a dictionary, and then do a reverse layout lookup.

```
# layouts
sed '/^! layout$/,/^ *$/!d;//d' /usr/share/X11/xkb/rules/base.lst
# variants
sed '/^! variant$/,/^ *$/!d;//d' /usr/share/X11/xkb/rules/base.lst
```

I wonder, why swaymsg is not printing this information already...

On a sparsely related topic, I was looking up the swaymsg documentation more in depth. I failed at finding how to make the output more verbose. However I found something cool. You can launch a monitor and subscribe to input events.

```
 swaymsg -m -t subscribe '["input"]'
```

So you get an instant notification each time the keyboard layout changes. Right now there is a delay between keyboard switch and py3status.

**Comment by lasers** [comment]
>(e.g. English US to us)?

More like `us` --> `English (US)` since one of the switcher prints plain `English`. I don't remember if a  switcher prints plain `{variant}`. I want consistency in `{n}`. If this is just for `English` vs `English (US)` alone, then maybe that switcher will print some other languages without parenthesis too.

>So you get an instant notification each time the keyboard layout changes. Right now there is a delay between keyboard switch and py3status.

I done add it. You test it. :fire:

**Comment by javiertury** [comment]
That was really quick. I've tested the subscribe functionality, and works perfectly. Thank you.

Going back to consistency of format, I meant to use `symbol` as the variable printed by default, and the variable used for selecting color. All of the xkb utilities provide it.

```
$ xkb-switch
us
$ xkbgroup get all_data
0: us - English (US) - ""
$ xkblayout-state print '%s %v %N'
us  English
```

`swaymsg` doesn't provide the symbol directly, but we can use `/usr/share/X11/xkb/rules/base.lst` to find it. Take a look at this pull request.
https://github.com/lasers/py3status/pull/8/files

Now we can confidently set the thresholds to something like:
```
thresholds = [
    ("es", "red"),
    ("de", "yellow"),
    ("us", "lightskyblue"),
]
```
