### ISSUE TITLE
Add down format to wifi module

### ISSUE THREAD

**Issue by afraidofmusic** [ultrabug/py3status#1826]
Is it possible to add a down format for the wifi module? So it doesn't look like this when the device is unconnected.
![screenshot](https://user-images.githubusercontent.com/25895258/61731514-52537400-ad84-11e9-847c-2170dc1bd8cd.png)

**Comment by lasers** [comment]
The default format is `"W: {bitrate} {bitrate_unit} {signal_percent}% {ssid}|W: down"`.

It looks like you're trying to customize yours so you might want something like this.
`format = "[{device}: {ssid} {signal_percent}]"`.

**Comment by afraidofmusic** [comment]
Oh, completely missed that in the documentation. Thanks

**Comment by afraidofmusic** [comment]
Oh, completely missed that in the documentation. Thanks
