### ISSUE TITLE
relative separator_block_width parameter

### ISSUE THREAD

**Issue by GreyXor** [ultrabug/py3status#1828]
Hello everyone, I was wondering if it was possible to define a relative value for separator_block_width?
Currently we can only put the value in pixels. which is not good for me since I use py3status with screens of different resolutions because it has the effect of not having the same separation size 

You can see on this screenshot that the separations are not the same according to the resolution (full HD on the left, 4K on the right) : https://snag.gy/p487cN.jpg

**Comment by lasers** [comment]
>use py3status with screens of different resolutions

What about this...

You can try using different configs for different resolutions. See `5.7`. https://i3wm.org/docs/userguide.html where you can specify bars to different outputs. You would have to add identical modules to both configs or you can list them differently too (more flexible).

**Comment by lasers** [comment]
We didn't make `separator_block_width`. You can try filing a feature request at https://github.com/i3/i3 as it should be better there because it would be available for other status commands too.

Also, there might be similar feature request/enhancements already made there too. Cheers.
