### ISSUE TITLE
Add option to format backlight module output if there's no device found

### ISSUE THREAD

**Issue by jose1711** [ultrabug/py3status#1863]
similarly to #1862 it would be nice to have an option to configure alternate output (not receive an error) when a backlight device is not available (e. g. inside a virtual machine)

**Comment by lasers** [comment]
It looks like somebody already made this config. Try it?
>hide_when_unavailable: Hide if no backlight is found (default False)

**Comment by jose1711** [comment]
thank you, that works. closing
