### ISSUE TITLE
Spotify module

### ISSUE THREAD

**Issue by LuchiLucs** [ultrabug/py3status#1888]
I installed today py3status and tried the Spotify module without success "No module named dbus..." like closed issue "Module Spotify #183". I tried installing the optional dependency of py3status for dbus modules, nothing. I'm on Arch.

**Comment by maximbaz** [comment]
I'm not using spotify module, but I can see it depends on `python-dbus` and not on `python-pydbus` as the majority of other modules.

Please try installing `python-dbus` and let me know if this fixes the issue.

In any case, we should agree on which library we use and unite all modules.

**Comment by LuchiLucs** [comment]
Hello @maximbaz, installing `python-dbus` solved the issue. I leave it open as a reminder to edit the documentation or to unite your modules. Thanks

**Comment by ultrabug** [comment]
Thanks
