### ISSUE TITLE
[net_iplist] interface parsing mistake on arch

### ISSUE THREAD

**Issue by Segaja** [ultrabug/py3status#1892]
On archlinux you sometimes have bridge devices in your interfaces which produces an output for `ip address show` like this:
```
*snip*
5: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 34:f3:9a:33:54:aa brd ff:ff:ff:ff:ff:ff
6: br-f03fcc540210: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:6c:cc:c3:60 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-f03fcc540210
       valid_lft forever preferred_lft forever
```

The regex used here ( https://github.com/ultrabug/py3status/blob/master/py3status/modules/net_iplist.py#L80 ) matches only `\w+` which is `a-zA-Z0-0_`. This doesn't include the `-` which is why the code never sees that a new interface definition begins. This leads to the wlan0 device being listed as up with the ip "172.18.0.1".

**Comment by ultrabug** [comment]
Thanks for reporting @Segaja ! You're right, I've fixed the regex :)

Cheers mate!
