### ISSUE TITLE
mpd_status: py3staus doesn't die on SIGTERM with idle

### ISSUE THREAD

**Issue by L0ric0** [ultrabug/py3status#1894]
when idle is enabled on mpd_status py3status doesn't die on a `SIGTERM` this leaves swaybar and py3status processes running when reloading sway

this is probably to not killing the tread for the idling correctly

**Comment by ultrabug** [comment]
ping @girst plz?

**Comment by girst** [comment]
opened a pr with a fix; would you mind to test it out? https://github.com/ultrabug/py3status/pull/1895

**Comment by L0ric0** [comment]
seems to wrok. at last it terminates on sway reload and strg+c when started from the terminal.
