### ISSUE TITLE
Using colors in modules adds spaces under Sway

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#1897]
No colors:

![image](https://user-images.githubusercontent.com/1177900/73136346-e7de0200-404c-11ea-9d03-c9e9d7ddaf39.png)

With colors: 

![image](https://user-images.githubusercontent.com/1177900/73136351-f9270e80-404c-11ea-9895-ca811e3c565b.png)

Config:

```
xkb_input {
  cache_timeout = -1
  button_prev = None
  button_next = None
  format = "{format_input}"
  format_input = '[\?color=s {s}]'
  format_input_separator = " "
  inputs = [{"name": "*eyboard"}]
  thresholds = [
    ('ru', '#fb4934'),
  ]
}
```

I confirmed that with `thresholds = []` there is no artificial spacer.

This only happens under sway, so I'm not sure if the problem is on our end or somewhere in swaybar...?

----

This is another example:

![image](https://user-images.githubusercontent.com/1177900/73136387-5f139600-404d-11ea-9725-345d453838d0.png)

```
usbguard {
  format_button_allow = '  '
  format_button_reject = '  '
}
```

**Comment by lasers** [comment]
>...I'm not sure if the problem is on our end or somewhere in swaybar...?

I wonder if it is a HiDPI-related issue on sway or swaybar. I'm almost certain you would notice this issue long time ago so something might had changed recently. Could try downgrading sway/swaybar.

**Comment by maximbaz** [comment]
I can reproduce this on regular DPI screen, and I only recently switched to sway, so I don't know if it ever worked as expected (but there was one new release already of sway/swaybar since I moved to it, and the issue persisted after update).

**Comment by Sviests** [comment]
I`m experiencing a similar issue. I switched to sway from i3wm recently and the modules using this formatting have extra spaces when rendered. In my case, modules memory and loadavg have these issues.
![image](https://user-images.githubusercontent.com/8798050/108030040-2fa84080-7037-11eb-89ea-b754a38ed123.png)

This is my config:
`loadavg {
    # htop - mc and three shades of gray is similar. htop - mc
    # have higher contrast between time periods over three shades
    # of gray for better readability. your mileage may vary.

    thresholds = {
        '1avg': [
            (0, '#9dd7fb'),
            (19, '#50fa7b'), (29, '#f1fa8c'),
            (39, '#ffa500'), (50, '#FF5555')
        ],
        '5avg': [
            (0, '#4bb6f8'),
            (19, '#50fa7b'), (29, '#f1fa8c'),
            (39, '#ffa500'), (50, '#FF5555')
        ],
        '15avg': [
            (0, '#0991e5'),
            (19, '#50fa7b'), (29, '#f1fa8c'),
            (39, '#ffa500'), (59, '#FF5555')
        ],
    }
    format = '  [\?color=1avg {1min}] '
    format += '[\?color=5avg {5min}] [\?color=15avg {15min}] '
}

conky {
    config = {
        'update_interval': 10,             # update interval for conky
        'update_interval_on_battery': 60,  # update interval when on battery
        'format_human_readable': True,    # if False, print in bytes
        'short_units': True,              # shortens units, eg kiB->k, GiB->G
        'uppercase': True,                # upper placeholders
    }
}

conky memory {
    format = '  [\?color=memperc {mem}/{memmax}] '
    thresholds = [
        (0, 'darkgray'), (0.001, '#9dd7fb'), (50, '#f1fa8c'),
        (75, 'orange'), (85, '#FF5555')
    ]
}`

**Comment by kenoh** [comment]
This has been fixed in Sway master now: https://github.com/swaywm/sway/commit/d6ac30753ded44c5f1921a3bbccb5856d5ef6539
Just backporting the patch into Sway 1.5.1 did the charm for me.

**Comment by lasers** [comment]
@Sviests (FYI) Your `conky {}` instance doesn't do anything.

To apply conky's config to `conky memory {}` instance. Do it like this.

```python
order += "conky memory"
conky memory {
    format = '  [?color=memperc {mem}/{memmax}] '
    thresholds = [
        (0, 'darkgray'), (0.001, '#9dd7fb'), (50, '#f1fa8c'),
        (75, 'orange'), (85, '#FF5555')
    ]
    config = {
        'update_interval': 10, # update interval for conky
        'update_interval_on_battery': 60, # update interval when on battery
        'format_human_readable': True, # if False, print in bytes
        'short_units': True, # shortens units, eg kiB->k, GiB->G
        'uppercase': True, # upper placeholders
    }
}
```

**Comment by Sviests** [comment]
@lasers Thank you for the heads up! I must have copy-pasted this without giving it a thought...

**Comment by ultrabug** [comment]
Thanks @kenoh ; I guess I can close this now then. If not tell me and I'll reopen.

**Comment by su8** [comment]
@ultrabug why is not @lasers Collaborator

**Comment by ultrabug** [comment]
@su8 he was for a while and decided to remove himself from it
