### ISSUE TITLE
imap: add filtering like in mail plugin

### ISSUE THREAD

**Issue by L0ric0** [ultrabug/py3status#1902]
it would be nice to have mailbox filtering in the imap plugin like in the mail plugin, so that it is possible to filter for example for all mailboxes that don't contain spam

**Comment by girst** [comment]
you can tell `imap` which mailbox(es) to query with the `mailbox=` option. iirc, it takes multiple ones when separated by a comma, like `"foo,bar"`.

**Comment by L0ric0** [comment]
yeah i know, but if you have sieve filters which can create mailboxes that is not rely an option

**Comment by ultrabug** [comment]
closing as per #1926
