### ISSUE TITLE
Add a simple generic module to show output of external script

### ISSUE THREAD

**Issue by abolognino** [ultrabug/py3status#1905]
Unless I'm missing something obvious, I see no way to display the output of a custom command, this would be very useful to add info.

**Comment by lasers** [comment]
Thoughts on [.../modules/external_script.py](https://github.com/ultrabug/py3status/blob/master/py3status/modules/external_script.py)?

**Comment by abolognino** [comment]
Sorry, I don't know how I missed that. I've looked at the docs multiple times...
