### ISSUE TITLE
Add notification to wifi module

### ISSUE THREAD

**Issue by rixx** [ultrabug/py3status#1912]
I only need to see my IP address and further network information occasionally, so it would be nice to display it in an on-click notification on the wifi module.

**Comment by lasers** [comment]
Possible solution.

`~/.config/py3status/config`
```python
order += "static_string ip_addr"
static_string ip_addr {
  format = '\?color=lightblue \[ip addr\]'
  on_click 1 = 'exec ~/.bin/notify-ip-addr.sh'
}
```

`~/.bin/notify-ip-addr.sh`
```bash
#!/usr/bin/env sh

TITLE='[ip addr]'
BODY=`ip addr | awk '/^[0-9]+:/ {
  sub(/:/,"",$2); iface=$2 }
/^[[:space:]]*inet / {
  split($2, a, "/")
  print iface" : "a[1]
}'`

notify-send "$TITLE" "$BODY"
```

**Comment by ultrabug** [comment]
I'm unsure how to respond to this tbh @rixx since we could argue this need to be true for other modules combinations...

Maybe the best way would be to add such an action feature on v4.. something generic like `on_click 1 = 'notify_output <other_module_instance_name>'`?

**Comment by rixx** [comment]
If you think this is too complex, feel free to close the issue. I made my own wifi module several years ago to satisfy this requirement (I usually don't care about IP addresses and don't want to clutter my i3bar). I only opened this issue when I tried to migrate away from my set of custom modules towards official ones.

**Comment by lasers** [comment]
@ultrabug We could treat this as duplicate https://github.com/ultrabug/py3status/issues/1531, thus closing this one.

**Comment by ultrabug** [comment]
Indeed @lasers thank you
