### ISSUE TITLE
Coin Market module not working

### ISSUE THREAD

**Issue by aubruz** [ultrabug/py3status#1913]
According to the coinmarketcap doc, the free api is deprecated. But it's still possible to use the pro api for free with an account. 

Source: [https://pro.coinmarketcap.com/migrate/](https://pro.coinmarketcap.com/migrate/)

**Comment by ehula** [comment]
What changes to the code are required to use the pro api? Can this module be updated so that if we have a pro account we can continue using it?

**Comment by aubruz** [comment]
I didn't look at the details of the code. This module can be updated to continue using it with a pro/free account. Unfortunately I didn't have much time to take a closer look at it.

**Comment by ehula** [comment]
Would love it if you could update it! :)

**Comment by aubruz** [comment]
I will try to arrange some time this month to take care of it.

**Comment by aubruz** [comment]
@lasers thanks!
