### ISSUE TITLE
Fix order of flags in `amixer`

### ISSUE THREAD

**Issue by jose1711** [ultrabug/py3status#1914]
https://github.com/ultrabug/py3status/blob/2dbe8b8cabb721edb4ddce902e80636fb10aadd4/py3status/modules/volume_status.py#L133

I am not really sure what's happening here but looks like the order of flags given to `amixer` matters.
1. `-D` first (the way how `py3status` invokes `amixer`):
  ```
$ amixer -D default -c 0 sget Master
amixer: Unable to find simple control 'Master',0
  ```
2. `-c` first:
  ```
$ amixer -c 0 -D default sget Master
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 1968 [3%] [on]
  Front Right: Playback 0 [0%] [on]
  ```
Maybe this is a problem of `amixer` as I don't see any warning about the order in its man-pages.

**Comment by lasers** [comment]
What version? `amixer -D default -c 0 sget Master` works fine here on `amixer version 1.2.2`.

**Comment by jose1711** [comment]
`alsa-utils 1.1.8-2` in Raspbian 10 (`buster`)

**Comment by ultrabug** [comment]
Hi

So it looks like older versions are affected by ordering, I proposed a PR

**Comment by jose1711** [comment]
thanks for the fix!
