### ISSUE TITLE
py3-cmd doesn't click on clock module

### ISSUE THREAD

**Issue by TRSx80** [ultrabug/py3status#1917]
Hallo again. I am really enjoying this tool. :) I came across something though that I wanted to bring to your attention.

I was trying to use `py3-cmd` to click and cycle through `clock` module formats like so:
```
py3-cmd click --button 3 clock
```
This works from command line, cycling through various time formats, so far so good. However, when I try to do so from keybinding in i3(-gaps) like following, for some reason it fails:
```
bindsym $mod+t exec py3-cmd click --button 3 clock
```
Now, just to make sure I don't make typo, or the problem is not with i3(-gaps), I did the following, which worked:
```
bindsym $mod+t exec notify-send wtf
```
So then I was scratching my head. I double, triple, quadruple check my syntax but I didn't see anything wrong.

I ended up getting the job done with `xdotool` but I like you guys so I wanted to take the time to file a bug report.

Cheers!

**Comment by lasers** [comment]
This works fine for me with default `button 1`. 
>bindsym $mod+t exec py3-cmd click --button 1 clock

Strange, indeed if you can't find anything wrong. :confused:

**Comment by TRSx80** [comment]
I had to go back and play with this to remember the problem.

Now I didn't dig back through the code this time, but I seem to recall that button 1 (left mouse button for me) is for switching the location / time zone, while button 3 (right mouse button for me) is for cycling through the formats.

I don't have any different time zones configured (although I seem to remember playing with some for testing) only different time formats (ISO long date, short time only, etc...), hence the button 3.

Maybe set up a couple different formats and try to right click on them, and then try and do the same programmatically (with `py3-cmd click`) and you should see what I mean.

Unless I badly mis-understood the code or my config (possible!). :smile:

**Comment by lasers** [comment]
Can we use your `clock` config instead? :hot_face:

**Comment by TRSx80** [comment]
Yeah, that thought had crossed my mind as I was reading my commented config and remembering some things. At any rate, a consistent config should help us narrow down the issue, anyway. You might have to adjust `3` though if your hardware is different? Here is my exact config:
```
clock {
      # This was neat and worked good, but I just want a more clean look now.
      #format = [" Virginia{America/New_York}", " Igor{Europe/Ljubljana}", " Utah{America/Denver}"]
      format_time = [
      		    " %H:%M ",
		    " %a %-d %b %H:%M ",
		    " %a %-d %b %H:%M %Z ",
		    " %F %a %H:%M %Z ",
		    # This from source, helped me figure out and give good format:
		    #"[ {name_unclear} ]%a %-d %b %H:%M %Z ",
		    #"[ {name_unclear} ]%F %a %H:%M %Z ",
		    #"[ {name_unclear} ]%a %H:%M ",
		    #"[ {name_unclear} ]{icon} ",
		    ]
      # R button on Corsair mouse
      button_change_time_format = 3
      # I struggled with this quite a while before I realized the
      # following setting was conflicting (default = 3)!
      button_reset = 0
      }
```

**Comment by lasers** [comment]
This works fine for me using your config as `clock test {..}` and...

```
bindsym $mod+t exec py3-cmd click --button 3 "clock test"
```
I added numbers to `format_time` too and can see them all cycling okay via bindsym and mouse.

Maybe there is something using your $mod+t shortcut?

**Comment by ultrabug** [comment]
timeout, closing
