### ISSUE TITLE
vpn_status loses state if you close i3 and log back in

### ISSUE THREAD

**Issue by TRSx80** [ultrabug/py3status#1918]
By "close" I mean doing (what I have set to) mod+shift+q; i.e. `exit` i3; perhaps that is too aggressive?

So, `vpn_status` seems to work (sort of), by that I mean:
* When you log in and no VPN is connected, it shows up red and with the correct string I formatted.
* When you log on to VPN, it turns green and even gives name of VPN. Very nice! And this was one of main reasons I switched from vanilla `i3status`.

But then, if I log out via `exit` command in i3(-gaps) back out to `lightdm` and then log back in, I can see `nm-applet` still correctly showing the lock icon, and I can also verify my IP by going somewhere like ipchicken, however the `vpn_status` logo stays red as if it's not connected.

I tried playing with some settings with the pidfile, etc. but couldn't seem to get anything to work.

The default `i3status` bar does not give the name of the VPN, but in the time I was using it (before switching to `py3status`) it did seem to update to the correct status almost immediately (both ON and OFF).

My setup at this point is down to the bare minimum:

`~/.config/py3status/config`:
```
vpn_status {
	 format = " {name} | VPN "
}
```

**Comment by ultrabug** [comment]
This is because the dbus monitor is triggered only on the `onPropertiesChanged` event so far

#2074 should fix this, please follow up there and report, closing here
