### ISSUE TITLE
Icon size in status bar too small

### ISSUE THREAD

**Issue by nylocx** [ultrabug/py3status#1919]
As a picture says more than my words could here is the effect:

![image](https://user-images.githubusercontent.com/3329124/76350020-4dd7cd80-630b-11ea-9566-894c7af285ab.png)

I'm not sure when this started, but it is a bit annoying that the icons are that small compared to the font size.

I'm on py3status version 3.27 python 3.8.1 on i3 (arch linux)

**Comment by ultrabug** [comment]
Hi @nylocx are you supposing this is due to py3status itself? Because AFAIK we only spout text as JSON to the i3bar and it's the bar's responsibility to render it :/

**Comment by nylocx** [comment]
I wasn't aware that the complete rendering is done by the i3bar. I guess that the fault lies in there. I will try at the i3 bugtracker (if I can find it :P).
