### ISSUE TITLE
Python Dict for expected in whatismyip means only one city (or other criteria) at a time?

### ISSUE THREAD

**Issue by TRSx80** [ultrabug/py3status#1922]
Hai guise! Hope I'm not being too much of a pest. :smile: Just logging some annoyances here until maybe I get enough annoyed to dust off my Python and think about submitting a PR. :smile: 

Until I can get [VPN](https://github.com/ultrabug/py3status/issues/1918) working reliably for me, I have been looking for workarounds, which led me to `whatismyip` module. So far I set it up to display the city of my VPN, and turn green when it's on that city (i.e., when VPN is using that exit node).

But sometimes I use different exit nodes. And according to [Python docs](https://docs.python.org/3/tutorial/datastructures.html#dictionaries) (emphasis mine):
> It is best to think of a dictionary as a set of key: value pairs, with the requirement that *the keys are unique* (within one dictionary)

If I am understanding this correctly, then that means we can only have one "city" (or other criteria) at a time for the `expected` dict? Is that right?

**Comment by lasers** [comment]
Yup. To improve this, `expected` could be accepting lists too. Maybe `fnmatch` too just cuz...
```python
expected = {
    "country": ["France", "German", "Ru*"]
}
```

**Comment by ultrabug** [comment]
@TRSx80 if that answers your question, could you please close this issue mate?

**Comment by TRSx80** [comment]
I took lasers post two above this one to mean that this is something that needs to be implemented in the code? More than a simple change that maybe I could do myself?

So I guess yes we can close it in the sense that my question was answered, but no if you want to keep it open for any interested party to track the issue. Personally, I don't suppose I care either way, so I leave it up to you guys.

Or maybe I just misunderstood out of still low Python wizard level. :smile: 

Thanks again for all your work!

**Comment by ultrabug** [comment]
See comment in related PR, thanks
