### ISSUE TITLE
Multiple instances of lm_sensors: only last one is using thresholds

### ISSUE THREAD

**Issue by ya-isakov** [ultrabug/py3status#1927]
Hello! I'm using py3status-3.27 with sway, and many applets has colors, e.g. volume_status or wifi. But, only last instance of lm_sensor is using thresholds to change the color of values. Relevant part of my config:

```
general {
        colors = true
        interval = 5
}
order += "lm_sensors fan"
order += "lm_sensors temps"
order += "lm_sensors hdd"

lm_sensors fan {
    format_sensor = "[\?color=auto.input {input}]"
    format_chip = "{format_sensor}"
    chips = ["thinkpad-isa-0000"]
    sensors = ["fan1", "temp1"]
}

lm_sensors temps {
    format_sensor = "[\?color=auto.input {input}]"
    format_chip = "{format_sensor}"
    format_sensor_separator = "/"
    chips = ["coretemp-isa-0000"]
}

lm_sensors hdd {
    cache_timeout = 60
    format_sensor = "[\?color=auto.input {input}]"
    format_chip = "{format_sensor}"
    chips = ["drivetemp-scsi-1-0"]
}
```

**Comment by ya-isakov** [comment]
Sometimes I can see color on two lm_sensor's instances, sometimes on one, sometimes I cannot see color on any instance. It looks like it's a problem with auto.input, with custom thresholds on every instance, no problems with colors.

**Comment by lasers** [comment]
We could use `sensors -u` too to attempt reproducing this. I might look into this.

**Comment by ultrabug** [comment]
I cannot reproduce this I'm afraid @ya-isakov 

@lasers I guess you couldn't too?

**Comment by lasers** [comment]
@ultrabug Sorry. I reproduced this months ago. I think it's because module instances are being shared via module basename.

**Comment by lasers** [comment]
@ya-isakov Can you use this instead?
```python
lm_sensors {
    format_chip = '[\?if=name=thinkpad-isa-0000 fan ]'
    format_chip += '[\?if=name=coretemp-isa-0000 temp ]'
    format_chip += '[\?if=name=drivetemp-scsi-1-0 hdd ]'
    format_chip += '{format_sensor}'
    format_sensor = '\?color=auto.input {input}'
}
```

It's more efficient this way because your system wouldn't execute `sensors` three times-ish every interval and would parse everything in one go. You would lose your separator for the cores tho.

**Comment by lasers** [comment]
@ultrabug No response from the author. IIRC it is an "issue" not exclusive to lm_sensors because I vaguely remember I had issue with reusing same color threshold names with different configs for different formats too... I was not familiar with py3status too.

If it's the same one, this one looks to be occurring between instances too. Shared and all that.

Trivial issue imho. Kindly ignore this one.

**Comment by ultrabug** [comment]
Yep, thanks

**Comment by ya-isakov** [comment]
Sorry for not answering, I've changed my sensors from auto.input to use some defined limits, and now it works.
