### ISSUE TITLE
Can't use custom modules

### ISSUE THREAD

**Issue by IgnisDa** [ultrabug/py3status#1929]
I tried to follow along [this](https://py3status.readthedocs.io/en/latest/writing_modules.html) doc, and saved a configuration file in `~/.config/py3status/config`. Then I created a new file `hello_world2.py` in the same directory and added this lines to my `config`.
```
order += "hello_world2"
hello_world2{
   format= 'IT WORKS!'
}
```
This is what hello_world2.py has:
```
class Py3status:
    format = 'Hello_World!'

    def Hello_World(self):
        return {
            'full_text': self.format,
            'cached_until': self.py3.CACHE_FOREVER
        }
```
However, I am not getting the desired output which I want (`IT WORKS!`). What am i doing wrong, and how can I do it correctly?

**Comment by lasers** [comment]
>Then I created a new file hello_world2.py in the same directory...

For clarification, the custom modules goes in `~/.config/py3status/modules/` directory.

**Comment by IgnisDa** [comment]
Thank you very much, it works now. Also how do I get the .py files of the preinstalled modules like clementine, time etc?

**Comment by lasers** [comment]
That's distro specific and I don't know your distro. Find this action. :package: 
>Display files provided by local package 

https://wiki.archlinux.org/index.php/Pacman/Rosetta#Querying_specific_packages

**Comment by IgnisDa** [comment]
Well, thanks, I'll be trying that out. My distributionis Arch Linux.

**Comment by ultrabug** [comment]
Closing, happy coding @IgnisDa and thx @lasers
