### ISSUE TITLE
py3status.modules unable to import lm_sensors

### ISSUE THREAD

**Issue by thepyguy** [ultrabug/py3status#1937]
I checked and lm_sensors is installed I'm just guessing something happened with versioning and it is broken? If anybody has experienced this issue or has a fix please let me know.

**Comment by ultrabug** [comment]
Hi @thepyguy I'm unaware of this problem. What version are you running and what OS please?

**Comment by thepyguy** [comment]
Ubuntu 18.04 LTS
py3status version 3.7 (python 3.6.9)
/usr/bin/py3status
lm_sensors: Import Error, No module named 'py3status.modules.lm_sensors'

02:48:19  eusid @sol  ~/.config/i3 $  which sensors
/usr/bin/sensors

# ~/.config/i3/config
bar {
        strip_workspace_numbers yes
        status_command py3status -c ~/.config/i3/i3status.conf
        colors {
          separator #eceff4
          background #3b4252
          focused_workspace #4c566a #4c566a #d8dee9
        }
}


#~/.config/i3/i3status.conf
order += process_status
order += lm_sensors
order += sysdata
order += net_rate
order += uptime
order += time

lm_sensors {
    sensors = ['tdie']
    color_input = "#a3be8c"
    format_chip = "{format_sensor}"
    color_excl_input = "#a3be8c"
}
py3status {
    navbar_font='pango:Ubuntu Mono 14'
    align="center"
}
general {
    color_good = "#a3be8c"
    color_bad = "#bf616a"
    color_degraded = "#d08770"
}
process_status {
    format ="{process}"
    process = "ezstream"
}
time {
    format = "%A %m.%d.%Y %H:%M:%S"
}
net_rate {
    format = "{down}↓ {up}↑"
}
uptime {
    format = "uptime: {days}d {hours}:{minutes:02d}:{seconds:02d}"
}

Was working until last week I'm not really sure what I could have done but to my knowledge I haven't touched my install.

**Comment by ultrabug** [comment]
@thepyguy well I don't know what changed on your side but you sure have an old version of py3status where the lm_sensors module did not exist.

You run 3.7, we are 3.28 mate

Maybe something got mixed up when running a system upgrade?

**Comment by ultrabug** [comment]
FYI it got added on version 3.13 (2018-09-28)

**Comment by thepyguy** [comment]
3.7 is not newer than 3.28???

**Comment by ultrabug** [comment]
nope; 7 < 28

**Comment by thepyguy** [comment]
Thanks the update fixed it

**Comment by ultrabug** [comment]
np mate, closing
