### ISSUE TITLE
module available, but getting py3status: loading module failed?

### ISSUE THREAD

**Issue by nschubach** [ultrabug/py3status#194]
Sorry if this is not the appropriate place, but I can't find a support list or forum?  I'm trying to add a status for mpc to my bar.  I looked at:

$ py3status modules list
  mpd_status             Display information from mpd.

So I assume it's "installed" and available.  I added the following to my .i3status.conf:

order += "mpdstatus"
and
mpdstatus {
        name = "♬"
        cache_timeout = 0
        host = "localhost"
        port = 6600
}

per http://py3status-modules.readthedocs.org/en/latest/configuration.html?#id4

but every time I reload with this module, I get a problem

loading module "mpdstatus" failed (No module named mpdstatus)

error in i3 when I reload.  I figured I missed a step of `py3status modules install mpd_status` or something, but the docs here:
https://github.com/ultrabug/py3status/wiki/Load-and-order-py3status-modules-directly-from-your-current-i3status-config

simply state I should be able to use the name of the module without any special installation?  I've tried using mpd_status as the module name, but then I get an error about missing the `mpd` module.

What am I missing?

**Comment by pydsigner** [comment]
You need to pass `-i path/to/my/modules/dir` to py3status in your i3 config.

**Comment by nschubach** [comment]
I did do:
```
sudo pypi-install python-mpd2
```

which I though installed, but running it again I get a long winded return that states:

No local packages or download links found for tox
error: Could not find suitable distribution for Requirement.parse('tox')
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=1: python2.7 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.7 --dir . returned exit code 13
debian/rules:7: recipe for target 'build' failed

**Comment by ultrabug** [comment]
Hi @nschubach 

First of all, just so it's clear, all the modules listed by `py3status modules list` really are available to you. There's nothing more to install.

As far as I see it, the main reason is that you missed the underscore in the order and config of `mpd_status`. Here is an example of my working setup:

```
order += "mpd_status trotrobox"

mpd_status trotrobox {
	cache_timeout = 15
	color = "true"
	format = "{name}|{artist}"
	max_width = 50
	host = 'trotrobox'
	port = 1337
	on_click 1 = "exec mpc -h trotrobox -p 1337 toggle"
	on_click 2 = "exec mpc -h trotrobox -p 1337 prev"
	on_click 3 = "exec mpc -h trotrobox -p 1337 next"
	on_click 4 = "exec mpc -h trotrobox -p 1337 volume +20"
	on_click 5 = "exec mpc -h trotrobox -p 1337 volume -20"
}
```

And yes, you have to install any dependency listed on the modules' doc before using it. For the mpd_status one, it's `python-mpd2` which should be listed if you run a `pip freeze` on your machine.

Also note that you can get all modules' documentation by running `py3status modules details` or going to this page : https://github.com/ultrabug/py3status/blob/master/py3status/modules/README.md

Finally, feel free to come over on FreeNode IRC channel #py3status if you wish !

Hope this helps :)

**Comment by pydsigner** [comment]
The problem with your install looks to me to be that you used `pypi-install`. I'm not familiar with that tool, but you should definitely be using `pip install` instead. Note that you might have to install pip first.

**Comment by nschubach** [comment]
I was using pypi-install because I'm on Debian and one of the install docs at one point said that I'd need to pull it that way instead of pip.  I haven't done any Python in some time so I just followed along.

**Comment by ultrabug** [comment]
Yes I guessed you were a Debian user. This tip was given by a Debian dev who's a py3status user because you ended up with permission problems when using pip.

Did my comment above help you @nschubach ? are you still stuck ?

**Comment by nschubach** [comment]
Sorry, been super busy with work and haven't had a chance to get back to this.  I'll carve out some time today.

**Comment by nschubach** [comment]
Finally got back to this and installing `python-pip` (Debian) then running `pip install python-mpd2` solved the issue.

Thanks for the help!
