### ISSUE TITLE
Commit 9cf96a91 Broke battery_level module

### ISSUE THREAD

**Issue by naclander** [ultrabug/py3status#1950]
Hello,

From my investigation commit 9cf96a91 broke the `battery_level` module. 

I'm running on Arch Linux and the latest update to py3status seemed to have pulled this in. 

I pulled the source from this github repo and installed py3status on my machine, with 9cf96a91 reverted, and the `battery_level` module seems to be working fine again.

Can we revert this commit until a working solution is refined?

**Comment by armandg** [comment]
I have the same experience:
`battery_level: unsupported operand type(s) for /: 'NoneType' and 'NoneType'`

**Comment by ultrabug** [comment]
ping @dkm

**Comment by ultrabug** [comment]
@armandg @naclander can any of you reproduce this and get a larger backtrace to understand where this comes from?

I can't reproduce this here :/

**Comment by dkm** [comment]
Maybe it's a python version thing ? I'll have a look later today. Can you please provide your python version so I can fix this quickly ? Sorry !

**Comment by armandg** [comment]
@dkm 
 ~ $ python3 --version
Python 3.8.2

**Comment by armandg** [comment]
A thought:

What kind of batteries will not be checked if we leave out the `"*bat*"` from the bglobs variable in line 298?

**Comment by dkm** [comment]
@armandg : The kind that motivated the original patch (GPD Pocket v1) `max170xx_battery`. I was thinking of better filtering by checking the subdir contains the correct files before proceeding. I'll push some patch later tonight (after kids are asleep :D)

**Comment by dkm** [comment]
Could you provide me with a listing of files within your `/sys/class/power_supply/hidpp_battery_0` dir ? To be sure that filtering on the existence of the files used in `battery_level` is enough.

**Comment by naclander** [comment]
Below is a listing of all files under `/sys/class/power_supply/` :

```
tree /sys/class/power_supply

/sys/class/power_supply/
├── AC -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/AC/
├── BAT0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/
├── ucsi-source-psy-USBC000:001 -> ../../devices/platform/USBC000:00/power_supply/ucsi-source-psy-USBC000:001/
├── ucsi-source-psy-USBC000:002 -> ../../devices/platform/USBC000:00/power_supply/ucsi-source-psy-USBC000:002/
└── wacom_battery_0 -> ../../devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-WCOM4840:00/0018:056A:4840.0001/power_supply/wacom_battery_0/

5 directories, 0 files
```

**Comment by dkm** [comment]
Thanks. I only see now that the merge of the PR did not include my original commit message : https://github.com/dkm/py3status/commit/5300b79dc5925e85ee9ab2a616437154d6f7d4d6

```
Previous code only matches with "BAT*" names in the /sys/class/power_supply.
There does not seem to be any naming convention in the documentation:
https://www.kernel.org/doc/html/latest/power/power_supply_class.html
For example, the battery on the GPD Pocket is exposed as "max170xx_battery".

This patch allows for easier addition of glob patterns to use to match for
battery nodes and adds "*bat*" in the list.
```

That would have answered your previous question.

**Comment by dkm** [comment]
Can you test this : https://github.com/dkm/py3status/tree/pr-fix-1950 ?

**Comment by naclander** [comment]
Applied https://github.com/dkm/py3status/commit/a2f69e5258059f13e319c54f9e67723fbed425a5.patch to my tree,

I'm seeing the same behavior:

```
~/Projects/python/py3status/py3status/modules(master*) » python battery_level.py                      0s
Module `test_module`: selected measurement_mode `sys`
unsupported operand type(s) for /: 'NoneType' and 'NoneType' (TypeError) module.py line 940.
Traceback
TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'
  File "/usr/lib/python3.8/site-packages/py3status-3.29-py3.8.egg/py3status/module.py", line 940, in run
    response = method()
  File "battery_level.py", line 176, in battery_level
    battery_list = self.get_battery_info()
  File "battery_level.py", line 324, in _extract_battery_info_from_sys
    math.floor(remaining_energy / capacity * 100)

```

**Comment by dkm** [comment]
Ok, thanks for testing. Was hoping this simple fix would work. Will do something better later tonight !

**Comment by armandg** [comment]
@dkm Full tree of requested folder:
```
/sys/class/power_supply/hidpp_battery_0
├── capacity_level
├── device -> ../../../0003:046D:4069.0004
├── hwmon6
│   ├── device -> ../../hidpp_battery_0
│   ├── name
│   ├── power
│   │   ├── async
│   │   ├── autosuspend_delay_ms
│   │   ├── control
│   │   ├── runtime_active_kids
│   │   ├── runtime_active_time
│   │   ├── runtime_enabled
│   │   ├── runtime_status
│   │   ├── runtime_suspended_time
│   │   └── runtime_usage
│   ├── subsystem -> ../../../../../../../../../../../../class/hwmon
│   ├── temp1_label
│   ├── temp2_label
│   └── uevent
├── manufacturer
├── model_name
├── online
├── power
│   ├── async
│   ├── autosuspend_delay_ms
│   ├── control
│   ├── runtime_active_kids
│   ├── runtime_active_time
│   ├── runtime_enabled
│   ├── runtime_status
│   ├── runtime_suspended_time
│   ├── runtime_usage
│   ├── wakeup
│   ├── wakeup_abort_count
│   ├── wakeup_active
│   ├── wakeup_active_count
│   ├── wakeup_count
│   ├── wakeup_expire_count
│   ├── wakeup_last_time_ms
│   ├── wakeup_max_time_ms
│   └── wakeup_total_time_ms
├── powers -> ../../../0003:046D:4069.0004
├── scope
├── serial_number
├── status
├── subsystem -> ../../../../../../../../../../../class/power_supply
├── type
├── uevent
└── wakeup40
    ├── active_count
    ├── active_time_ms
    ├── device -> ../../hidpp_battery_0
    ├── event_count
    ├── expire_count
    ├── last_change_ms
    ├── max_time_ms
    ├── name
    ├── prevent_suspend_time_ms
    ├── subsystem -> ../../../../../../../../../../../../class/wakeup
    ├── total_time_ms
    ├── uevent
    └── wakeup_count
```

**Comment by dkm** [comment]
Ah ! `uevent` is here, so that explains that my previous patch is not working. I'll filter on required values.

**Comment by naclander** [comment]
@dkm I tried applying commit  4e6421 on top of master and that seemed to have fixed the stacktrace.

**Comment by dkm** [comment]
Great ! Let's see if @ultrabug has any issue with this patch. Sorry for the disturbance, even if this could have happened with any other device having `BAT` in its name. My fix made it easier to hit this !

You are right about tests, but I've not looked how they work. I may add one if @ultrabug think this is an easy task.

**Comment by ultrabug** [comment]
Thanks a lot guys, I'll merge & release a new version today

There is no real testing framework for individual modules yet I'm afraid
