### ISSUE TITLE
Battery level is sometimes greater than 100%

### ISSUE THREAD

**Issue by lovetocode999** [ultrabug/py3status#1953]
Sometimes, the battery_level indicator reports values greater than 100%. Is this to be expected?
![image](https://user-images.githubusercontent.com/36867192/94218475-c9f9c300-fea1-11ea-8c11-0848392c1d36.png)

System Info:
OS: Bedrock Linux
WM: Sway

~/.config/i3status/config:
```conf
# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        interval = 5
        color_good = "#75b938"
        color_degraded = "#dbb32d"
        color_bad = "#fa5750"
}

order += "load"
order += "disk /"
order += "memory"
order += "battery_level"
order += "clock"
order += "wireless _first_"

wireless _first_ {
        format_up = " %essid at %ip  "
        format_down = " internet down  "
}

battery_level {
        blocks = ""
        format = " {percent}% {icon}  "
        threshold_degraded = 20
        notify_low_level = true
}

disk "/" {
        format = " %avail   "
}

load {
        format = " %1min   "
}

memory {
        format = " %used / %total   "
        threshold_degraded = "1G"
        format_degraded = " MEMORY < %available "
}

clock {
        format = ["{America/Denver}"]
        format_time = " %Y-%m-%d %I:%M:%S %P {icon} "
}
```

**Comment by lasers** [comment]
>Sometimes, the battery_level indicator reports values greater than 100%. Is this to be expected?

Let's find out by looking into which `measurement_mode` did it went with at startup. You could run both at same time to find this out quickly. From there, glance at the code and/or the files to see if the code still hold up.

**Comment by lovetocode999** [comment]
@ultrabug Whoops, sorry! I have been rather busy and forgot about this issue, I sincerely apologize!
I did some investigation a while ago, and it only does this when using the `'sys'` `measurement_mode`. The `'acpi'` `measurement_mode` has no issues. After a quick glance at the code, nothing appears to be wrong with it - it appears to be extracting the percent value from one of the batteries in `/sys/class/power_supply`. I will have to further investigate which subdirectory of `/sys/class/power_supply` py3status is using, as I have 3 - AC, BAT0, and hidpp_battery. Whichever one it is, though, the problem is most likely with my own system, rather than a problem in py3status.

**Comment by ultrabug** [comment]
Thanks for reporting back @lovetocode999 ; no need to apologize this is our free time here <3

Should we close this issue then mate?

**Comment by lovetocode999** [comment]
> Thanks for reporting back @lovetocode999 ; no need to apologize this is our free time here <3

Thanks!

> Should we close this issue then mate?

Yes, we should.
