### ISSUE TITLE
on click support cycle the output of external script?

### ISSUE THREAD

**Issue by azzamsa** [ultrabug/py3status#1956]
Hi, how to add `on click` functionality on external script?

Let say, I want it to run `echo "foo"` then on click it will run `echo "bar"`. if I click it again, it will cycle.

```
external_script {
    format = "{output}"
    script_path = "echo 'foo'"
    on_click 1= "ehco 'bar'"
}
```
this doesn't work, it just print "foo" and I can't click it. do we have something like ?

```
external_script {
    format = "{output}"
    script_path = ["echo 'foo'", "echo 'bar'"]
    on_click 1= "ehco 'bar'"
}
```

i3status-rs has this functionality with the config below:

```
[[block]]
block = "custom"
cycle = ["echo 'foo'", "echo 'bar'"]
on_click = "<command>"
```

Thanks for Py3status.

**Comment by ultrabug** [comment]
Hi @azzamsa 

Indeed this feature looks to be an implementation specific to i3status-rs which we do not have in py3status I'm afraid

I think you can achieve what you're looking for by using a group with two external_script instances, the click would cycle the group for you

something like:

```
group echos {
    button_next = 1

    external_script {
        format = "{output}"
        script_path = "echo 'foo'"
    }
    external_script {
        format = "{output}"
        script_path = "echo 'foo'"
    }

}
```

**Comment by azzamsa** [comment]
Wow!. I don't believe it's doable. I never know such `group` keyword.

I am searching thought issue and docs, but I don't find anything regarding this other than external_script doc.

I also doesn't find the answer in [this issue](https://github.com/ultrabug/py3status/issues/1372). SO I thought it's not doable at the time. 

Thanks a lot

--- 

Added [py3status example](https://sr.ht/~azzamsa/Bilal/#usage-with-other-tools), thanks a lot.

**Comment by ultrabug** [comment]
Glad to help @azzamsa ;)
