### ISSUE TITLE
weather via wttr.in

### ISSUE THREAD

**Issue by CorruptCommit** [ultrabug/py3status#1959]
I recently configured py3status to get the current weather via [chubin/wttr.in][0] with something like the following:

```
getjson wttr {
    url = "https://wttr.in/Paris?format=j1"
    format = "{current_condition-0-FeelsLikeC}° {current_condition-0-weatherDesc-0-value}"
    cache_timeout = 3600
}
```
result:  `6° Partly cloudy`

Note, wttr.in has a lower barrier of entry than the [weather_owm][1] module as an API key is not required. 

I am curious if this example should get added to the [getjson][2] documentation or if it makes more sense to build out a module.  

[0]: https://github.com/chubin/wttr.in
[1]: https://py3status.readthedocs.io/en/latest/modules.html#weather-owm
[2]: https://py3status.readthedocs.io/en/latest/modules.html#getjson

**Comment by ultrabug** [comment]
Hey @CorruptCommit thanks for sharing this!

I guess an example would be smart + maybe a mention of this on the weather_owm module itself too?

**Comment by CorruptCommit** [comment]
While I think those ideas would work just fine, I do have another idea.  

What about having an issue (or maybe use the Wiki) as a place for community json configurations?  This might encourage people to share and inspire others to make proper module.  Although, this might be overkill.

**Comment by ultrabug** [comment]
I actually like the idea @CorruptCommit and I'd rather have it as a section in the official documentation that is accessible on readthedocs

Something like: "user contributed configuration examples"?

**Comment by CorruptCommit** [comment]
Glad to hear you like the idea.  

When I pitched the idea of having this outside of the official documentation, I was thinking about barrier to entry for users, time and effort of approving Pull requests, and clear separation about what is 'officially' supported.  That being said, I can see the benefits of including it within the official documentation. My concerns might not be that big of deal and/or could be addressed in other ways.  I don't feel too strongly either way, do what you think is best for your project.

> Something like: "user contributed configuration examples"?

Sounds good to me.

**Comment by ultrabug** [comment]
Here we go @CorruptCommit thanks : https://github.com/ultrabug/py3status/commit/62923650993b4c35288ac79c8911784445e2be1f

It should appear on readthedocs soon

I've been a good citizen and shared some of my magic config :p
