### ISSUE TITLE
Setup error (FileNotFoundError) parse_config.py line 722

### ISSUE THREAD

**Issue by Bouni** [ultrabug/py3status#1961]
Hi,

I switched to NixOS and strugeled to get py3status running.
But I got the error `Setup error (FileNotFoundError) parse_config.py line 722`

After some debugging I realized that you call the `file` utility [here](https://github.com/ultrabug/py3status/blob/master/py3status/parse_config.py#L709)

Unfortunately it is not installed on NixOS by default and the error message Is not clearly indicating the missing dependency.

**Comment by ultrabug** [comment]
Thanks for reporting this @Bouni !

As a NixOS user, what would you think should happen?

1. crash and report missing `file` utility
2. do not crash, assume utf-8 instead (as for BSD)

**Comment by Bouni** [comment]
I've used NixOS for 2 days now, so my experiance ist very limited.
In my opinion, a meaningful error message that clearly says that `file` is missing would be great.
Somehow you should make clear that the file utility is meant, not a file like a config file or something like this.
Thats what I searched for in the first place 😁

**Comment by ultrabug** [comment]
@Bouni I see and I'll make that happen

But TBH this is a packaging issue too and it would be cool to ping the NixOS maintainer about this right?

**Comment by ultrabug** [comment]
I've added a notification on missing 'file' command and allowed py3status to keep on running since this is not vital (used for config file encoding detection)
