### ISSUE TITLE
Doesn't seem to switch time automatically (clock widget)

### ISSUE THREAD

**Issue by sTiKyt** [ultrabug/py3status#1962]
I have this setting:
![image](https://user-images.githubusercontent.com/35602029/97241246-6f2cf180-17e8-11eb-8cdf-bd46c39f5a76.png)

Ukraine changes it's time twice a year. Yesterday time was changed 1 hour back, but it didn't change automatically on my system. (Like it does, for example, on my phone or on KDE Plasma)

**Comment by sTiKyt** [comment]
It doesn't appear to be fixed on my system after update. Am i supposed to delete some files or something? Something i have to change permissions for? System is Arch Linux, in case it matters.

**Comment by ultrabug** [comment]
hi @sTiKyt ; how do you test it exactly on your side?

**Comment by sTiKyt** [comment]
Well, i just updated package and was hoping magic will happen xD

**Comment by ultrabug** [comment]
ahah @sTiKyt then I guess you reloaded i3wm and nothing happens?

If that's the case there must be something else going on wrong in your setup or in the way the module interprets it

I was targeting time skews due to timezone daylight saving but if you still experience a difference between your current time and the module's then something else is at play I guess

Can you confirm and share:
- run `date` from a shell
- run  `date +%Z` from a shell
- run `cat /etc/localtime` from a shell
- screenshot the module's output at the same time

Cheers

**Comment by sTiKyt** [comment]
![image](https://user-images.githubusercontent.com/35602029/99807737-d748cc00-2b37-11eb-9a8d-eef4237b440d.png)

Module output:
![image](https://user-images.githubusercontent.com/35602029/99807765-dfa10700-2b37-11eb-99a5-a06280e502e4.png)

Module settings:
![image](https://user-images.githubusercontent.com/35602029/99807835-f34c6d80-2b37-11eb-8b20-2dc22277bc77.png)

**Comment by eumiro** [comment]
This is a problem of how the country's time zone is retrieved and the coincidence in the tz database.

Code: https://github.com/ultrabug/py3status/blob/master/py3status/modules/clock.py#L200-L208

If the country has more than a single time zone, *the first one* is chosen here.

And look at the case of Ukraine:

```
import datetime, pytz
before = datetime.datetime(2020, 10, 25, 0, 0)
after = datetime.datetime(2020, 10, 25, 5, 0)
for name in pytz.country_timezones('ua'):
    tz = pytz.timezone(name)
    print(name, tz.localize(before).utcoffset(), tz.localize(after).utcoffset())
```

returns

```
Europe/Simferopol 3:00:00 3:00:00
Europe/Kiev 3:00:00 2:00:00
Europe/Uzhgorod 3:00:00 2:00:00
Europe/Zaporozhye 3:00:00 2:00:00
```

So in this case @sTiKyt gets the time zone of `Europe/Simferopol` that does not use DST.

That piece of code is marked as broken and it is broken. I'd forbid the usage of country codes and let the user choose a real time zone, such as `Europe/Kiev`.

**Comment by eumiro** [comment]
> Thanks @sTiKyt indeed looking at the code, the timezone was read only once on start
> 
> I've changed it so we pick it every time we render the time
> 
> It's not super optimal but it should fix the problem

You don't have to reload the time zone each time. Maybe only if the tz database (and the `pytz` lib)  is updated a few times a year and accidentally a change concerns exactly the time zone of the user, which is not very probable. Converting a datetime object to string every second/minute/whatever does the correct job during DST switches.

**Comment by ultrabug** [comment]
Impressive TZ debug (one of the most complex in IT!) thanks!
