### ISSUE TITLE
volume_status hide status when device is disconnected

### ISSUE THREAD

**Issue by hasmaneuroda** [ultrabug/py3status#1964]
I use a bluetooth headset and want its volume not to be shown in the statusbar when the headset is disconnected.
Is there any chance to get something like a 
format_down = ' ' 
option like in the wifi/ethernet modules?

**Comment by ultrabug** [comment]
why do you need a regex at all exactly?

**Comment by hasmaneuroda** [comment]
To cover different headsets. If I use headset A and later on headset B C or D.
If I do not define a device, I can see the volume in the statusbar and am able to change its value by using the mousewheel. But it has no effect volumewise.

**Comment by ultrabug** [comment]
I guess ` device = "bluez_sink..+.a2dp_sink"` should work then :)

**Comment by hasmaneuroda** [comment]
Thank you so much! You helped me big time. :)

**Comment by ultrabug** [comment]
Happy usage @hasmaneuroda :)
