### ISSUE TITLE
How to stop closed group from refreshing?

### ISSUE THREAD

**Issue by eugenenelou** [ultrabug/py3status#1971]
Hello,

I'm trying to customize the group module so that it only fetches data when it's open. 
It would be useful when the module makes some API calls and I don't want them made when I don't use them.

I'm not understanding how I can do that. I tried overriding the `_get_output` method of the group module but the submodules are still updated.

**Comment by ultrabug** [comment]
Hello Eugène

I haven't looked back at the code but I guess something like `disable_module`/`wake` on the given modules should do?

**Comment by eugenenelou** [comment]
Sleeping does not seem to do anything.
And `disable_module` is raising many errors: the group module is still being run it seems and its items are empty. Where can I find the traceback of the errors?

**Comment by ultrabug** [comment]
Run py3status with the -d flag and check your user logs
