### ISSUE TITLE
Allow for the '%+' format string to update by seconds on BSD.

### ISSUE THREAD

**Issue by Parakleta** [ultrabug/py3status#1973]
The '%+' format works similarly to '%c' on BSD, but gives the format I prefer.

https://github.com/ultrabug/py3status/blob/d540d9276f4d730227cb352dbb447775de6dca21/py3status/i3status.py#L115

**Comment by ultrabug** [comment]
Hi @Parakleta

Would you be okay to propose a PR for this maybe?

**Comment by Parakleta** [comment]
Done, in PR #1975

**Comment by ultrabug** [comment]
Cheers mate
