### ISSUE TITLE
tztime not working with pango markup

### ISSUE THREAD

**Issue by infabo** [ultrabug/py3status#1976]
I replaced i3status with py3status today.

Working except for **tztime** with pango markup. All other modules work as expected fine and output pango.

```
general {
        colors = false
        interval = 5
        output_format = "i3bar"
        markup = pango
        color_good = '#2f343f'
        color_degraded = '#ebcb8b'
        color_bad = '#ba5e57'
}
```

i3status configuration block:

```
tztime local {
	format = "<span background='#81a1c1'> %time </span>"
	format_time = " %a %-d %b %H:%M"
}
```

Even a minimal format_time just outputs the `<span>` raw.

```
tztime local {
	format = "<span background='#81a1c1'> %time </span>"
	format_time = "%H:%M"
}
```

How it looks with **i3status** in original:

![image](https://user-images.githubusercontent.com/3999104/100348485-436b7a00-2fe7-11eb-97e8-4e49bb262687.png)

How it looks with **py3status** now (sry for the dark font):

![image](https://user-images.githubusercontent.com/3999104/100348540-567e4a00-2fe7-11eb-8996-116a3b3ba337.png)

# Version

`py3status version 3.30 (python 3.8.6) on i3`

**Comment by ultrabug** [comment]
Thanks for reporting @infabo ; I believe this is fixed now

**Comment by infabo** [comment]
Yes, can confirm it's fixed now. Thank you!
