### ISSUE TITLE
keyboard_layouts Greek with polytonic variant set causes on_click error

### ISSUE THREAD

**Issue by Madcliff** [ultrabug/py3status#1987]
After setting via setxkbmap greek to polytonic, when I define 'gr' in layouts trying to switch to the layout causes it to return a layout error. 

I am not sure if I am doing the configuration wrong?

**Comment by lasers** [comment]
What's the commands to debug this? Can you try `xkb_input module` too?

**Comment by ultrabug** [comment]
Closing as opener did not answer yet, if you do mate, plz reopen

**Comment by lasers** [comment]
Something like `setxkbmap 'gr' -variant 'polytonic'`. I hadn't used i3 in a while.

**Comment by lasers** [comment]
(FYI) I can't reproduce this.
