### ISSUE TITLE
order of variant in keyboard_layout module

### ISSUE THREAD

**Issue by makrobios** [ultrabug/py3status#1988]
Hi, it is a minor Issue I have with the keyboard_layout module. I use `de` layout and `de neo`. I can switch between those but whenever I log in `de` is displayed in the status bar although `de neo` is active. After clicking once it is in sync again and showing the layout correctly.
I tried to change the order in `.i3status.conf` but i can't make it to work. BTW, is it possible to uppercase the format?

```
keyboard_layout {
	layouts = ["de neo", "de"]
	format = "[{variant} |{layout}] "
	color_de = "#729FCF"
	color_de_neo = "#FC5B4F"
	button_next = 1
	min_width = 60
	}
```
and here the output of setxkbmap -query:

```
rules:      evdev
model:      pc105
layout:     de
variant:    neo
```

**Comment by lasers** [comment]
Thanks for the debug config. Can you try `xkb_input` module too?

**Comment by makrobios** [comment]
Sure i'd like to try, i just don't know how to use the module. I am on Ubuntu and have no xkb-switch or xkblayout-state installed and i am not using sway. Can I still use it?

**Comment by lasers** [comment]
You can if you compile `xkblayout-state`. https://askubuntu.com/questions/826577/switch-keyboard-layouts-with-i3

**Comment by makrobios** [comment]
Thank you, that worked fine! Just after login it displays "us" although i have two "de" layouts but after some seconds it switches to the correct one. Here is what i have in my config now.
```
xkb_input{
	switcher = "xkblayout-state"
	format_input = "[{v}|{s}]"
	button_next = 1
}
```

**Comment by lasers** [comment]
Just FYI: You technically don't need `switcher` because `xkb_input` will check for available binaries on startup if left unset.

`xkblayout-state` printed `us`. There are nothing in the `xkb_input` that caused this. Find a way to set your layout earlier or just let it slide?

**Comment by makrobios** [comment]
Thanks again, I can close the issue.
