### ISSUE TITLE
Doc: move from reStructuredText to Markdown

### ISSUE THREAD

**Issue by Horgix** [ultrabug/py3status#199]
Hi,

This issue follows the discussion on the PR #196 about how horrible is reStructuredText syntax.

So, I took a bit of time to look at it. I found [the issue about this fight](https://bitbucket.org/pypa/pypi/issues/148/support-markdown-for-readmes) and there may be some hope !

- Pypi parses the [`long_description` from the `setup.py`](https://github.com/ultrabug/py3status/blob/master/setup.py#L22) to get the content of what will be displayed on the site (back to middle ages, yeah !)
- Currently, we have this set to `read('README.rst')`

So I think it's possible to move to markdown with 2 solutions :

1. As suggested by [the last post of the issue](https://bitbucket.org/pypa/pypi/issues/148/support-markdown-for-readmes#comment-23875412), we can use `pypandoc` in the `setup.py` and assign `pypandoc.convert('README.md', 'rst')` to `long_description`
2. We can have a `README.md` officially maintained, keep the `read('README.rst')` in the `setup.py`, and before each release we convert the `README.md` to a `README.rst` with whatever tool converts markdown to reStructuredText (all hail pandoc !)

I think that the second solution would be cleaner and would stay in the "no additionnal dependency" philisophy of py3status. Plus, there is something else I would like to point : I was thinking about working on a man page... and I don't know if you have ever seen the man syntax but it's absolutely horrible. But here again pandoc might be our saviour : it also know how to convert to man :) (but of course it's not the only tool which can do that).

What do you think of this ?

**Comment by Horgix** [comment]
Ping @ultrabug and @pydsigner btw

**Comment by ultrabug** [comment]
Thanks @Horgix, but I really think this is not worth the (continuous) effort and complexity.

**Comment by pydsigner** [comment]
@Horgix I've been thinking about this issue as well. I'm mostly with @ultrabug on this, although I really want to see a markdown readme as soon as PyPI is obliging. I will note that I am automatically pinged on all py3status issues and PRs, and I'm sure @ultrabug is as well, so the explicit callout isn't needed.
