### ISSUE TITLE
Extra space character in mpd_status

### ISSUE THREAD

**Issue by nsirolli** [ultrabug/py3status#1990]
The output from mpd_status is (using underscores to indicate whitespaces)

`[play]__-_MyRadio`

Shouldn't it be

`[play]_-_MyRadio`

?

The same with the pause/stop status.

I'm using py3status 3.31-2.

**Comment by lasers** [comment]
Maybe the default `format` need to be fixed to deal with empty `{artist}` placeholder too.

Untested.
```python
order += "mpd_status"
mpd_status {
    format = "{state} [{artist}[\?soft  - ]{title}|{file}]"
}
```
If that doesn't do what you want, then you'll have to play with it until you get it. I'm not using i3 right now.

**Comment by nsirolli** [comment]
That worked! Thanks. A slightly simpler fix:

`
        format = '{state} [[[{artist} ]- {title}]|[{file}]]'
`

**Comment by ultrabug** [comment]
@nsirolli would you like to propose this as a PR maybe?

**Comment by nsirolli** [comment]
Sure, I'll do it.
