### ISSUE TITLE
"colors" directive ignored

### ISSUE THREAD

**Issue by infabo** [ultrabug/py3status#1999]
There is a directive in i3status called `colors`. It enables one to disable colors by setting `colors = false`.

see https://i3wm.org/docs/i3status.html

![image](https://user-images.githubusercontent.com/3999104/104710319-3aae3f00-5720-11eb-8890-63a388bb8bcd.png)

py3status does not honor this setting.

**Comment by ultrabug** [comment]
Thanks a lot for spotting this @infabo :) looks like after all these years nobody actually noticed :D
