### ISSUE TITLE
`window` does not work under sway

### ISSUE THREAD

**Issue by ssiyad** [ultrabug/py3status#2000]
#### Problem:
- Module named `window` does not work under sway (wayland), however it does work okay under Xwayland
#### Reason:
- Most probably because sway does not provide `window_properties` for wayland applications
#### Suggestion:
- Change `window_properties.title` to `name`

edit:
sway version 1.5-5f1fe33d (Dec 24 2020, branch 'master')
py3status version 3.31 (python 3.9.1) on i3

**Comment by ssiyad** [comment]
Update: Works after installing `python-i3ipc`, so it's not optional as stated in docs?

**Comment by lasers** [comment]
`python-i3ipc` is optional. Me think default format should be `{name}` instead of `{title}`.

**Comment by lasers** [comment]
If you want to test this or come up with a different fix, I can't test sway. The multi-line diff fixes a slightly different `hide_title` behavior on empty workspace. At first, I wanted to add more placeholders like `{name}`, `{output}`, `{current_border_width}`, `{id}`, `{percent}`, etc..., but now I meh'd. 


```diff
diff --git a/py3status/modules/window.py b/py3status/modules/window.py
index 87c77c3..5cafed0 100644
--- a/py3status/modules/window.py
+++ b/py3status/modules/window.py
@@ -131,7 +131,7 @@ class Msg(Ipc):
         tree = self.json_loads(self.parent.py3.command_output(self.tree_command))
         focused = self.find_needle(tree)
         window_properties = focused.get(
-            "window_properties", {"title": None, "class": None, "instance": None}
+            "window_properties", {"title": focused["name"], "class": None, "instance": None}
         )
 
         # hide title on containers with window title
@@ -145,7 +145,11 @@ class Msg(Ipc):
                     and len(parent["nodes"]) > 1
                 )
             ):
-                window_properties["title"] = None
+                if "window_properties" in focused:
+                    window_properties["title"] = None
+                else:
+                    window_properties["title"] = focused["name"]
+
         window_properties = self.compatibility(window_properties)
         return window_properties
 
```

**Comment by ultrabug** [comment]
Thanks for reporting @ssiyad ; I've changed optional to required!
