### ISSUE TITLE
volume_status module spams journal

### ISSUE THREAD

**Issue by Sviests** [ultrabug/py3status#2002]
I`ve noticed that my journal is being spammed by module volume_status listing its available devices. I found this line which seems to be the one with the issue. Is it really necessary to log available devices this often?

https://github.com/ultrabug/py3status/blob/748752386188ada09ff4b59dce5b63ffccaac878/py3status/modules/volume_status.py#L266

![image](https://user-images.githubusercontent.com/8798050/105684180-4dcdc580-5efd-11eb-91d5-7654cef3211f.png)

**Comment by ultrabug** [comment]
Hi @Sviests indeed I had multiple reports about this: some like it because they tend to change devices quite often, some don't... I guess I'll just drop it since the "don't" users are a majority :)

**Comment by Sviests** [comment]
Thanks for the quick reply @ultrabug ! Maybe there is a possibility to add a parameter in config which would enable verbose logging for users that might need it?

**Comment by anarcat** [comment]
for people having this issue in Debian 11 bullseye (current stable), a good workaround is simply to upgrade to the testing package, if you have bookworm sources:

    apt install py3status/bookworm

that gives you *almost* the latest (3.44).
