### ISSUE TITLE
'window' module nonfunctional if a window title contains an ampersand (&) symbol

### ISSUE THREAD

**Issue by richardso21** [ultrabug/py3status#2008]
### Problem:
- If the title name has an ampersand symbol (&), the `window` module does not show the title entirely
  - This happens regardless of the length of the title
- The issue may be prevalent with other ambiguous/uncommon symbols

### Expected Behavior:
- The window title is shown as is with the '&' sign

### Environment:
- i3-gaps version 4.19.1 (2021-02-01)
- py3status version 3.33 (python 3.9.1) on i3

It's probably an uncommon case, but nonetheless, it exists. Not sure if this is an issue with i3, i3ipc, or the module. If it's the module, it might have something to do with how the string is parsed. I'd really appreciate it if it can be fixed!

**Comment by richardso21** [comment]
**UPDATE**: Aha! Having `markup = 'pango'` on the config file prevents the ampersand '&' from showing anywhere on the status bar. 

Py3status is awesome, by the way!

**Comment by ultrabug** [comment]
Thanks for your kind words @richardso21 

> This can be fixed on the actual module with a small code segment that replaces every instance of & with &amp; before the title string is returned.

Question is: does it behave the same on i3status? I'd guess so since py3status is not interfering with bar rendering

**Comment by richardso21** [comment]
Yes, only if the markup parameter is set to 'pango.' It's no longer an issue with py3status.

**Comment by ultrabug** [comment]
Thanks for your confirmation

**Comment by lasers** [comment]
@richardso21 Which modules do you use pango markup format in? If there are none, then you don't need to set a markup config anywhere.

@ultrabug Same reason with https://github.com/ultrabug/py3status/issues/1719. Users shouldn't set pango markup globally because it breaks interactive modules like `group`, `frame`, etc but can be okay for readonly modules like `window`, `sysdata`, `loadavg`, etc.
