### ISSUE TITLE
Making modules/README.md more friendly

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#201]
the current README.md https://github.com/ultrabug/py3status/tree/master/py3status/modules is hard to navigate and read.

I've had a go at making it more readable see  https://github.com/tobes/py3status/tree/modules_readme/py3status/modules#top

It's a work in progress I've done what I can using my vim skills without having to do much manual intervention.  If you are interested I'll manually fix it up.

I'm quite happy to change how things like defaults are shown etc

general layout

### module

description

Configuration parameters:
- `param` Param description *(default value)*

Format status string parameters:
- `{item}` Description

requires:
- `{requirement}` extra info

**author** Author  **license** License

**Comment by pydsigner** [comment]
I like it, other than the `^top` links. I'd rather just hit Back in my web browser.

**Comment by tobes** [comment]
closing this as there is now a pull request for this feature
