### ISSUE TITLE
What's the default for format_device in networkmanager plugin?

### ISSUE THREAD

**Issue by JulienPalard** [ultrabug/py3status#2016]
It is documented as:

```
format_device format for devices (default “[\?if=general_connection {general_device}[\?soft ]” “[\?color=ap_signal {ap_ssid} {ap_bars} {ap_signal}%][\?soft ]” “[\?color=good {ip4_address1}]]”)
```

which looks wrong: strange placement of quotes, strage quote symbol used.

In the code it is documented in the module docstring as:

```
    format_device: format for devices
        *(default "[\?if=general_connection {general_device}[\?soft  ]"
        "[\?color=ap_signal {ap_ssid} {ap_bars} {ap_signal}%][\?soft  ]"
        "[\?color=good {ip4_address1}]]")*
```

which looks strange to me too.

**Comment by ultrabug** [comment]
Hello @JulienPalard 

In the code it is declared like this:

```python
    format_device = (
        r"[\?if=general_connection {general_device}[\?soft  ]"
        r"[\?color=ap_signal {ap_ssid} {ap_bars} {ap_signal}%][\?soft  ]"
        r"[\?color=good {ip4_address1}]]"
    )
```

The module works and the output is looking good to me so even if I must admit that I'm not an expert in this kind of formatting (which I personally don't like very much) it has been proven useful to users so far.

Still, I'm having trouble understanding what you expect or what is causing a problem for you please?

**Comment by JulienPalard** [comment]
I'm trying to personalize it, so in my `~/.config/i3status/config` I'm first trying to set the default explicitly as a first step, like:

```
networkmanager {
    format_device = "[\?if=general_connection {general_device}[\?soft  ][\?color=ap_signal {ap_ssid} {ap_bars} {ap_signal}%][\?soft  ][\?color=good {ip4_address1}]]"
}
```

and when I tried, it did not worked, got a parsing error. But now it works, so I did it wrong in a way or another this morning.

So I think the docstring and the doc should be updated to tell it's:

```
format_device = "[\?if=general_connection {general_device}[\?soft  ][\?color=ap_signal {ap_ssid} {ap_bars} {ap_signal}%][\?soft  ][\?color=good {ip4_address1}]]"
```
not:
```
                "[\?if=general_connection {general_device}[\?soft ]” “[\?color=ap_signal {ap_ssid} {ap_bars} {ap_signal}%][\?soft ]” “[\?color=good {ip4_address1}]]"
```

**Comment by ultrabug** [comment]
I understand Julien but I think it has been split into multiple strings because of QA and code linters checks

Since it's a line in a large docstring I don't know if we can/want to split the docstring or just accept this as-is since I can't add a noqa to that specific line AFAIK

**Comment by ultrabug** [comment]
I just tested and it turns out it does not break QA... so let's make it less confusing!

Merci Julien :+1:

**Comment by lasers** [comment]
(FYI) You can break up a long line in your config too using `+=`. 
```python
networkmanager {
    format_device = "[\?if=general_connection {general_device}[\?soft  ]"
    format_device += "[\?color=ap_signal {ap_ssid} {ap_bars} {ap_signal}%]"
    format_device += "[\?soft  ][\?color=good {ip4_address1}]]"
}
```
