### ISSUE TITLE
screenshot module doesn't overwrite format

### ISSUE THREAD

**Issue by djangoliv** [ultrabug/py3status#2017]
This configuration works well but the format is not taken into account 

```
screenshot {
    format = "my String"
    screenshot_command = "maim"
}
```

Regards

**Comment by ultrabug** [comment]
Hello @djangoliv 

```
order += "screenshot"

screenshot {
    format = "toto"
}
```

It does work for me, could you tell us which version of py3status you run? `py3status -v`

Thanks

**Comment by djangoliv** [comment]
@ultrabug 
Here the version:

$ py3status -v
py3status version 3.14 (python 3.7.3)

Thanks

**Comment by lasers** [comment]
`py3status v3.14` came out in Nov 2018. There is no `format` config for module screenshot at that time.

Feb 2019 added it - #1714.

**Comment by ultrabug** [comment]
Please upgrade @djangoliv and enjoy :) closing
