### ISSUE TITLE
(Mostly Cosmetic):  Clock is 30 seconds off

### ISSUE THREAD

**Issue by mlmatlock** [ultrabug/py3status#2025]
I synchronize my time with the WWV time servers at [https://tf.nist.gov/tf-cgi/servers.cgi](url).

Both my HW clock and a time display from conky are in-sync to the second with the radio station time signals, both broadcast, *and* the telephone service.

py3status module 'clock' lags by 30 seconds, even with 

`
Interval = 1
`

in the config section.

Not any kind of earth-shaking deal breaker, just interesting behavior.

**Comment by ultrabug** [comment]
Hi @mlmatlock 

Just to be on the same page, can you share your clock module configuration and your py3status version please?

Cheers

**Comment by mlmatlock** [comment]
@ultrabug, here you go:

i3-gaps 4.19.1 on Arch Linux.
```
py3status -v
py3status version 3.34 (python 3.9.2) on i3
```
```
clock {
        interval = 1
        color = '#8C9440'
        format = "{Local}"
        format_time = " %d %b %y / %H:%M "
}
```

The capitalization of `interval` doesn't make a difference (for me, anyway).

A few screenshots:

![2021-03-10-171100_1920x1080_scrot](https://user-images.githubusercontent.com/42914546/110705053-d3fb4e00-81c3-11eb-9ad1-9137f90f17a8.png)
![2021-03-10-171125_1920x1080_scrot](https://user-images.githubusercontent.com/42914546/110705054-d3fb4e00-81c3-11eb-84e1-16c71fd51d43.png)
![2021-03-10-171130_1920x1080_scrot](https://user-images.githubusercontent.com/42914546/110705056-d493e480-81c3-11eb-8a68-d40af39c7241.png)

**Comment by ultrabug** [comment]
@mlmatlock I think I get it, you're not using any seconds resolution in your module and there is no `interval` configuration parameter for the clock module

if you were to use

```
        format_time = " %d %b %y / %H:%M:%S "
```

you would see that the clock module is effectively in sync

why? because the clock module tries to be smart about its refresh rate as you can see here : https://github.com/ultrabug/py3status/blob/master/py3status/modules/clock.py#L145

it also does not honor any cache_timeout since it bases itself on its own refresh rate detection...

does it make sense?

**Comment by mlmatlock** [comment]
> @mlmatlock I think I get it, you're not using any seconds resolution in your module and there is no `interval` configuration parameter for the clock module
> 
> if you were to use
> 
> ```
>         format_time = " %d %b %y / %H:%M:%S "
> ```
> 
> you would see that the clock module is effectively in sync
> 

Yeah, when I added the seconds, it was good.

> it also does not honor any cache_timeout since it bases itself on its own refresh rate detection...
> 
> does it make sense?

It does, thanks for the explanation!

As an aside, I probably would've never even noticed it if I wasn't in the middle of migrating to sway/wayland.  Conky doesn't play nice with wayland, and stays on top of everything.

Thanks, @ultrabug!

**Comment by ya-isakov** [comment]
@mlmatlock, do you use py3status-3.32 or newer? I think I found a cause of this issue, I created a separate ticket for it.
