### ISSUE TITLE
development setup raises Invalid syntax error

### ISSUE THREAD

**Issue by b10n1k** [ultrabug/py3status#2027]
**Describe the bug**
Running `sudo python setup.py develop` returns the following error 
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import fastentrypoints  # noqa f401
  File "/home/iob/Documents/Hacker/Code/github/py3status/fastentrypoints.py", line 77
    yield from args
             ^
SyntaxError: invalid syntax
```
**Your py3status version**
py3status version 3.28 (python 3.8.8) on i3

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Clone repos and cd into it
2. Run `sudo python setup.py develop`

**Expected behavior**
Install dev enviroment

**Additional context**
OS: Tumbleweed 20210307

**Comment by lasers** [comment]
Does `python --version` print `3.8.8` or `2.7`? You might want `python3`.

**Comment by b10n1k** [comment]
you are right. for some reason i was sure that i was with python3 but i wasnt.
