### ISSUE TITLE
py3.time_in is off by ~20 seconds if sync_to=60 (regression)

### ISSUE THREAD

**Issue by ya-isakov** [ultrabug/py3status#2028]
**Describe the bug**
I found that after commit e431f5ec300def69f3015d3b2928894d3ed6bfac, clock widget is off by e.g. 20 seconds, if I'm using only hours an minutes.

**Your py3status version**
py3status version 3.33 (python 3.8.7) on sway

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Add module 'clock'
2. Configure module like this 'clock {
   format = ["{Local}", "{America/Los_Angeles}"]
   format_time = "%Y-%m-%d %H:%M %a"
}'
3. Run py3status
4. See that minutes are changed e.g. 20 seconds later.

**Expected behavior**
Minutes should change synchronously to real clock.

**Screenshots**
N/A

**Additional context**
I've tried to reproduce this issue in python cli:
```
>>> datetime.now(); requested = time.perf_counter()
datetime.datetime(2021, 3, 16, 23, 30, 19, 244439)
>>> r1 = (requested + 60) - (requested % 60)
>>> r1 - requested
1.356851185002597
```
This means, that time_in will wait for 1 second, if its ..:19.
`next_run_in = r1 - requested` could be simplified to `next_run_in = 60 - time.perf_counter % 60`. As perf counter could start at any wall clock second, this will cause a delay.

Here is another example:
```
>>> datetime.now(); requested = time.perf_counter()
datetime.datetime(2021, 3, 16, 23, 32, 41, 105984)
>>> r1 = (requested + 60) - (requested % 60)
>>> r1 - requested
39.49525859300047
```
it will wait until 41+39 = ...:20 again.

In py3status before this commit (when time.time() was used), it worked perfectly:
```
>>> datetime.now(); requested = time.time()
datetime.datetime(2021, 3, 16, 23, 34, 41, 519036)
>>> r1 = (requested + 60) - (requested % 60)
>>> r1 - requested
18.480836868286133
```
My guess is that the shift is the same, when perf counter was started. So, in my case, perf counter should be started at ...:20

P.S. I saw similar issue https://github.com/ultrabug/py3status/issues/2025, but it was closed as cosmetic, and I think this is worthy to be raised again.

P.P.S. 1-second interval should be broken as well, but it's much harder to see the delay in this case.

P.P.P.S perf counter should never be used for wall-clock-like things, it's only purpose - to measure some intervals of time on the same machine, e.g `t = time.perf_counter(); some_work; time_diff = time.perf_counter() - t`

**Comment by mlmatlock** [comment]
Nice investigating, @ya-isakov!

Info:  py3status 3.34/python 3.9.2 on sway/Arch.

**Comment by ya-isakov** [comment]
@ultrabug BTW, I think that offset parameter is not quite working, as without sync_to it will be
return (time.perf_counter() + seconds - offset) + offset, so, essentially, offset is just ignored.

**Comment by ya-isakov** [comment]
After some digging, it seems that we have two problems here:
1) if seconds are specified in time_in, and time.time() is used, it could happen that e.g. leap second will increase next caching period. Also, some manual changes to current time by e.g. administrator will also affect this.
2) if sync_to is specified, and time.perf_counter is used, it will result in the problem described in this bug.

So, as sync_to is not working properly, and it's used only in clock, i3block, i3pystatus, i3status, maybe it would be better to drop sync_to, and set seconds=1 for these modules? At least the maximum error would be up to second, and not up to minute.

**Comment by ultrabug** [comment]
Thanks for your investigation @ya-isakov

For the record this whole module updating logic I want to trash because it's been too complex and confusing over the time

When @eumiro proposed this change, I hoped for a way to start cleaning that up but my misunderstanding of perf_counter() obviously allowed introducing this kind of problem...

@eumiro what's your opinion plz?
@ya-isakov what's your recommendation here? revert the whole commit on all files?

**Comment by eumiro** [comment]
Sorry for taking more time to respond and to @ya-isakov for reporting the bug. The `perf_counter` has, of course, nothing to do with the hours/minutes/seconds on the wall clock, and therefore should not be actually used in the `clock` module. In this case, if the system clock gets updated (e.g. using NTP), then it should also get updated, because it should show the current time and not the difference between some past event and now.

**Comment by ya-isakov** [comment]
@eumiro Yes, exactly, it's probably a issue for clock, and maybe i3status or i3block modules, which also depends on being run on first second of minute, or something like that.

**Comment by ya-isakov** [comment]
@ultrabug I think I'm even fine with dropping sync_to parameter, and updating clock every second - it will be probably not energy-efficient, but at least will be (mostly) precise.

**Comment by ultrabug** [comment]
I guess thanks to you we can close this one too?

**Comment by mlmatlock** [comment]
Great job, y'all!!

**Comment by ya-isakov** [comment]
@ultrabug My changes should fix issue with sync_to, but, I think, that changes from https://github.com/ultrabug/py3status/pull/2031 are still needed, if cycle is used.

**Comment by ultrabug** [comment]
ok @ya-isakov I moved it back to time.time in clock.py

This is now in version 3.36 please reopen if needed and thanks again for your work and help!
