### ISSUE TITLE
Can't decode battery status file on Fedora 33

### ISSUE THREAD

**Issue by iliakur** [ultrabug/py3status#2035]
**Describe the bug**
Battery level/status isn't shown in status bar.

**Your py3status version**
```
py3status version 3.34 (python 3.9.2) on i3
```

**To Reproduce**

Relevant config entry:
```
battery_level {
	format = "{icon} {percent}%"
}
```
Running `py3status --debug` and looking at the logfile I see this error:
```
2021-04-04 11:40:36 WARNING Instance `battery_level`, user method `battery_level` failed.
2021-04-04 11:40:36 INFO Traceback
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 474: invalid start byte
  File "/home/ilja/.local/pipx/venvs/py3status/lib64/python3.9/site-packages/py3status/module.py", line 948, in run
    response = method()
  File "/home/ilja/.local/pipx/venvs/py3status/lib64/python3.9/site-packages/py3status/modules/battery_level.py", line 176, in battery_level
    battery_list = self.get_battery_info()
  File "/home/ilja/.local/pipx/venvs/py3status/lib64/python3.9/site-packages/py3status/modules/battery_level.py", line 304, in _extract_battery_info_from_sys
    r = _parse_battery_info(path)
  File "/home/ilja/.local/pipx/venvs/py3status/lib64/python3.9/site-packages/py3status/modules/battery_level.py", line 288, in _parse_battery_info
    for var in f.read().splitlines():
  File "/usr/lib64/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
```

**Additional context**
Here's the output of `file -bi`:
```sh
$ file -bi /sys/class/power_supply/BAT0/uevent                                                                                    
text/plain; charset=iso-8859-1
```
I tried changing that to `utf-8`, but my linux-fu isn't good enough and that failed for some reason.

For the record, this is Fedora 33. I also have a laptop with Fedora 32 and that works fine.
What also works is if I set `measurement_mode = "acpi"` (I have `acpi` installed for other reasons anyway).

At this point this was just a bit of a pain to debug, I'm filing the issue mostly to give a headsup and double-check that nothing's screwed up on my machine that I should maybe fix.

Thanks for your work on this!

**Comment by ultrabug** [comment]
Thanks for reporting this and letting us know @iliakur . I'm glad this is at least not preventing you from using py3status and this module.

So you say on Fedora 32 the same `/sys/class/power_supply/BAT0/uevent` file is utf-8 right?

Tbh, this encoding support path could lead to complexity which I'm not sure I want us to support everywhere in the code base (we do support it for the py3status config file FYI)

My best man in encoding is @eumiro so I'm allowing myself to friendly ping him in case he has some magic trick about this... :)

**Comment by eumiro** [comment]
I have accidentally access to a Fedora 33 laptop and that one file is 
"text/plain; charset=us-ascii" and looks valid to me, so no idea what 
happens in this case.

Can @iliakur post the exact content of their file? As quoted base64 here 
in the issue for instance.

**Comment by iliakur** [comment]
Sorry about the delay.

Just to be sure I compare the two files again.

**Fedora 33**:
```sh
$ file -bi /sys/class/power_supply/BAT0/uevent                                                                                                                                             
text/plain; charset=iso-8859-1
$ cat /sys/class/power_supply/BAT0/uevent                                                                                                                                                  
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_TYPE=Battery
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-poly
POWER_SUPPLY_CYCLE_COUNT=48
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
POWER_SUPPLY_VOLTAGE_NOW=11327000
POWER_SUPPLY_POWER_NOW=8449000
POWER_SUPPLY_ENERGY_FULL_DESIGN=45000000
POWER_SUPPLY_ENERGY_FULL=45330000
POWER_SUPPLY_ENERGY_NOW=24160000
POWER_SUPPLY_CAPACITY=53
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=LNV-5B10W13894@�
POWER_SUPPLY_MANUFACTURER=LGC
POWER_SUPPLY_SERIAL_NUMBER= 4194
                                                                                                                                                                                              
```

**Fedora 32**:
```sh
$ file -bi /sys/class/power_supply/BAT0/uevent                                                                                                                                             
text/plain; charset=us-ascii
```

**Comment by eumiro** [comment]
Thanks! The first hint I see here is:

```
POWER_SUPPLY_MODEL_NAME=LNV-5B10W13894@�
```

but I am not sure what character(s) were there at the end of line before 
you copied it here. That's why I asked you to base64 it so that we can 
see the original file.

Anyway the rest of the file looks good, so it's really just the encoding 
that has to be detected and set correctly and py3status can use the data.

**Comment by iliakur** [comment]
Ah, sorry, missed that somehow, here's the encoded contents for completeness:

```
UE9XRVJfU1VQUExZX05BTUU9QkFUMApQT1dFUl9TVVBQTFlfVFlQRT1CYXR0ZXJ5ClBPV0VSX1NV
UFBMWV9TVEFUVVM9RGlzY2hhcmdpbmcKUE9XRVJfU1VQUExZX1BSRVNFTlQ9MQpQT1dFUl9TVVBQ
TFlfVEVDSE5PTE9HWT1MaS1wb2x5ClBPV0VSX1NVUFBMWV9DWUNMRV9DT1VOVD00OApQT1dFUl9T
VVBQTFlfVk9MVEFHRV9NSU5fREVTSUdOPTExMTAwMDAwClBPV0VSX1NVUFBMWV9WT0xUQUdFX05P
Vz0xMDk4MDAwMApQT1dFUl9TVVBQTFlfUE9XRVJfTk9XPTg3MTgwMDAKUE9XRVJfU1VQUExZX0VO
RVJHWV9GVUxMX0RFU0lHTj00NTAwMDAwMApQT1dFUl9TVVBQTFlfRU5FUkdZX0ZVTEw9NDUzMzAw
MDAKUE9XRVJfU1VQUExZX0VORVJHWV9OT1c9OTAzMDAwMApQT1dFUl9TVVBQTFlfQ0FQQUNJVFk9
MTkKUE9XRVJfU1VQUExZX0NBUEFDSVRZX0xFVkVMPU5vcm1hbApQT1dFUl9TVVBQTFlfTU9ERUxf
TkFNRT1MTlYtNUIxMFcxMzg5NEDQClBPV0VSX1NVUFBMWV9NQU5VRkFDVFVSRVI9TEdDClBPV0VS
X1NVUFBMWV9TRVJJQUxfTlVNQkVSPSA0MTk0Cg==
```

**Comment by eumiro** [comment]
Thanks. That one character is byte with value 208 (0xD0), which makes the file illegal in UTF-8.

If interpreted as ISO-8859-1, it is the character `Đ` which does not tell me anything in this context. We could check it in any other 8-bit encoding and get different character which very probably wouldn't bring us further.

Other than that, all other bytes in this file and all bytes in the other file are less than 128, which makes them legal and look the same in ASCII, ISO-8859-1, and UTF-8. 

I have no idea on what to expect here in general. We can read these two files as ISO-8859-1 and they'd be both interpreted correctly. But what if there are users out there who have these files as UTF-8? We most probably wouldn't have a problem when interpreting everything as ISO-8859-1 because if there are characters beyond ASCII in UTF-8, they'd look like scrambled eggs when interpreted as ISO-8859-1, but they'd still be contained most probably only within `POWER_SUPPLY_MODEL_NAME` or similar custom strings. All the keys, equal signs, and relevant machine-readable values should be kept below 128.

**Comment by iliakur** [comment]
To me it sounds like this isn't really worth "fixing" in `py3status`... Do you think it's worth it to bring this up somehow upstream? At least one con is that I don't really know what *upstream* is in this context, the folks who write the linux driver for the battery/laptop?

**Comment by eumiro** [comment]
As long as we have not enough information about the general format of the file, I wouldn't change it here.

**Comment by ultrabug** [comment]
> the folks who write the linux driver for the battery/laptop?

maybe... or maybe ask the Fedora people for their opinion?

Closing as I agree that we should not modify it here; thanks @iliakur and @eumiro
