### ISSUE TITLE
Expected behavior of default `--log-file` value

### ISSUE THREAD

**Issue by iliakur** [ultrabug/py3status#2036]
**How can we help you today?**

If I run `py3status --debug` but don't specify any logfile, what's the expected behavior? I couldn't find the logs and was only able to read them once I passed the `--log-file=path/to/my/logfile`. 

This came up as I was debugging #2035

**Comment by lasers** [comment]
>couldn't find the logs

Without looking into this, what about `journalctl -r $(which py3status)` ?

**Comment by ultrabug** [comment]
The expected behavior is to be verbose in the logs @iliakur , not to output everything to stdout

**Comment by iliakur** [comment]
Thanks for the explanations. Do you mind if I open a PR with the following changes to the documentation for the options?

```
--debug       Enable debug logging to syslog or log file if `--log-file` is provided.
--log-file       Log to file (syslog if not specified).
```

I think this will make it clearer where to find the logs if `py3status --debug` is invoked. Maybe I can even massage the (`default: None)` message into saying something about syslog :)

**Comment by ultrabug** [comment]
@iliakur by all means please do! Thanks a lot in advance :+1:

**Comment by iliakur** [comment]
Oki, see #2044

**Comment by ultrabug** [comment]
Thank you
