### ISSUE TITLE
Load modules from XDG_CONFIG_HOME by default

### ISSUE THREAD

**Issue by tobanw** [ultrabug/py3status#204]
Currently, `py3status` modules are [loaded by default](https://github.com/ultrabug/py3status/blob/master/py3status/core.py#L51) from `~/.i3/py3status/` only. I suggest adding `~/.config/i3status/py3status/` (and possibly also `~/.config/i3/py3status/`) to the `include_paths` list. I'm currently specifying the path manually with the `-i` flag.

The `i3status.conf` is already [loaded from the XDG config dirs](https://github.com/ultrabug/py3status/blob/master/py3status/core.py#L65), so this improves consistency. Also, using `~/.config/` is common: for example, the [Arch wiki presumes](https://wiki.archlinux.org/index.php/i3#Configuration) it for i3 config files.

P.S. It seems to me that [line 67-68](https://github.com/ultrabug/py3status/blob/master/py3status/core.py#L67) has an error, since [XDG_CONFIG_HOME expands to](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support#User_directories) `~/.config/`. In my case, this variable isn't set, so the `os.environ.get` call returns `home_path`. But if it were set, the resulting path would be `~/.config/.config/i3status/config`.

**Comment by ultrabug** [comment]
I'm not forgetting your issue @tobanw and I think you got a good point.

It's just that for now there are some major PR open that need attention, please bear with me.

**Comment by ultrabug** [comment]
fixed by @tobes on #297 thanks !
