### ISSUE TITLE
lm_sensors doesn't colour k10-temp-pci sensor output properly.

### ISSUE THREAD

**Issue by kozross** [ultrabug/py3status#2045]
**Describe the bug**

I have the following `group` block in my config:

```
group perf_stuff {
  format = "{output}"
  click_mode = "all"
  fixed_width = True
  button_next = 1

  frame {
    format_separator = ' '
    sysdata {
      format = "CPU: [\?color=cpu {cpu_usage}%], RAM: [\?color=mem {mem_used_percent}%],"
    }

    lm_sensors {
      format_chip = 'Temp: {format_sensor},'
      format_sensor = '[\?color=auto.input {input:g}°C]'
      chips = ['k10temp-pci-00c3']
      sensors = ['tdie']
      thresholds = {'auto.input': [(0, 'good'), (82, 'bad')]}
    }
    
    lm_sensors {
      format_chip = 'GPU Temp: {format_sensor}'
      format_sensor = '[\?color=auto.input {input:g}°C]'
      chips = ['amdgpu-pci-0a00']
      sensors = ['edge']
      thresholds = {'auto.input': [(0, 'good'), (94, 'bad')]}
    }
  }
}
```
The sensor information _values_ (namely, temperatures, CPU use and RAM load) appear correctly. However, the GPU temperature is colourized based on the current value (as per its `thresholds`), but the CPU temperature (from the `k10-temp-pci`) is not - it's always white, regardless of value.

**Your py3status version**

```
py3status version 3.36 (python 3.9.4) on i3
```

**To Reproduce**

1. Have a CPU whose temperature is monitored by `k10-temp`.
2. Add the block as above.
3. Watch your lack of colour and lament.

**Expected behavior**

Colour should be based on the `threshold` specified.

**Comment by lasers** [comment]
I'm on phone so I can't verify anything.

>always white

There is an issue of using shared thresholds so it's not possible to use multiple instances of lm_sensors with auto.input thresholds. I'm sure you can find it (closed issue). 

The issue here I think is related to improper config. You wanted both 'color=input' and (filled) 'thresholds = []'.

Let me know how it goes. Hope that helps. Cheers.

**Comment by kozross** [comment]
Found the [issue in question](https://github.com/ultrabug/py3status/issues/1927). However, this really doesn't help me figure out how to set things up so that I see the same stuff, just with colour. What's even stranger is that this _used_ to work when I used `coretemp` instead.

**Comment by lasers** [comment]
Fixing your config on phone. Does this do what you want?
 
    lm_sensors {
      format_chip = 'Temp: {format_sensor},'
      format_sensor = '[\?color=input {input:g}°C]'
      chips = ['k10temp-pci-00c3']
      sensors = ['tdie']
      thresholds = [(0, 'good'), (82, 'bad')]
    }
    
    lm_sensors {
      format_chip = 'GPU Temp: {format_sensor}'
      format_sensor = '[\?color=input {input:g}°C]'
      chips = ['amdgpu-pci-0a00']
      sensors = ['edge']
      thresholds = [(0, 'good'), (94, 'bad')]
    }

**Comment by kozross** [comment]
Yes! Thank you. My exact config below for any future folks to reference:

```
group perf_stuff {
  format = "{output}"
  click_mode = "all"
  fixed_width = True
  button_next = 1

  frame {
    format_separator = ' '
    sysdata {
      format = "CPU: [\?color=cpu {cpu_usage}%], RAM: [\?color=mem {mem_used_percent}%],"
    }

    lm_sensors {
      format_chip = 'Temp: {format_sensor},'
      format_sensor = '[\?color=input {input}°C]'
      chips = ['k10temp-pci-00c3']
      sensors = ['tdie']
      thresholds = [(0, 'good'), (82, 'bad')]
    }
    
    lm_sensors {
      format_chip = 'GPU Temp: {format_sensor}'
      format_sensor = '[\?color=input {input}°C]'
      chips = ['amdgpu-pci-0a00']
      sensors = ['edge']
      thresholds = [(0, 'good'), (94, 'bad')]
    }
  }
}

**Comment by lasers** [comment]
* Maybe `\?color=auto.input` could be replaced with `thresholds = auto` to make  `format_sensor` easier.
* Maybe white issue can be fixed by containing all this in a module. Doesn't look like a trivial fix. Color names could be quite long like `\?color=k10temp-pci-00c3_input` or we fix up thresholds on every input. Unknown. Would need to experiment.
* This issue has been solved. Please close this. Thank you. :)
