### ISSUE TITLE
bitcoin_price.py points to old API

### ISSUE THREAD

**Issue by lunar-mining** [ultrabug/py3status#2046]
The bitcoin price outputted by bitcoin_price.py is incorrect. It is pointing to an API http://api.bitcoincharts.com/v1/markets.json that has not been updated since 2018. The website hosting the API appears to have been inactive for several years.

Here is the relevant code:

```python
    def post_config_hook(self):
        """
        Initialize last_price, set the currency mapping
        and the url containing the data.
        """
        self.currency_map = {
            "AUD": "$",
            "CNY": "¥",
            "EUR": "€",
            "GBP": "£",
            "USD": "$",
            "YEN": "¥",
        }
        self.last_price = 0
        self.url = "http://api.bitcoincharts.com/v1/markets.json"        
```
You can reproduce this behavior by running python bitcoin_price.py and comparing the output to today's Bitcoin price.

**Comment by lunar-mining** [comment]
I suggest replacing with a more contemporary API, such as https://api.kraken.com/0/public/Ticker?pair=BTCUSD.

Bitmex also has a python module https://pypi.org/project/bitmex/ but this approach will require some refactoring.

**Comment by ultrabug** [comment]
Thanks @lunar-mining
