### ISSUE TITLE
exchange_rate: You have not supplied an API Access Key

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#2048]
**Describe the bug**
```python
$ python3 exchange_rate.py --term
$? £? ¥?
$? £? ¥?
$? £? ¥?
```

```json
{
  "success": false,
  "error": {
    "code": 101,
    "type": "missing_access_key",
    "info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"
  }
}
```
_via https://api.exchangeratesapi.io/latest_

**Your py3status version**
`py3status version 3.36 (python 3.8.8) on sway` (I'm on KDE).

**Additional context**
Free plan requires personal/billing information.

>:house: Free
>
>Try exchangeratesapi for free.
>$0 per month
>Sign Up
>
>    250 Requests / mo
>    Daily Updates
>    Historical Rates
>    Limited Support

_via https://exchangeratesapi.io/pricing/_

**Comment by ultrabug** [comment]
Thanks for the notice
