### ISSUE TITLE
Documentation unavailable

### ISSUE THREAD

**Issue by oceyral** [ultrabug/py3status#2062]
**Describe the bug**

Hi, the documentation on Readthedocs is not working anymore on Firefox or Chrome.

It looks like it's an issue with incorrect MIME types sent by the server. I don't see the issue with documentation from other projects hosted on Readthedocs.

The message spammed in the console in Firefox for a lot of resources : 
```
The resource from “https://py3status.readthedocs.io/py3status/search/main.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by ultrabug** [comment]
Hello @oceyral , we're talking about https://py3status.readthedocs.io/ right?

Going on this URL, on two browsers + my mobile phone just works fine... I'm not sure what to do to see what you see

**Comment by oceyral** [comment]
Ok, so https://py3status.readthedocs.io/ does work for me too, and I can follow the links from there.

What doesn't work is clicking on the links in the repo README.md (which is what I was doing initially), and then clicking on anything from there - likely because the dependencies haven't been loaded.

For example, clicking on  the link to https://py3status.readthedocs.io/en/latest/modules.html at line 108 in README.md doesn't work, but going directly to https://py3status.readthedocs.io/en/latest/user-guide/modules/, or following the links from  https://py3status.readthedocs.io/ works.

So, I guess it's just an issue of the links in the README needing to be updated.

**Comment by ultrabug** [comment]
Ohhhhhh I feel ashamed to have forgotten to update the README files!

Thank you so much, this should be fixed now :+1:
