### ISSUE TITLE
Local time zone does not work

### ISSUE THREAD

**Issue by vzaliva** [ultrabug/py3status#2066]
**Describe the bug**
Local time format does not work in Clock module.

**Your py3status version**
py3status version 3.22 (python 3.8.10) on i3

**To Reproduce**
Configure module like this:

```
clock {
    formal = "{Local}"
    format_time = "%a %Y-%m-%d %H:%M {timezone} "
}
```

**Expected behavior**
Show local time.

It shows just word "Clock" in red instead!

**Additional context**
I did some digging in clock.py and in `_get_timezone` function for local it does:
`return tzlocal.get_localzone()` while for specific time zone it returns `pytz.timezone(tz)`.

It looks like the objects returned by these functions does not have the same type:

```
In [2]: tzlocal.get_localzone()                                                      
Out[2]: backports.zoneinfo.ZoneInfo(key='America/Los_Angeles')

In [6]: pytz.timezone('America/Los_Angeles')                                         
Out[6]: <DstTzInfo 'America/Los_Angeles' LMT-1 day, 16:07:00 STD>
```

**Comment by vzaliva** [comment]
Running from command line:

```
python3 clock.py 
storage_path: /home/lord/.cache/py3status_cache.data
storage_data: {'clock': {'timezone': '{GMT}', '_ctime': 1632855446.3516397, '_mtime': 1632856462.5763671}}
'backports.zoneinfo.ZoneInfo' object has no attribute 'zone' (AttributeError) module.py line 946.
Traceback
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'zone'
  File "/usr/lib/python3/dist-packages/py3status/module.py", line 946, in run
    response = method()
  File "clock.py", line 284, in clock
    timezone = zone.zone
```

**Comment by vzaliva** [comment]
Potentially related https://github.com/regebro/tzlocal/issues/117

**Comment by vzaliva** [comment]
Tagging @tobes as the original module author.

**Comment by ultrabug** [comment]
Hello @vzaliva , the problem you're facing has been fixed in py3status version 3.39 :)

Please update & enjoy ;)

**Comment by vzaliva** [comment]
I've upgraded and it shows now local time. But clicking on it to cycle time zones does not work
with the following config:

```
clock {
   formal = ["{Local}", "{GMT}"]
   format_time = "%a %Y-%m-%d %H:%M {timezone} "
}
```

When I change to:
```
clock {
    format = ["{America/Los_Angeles}", "{GMT}"]
    format_time = "%a %Y-%m-%d %H:%M {timezone} "
}
```

click-to-cycle works. Is it related?

**Comment by vzaliva** [comment]
The original issue is fixed. Opening separate issue for clicking https://github.com/ultrabug/py3status/issues/2067
