### ISSUE TITLE
Click-to-cycle on  the clock does not work with "Local"

### ISSUE THREAD

**Issue by vzaliva** [ultrabug/py3status#2067]
The following shows now local time. But clicking on it to cycle time zones does not work
with the following config:
```
clock {
   formal = ["{Local}", "{GMT}"]
   format_time = "%a %Y-%m-%d %H:%M {timezone} "
}
```

It works when I change to:

```
clock {
    format = ["{America/Los_Angeles}", "{GMT}"]
    format_time = "%a %Y-%m-%d %H:%M {timezone} "
}
```

I would like the first config to work and I think it is a bug.

**Your py3status version**
py3status version 3.39 (python 3.8.10) on i3

**Comment by ultrabug** [comment]
Hi @vzaliva sorry for the response delay

I think you just made a typo on your first config? `formal` => `format`

If I fix the typo and try on my machine, it works fine

**Comment by vzaliva** [comment]
Thanks. Silly me :)
