### ISSUE TITLE
New error for 'Volume_Status' module

### ISSUE THREAD

**Issue by mlmatlock** [ultrabug/py3status#2071]
**Describe the bug**
Volume_Status fails on load/reload with:
```
Exception in `volume_status` post_config_hook()
```

**Your py3status version**
py3status version 3.39 (python 3.9.7) on sway (Arch Linux)

**To Reproduce**

1. Add module 'volume_status'
2. Configure module:
```
volume_status {
format = " : {percentage}%"
format_muted = "ﱝ "
}
```

3. Run py3status '....'
```
Oct 16 22:52:02 Jammin1 py3status[78922]: ========
Oct 16 22:52:02 Jammin1 py3status[78922]: Starting py3status version 3.39 python 3.9.7
Oct 16 22:52:02 Jammin1 py3status[78922]: window manager: sway
Oct 16 22:52:02 Jammin1 py3status[78922]: config file: /home/merell/.config/py3status/config
Oct 16 22:52:02 Jammin1 py3status[78922]: modules include paths: []
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "sway_idle" from py3status.modules.sway_idle
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "sysdata" from py3status.modules.sysdata
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "conky proc" from py3status.modules.conky
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "scratchpad" from py3status.modules.scratchpad
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "arch_updates" from py3status.modules.arch_updates
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "external_script checkupdates_aur" from py3status.modules.external_script
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "weather_owm" from py3status.modules.weather_owm
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "volume_status" from py3status.modules.volume_status
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "clock" from py3status.modules.clock
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "systemd" from py3status.modules.systemd
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "lm_sensors _anon_module_0" from py3status.modules.lm_sensors
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "lm_sensors _anon_module_1" from py3status.modules.lm_sensors
Oct 16 22:52:02 Jammin1 py3status[78922]: loading module "frame lm_sensors" from py3status.modules.frame
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module sway_idle
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module scratchpad
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module external_script checkupdates_aur
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module weather_owm
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module arch_updates
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module conky proc
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module sysdata
Oct 16 22:52:02 Jammin1 py3status[78922]: storage_path: /home/merell/.cache/py3status_cache.data
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module lm_sensors _anon_module_1
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module frame lm_sensors
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module clock
Oct 16 22:52:02 Jammin1 py3status[78922]: starting module lm_sensors _anon_module_0
Oct 16 22:52:03 Jammin1 py3status[78922]: starting module systemd
Oct 16 22:52:03 Jammin1 py3status[78922]: Exception in `volume_status` post_config_hook().
Oct 16 22:52:03 Jammin1 py3status[78922]: terminating module volume_status
```

**Expected behavior**

Module in status bar.

**Additional context**

ALSA only on this system; don't use JACK/JACK2/pulseaudio/pipewire.

**Comment by lasers** [comment]
I see the bug. Run 'py3status --debug' for more meaningful log messages.

**Comment by mlmatlock** [comment]
Hi @lasers!

Here you go.

[Journal](http://ix.io/3C4v) entries with debug switch.

[command-line output](http://ix.io/3C4w)

**Comment by lasers** [comment]
Sorry. That wasn't helpful. I don't see anything standing out that could be a culprit.

And you will want to get a new 'weather_owm‘'s api_key‘.

**Comment by lasers** [comment]
I'm on phone so I can't test anything. Check 'pactl info' output.

If you installed it recently, you might need to start a service or try restarting the machine.

Is it a fresh installation recently? I somewhat recall getting those kind of errors long time ago.

**Comment by mlmatlock** [comment]
> Check 'pactl info' output.
```
pactl info
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```
> If you installed it recently, you might need to start a service or try restarting the machine.
> Is it a fresh installation recently? I somewhat recall getting those kind of errors long time ago.

Nothing too recent.

I only have libpulse installed (not the main pulseaudio server package, and libpulse provides the pactl binary).  Last install for libpulse was 28 Jul 2021, and this problem just manifested itself last Friday evening; and after poking around discovered (much to my dismay) that an upgrade to mpd installed that fscking pipewire - I wonder if that has anything to do with the new error.

Addendum:  Looked at the module docs again.  I added
```
command = "amixer"
```
to my config...viola...it's back and working again.

Sorry for the noise...:(

**Comment by tkrizek** [comment]
I get the same error when:
- `commad = "pactl"` is present in config
- pipewire, wireplumber and pipewire-pulse is installed
- py3status is loaded during session startup

Workaround: as @mlmatlock mentioned: `command = "amixer"`

If I reload py3status after session is initialized, it is loaded properly. Since pipewire is started as a systemd user service, I suspect there is some sort of race condition when `pactl` doesn't report any devices yet at the time when `volume_status` is loaded.

Interesting messages from log:
```

Apr 03 22:43:20 katze py3status[609]: Module `volume_status`: available sinks: {'34': 'auto_null'}
Apr 03 22:43:20 katze py3status[609]: Exception in `volume_status` post_config_hook().
Apr 03 22:43:20 katze py3status[609]: terminating module volume_status
Apr 03 22:43:20 katze wireplumber[630]: Failed to set scheduler settings: Operation not permitted
Apr 03 22:43:21 katze wireplumber[630]: <WpSiAudioAdapter:0x55c7481d5090> Object activation aborted: proxy destroyed
Apr 03 22:43:21 katze wireplumber[630]: <WpSiAudioAdapter:0x55c7481d5090> failed to activate item: Object activation aborted: proxy destroyed
Apr 03 22:43:25 katze py3status[609]: i3status died and said: i3status: exiting due to signal.
...

Apr 03 22:43:25 katze py3status[664]: loading module "volume_status" from py3status.modules.volume_status
Apr 03 22:43:25 katze py3status[664]: Module `volume_status`: available sinks: {'52': 'alsa_output.pci-0000_00_1f.3.analog-stereo'}
```

Full log here: https://0x0.st/ob-h.log

**Comment by ultrabug** [comment]
@tkrizek hi,

It would help to get the actual exception from the module, could you run it using something like :

```
python py3status/modules/volume_status.py --term
```

On my box, I have piprewire and pulseaudio installed but not wireplumber or pipewire-pulse...

**Comment by tkrizek** [comment]
```
python py3status/modules/volume_status.py --term
```

When I run this on sway startup, I get no output at all and the command keeps running.

If I run it terminal after session is started, I get what seems to be the expected output:

```
Module `test_module`: available sinks: {'183': 'alsa_output.pci-0000_0d_00.3.iec958-stereo', '222': 'alsa_output.usb-0c76_USB_PnP_Audio_Device-00.analog-stereo', '7228': 'alsa_output.pci-0000_0b_00.1.hdmi-stereo-extra3'}
♪: 61%
```
