### ISSUE TITLE
[Mpris] BrokenDBus is broken in multible ways (click event, init metadata, subscription disconnect handling)

### ISSUE THREAD

**Issue by valdur55** [ultrabug/py3status#2076]
**Describe the bug**
 BrokenDBus is broken in multible ways:

-  Clicking on mpris module while chrome/chromium playing is stopping statusbar update
- Metadata and playbackstatus is none on BrokenDBusMpris init.
- player_on_change function gets called by old no existent player_id and it will cause module crash

**Your py3status version**
3.40 . Problem is also in older versions

**To Reproduce**
**Clicking on mpris module while chrome/chromium playing is stopping statusbar update**

1.  Open media in chrome/chromium
2. Click on mpris module
3. Check if mediaplayer is now paused or not

**Metadata and playbackstatus is none on BrokenDBusMpris init.**

1. Open media in chrome/chromium
2. Check mpris player status
3. Reload i3wm
Check if player status is same or not. Expect playerstatus "stopped"

**player_on_change function gets called by old no existent player_id and it will cause module crash**

1. Open media in chrome/chromium
2. Close all chrome/chromium windows
3. Open media in chrome/chromium
4. Check if py3status values are updated or not

**Comment by ultrabug** [comment]
@valdur55 I guess we can close this one thanks to you
