### ISSUE TITLE
battery_level does display 0.0 for {power} with sys

### ISSUE THREAD

**Issue by BonaBeavis** [ultrabug/py3status#2078]
**Describe the bug**
battery_level does display 0.0 for {power}

**Your py3status version**
py3status version 3.39 (python 3.9.7) on i3

Issue is that battery_level calculates power by querying and multiplying voltage and current from sys. My model does not have "current_now" but has "power_now"

**Comment by lasers** [comment]
I don't have a linux laptop to test this. The fix may look something like this...
```diff
diff --git a/py3status/modules/battery_level.py b/py3status/modules/battery_level.py
index f5d7f89..c147d8e 100644
--- a/py3status/modules/battery_level.py
+++ b/py3status/modules/battery_level.py
@@ -338,7 +338,9 @@ class Py3status:
             remaining_energy = r.get(
                 "POWER_SUPPLY_ENERGY_NOW", r.get("POWER_SUPPLY_CHARGE_NOW")
             )
-            current_now = r.get("POWER_SUPPLY_CURRENT_NOW", 0)
+            current_now = r.get(
+                "POWER_SUPPLY_CURRENT_NOW", r.get("POWER_SUPPLY_POWER_NOW", 0)
+            )
             voltage_now = r.get("POWER_SUPPLY_VOLTAGE_NOW", 0)
 
             # missing values may indicate this is not a battery and should be skipped
```

**Comment by BonaBeavis** [comment]
I think this does not work, because `current != power`.  It is `current x voltage = power`

**Comment by ultrabug** [comment]
@BonaBeavis power is calculated after this from current_now * voltage_now

In my current understanding, this is the closest we'll get so I added lasers suggestion as a fallback for people like you
