### ISSUE TITLE
High cpu load after clicking mrpis pause.

### ISSUE THREAD

**Issue by valdur55** [ultrabug/py3status#2085]
**Describe the bug**
High cpu load by py3status. 
update_due gets negative value at line https://github.com/ultrabug/py3status/blob/master/py3status/core.py#L1031
It causes endless and rapid loop which moves to negative direction.
I made branch where issue is always occuring: https://github.com/valdur55/py3status/tree/mpris-cpu-load
And added one if check which reports: "Negative update_due occured. Reseting to 1" when issue happens.

Using VLC as media player (maybe it matters).

**Your py3status version**
3.40 (python 3.8.10)

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Add module 'mpris'
2. Configure module like this '{time} {player}'   (with my branch no need for that)
3. Run py3status.
4. Make player to playing state
5. Change player to paused state
6. High CPU load occurs.  ( in my mpris-cpu-load there will be log message "Negative update_due occured. Reseting to 1")

**Expected behavior**
CPU load should come down because paused state player will not update it's time value.

**Comment by valdur55** [comment]
Did some analysis and found data flow:
When mediaplayer is playing, cache_until is set to  time.perf_counter() + 0.5
When mediaplayer gets non-playing state,  cache_until is set to -1
Update request from playing state is still up and when update time comes it isn't checking if cache_until is -1 and gets into endless loop for waiting module update/change.


Data for update_due values during high cpu load:
Update due -8.550362663998385
Update due -8.561496337002609
Update due -8.614066078007454
Update due -8.62588996499835
Update due -8.678577004000545
Update due -8.731410777996643
Update due -8.742878290009685
Update due -8.7540116480086
Update due -8.806623505006428

**Comment by valdur55** [comment]
Made bug occuring more noticable... And here is full log: https://termbin.com/m4h0v
Mpris module is using normal time_perf() + 0.5 update and nagbar will noify about due_time which are between -0.1 and 0.
Critical place: https://github.com/valdur55/py3status/blob/mpris-cpu-load/py3status/core.py#L406

**Comment by valdur55** [comment]
Made update at my test branch and made module which consist only logic for changing cache_timeout and string which updates on every module call. ( https://github.com/valdur55/py3status/blob/mpris-cpu-load/py3status/modules/autoupdate_sandbox.py )
To repro issue. You need to click once left click to start updating and second click for stopping auto update.
You should see notification about negative timeout_due (changed notification text, point is same) after click.

And there are other keybindings too:
Middle click changes auto update on
Right click stops auto update.

**Comment by valdur55** [comment]
Did deeper digging into py3status core code and made changes in mpris-cpu-load branch to forcefully go into high cpu situation.
Use branch: https://github.com/valdur55/py3status/tree/mpris-cpu-load
Make separate panel for module:
**i3 config**
```
bar {
     tray_output none
     id bar-debug
     position bottom
     workspace_buttons no
     #Adding --dbus-notify is useful.
     status_command py3status -s -l ~/py3status-bar-debug.log -c ~/.config/py3status-bar-debug.log -d   
}
```
**Py3status config**
```
py3status {
 "on_error" = "show"
}

#Without instance name "crash" is just works as stoppable clock
order += "autoupdate_sandbox crash"
```

Auto update mode works, but things get problematic when you stop clock.

To prevent high cpu load, I have added monitor at https://github.com/valdur55/py3status/blob/mpris-cpu-load/py3status/core.py#L408
If you enable negative timeout_due high cpu load will occur. High cpu load is produced by loop: https://github.com/valdur55/py3status/blob/90a1c00a1093c545d2a5331d2ed765da63588f93/py3status/core.py#L1032 which isn't doing sleeps.

Sidenote: 
Actually there is also issue in design.

PEP 418 tells for what purpose functions should be used ( https://www.python.org/dev/peps/pep-0418/ ) :
```
New functions:

time.monotonic(): timeout and scheduling, not affected by system clock updates
time.perf_counter(): benchmarking, most precise clock for short period
time.process_time(): profiling, CPU time of the process
```
Replacing time.perf_counter() with time.monotonic() didn't solve original high cpu load.

Long story short. I have dropped negative update_due (with notification) several days and I haven't noticed bad effects.
In long term it feels like Py3.CACHE_FOREVER isn't handled correctly in update queue, because issue starts after next update should be handled. 

And here is test which provides reasoning for that feeling:

Using 5s and 10s for update interval. (for better time resolution i used time.perf_counter as log's time_str)
Test screnario is same:
1) Let player get two auto updates.
2) Click pause
3) Wait for high cpu load.

**Update interval 5s** 10127.033332662  - 10122.035957793 = 4,997374869
```
10117.032689625 INFO method mpris returned {'color': '#00FF00', 'composite': [{'full_text': '▷ 0:23 VLC meediaesitaja', 'instance': 'onlytime 0', 'name': 'mpris', 'color': '#00FF00'}], 'instance': 'onlytime', 'name': 'mpris'} 
10122.035957793 INFO method mpris returned {'color': '#00FF00', 'composite': [{'full_text': '▷ 0:28 VLC meediaesitaja', 'instance': 'onlytime 0', 'name': 'mpris', 'color': '#00FF00'}], 'instance': 'onlytime', 'name': 'mpris'} 
10124.060585446 INFO received event {'name': 'mpris', 'instance': 'onlytime 0', 'button': 1, 'modifiers': ['Mod2'], 'x': 3138, 'y': 1076, 'relative_x': 50, 'relative_y': 17, 'output_x': 1772, 'output_y': 1076, 'width': 198, 'height': 21}
10124.060780987 INFO trying to dispatch event to module "mpris onlytime"
10124.062145305 INFO dispatching event {'name': 'mpris', 'instance': 'onlytime', 'button': 1, 'modifiers': ['Mod2'], 'x': 3138, 'y': 1076, 'relative_x': 50, 'relative_y': 17, 'output_x': 1772, 'output_y': 1076, 'width': 198, 'height': 21, 'index': 0}
10124.06274423 INFO clearing cache for method mpris
10124.069438856 INFO method mpris returned {'color': '#FFFF00', 'composite': [{'full_text': '◫ 0:30 VLC meediaesitaja', 'instance': 'onlytime 0', 'name': 'mpris', 'color': '#FFFF00'}], 'instance': 'onlytime', 'name': 'mpris'} 
10127.033332662 INFO Negative update_due occured -0.00015582299965899438. Using as is
10127.033489892 INFO Negative update_due occured -0.000447149999672547. Using as is
10127.033571029 INFO Negative update_due occured -0.0005346199995983625. Using as is
10127.033639074 INFO Negative update_due occured -0.0006072649994166568. Using as is
```

**Update interval 10s**  10942.879856437 - 10932.881037896 = 9,998818541

```
10922.878785907 INFO method mpris returned {'color': '#00FF00', 'composite': [{'full_text': '▷ 13:08 VLC meediaesitaja', 'instance': 'onlytime 0', 'name': 'mpris', 'color': '#00FF00'}], 'instance': 'onlytime', 'name': 'mpris'} 
10932.881037896 INFO method mpris returned {'color': '#00FF00', 'composite': [{'full_text': '▷ 13:18 VLC meediaesitaja', 'instance': 'onlytime 0', 'name': 'mpris', 'color': '#00FF00'}], 'instance': 'onlytime', 'name': 'mpris'} 
10936.267237664 INFO received event {'name': 'mpris', 'instance': 'onlytime 0', 'button': 1, 'modifiers': ['Mod2'], 'x': 3201, 'y': 1069, 'relative_x': 121, 'relative_y': 10, 'output_x': 1835, 'output_y': 1069, 'width': 206, 'height': 21}
10936.267523372 INFO trying to dispatch event to module "mpris onlytime"
10936.271384195 INFO dispatching event {'name': 'mpris', 'instance': 'onlytime', 'button': 1, 'modifiers': ['Mod2'], 'x': 3201, 'y': 1069, 'relative_x': 121, 'relative_y': 10, 'output_x': 1835, 'output_y': 1069, 'width': 206, 'height': 21, 'index': 0}
10936.271487072 INFO clearing cache for method mpris
10942.879856437 INFO Negative update_due occured -0.0008352370005013654. Using as is
10942.88014096 INFO Negative update_due occured -0.0011997210003755754. Using as is
10942.880361874 INFO Negative update_due occured -0.0014134240009298082. Using as is
10942.880927433 INFO Negative update_due occured -0.001954806000867393. Using as is
10942.881227249 INFO Negative update_due occured -0.0022632920008618385. Using as is
10942.881549943 INFO Negative update_due occured -0.002594130000943551. Using as is
10942.882168247 INFO Negative update_due occured -0.003207488000043668. Using as is
10942.882386331 INFO Negative update_due occured -0.003464973000518512. Using as is
10942.882799233 INFO Negative update_due occured -0.003646299001047737. Using as is
10942.883013677 INFO Negative update_due occured -0.004082331000972772. Using as is
10942.883180264 INFO Negative update_due occured -0.004272735999620636. Using as is
10942.883522385 INFO Negative update_due occured -0.004406879001180641. Using as is
10942.88369651 INFO Negative update_due occured -0.0047711120005260454. Using as is
10942.883838594 INFO Negative update_due occured -0.004925715000354103. Using as is
10942.884224745 INFO Negative update_due occured -0.005093298001156654. Using as is
10942.884441754 INFO Negative update_due occured -0.005499901999428403. Using as is
10942.88458682 INFO Negative update_due occured -0.005675001999406959. Using as is
10942.884903806 INFO Negative update_due occured -0.00580778800031112. Using as is
10942.885040324 INFO Negative update_due occured -0.006136795000202255. Using as is
10942.885144885 INFO Negative update_due occured -0.00624856000104046. Using as is
10942.885242041 INFO Negative update_due occured -0.006346657000904088. Using as is
10942.885802593 INFO Negative update_due occured -0.006482582999524311. Using as is
10942.885846691 INFO method mpris returned {'color': '#FFFF00', 'composite': [{'full_text': '◫ 13:21 VLC meediaesitaja', 'instance': 'onlytime 0', 'name': 'mpris', 'color': '#FFFF00'}], 'instance': 'onlytime', 'name': 'mpris'} 
10942.886033423 INFO Negative update_due occured -0.007089429000188829. Using as is

```


And I managed to get messages for same principle (preventing negative sleep time) with one terminal emulator: https://i.imgur.com/GpAva7z.jpg
And commit for that another program to get some context: https://www.mail-archive.com/enlightenment-devel@lists.sourceforge.net/msg107295.html
```
EAPI void
ecore_loop_time_set(double t)
{
   double tnow = ecore_time_get();
   double tdelta = t - tnow;

   if (tdelta > 0.0)
     {
        fprintf(stderr,
                "Eccore: Trying to set loop time (%1.8f) %1.8fs too far in the future\n",
                t, tdelta);
        return;
     }
   efl_loop_time_set(ML_OBJ, t);
}
```

And there is _ecore_time_init(void)  (https://git.enlightenment.org/core/efl.git/tree/src/lib/ecore/ecore_time.c#n102  which decides what type of clock is used in program.

**Comment by valdur55** [comment]
While working with window and scratchpad module after sway -> i3 switch (logout and login) i captured high cpu usage by old py3status process:
![image](https://user-images.githubusercontent.com/3678057/149820340-4d077b41-5f38-4f77-b2d2-4fadeb7dad93.png)

**Comment by ultrabug** [comment]
@eumiro that PEP 418 pointer to monotonic sounds like a legitimate point. Since you provided the updates to using perf_counter, would you have an opinion on this please mate?

**Comment by valdur55** [comment]
During chatting in irc two key points added:
Some time ago I looked into hisotry and found difference:
Old:
https://github.com/ultrabug/py3status/blob/7ff0f562b347d065d67ac8a25764949c8dd5ce24/py3status/core.py#L295-L299

Current:
https://github.com/ultrabug/py3status/blob/0f228a74484a2da29cbcff652856daddf9889996/py3status/core.py#L404-L406

And have noticed that I didn't push my mpris-cpu-cload force crash commit: https://github.com/valdur55/py3status/commit/ad355f9a93be212dcb2e47b98ffe22b4e676e0c8

**Comment by ultrabug** [comment]
Thanks, #2092 fixes it
