### ISSUE TITLE
EXCHANGE_RATE wont load

### ISSUE THREAD

**Issue by evofromko** [ultrabug/py3status#2089]
**Describe the bug**
exchange_rate wont load rates , shows "?"

**Your py3status version**
py3status version 3.40 ( python 3.10.1) on i3

api_key = My api key
base = "USD"
cache_timeout = 43200 ( tried with 6, 60,600 and any other numbers )
format = "$={EUR}"

Tried default EUR to USD - still same.
API Usage:	0% (0 / 250)  API Usage -  from API website.

**Comment by lasers** [comment]
I can't help you there, but I can try.

Change `base` and `api_key` in the url. You might find out why.

http://api.exchangeratesapi.io/v1/latest?base={base}&access_key={api_key}

**Comment by evofromko** [comment]
Thank You!
Interesting as it says :`{"error":{"code":"invalid_access_key","message":"You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]"}}`

Changed API key - same.
Long shot - but i dont want to spend 10$ for cheapest option just to check it.
Do i need pay`d version or free is ok ?  As it looks like i might need to pay.

**Comment by lasers** [comment]
I don't use this module so I can't comment on anything.

Idk if it's invalid api key or something stupid/outdated on your/our side.  

Hopefully somebody else will look into this soon enough.

IIRC, this module used to use a different site that doesn't require accounts. That stopped so the author looked for a different site to use.

**Comment by evofromko** [comment]
Understood... i think gonna be something stupid on my PC but its a fresh install, we will see with time ill probably gonna try to take a deeper look at it as well.
Thanks for your input.

**Comment by ultrabug** [comment]
Closing since it looks like it's not a problem from the module itself
