### ISSUE TITLE
The future and i3bar version 4.12

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#209]
With the release of i3bar 4.12 things are going to go a bit crazy

```
response = {
    'full_text': '<span foreground="blue" size="x-large">Blue text</span> is <i>cool</i>!',
    'background': "#FF00FF',
    'markup': 'pango'
}
```
If I have i3bar 4.12 I have new exciting formatting, if not then I get a horrible bit of raw html.

I think it would be nice to keep compatibility with old and new versions of both i3bar and py3status

the simplest way I can see to do this is to make responses like

```
response = {
    'full_text': 'this is legacy output',
    'pango': '<b>New</b> <span foreground="blue">output</span>',
}
```

py3status could then use pango if we have i3bar >= 4.12 else use full_text.  We could also strip any tags from full_text to stop people just using that for pango output. seeing as i3bar ignores stuff it doesn't know sending the 'pango' bit of response to it for legacy py3ststus would be fine.

Anyhow this is my thoughts on how to deal with this change.

What do others think?

**Comment by tobes** [comment]
Another option would be to have something like `'pango': True` in the `i3s_config` on the modules function calls so that the module knows it can use pango output

**Comment by ultrabug** [comment]
Well yes, but the pango markup has been there for a long time now and always been available on i3s_config for modules to use or not.

AFAIK you had to add it to the main i3status.conf to enable it for the whole bar, has it changed ? I'm asking because you seem to say that a module could now have a `markup: pango` in its JSON and it would also work ?

> Another option would be to have something like 'pango': True in the i3s_config on the modules function calls so that the module knows it can use pango output

That's already supported as it is yes.

**Comment by tobes** [comment]
Ok, I thought the pango was new.  `background` has definitely been added in this version.  I've been pondering this and actually it's not such an issue as I'd thought.  For  most modules `format` etc would be fine.  I think the only one I'm aware off with a problem is the `weather_yahoo` around having the color defined by today's temperature but that could be fixed by just adding that feature to the module.

Maybe we should also add 'pango' as a universal option.  Keeping it out of modules would keep them pango markup free which is probably a good thing as the general look should be the users choice as much as possible.

**Comment by ultrabug** [comment]
> Maybe we should also add 'pango' as a universal option. Keeping it out of modules would keep them pango markup free which is probably a good thing as the general look should be the users choice as much as possible.

Sounds reasonable indeed !

**Comment by tobes** [comment]
I'm closing this issue.

My thinking is should just contain simple text and then users can set the format with pango etc.
