### ISSUE TITLE
weather_owm: forecast_days controls 3-hour intervals, not daily intervals

### ISSUE THREAD

**Issue by cjquines** [ultrabug/py3status#2096]
The documentation suggests that `forecast_days` controls days, but in reality, it returns 3-hour intervals. The current forecast uses [the 5 Day / 3 Hour API](https://openweathermap.org/forecast5), so the data returned in `list` is separated by 3 hours, and not by days. Either:

* Change [_get_forecast](https://github.com/ultrabug/py3status/blob/master/py3status/modules/weather_owm.py#L543) to somehow take `cnt: 8*self.forecast_days` instead, and then take every eighth interval, or
* Use the [One Call API](https://openweathermap.org/api/one-call-api), which has a `daily` field. This is probably better, but will involve more code change, as the output format is different.

**Comment by ultrabug** [comment]
Hi @cjquines thanks for pointing this out so clearly

Could you try https://github.com/ultrabug/py3status/pull/2097 ? which implements the onecall endpoint!

**Comment by cjquines** [comment]
yeah that works! thanks so much!
