### ISSUE TITLE
3.41 update broke weather_owm module

### ISSUE THREAD

**Issue by mlmatlock** [ultrabug/py3status#2106]
**Describe the bug**

Upgrade to v3.41 broke weather_owm for me

**Your py3status version**

py3status version 3.41 (python 3.10.2) on sway

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Add module 'weather_owm'
2. Configure module like this [my weather_owm config snippet](http://ix.io/3QWG)
3. Run py3status 'Normal statusbar start from sway config.'

**Expected behavior**

Proper module output/display as from previous versions

**Screenshots**
Screenshot from v3.40:
![3 40_no_error](https://user-images.githubusercontent.com/42914546/155900049-2a4e5c64-1316-4cab-9462-75531d1186a6.png)

Screenshot from v3.41:
![3 41_error](https://user-images.githubusercontent.com/42914546/155900071-a992b9d6-3faa-462d-9a87-3b0e6d1cce09.png)

**Additional context**

Bisect accomplished.  Results:

`86f465972bc298c38925dc9fb00c84639b4bc3be is the first bad commit
commit 86f465972bc298c38925dc9fb00c84639b4bc3be
Author: Ultrabug <ultrabug@users.noreply.github.com>
Date:   Tue Feb 1 11:01:44 2022 +0100

    weather_owm module: fix forecast by using new onecall api endpoint (#2097)
    
    thx to @cjquines
    
    closes #2096

 py3status/modules/weather_owm.py | 47 +++++++++++++++++++++++++++-------------
 1 file changed, 32 insertions(+), 15 deletions(-)`

**Comment by ultrabug** [comment]
Sorry for breaking your module @mlmatlock :innocent:  Nice setup!

So we get a HTTP 400 error... pfff :( I'll check it out

**Comment by ultrabug** [comment]
Found & fixed, thanks for providing everything I needed to help

**Comment by mlmatlock** [comment]
Thanks, @ultrabug!  I miss my weather.  :)

Now, I am noticing (still related, I would think):

 The call to the `onecall` API seems to be for a `DAILY` request; so while my `forecast_icons` now match with the onecall output, I've lost my `CURRENT` conditions (right now, the remainder of my display is based on the `daily` JSON output key).

Playing with direct requests to the API, I've found that you can get the current conditions and daily forecast by excluding the minutely and hourly keys.

**Comment by mlmatlock** [comment]
@ultrabug:

Note:  py3status was refreshed immediately prior to the API call.

![3 41_git_update](https://user-images.githubusercontent.com/42914546/156004663-e584d75c-f621-4f5d-b442-e63079d09e1d.png)

[Raw JSON output](http://ix.io/3R0g)

[Filtered thru a viewer (thru day 3)](http://ix.io/3R0k)

As you can see, the current conditions do not match the output, but the forecast icons are correct.

**Comment by mlmatlock** [comment]
Ok, so I figured out how to put my api key and location directly into a stand-alone copy of weather_owm.py, and ran it.  Below status bar output is from the 3.40 version, running as a custom module, and updated immediately prior to running the self test.

![20220301_10h19m23s_grim](https://user-images.githubusercontent.com/42914546/156196726-f1935ece-1141-42b8-82fa-62895891b292.png)

[This](http://ix.io/3R5F) is the terminal output of the test (no need to let it run forever).

**Comment by ultrabug** [comment]
Well @mlmatlock indeed, the "current" one is derived from the `daily` forecast, day 0 (= current) which might be less accurate than the real current one

Thing is, the onecall API does not expose a consistent view on each of the forecast versions it returns...

**Comment by mlmatlock** [comment]
It will be inaccurate, because it is still a forecast of conditions.

Like I've said before, I'm not a coder, but I see:

```
OWM_CURR_ENDPOINT = "https://api.openweathermap.org/data/2.5/weather?"
OWM_FUTURE_ENDPOINT = "https://api.openweathermap.org/data/2.5/forecast?"
OWM_ONECALL_ENDPOINT = "https://api.openweathermap.org/data/2.5/onecall?"
```

and

```
    def _get_weather(self, extras):
        # Get and process the current weather
        params = {"appid": self.api_key, "lang": self.lang}
        extras.update(params)
        return self._make_req(OWM_CURR_ENDPOINT, extras)

    def _get_forecast(self, extras):
        # Get the next few days
        if self.forecast_days == 0:
            return []
        # Get raw data
        params = {
            "appid": self.api_key,
            "lang": self.lang,
            "cnt": self.forecast_days + 1,
        }
        extras.update(params)
        data = self._make_req(OWM_FUTURE_ENDPOINT, extras)
        # Extract forecast
        weathers = data["list"]
        return weathers[:-1] if self.forecast_include_today else weathers[1:]

    def _get_onecall(self, extras):
        # Get and process the current weather
        params = {"appid": self.api_key, "lang": self.lang}
        extras.update(params)
        return self._make_req(OWM_ONECALL_ENDPOINT, extras)
```
Does this mean that whatever the `def_getonecall...` returns, that is the output that will get processed, regardless of whatever the previous `get` calls returned?
