### ISSUE TITLE
py3status inhibits SIGSTP when bar is shown for less than one second

### ISSUE THREAD

**Issue by MFHKiwi** [ultrabug/py3status#2107]
**Describe the bug**
When I open my bar for a short time, less than one second, py3status blocks `SIGSTP` and continues to update.

**Your py3status version**
`py3status version 3.41 (python 3.9.9) on i3`

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Set i3bar `mode` to `hide`
2. Display bar for less than one second
3. Check syslog

[py3status config](https://pastebin.com/x8mpeUAD)

**Expected behavior**
py3status accepts the `SIGSTP` and stops using the CPU.

**Additional context**
Syslog when displaying for over one second: `py3status: received stop_signal SIGTSTP`
Syslog when displaying for less than one second: `py3status: inhibited stop_signal SIGTSTP`

**Comment by lasers** [comment]
`Not Found (#404)`

**Comment by MFHKiwi** [comment]
> `Not Found (#404)`

Should be fixed.

**Comment by ultrabug** [comment]
Hello @MFHKiwi 

You can disable this behavior using : https://py3status.readthedocs.io/en/latest/user-guide/configuration/#the-py3status-configuration-section

**Comment by MFHKiwi** [comment]
> Hello @MFHKiwi
> 
> You can disable this behavior using : https://py3status.readthedocs.io/en/latest/user-guide/configuration/#the-py3status-configuration-section

Thank you, but I do not wish to disable the feature; I am making this bug report because I'd like the feature to function properly so that I can take advantage of it.

**Comment by ultrabug** [comment]
I would have to add an option then because if you check #2093 you'll understand that this mechanism has been created to avoid signal flickering... I'll think about it

**Comment by MFHKiwi** [comment]
> I would have to add an option then because if you check #2093 you'll understand that this mechanism has been created to avoid signal flickering... I'll think about it

Cool, thank you. :)

**Comment by MFHKiwi** [comment]
Hi, are there any plans for this? I'd really love to see an option implemented.

**Comment by ultrabug** [comment]
In the end I worked so that we don't need an option for this, I hate adding too much options :)

See #2115 ; will be released as part of v3.43
