### ISSUE TITLE
python 3.6 is dead... end of life

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#2117]
**Describe the bug**

python 3.6 is dead.... end of life since dec 23, 2021.

* no more bug fixes.
* no more security fixes.
* it's dead, jim.

**Your py3status version**
* git

**Additional context**
* stretch, debian's oldoldstable, is on python 3.5 and has been discontinued since july 6, 2020.
* buster, debian's current oldstable, is on python 3.7
* bullseye, debian's current stable, is on python 3.9.1
* py3status 3.43 released recently... 3 months after python 3.6 end of life.
* py3status should announce end of life support for python 3.6 in next release.

**Comment by ultrabug** [comment]
CHANGELOG has been updated as such for release 3.44

Release 3.45 will ditch py3.6, if you're up for it you can open a cleanup PR thanks mate
