### ISSUE TITLE
Pango markup for modules nested inside groups broken in version 3.43

### ISSUE THREAD

**Issue by diabonas** [ultrabug/py3status#2118]
**Describe the bug**
In py3status version 3.43, modules inside groups that have Pango markup enabled are not rendered correctly: the markup is shown verbatim instead of getting turned into a styled text. This is a regression from version 3.42.

Note that only modules inside groups appear to be affected, modules placed at the top level have their markup rendered correctly.

**Your py3status version**
py3status version 3.43 (python 3.10.4) on sway

**To Reproduce**
Consider the following minimal configuration:
```
order += "group test"

group test {
    static_string {
        format = "<b>test</b>"
        markup = "pango"
    }
}
```
When run with py3status 3.43, it produces the following output:
```json
{"version": 1, "click_events": true, "stop_signal": 20}
[[]
,[]
,[{"full_text": "&lt;b&gt;test&lt;/b&gt;", "markup": "pango", "instance": "_anon_module_0 0", "name": "static_string"}]
```
Note that the markup characters are escaped, meaning that the module will be rendered verbatim as `<b>test</b>`.

**Expected behavior**
When running the above configuration with py3status 3.42, the output is as follows:
```json
{"version": 1, "click_events": true, "stop_signal": 20}
[[]
,[]
,[{"full_text": "<b>test</b>", "markup": "pango", "instance": "_anon_module_0 0", "name": "static_string"}]
```
Since the characters are not escaped, the module renders as <code><b>test</b></code> as expected.

**Additional context**
A bisect shows that this issue was introduced by commit cf98b89f932c636a2566d8d112117a1a5d2e7fb0.

**Comment by lasers** [comment]
What's the real config that broke this?

**Comment by diabonas** [comment]
My actual configuration looks similar to the minimal example, but with multiple group members that are `external_script`s instead of `static_string`s: I am using some custom scripts that produce multi-coloured output using Pango markup. Several of these scripts are grouped together so that I can cycle through them by clicking on the group.

So something like
```
order += "group test"

group test {
    button_next = 1

    external_script {
        script_path = "myscript1.sh"
        markup = "pango"
    }

    external_script {
        script_path = "myscript2.sh"
        markup = "pango"
    }

    external_script {
        script_path = "myscript3.sh"
        markup = "pango"
    }
}
```
where the output of the custom scripts looks like
```html
a: <span color="red">1</span>, b: <span color="yellow">2</span>, c: <span color="green">3</span>
```

**Comment by lasers** [comment]
(Opinion) I think py3status should stop trying to escape pango markups for the users. Let users do it themselves in the `format` and/or in the scripts too... is which why I want to see what the real config looks like... then that would be all. Also, we might have to escape markups only for the placeholders someday if necessary.

Seeing your example, you don't have to change anything because you already did this for your output. It's just that py3status changed replacing from single `&` to `&amp;`... to multiple html entitles now.

Also, IIRC when I looked at this last time, there were other issues too... First, it was basically hard to make pango markup working nicely with py3status formatter... and secondly, having pango markup on ought to break interactive modules on purpose too.
 
https://github.com/lasers/py3status/tree/no-more-html

**Comment by diabonas** [comment]
I agree that escaping Pango markup would never be useful for me since I do all the formatting myself anyway. I am not sure whether there are other use cases where this is necessary, but I would argue that when users explicitly enable Pango markup, they should be aware of having to do HTML escaping themselves if necessary.

I guess the origin of this code path, commit fe027c0acfac8909bb280f522628127385ca4d6d, intended to make it a bit easier to use ampersands, but even that seems (slightly) wrong because [Pango markup could theoretically contain XML entities](https://docs.gtk.org/Pango/pango_markup.html).

I would therefore support removing the escaping altogether as proposed by https://github.com/lasers/py3status/commit/57a4f849e0019865e21a0dd36472c4c74fd6ca65.
