### ISSUE TITLE
add format_stopped to deadbeef

### ISSUE THREAD

**Issue by porudev** [ultrabug/py3status#2134]
**Is your feature request related to a problem? Please describe.**
Yes, currently there is no option to hide deadbeef's custom format when it not running

**Your py3status version**
py3status version 3.45 (python 3.10.5) on i3

**Describe the solution you'd like**
Add an option like format_stopped = "" to show nothing while it not running when there is a custom format already set

**Describe alternatives you've considered**
Use deadbeef without a custom format but look really bad on my setup

**Additional context**
![image](https://user-images.githubusercontent.com/81072838/181767505-f6c9a1c5-439a-455b-b2da-f86265f03160.png)
![image](https://user-images.githubusercontent.com/81072838/181767655-8db561be-861d-421f-8f45-883e24ac8572.png)

The second image is when i don't use custom format, it disappear when i close deadbeef, the first one is with custom format and it doesn't disappear when i close deadbeef

**Comment by lasers** [comment]
Your custom format should look something like this.

```python
format = "[\?if=title ICON ][{artist} - ][{title}]"
```

**Comment by porudev** [comment]
> 

that's a chief kiss, thank you!

**Comment by ultrabug** [comment]
<3
