### ISSUE TITLE
i3-nagbar is hidden under py3status bar in battery_level module

### ISSUE THREAD

**Issue by jdholtz** [ultrabug/py3status#2135]
**Describe the bug**
I was testing out the notification feature on the `battery_level` module. As I was testing it out, I noticed that, when i3-nagbar is displayed, once I show the py3status bar again, the black outline of the py3status bar does not get removed. 
See the attached screenshot of what is happening.

**Your py3status version**
py3status version 3.45 (python 3.10.5) on i3

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Configure i3bar to have "mode hide" and "modifier <Mod key>" 
2. Add module 'battery_level'
3. Configure module like this 'notification = true'
4. Click on the battery_level module
5. When you re-hide the py3status bar (by releasing the Mod key), you will notice that a black outline is still shown, hiding the i3-nagbar.

**Expected behavior**
I expect the battery_level module nagbars to work exactly like i3-nagbar, in the sense that it does not block the nagbar after the py3status bar is re-hidden.

**Screenshots**
![2022-08-04-101608_1920x75_scrot](https://user-images.githubusercontent.com/89617856/182883793-a0cc2df7-7ac9-4519-8be1-339bf08a7485.png)

**Additional context**
I also cannot actually interact with the nagbar (pressing 'X'). 

It most likely has something to do with the way this module uses i3-nagbar because, if I spawn my own nagbar first, and then click on the module - with the new nagbar moving to the bottom - I don't get this error. However, when I remove the nagbar I created, the issue reappears.

**Comment by ultrabug** [comment]
hello @jdholtz to my understanding neither py3status not any of its modules is responsible of how i3wm handles i3-nagbar rendering.

py3status just calls i3-nagbar just like anyone else, by issuing a background command which is interpreted and rendered by i3wm itself.

So sadly I'm not sure what we can do more about this here I'm afraid.

**Comment by jdholtz** [comment]
I figured it probably wasn’t py3status , but it is strange that this is the only time I run into this issue. I did try it by doing it in the same way in python and was not able to replicate this either. 

I’ll close this as there isn’t anything that can be done about this with py3status.

**Comment by ultrabug** [comment]
Sorry I can't be of a better help @jdholtz ; I hope py3status suits you well :) enjoy!

**Comment by jdholtz** [comment]
Fixed by adding
```
py3status {
    stop_signal = 0
}
```
