### ISSUE TITLE
clock.py:269: PytzUsageWarning: The zone attribute is specific to pytz's interface

### ISSUE THREAD

**Issue by valdur55** [ultrabug/py3status#2150]
**Describe the bug**
clock.py:269: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

**Your py3status version**
py3status version 3.47 (python 3.8.10) on i3
Ubuntu 20.04

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Run clock.py module inside of terminal emulator.

**Expected behavior**
No warning shown.

**Comment by ultrabug** [comment]
thanks for the hint, see proposed PR

**Comment by valdur55** [comment]
Looks good, but it works with >=python3.9. (Refered documentation also states New in python 3.9) (https://docs.python.org/3/library/zoneinfo.html ) 
In tox there are supported python versions 3.7 and 3.8
With python 3.8.10 i get `ModuleNotFoundError: No module named 'zoneinfo'`
