### ISSUE TITLE
Module volume_status fails with error after 3.47 update.

### ISSUE THREAD

**Issue by valdur55** [ultrabug/py3status#2151]
**Describe the bug**
After upgrading to 3.47 volume_status fails with error.

**Your py3status version**
py3status version 3.47 (python 3.8.10) on i3

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Add module volume_status
2. Configure module like this 
```
volume_status {
    command = "amixer"
    device = "pulse"
}

```
4. Run py3status
5. See error on log
```
2022-10-04 23:26:00 WARNING Instance `volume_status`, user method `volume_status` failed.
2022-10-04 23:26:00 INFO Traceback
CommandError: Command `amixer -M -c 0 -D pulse sget IEC958` returned non-zero exit status 1
  File "/home/valdur/arendus/py3status-valdur55/py3status/module.py", line 948, in run
    response = method()
  File "/home/valdur/arendus/py3status-valdur55/py3status/modules/volume_status.py", line 390, in volume_status
    perc, muted = self.backend.get_volume()
  File "/home/valdur/arendus/py3status-valdur55/py3status/modules/volume_status.py", line 151, in get_volume
    output = self.command_output(self.get_volume_cmd)
  File "/home/valdur/arendus/py3status-valdur55/py3status/modules/volume_status.py", line 114, in command_output
    return self.parent.py3.command_output(cmd)
  File "/home/valdur/arendus/py3status-valdur55/py3status/py3.py", line 1044, in command_output
    raise exceptions.CommandError(

```
**Expected behavior**
Error should not happen

**Comment by lasers** [comment]
It looks like `amixer scontrols` and `amixer -D pulse scontrols` isn't same? I see you got `IEC958` instead of `Master`. Maybe we have to sort or loop through the list to look for `Master` first before grabbing a first one... I can't test anything, but happy to make changes.

**Comment by valdur55** [comment]
Yes, they are different.

```
~ $ amixer -M -c 0 scontrols                                                                                   
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958',1
Simple mixer control 'IEC958',2
Simple mixer control 'IEC958',3
Simple mixer control 'IEC958',4
~ $ amixer -M -c 0 -D pulse scontrols                                                                          
Simple mixer control 'Master',0
Simple mixer control 'Capture',0
```
When looking line
https://github.com/ultrabug/py3status/blob/7f28acb4b7e33ee4681e600f6fc618336fb75b57/py3status/modules/volume_status.py#L123
Adding device and card arguments might be good idea to be in same scope with other commands.

For me, it fixes problem.
I studied refered issue from pr: (#2126)
@jose1711 is it possible that you test my pull request with raspberry PI?

**Comment by valdur55** [comment]
Tested with my Raspberry Pi
```
amixer scontrols
Simple mixer control 'Headphone',0
```

And module loading with default config also worked
