### ISSUE TITLE
weather_owm crashes without onecall subscription.

### ISSUE THREAD

**Issue by clvLabs** [ultrabug/py3status#2156]
**Describe the bug**

Using a free `api key` just generated at `openweathermap.org`, the module just displays the literal `weather_owm` (no weather info).

**Your py3status version**

```
py3status version 3.47 (python 3.8.10) on i3
```

**To Reproduce**

1. Create a free account in [openweathermap.org](https://home.openweathermap.org/users/sign_up).
2. Go to the `API keys` section in your `openweathermap` user profile.
3. Generate a new `API key`.
4. `py3status` config:
    1. Add module `weather_owm`.
    2. Configure module with just the `api_key` you just created:
    ```
    weather_owm {
            api_key = "xxxxxxxxxxxxxxxxxx"
    }
    ```
5. Run `py3status`
6. See result:
    ```json
    {"full_text": "my_weather_owm", "color": "#FF0000", "instance": "", "name": "my_weather_owm"}
    ```

**Expected behavior**

Some weather info should be displayed, maybe something like:
```json
{"full_text": "My town name \u2601 \u25cb 80\u00b0F, scattered clouds ", "instance": " 0", "name": "my_weather_owm"}
```

**Screenshots**

(not necessary in this case).

**Additional context**

(not necessary in this case).

**Comment by lasers** [comment]
>the module just displays the literal weather_owm (no weather info).

It sounds like you ran into error and/or exception. Did you try clicking on it? It may expand with some more information.

**Comment by clvLabs** [comment]
I just tried clicking on the title and it shows `weather_owm: Unauthorized 401`

**Comment by clvLabs** [comment]
Sorry, what I meant with:
> This allows me to have weather_owm working (with no forecast, but working).

is that once the `401` exception is catched and the forecast string kept empty, the rest of the code is working correctly and allows me (or any other user not having an `onecall` account) to display basic weather info.

**Comment by lasers** [comment]
We tend to try not to add try/except in the modules so the modules can report the exceptions, if any, on the bar.

I'm more curious about how this can happen in first place.... and how you're able to trigger this. Does this happen because you reached end of 1,000 free calls (approximately every 1m26.4s) or is it because it's not available in your area?

Module history showed that new onecall api was added this year.

**Comment by ultrabug** [comment]
Hi @clvLabs ; first of all thanks for your time in explaining your experience and even proposing a fix!

The weather_owm API is free to use once registered using a token.
I think it respectful for their work to not try to bypass this netiquette on the usage of their service thus I'm sorry but if you want to use weather owm API, you need to comply with their terms.

Py3status itself won't add tricks to overcome this. I'm closing this issue and PR in the hope that you understand my point, there's nothing to diminish your work and I thank you again for this.

Kindly

**Comment by clvLabs** [comment]
Hi #ultrabug,

First of all, thanks for being so considerate.

I'll try to cover all points:

## About how does this happen
Sorry if I didn't make the full story clear, I'll explain in more detail:

I'm a new user of `py3status` and as I installed it and started configuring it found about the `weather_owm` module and wanted to use it.

I saw I had to create a user account in openweathermap.org to get an API key and got thru it immediately.

Once I had my account created I went to the `API keys` section in my profile and copied the `Default` key to use it in the `api_key` field in my config.

Anyway, `weather_owm` was not working... it kept showing its own name in red instead of the weather info.

That's when I started digging...

The question seems to be that in order to have `weather_owm` working you have to:
* Create an account in openweathermap.org.
* Subscribe to the "One Call by Call" plan.

Maybe what happened in my case was that, as a new user I didn't know about that "OneCall" plan and as soon as I had my openweathemap account and I could get an API key I thought I had it done.

Looking back at the docstring on [the module](https://github.com/ultrabug/py3status/blob/master/py3status/modules/weather_owm.py) I see it says:

> Requires an API key for OpenWeatherMap (OWM), but the free tier allows you
enough requests/sec to get accurate weather even up to the minute.

It also points to https://openweathermap.org/appid for more info.

I could not find anything in these documents to make me think I needed that "OneCall" subscription, so until I could trace the exception it seemed like a bug.

I guess if a new user with less tracing skills finds him/herself in the same situation they just might ignore the module, and being as nice as it is I think it's not fair :)

## About not adding `try/except`
Agree with you on this! When I started the `PR` my intention was to start a discussion on how my lame attempt to fix the problem could be changed to better fit the existing code.

## About the tricks to overcome the registration
If you read the previous points you'll see there's no _mean_ intentions at all in my proposal.

I've registered as requested, and I'm using the API key from my account.

## Maybe I did not explain myself
As far as I can see, with the _regular_ API key you get when you register, you can get the requests to https://api.openweathermap.org/data/2.5/weather working with no problem.

The problem is when you use that same API key on https://api.openweathermap.org/data/2.5/onecall you get the `401`.

When I found about the whole "OneCall" thing and saw that I had to provide my credit card info, I thought _"well, maybe I will do it without the forecast part"_ and decided to stick with just the "today" info of the weather, since it came for free with the API key I already had.

If the information block displayed by the module is built by several requests, the failure of one of them should not invalidate the whole process. That is the basic intent of this issue.

Maybe in a case like this the best solution would be to display all the remaining info and an error indicator in the forecast section, I dont' know the inners of `py3status` that much :)

Or maybe it's just a question of adding this info in the documentation, so new users can't get confused with the _double subscription_ issue.

Anyway... I've tried my existing API key and it turns out it does work on https://api.openweathermap.org/data/2.5/forecast so there's even a way to get forecast info without the "OneCall" subscription. Also, reading the code makes me think that unreferenced `_get_forecast()` was the previous way of getting forecasts.

Maybe it could be possible to have the module first trying to get the forecast from the `onecall` endpoint and if it fails it could retry with the `forecast` endpoint (this way, users with a "OneCall" subscription could get the info from that API).

... or maybe I'm talking too much :) :) :)

Won't bother you much more... 

Thanks for the great work BTW, I'll be using it for a while.

**Comment by lasers** [comment]
Looking into API Error 401. https://openweathermap.org/faq#onecall

>You can get the error 401 in the following cases:
>
>* You did not specify your [API key](https://home.openweathermap.org/api_keys) in API request.
>* Your API key is not activated yet. Within the next couple of hours, it will be activated and ready to use.
>* You are using wrong API key in API request. Please, check your right API key in [personal account](https://home.openweathermap.org/api_keys).
>* You are using a Free subscription and try requesting data available in other subscriptions . For example, [16 days/daily forecast API](https://openweathermap.org/forecast16), [any historical weather data](https://openweathermap.org/price#history),[ Weather maps 2.0](https://openweathermap.org/api/weather-map-2), etc). Please, check your subscription in your [personal account](https://home.openweathermap.org/).

I doubt you're trying to trick anything. Probably just wanting to make it work a little more better/smart.

Things we may want to consider is... if this module right now is a 500-calls-a day because of different requests... and if onecall can fetch everything... we may want to try and move everything over to new onecall 3.0 api.

>If the information block displayed by the module is built by several requests, the failure of one of them should not invalidate the whole process. That is the basic intent of this issue.

I think that's intentional. Otherwise, `weather_owm` keeps working fine with that one missing request. If we do this for all requests and they all came back empty, then the `weather_owm` would keep working fine too with no data...  Personally, it'd be good to update this module to stay with one request. Onecall was added later (see this module commit history).

**Comment by mlmatlock** [comment]
The one request approach would be good; but would probably need some good coding-I'd really hate to see changing to the onecall API, and have my issue `https://github.com/ultrabug/py3status/issues/2106` re-surface.
