### ISSUE TITLE
Undocumented requirement of dateutil

### ISSUE THREAD

**Issue by RasmusRendal** [ultrabug/py3status#2160]
**Describe the bug**
The timewarrior module, amongst others, depend on the dateutil module, but it is not described as a requirement:
https://github.com/ultrabug/py3status/blob/786d1b2f8d9c9196664b3fe60970968af48114e3/py3status/modules/timewarrior.py#L143

https://github.com/ultrabug/py3status/blob/786d1b2f8d9c9196664b3fe60970968af48114e3/py3status/modules/timewarrior.py#L56-L57

**Your py3status version**
I found it here:
```
py3status version 3.43 (python 3.10.4) on i3
``

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):
1. Try to use py3status with timewarrior without dateutil installed. This'll happen on nixos
2. See the error when clicking the timewarrior module on your bar

**Expected behavior**
I expect dateutil to be declared as a requirement for the timewarrior module

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by ultrabug** [comment]
Hello,

Modules dependencies which are listed under the **Requires** docstring should be installed by users.
Py3status couldn't possibly start depending on every module's dependency as you can imagine.

Thanks

**Comment by RasmusRendal** [comment]
> Hello,
> 
> Modules dependencies which are listed under the **Requires** docstring should be installed by users. Py3status couldn't possibly start depending on every module's dependency as you can imagine.
> 
> Thanks

Thanks for clarifying, I fixed the issue :)

**Comment by ultrabug** [comment]
Indeed @RasmusRendal ; would you like to propose a PR to add this to the module's docstring?
