### ISSUE TITLE
Add connexion status in kdeconnector module

### ISSUE THREAD

**Issue by florencebiree** [ultrabug/py3status#2162]
Dear developer,

**Your py3status version**
py3status version 3.47 (python 3.10.8) on sway

**Describe the solution you'd like**
I use kdeconnect and the kdeconnector module of py3status. It allow to display the percentage of battery from my smartphone, but I would like to display also the strength of the signal on the mobile network (from the smartphone). I think it should be possible, since gsconnect on gnome display it on the status bar.

**Comment by ultrabug** [comment]
Hello @florencebiree 

I must admit that I have no knowledge about it or KDE related stuff.

@ritze I see you're the original author of the module so if you're around, would you maybe be willing to help here?

Thanks

**Comment by ritze** [comment]
Hi @florencebiree and @ultrabug,

I don't use kdeconnector anymore. But if gsconnect can display the signal strength of your mobile network, this information should be available via dbus as all the other information which are currently supported by the kdeconnector module.

Theoretically we just need to find out the dbus path for this. It should work the same as [_get_battery()](https://github.com/ultrabug/py3status/blob/master/py3status/modules/kdeconnector.py#L183).

**Comment by ultrabug** [comment]
Thanks @ritze 

@florencebiree if you can provide the given output example, I can try to come up with a patch.

**Comment by florencebiree** [comment]
Maybe having two new variables: `{net_type}` and `{net_quality}`, net_type could be something like E (edge), 3G, 4g, etc… (GSConnect is able to retrieve this information, it must be on the dbus data…), and net_quality a percentage like the `{quality}` variable in the wifi module.

The default display could be something like `{net_type} {net_quality}` (ex: `4G 74%`), added at the end of the actual default format.

**Comment by valdur55** [comment]
Yes, it is possible with newer version. There is plugin called connectivity_report which registers org.kde.kdeconnect.device.connectivity_report path. ( https://invent.kde.org/network/kdeconnect-kde/-/blob/master/plugins/connectivity-report/connectivity_reportplugin.h#L45 )

Currently can't help much more because my home computer's kdeconnect is too old to support this feature. (still using ubuntu 20.04).

**Comment by valdur55** [comment]
I got raw data flowing, but cellularNetworkStrength needs some better output than just a number between 0-4. 
Maybe add some icons like qsconnect: ( https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/80c3d156fbc61c97d3a3a004172f41056d8ff316/src/service/plugins/connectivity_report.js#L65 )
Or use similar logic as volume_control ? ( _▂▄▆█ )

**Comment by ultrabug** [comment]
done by @valdur55 :+1:
