### ISSUE TITLE
The getargspec()  function got removed in Python 3.11

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#2183]
**Describe the bug**

The `getargspec()` function got removed in Python 3.11.

```
❯ grep -Iris 'getargspec'
py3status/autodoc.py:            args, vargs, kw, defaults = inspect.getargspec(item)
build/lib/py3status/module.py:        args, vargs, kw, defaults = inspect.getargspec(method)
build/lib/py3status/autodoc.py:            args, vargs, kw, defaults = inspect.getargspec(item)
```

https://docs.python.org/3.11/whatsnew/3.11.html#removed

> * Removed from the [inspect](https://docs.python.org/3.11/library/inspect.html#module-inspect) module:
>    * The getargspec() function, deprecated since Python 3.0; use [inspect.signature()](https://docs.python.org/3.11/library/inspect.html#inspect.signature) or [inspect.getfullargspec()](https://docs.python.org/3.11/library/inspect.html#inspect.getfullargspec) instead.
>

**Your py3status version**

This issue is for all py3status versions on python 3.11+.

**Comment by lasers** [comment]
Is this old RtD codes that should be removed?

**Comment by ultrabug** [comment]
Indeed, opening PR
