### ISSUE TITLE
py3status not recognising dbus import after PEP668 changes

### ISSUE THREAD

**Issue by MrConorAE** [ultrabug/py3status#2184]
**Describe the bug**
After upgrading pip, the python modules got moved to system package management (with apt). I've installed the `python3-dbus-python` package, which provides the `dbus-python` package, but the `mpris` and `spotify` bar items (and others) no longer recognise the import, resulting in a `ImportError: No module named 'dbus'` in the status bar.

**Your py3status version**
`py3status version 3.50 (python 3.11.2) on i3`

**To Reproduce**
1. Add an affected module, such as `mpris` or `spotify`
2. Have an upgraded pip which enables externally managed environments (see PEP 668)
3. Run py3status
4. Error appears on status bar and module does not function

**Expected behavior**
The `python3-dbus-python` package is installed, which should provide `dbus-python`.

**Additional context**
Due to the changes in PEP 668, pip packages can no longer be installed globally - instead, they must be:
- installed locally, in a venv, using pip, or
- installed globally as applications, using pipx (not an option here, as the `dbus` module is not a directly-runnable command), or
- installed globally as a module, using your system package management (e.g. through apt), reducing package conflicts and eliminating the risk of colliding packages.

Packages can be force-installed globally using the pip flag `--break-system-packages`, but I'd rather avoid this if possible.

**Comment by ultrabug** [comment]
@MrConorAE please try

```bash
sudo apt install libglib2.0-dev libdbus-1-dev 
pip install dbus-python
```

**Comment by phvr** [comment]
I had this same issue with the `xbacklight` module (`py3status 3.54`, after moving to Python 3.11 from 3.10, on Gentoo). I use pipx to run py3status, had to do
```
pipx inject py3status dbus-python
```

Maybe add a DBus implementation to the requirements?

**Comment by ultrabug** [comment]
What do you mean exactly @phvr ? I'm confused

**Comment by lasers** [comment]
@ultrabug I think they're wanting something like this... (Untested).
```diff
diff --git a/requirements/project.txt b/requirements/project.txt
index 1e4cbe9..31eb840 100644
--- a/requirements/project.txt
+++ b/requirements/project.txt
@@ -1 +1,3 @@
 hatch==1.7.0
+dbus-python==1.3.2
+PyGObject==3.46.0
```
And possibly additional requirements for modules... or they can pipx inject those themselves.

**Comment by ultrabug** [comment]
Alright, done
