### ISSUE TITLE
Drop pydbus

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#2192]
**Describe the bug**

1) Modules using pydbus mean py3status can't be used on faster Python3.11
  >Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite.

2) https://github.com/LEW21/pydbus 's last commit was May 6, 2008.... More than 15 years ago.

2) Python 3.11 changed the inspect code.

**Additional context**

Inspect the changed inspect - https://docs.python.org/3.13/whatsnew/3.11.html#removed
```python
❯ git grep -Iri 'inspect'
  pydbus/_inspect3.py:from inspect import getargspec
  pydbus/exitable.py:import inspect
  pydbus/exitable.py:             inspect.getcallargs(cb, exc_type, exc_value, traceback)
  pydbus/proxy_method.py: from inspect import Signature, Parameter
  pydbus/proxy_method.py: from ._inspect3 import Signature, Parameter
  pydbus/registration.py: from inspect import signature, Parameter
  pydbus/registration.py: from ._inspect3 import signature, Parameter
```

**Your py3status version**

This issue is for all py3status versions on python 3.11+.

**Modules**
```python
❯ git grep -Iri 'from pydbus'
  backlight.py:    from pydbus import SystemBus
  kdeconnector.py:from pydbus import SessionBus
  systemd.py:from pydbus import SessionBus, SystemBus
  vpn_status.py:from pydbus import SystemBus
  wwan.py:from pydbus import SystemBus
```

**Comment by lasers** [comment]
I can bring https://github.com/ultrabug/py3status/pull/1554 back to address `systemd` or is it still too much format magic? Lol.

**Comment by lasers** [comment]
@valdur55 can fix kdeconnector.py?

**Comment by valdur55** [comment]
Looks like I have skill to do it, because mpris already uses same target dbus package.
Started with kdeconnector first.
