### ISSUE TITLE
Time modules in group does not update per second

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#222]
Grouped time modules should update per second when used in a group (as it is when they're not grouped)

PS: maybe we could save CPU when no second is requested in the format.

```
group tz {
	cycle = 10
	format = "{output}"

	tztime la {
		format = "LA %H:%M:%S"
		timezone = "America/Los_Angeles"
	}

	tztime ny {
		format = "NY %H:%M:%S"
		timezone = "America/New_York"
	}

	tztime du {
		format = "DU %H:%M:%S"
		timezone = "Asia/Dubai"
	}
}
```

**Comment by tobes** [comment]
This is because i3status modules didn't know about the groups they were in.

I have a fix for this based on the speedy branch.  It moves the group update trigger from `Module.run()` into `Core.notify_update()` so both py3/i3s modules trigger updates

**Comment by tobes** [comment]
commit is here if you wanted to see it https://github.com/tobes/py3status/commit/e775ceda37f1f8152e6238ff66e0c10ad1f8c9ed

**Comment by tobes** [comment]
> PS: maybe we could save CPU when no second is requested in the format.

I might add that in the #221 fix

**Comment by ultrabug** [comment]
merged, :heart:
