### ISSUE TITLE
Manually determine output order of lm_sensors

### ISSUE THREAD

**Issue by mlmatlock** [ultrabug/py3status#2224]
**How can we help you today?**
Trying to get a more ordered output of lm_sensors

**Your py3status version**
py3status version 3.54 (python 3.11.6) on sway

**Share your configuration**
[sensors -u](https://0x0.st/HEXs.txt)

Module config:
```
lm_sensors {
    format_chip = '[\?if=name=drivetemp-scsi-0-0 sda: ]'
    format_chip += '[\?if=name=drivetemp-scsi-2-0 sdb: ]'
    format_chip += '[\?if=name=drivetemp-scsi-4-0 sdc: ]'
    format_chip += '{format_sensor}'
    format_sensor = '[\?if=name=motherboard MoBo: ]'
    format_sensor += '[\?if=name=cpu CPU: ]'
    format_sensor += '[\?if=name=edge GPU: ]'
    format_sensor += '[\?if=name=composite NVMe: ]'
    format_sensor += '[\?color=auto.input {input}°C]'
    sensors = ['composite', 'edge', 'motherboard', 'cpu', 'samsung*', 'hitachi*', 'input']
    }
```

**Additional context**
The output is taken straight down the sensor list

![20231227_09h28m01s_grim](https://github.com/ultrabug/py3status/assets/42914546/f9c19511-0106-4f8d-8993-be5f68713cf7)

Would really like to sort the output.

@lasers, tagging you as the module author.  :)

**Comment by lasers** [comment]
Can we get your `sensors -j` too? Yeah, I can see how that's annoying.

**Comment by mlmatlock** [comment]
Here you go:

[sensors -j](https://0x0.st/HE84.json)

**Comment by lasers** [comment]
You likely can run `lm_sensors` module twice. First one for sda stuff. Second one for other stuff. That's the current solution right now. I'll look into this issue in the future.

**Comment by lasers** [comment]
Try specifying ordered chips in `chips = []`. See if that works. (Untested)

**Comment by mlmatlock** [comment]
> You likely can run `lm_sensors` module twice. First one for sda stuff. Second one for other stuff. That's the current solution right now. 

This is what I started with:
```
 lm_sensors {
    format_chip = '{format_sensor}'
    format_sensor = '[\?if=name=motherboard MoBo: ]'
    format_sensor += '[\?if=name=cpu CPU: ]'
    format_sensor += '[\?if=name=edge GPU: ]'
    format_sensor += '[\?if=name=composite NVMe: ]'
    format_sensor += '[\?color=auto.input {input:.0f}°C]'
    sensors = ['composite', 'edge', 'motherboard', 'cpu']
    }
    lm_sensors {
    format_chip = '[\?if=name=drivetemp-scsi-0-0 sda: ]'
    format_chip += '[\?if=name=drivetemp-scsi-2-0 sdb: ]'
    format_chip += '[\?if=name=drivetemp-scsi-4-0 sdc: ]'
    format_chip += '{format_sensor}'
    format_sensor = '[\?color=auto.input {input}°C]'
    sensors = ['samsung*', 'hitachi*', 'input']
    }
```
![20231227_17h20m21s_grim](https://github.com/ultrabug/py3status/assets/42914546/df3c92b2-6bb2-48d4-8eb4-3a736a955dbb)

Was trying for colorized output for all temps.

**Comment by lasers** [comment]
It sounds like you got bit by https://github.com/ultrabug/py3status/issues/1927 if using multiple instances.

What about specifying ordered chips (comment above)?

**Comment by mlmatlock** [comment]
> It sounds like you got bit by #1927 if using multiple instances.
> 
> What about specifying ordered chips (comment above)? EDIT: Scratch that. It looks like `sensors -j` doesn't output correctly with chips if specified more than one. `ISSUE: https://github.com/lm-sensors/lm-sensors/issues/372`

Yeah, #1927 is me.

Wondering if the JSON output could be sorted by sensor?

**Comment by lasers** [comment]
>Wondering if the JSON output could be sorted by sensor?

It already does. It just didn't come out right. I made a PR. Talk there.

**Comment by ultrabug** [comment]
Version 3.55 is out!

**Comment by MacGyverNL** [comment]
Has this regressed? I'm on 3.62 and although
```
chips = ['coretemp-isa-0000 amdgpu-pci-1700 amdgpu-pci-6700 nct6798-isa-0290 nvme-pci-0200 nvme-pci-b400']
```
works to filter out unwanted sensors, 
```
chips = ['coretemp-isa-0000', 'amdgpu-pci-1700', 'amdgpu-pci-6700', 'nct6798-isa-0290', 'nvme-pci-0200', 'nvme-pci-b400']
```
fails with `Instance `lm_sensors`, user method `lm_sensors` failed.`

Judicious use of `self.py3.log` has led me to conclude that the curly-brace-insertion code doesn't actually insert any braces, because the chunk *already starts and ends* with `{` and `}`, but the first chunk's braces are now **unbalanced** due to split removing the last one in the chunk, crashing out of `_get_lm_sensors_data` with a `ValueError` / `JSONDecodeError` when `loads` tries to process it.

Example sensors -j output:
```
sensors -j amdgpu-pci-1700 amdgpu-pci-6700

{"amdgpu-pci-1700":{"Adapter":"PCI adapter","vddgfx":{"in0_input":0.875000},"fan1":{"fan1_input":1145.000000,"fan1_min":900.000000,"fan1_max":4200.000000},"edge":{"temp1_input":56.000000,"temp1_crit":97.000000,"temp1_crit_hyst":-273.150000},"PPT":{"power1_input":11.105000,"power1_cap":35.000000},"pwm1":{"pwm1":24.500000,"pwm1_enable":2.000000},"sclk":{"freq1_input":582930000.000000},"mclk":{"freq2_input":1500000000.000000}}}
{"amdgpu-pci-6700":{"Adapter":"PCI adapter","vddgfx":{"in0_input":0.006000},"fan1":{"fan1_input":0.000000,"fan1_min":0.000000,"fan1_max":3100.000000},"edge":{"temp1_input":37.000000,"temp1_crit":100.000000,"temp1_crit_hyst":-273.150000,"temp1_emergency":105.000000},"junction":{"temp2_input":41.000000,"temp2_crit":110.000000,"temp2_crit_hyst":-273.150000,"temp2_emergency":115.000000},"mem":{"temp3_input":38.000000,"temp3_crit":100.000000,"temp3_crit_hyst":-273.150000,"temp3_emergency":105.000000},"PPT":{"power1_average":6.000000,"power1_cap":264.000000},"pwm1":{"pwm1":0.000000,"pwm1_enable":2.000000},"sclk":{"freq1_input":0.000000},"mclk":{"freq2_input":96000000.000000}}}
```

Resulting first chunk in `_get_lm_sensors_data(self)`:
```
{"amdgpu-pci-1700":{"Adapter":"PCI adapter","vddgfx":{"in0_input":0.875000},"fan1":{"fan1_input":1146.000000,"fan1_min":900.000000,"fan1_max":4200.000000},"edge":{"temp1_input":55.000000,"temp1_crit":97.000000,"temp1_crit_hyst":-273.150000},"PPT":{"power1_input":10.210000,"power1_cap":35.000000},"pwm1":{"pwm1":24.500000,"pwm1_enable":2.000000},"sclk":{"freq1_input":255320000.000000},"mclk":{"freq2_input":1500000000.000000}}
```

Changing from `output.strip().split("}\n{")` to `output.strip().split("\n")` makes everything start working, but of course this feels rather fragile. Is there a better way to "repair" this json, short of outright catching `loads` ValueErrors, counting the opening and closing braces, then inserting that many at start / end?
