### ISSUE TITLE
Click on parts of external_script module output

### ISSUE THREAD

**Issue by syyyr** [ultrabug/py3status#2243]
**How can we help you today?**
Hi, I have this kind of a `external_script` module:
![image](https://github.com/ultrabug/py3status/assets/17759291/89fd6df3-3cd0-4a08-94ec-67eefbeaf062)
It basically just shows which packages from the aur should be updated. Now, I thought it'd be handy if I could click on the package, and it'd open the AUR page for it. Right now, I think it is possible to assign a script to `on_click` and even pass the output of the module to it, but there's no way to know which part of the output was clicked. I see that there's a "composite" module feature, which when clicked exports the `OUTPUT_PART` variable to the script, but I found no way to output a composite module from an `external_script`. Is this something like this doable in _py3status_? Could it be implemented?

Thanks.

**Your py3status version**
```
$ py3status -v
py3status version 3.56 (python 3.11.8) on i3
```

**Comment by lasers** [comment]
Additional information requested.

* What kind of `external_script` module is this?
* What does your config look like with this module?
* Et cetera.

It may be easier to write a new/custom module based on this kind of output instead.

**Comment by syyyr** [comment]
>What kind of external_script module is this?

I have a script that is able to print out available updates. It looks like this: https://github.com/syyyr/home-repo/blob/main/apps/py3status-aur.bash

>What does your config look like with this module?

The config currently looks like this:
```
external_script updates {
    cache_timeout = 3600
    markup = 'pango'
    script_path = '$HOME/apps/py3status-aur.bash updates'
}

external_script out-of-date {
    cache_timeout = 3600
    markup = 'pango'
    script_path = '$HOME/apps/py3status-aur.bash out-of-date'
}
```
The full config is here: https://github.com/syyyr/home-repo/blob/main/.config/i3status/config

>It may be easier to write a new/custom module based on this kind of output instead.

I'd say it is possible to write my own module for this, and AFAIK, I could make it clickable the way I want. However, it has some disadvantages. I wouldn't like to rewrite my simple script to Python, since it's such a simple one. But if I did, I probably couldn't contribute it to the repo, because it seems to me that it's such a niche. Although, there already is a script for Arch updates, so maybe it could be extended? I'm not sure.

Considering all this, I figured it would be nice, if I make my `external_script` module into a composite module, or detect what part of the output has been clicked. But maybe that is something that can't be easily supported by py3status, or maybe it doesn't make sense.

**Comment by syyyr** [comment]
>Is this for external_script out-of-date only?

No, it's mainly for `external_script updates`. My usecase: right now, I have an update available for mingw-w64-gettext, but unfortunately it doesn't build. When I package can't be built, I usually go to the associated AUR page, because sometimes people put fixes for build failures. I'd like to have a shortcut for this AUR page directly on my AUR updates module.

>What does aur-out-of-date -user syyyr -json looks like? I think we can work with this one.

Like I said, it's not mainly for the out-of-update script, but here it is:
```
$ aur-out-of-date -user syyyr -json
{"type":"package","name":"mingw-w64-doctest","message":"matches upstream version 2.4.11","version":"2.4.11-1","upstream":"v2.4.11","status":"UP-TO-DATE"}
{"type":"package","name":"mingw-w64-marisa","message":"matches upstream version 0.2.6","version":"0.2.6-1","upstream":"v0.2.6","status":"UP-TO-DATE"}
{"type":"package","name":"mingw-w64-trompeloeil","message":"matches upstream version 47","version":"47-1","upstream":"v47","status":"UP-TO-DATE"}
{"type":"package","name":"qt5-opcua","message":"No release found for git+https://code.qt.io/qt/qtopcua.git#branch=5.15.2","version":"5.15.2-1","status":"UNKNOWN"}
```
This could probably be added in some way to the `arch_updates`, but as of now, `arch_updates` doesn't allow for a format I want, so that's why I went with the script. Although it can use `auracle`, which is what I use in my own script.

**Comment by lasers** [comment]
Can you try this? https://github.com/lasers/py3status/tree/newmodule-json_lines

**Comment by syyyr** [comment]
The `qt5-opcua` is missing the `upstream` field, because field, because the json output doesn't have that, but I guess that can be easily fixable by either not outputting filtering that int he command, or via some clever usage of py3status format string.

**Comment by lasers** [comment]
>rewrite my script so that outputs a JSON instead of HTML. Tbh I'd rather do formatting inside the py3status config, instead of writing HTML in the script.

Just one thing. This prints json per line (package), not a list of JSON objects.
You can filter in this script or via py3status formatter.

>via some clever usage of py3status format string.

This should work... as long as the value doesn't contain a space or such.

```diff
-    format_json = "[\?color=lightblue {name}] [\?color=red {version}] [\?color=lightgrey&show ->] [\?color=lime {upstream}]"
+    format_json = "[\if=status=UP-TO-DATE [\?color=lightblue {name}] [\?color=red {version}] [\?color=lightgrey&show ->] [\?color=lime {upstream}]
```

**Comment by syyyr** [comment]
>Just one thing. This prints json per line (package), not a list of JSON objects.
You can filter in this script or via py3status formatter.

Yep, I'm aware of that :) hence "json_lines"

>This should work... as long as the value doesn't contain a space or such.

Yeah... well, to be honest, I'd probably just assure that the script outputs what should be printed. I'm not a big fan of the py3status format string.

>EDIT: Another way of filtering... Make it shell=True in command_output and add | grep UP-TO-DATE in your command.

Yeah, that's what I would probably do. Or just create a script of my own and exec that. Do you plan on making this module more AUR oriented? Now that I think of it, it could probably be just kind of merged into external_script as a different type of "mode". As in, allow external_script to output its output in a more structured way for py3status. Although I understand that you'd prefer people to write their own modules.

**Comment by syyyr** [comment]
Also, for my specific usecase, I could just have an "external_script_lines" module, and it would do the job for me.

**Comment by lasers** [comment]
I'm not planning on doing anything with `json_lines` because `aur-out-of-date -json` is invalid JSON.

I don't think a flag is needed for `external_script`... Just that external_script should be able to deal with multi-line output...   `format = "{format_line}"` and format_line... stuff. Most users would be targeting one-liner output anyway.

This would need `external_script` to rename `format` config to `format_line` at most.

**Comment by syyyr** [comment]
>I don't think a flag is needed for external_script... Just that external_script should be able to deal with multi-line output... format = "{format_line}" and format_line... stuff. Most users would be targeting one-liner output anyway.

If `external_script` could deal with multiple lines and be able to differentiate which line was clicked, I'd be most satisfied.

Thank you for looking into this by the way.

**Comment by lasers** [comment]
Maybe this work...

```diff
diff --git a/py3status/modules/external_script.py b/py3status/modules/external_script.py
index f103c95..64bf6a4 100644
--- a/py3status/modules/external_script.py
+++ b/py3status/modules/external_script.py
@@ -105,7 +105,7 @@ class Py3status:
             output = ""
 
         response["full_text"] = self.py3.safe_format(
-            self.format, {"output": output, "lines": len(output_lines)}
+            self.format, {"output": self.py3.safe_format(output), "lines": len(output_lines)}
         )
         return response
 
```
and you use `make_py3status` function that outputs this.

> echo "[\?color=lightblue&show $NAME] [\?color=red&show $OLD] ..."

**Comment by syyyr** [comment]
That would definitely help me remove the need to format stuff myself through HTML. I would just need the inidividual `[...]` to be clickable. Or is that already the case? I haven't tested.

**Comment by lasers** [comment]
I assume `$OUTPUT_PART` would be (package) `{name}` because of different colorized composites. If you don't colorize anything, then I think you you would be getting one whole thing (maybe just non-composite text, I don't recall).

It should be possible to make whole thing `[...]` clickable with custom `aur-out-of-date` module no matter what format you give it... This is just what I think may make this work with `external_script`.

**Comment by syyyr** [comment]
Okay, I didn't realize that number 3 can just be solved with your patch, and that `safe_format` already splits stuff into composites. So, if the patch from here https://github.com/ultrabug/py3status/issues/2243#issuecomment-2031034606 makes it into `external_script`, that would be enough for me.

**Comment by lasers** [comment]
> Even if I print the format string like this:

You can use `[\?soft  ]` or just a space `' '` instead of `[\?color=black&show  ]`.

**Comment by syyyr** [comment]
Hi. For the past two months I've been using:
1) the patch that adds `self.py3.safe_format` to _external_scripts_
2) this patch https://github.com/ultrabug/py3status/pull/2245

with great success.

My config currently looks like this:

```python
external_script updates {
    cache_timeout = 3600
    script_path = '$HOME/apps/py3status-aur.bash updates'
    on_click 1 = 'exec pacman -Q $OUTPUT_PART && google-chrome-stable https://aur.archlinux.org/packages/$OUTPUT_PART'
}

external_script out-of-date {
    cache_timeout = 3600
    script_path = '$HOME/apps/py3status-aur.bash out-of-date'
}
```
and the _py3status-aur.bash_ script is this: https://github.com/syyyr/home-repo/blob/main/apps/py3status-aur.bash but basically, it's a script that outputs a AUR updates in the format I want.

Clicking the individual parts in the string works flawlessly, and really helps me lookup issues in AUR packages (for example, if the package fails to build).

**Comment by lasers** [comment]
Added `[if=$NEW ...]` untested example to illustrate how the `lightgrey` dash can be skipped due to empty upstream in case you're not familiar with the formatter.
```bash
echo "[\?color=lightblue&show $NAME] [\?color=red&show $OLD][\?if=$NEW  [\?color=lightgrey&show -] [\?color=lime&show $NEW]]"
```
>Clicking the individual parts in the string works flawlessly, and really helps me lookup issues in AUR packages (for example, if the package fails to build).

👍

**Comment by ultrabug** [comment]
thx got both in for the next release!

**Comment by jumperfly** [comment]
Hi, I'd first just like to say thanks for contributing this project.  I've been using it for some time and it generally works great.

Unfortunately, as a side effect, this change has caused issues referencing `output` when overriding `format`.

For example, consider a script, `example.sh`:
```bash
#!/usr/bin/env bash
echo abc
```

Previously, the following configuration could be used:
```
external_script example {
  format = "[\?if=output=abc YES|NO]"
  script_path = "~/example.sh"
}
```

The above now returns `NO` but I would expect `YES` to be returned.  I believe due to the fact output is now a composite, rather than a string so the comparison always fails.
