### ISSUE TITLE
Mpris module reports wrong player identity with kdeconnect interface

### ISSUE THREAD

**Issue by valdur55** [ultrabug/py3status#2252]
**Describe the bug**
I noticed that mpris module reports wrong mediaplayer playing in the mobile. 

**Your py3status version**
py3status version 3.58 (python 3.12.4) on sway

**To Reproduce**
1. Install and configure kdeconnector
2. Enable kdeconnector module
3. Play media
4. Change media player

**Expected behavior**
Media player identity (name) should change.

**Comment by ultrabug** [comment]
closed via #2251 thanks!
