### ISSUE TITLE
modules/bluetooth.py:103: SyntaxWarning: invalid escape sequence '\?'

### ISSUE THREAD

**Issue by sdelafond** [ultrabug/py3status#2268]
**Describe the bug**
modules/bluetooth.py:103: SyntaxWarning: invalid escape sequence '\?', at least with python 3.12.

**Your py3status version**
py3status version 3.59 (python 3.12.6) on sway

**To Reproduce**
```# python3.12 /usr/lib/python3/dist-packages/py3status/modules/bluetooth.py
/usr/lib/python3/dist-packages/py3status/modules/bluetooth.py:103: SyntaxWarning: invalid escape sequence '\?'
  format_device = "\?if=connected&color=connected {alias}"```

This is Debian bug #1082501 (https://bugs.debian.org/1082501).

**Comment by ultrabug** [comment]
@sdelafond proposed fix for all modules and this debian bug : https://github.com/ultrabug/py3status/pull/2274

**Comment by sdelafond** [comment]
Thanks a lot, I just uploaded 3.61 to Debian unstable.
