### ISSUE TITLE
Yahoo Weather plugin broken since OAuth change

### ISSUE THREAD

**Issue by DasEarl** [ultrabug/py3status#228]
I don't know if someone mentioned this earlier but Yahoo changed to OAuth 1 now which breaks the current module.

https://developer.yahoo.com/weather/

**Comment by tobes** [comment]
I've seen problems with this too. Oddly it seems to be intermittent and sometimes public access works.

It'll be a pain if every user has to register and get an API key but that looks like the only way.

Are there any alternatives?  I had a look but all the ones I found also need signing up too.

**Comment by pydsigner** [comment]
I did not find anything not using OAuth or API keys either.

**Comment by tobes** [comment]
The best I've found is a 3 day forecast on the bbc getting the 'code' is a bit of a pain I'm assumming there is no geo locking 

eg http://open.live.bbc.co.uk/weather/feeds/en/524901/3dayforecast.rss

doesn't help with weather yahoo but here for info

**Comment by MobileAZN** [comment]
The API changed again yesterday.

https://developer.yahoo.com/weather/

**Comment by ultrabug** [comment]
Thanks @MobileAZN ! This is now working again.

Note: you have to switch your config to use the `woeid` setting from now on.
