### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#232]
I was thinking about adding a bit of documentation.  I was going to start with module docstring guidelines.

Currently there is some info in the `README.md`, a  `doc` directory containing `py3status.html`, the `wiki`, and propossed `CONTRIBUTING.md` in #195

Personally my preference would be to have `*.md` files in `/doc` the reasons for this is

* Easy to update for existing contributers (no need to clone the wiki etc) and can be updated with code PRs

* Displays nicely on github

* Is versioned with releases etc

@ultrabug where do you think is the best place for such stuff?

**Comment by cornerman** [comment]
Good idea! I would definitely be in favor of having a ```doc/``` directory in the repo, so PRs can already contain proper documentation for new features. Also github does not give a nice interface for handling PRs on wikis.

**Comment by tobes** [comment]
@ultrabug any thoughts on this yet?  I realise that sometimes things need to be pondered on for a while, so no rush.

**Comment by ultrabug** [comment]
I agree yes, what is the target layout of files in doc/ then ?

**Comment by tobes** [comment]
Keep it simple

```
docs/
    README.md  -- intro & index
    contributing.md
    custom_modules.md
    ...
```

I think for now that would be fine if it gets too big we can look at it again

**Comment by ultrabug** [comment]
Wouldn't a single README.md (which is displayed by default) with sections in it be better and more accessible ?

**Comment by tobes** [comment]
Personally I'd prefer them split, but a single one would be a start.

They can all be linked so they would be easily accessible (at least on github)

**Comment by ultrabug** [comment]
Let's start with one please, who's up for it ?

**Comment by tobes** [comment]
maybe we should split it into sections (on the single page) and get a few of us involved.

@Horgix maybe you want to move #195 (contributing) into this.

I'd be happy to do a creating modules with docstrings and formats (that migh take a while to get agreement)

what other sections do we need?
