### ISSUE TITLE
"killall -s USR1 py3status" does nothing

### ISSUE THREAD

**Issue by neutronst4r** [ultrabug/py3status#241]
I am trying to include the send signal into my script that lowers and raises the volume. I am using the module volume_status.py. The change in volume works but sending the signal does not refresh the statusbar.

example  command:
`pactl set-sink-volume $(pactl list short sinks|grep RUNNING|awk '{print $1}') -5%`
`killall -s USR1 py3status`

i3config:
`order += "volume_status"`
`volume_status {`
`	   format = "Vol.: {percentage}%"`
`	   format_muted = "Vol: mute"`
`	   device = "pulse"`
`}`

The bar only refreshes after the default 10sec. It is like py3status is completely ignoring the signal. Unfortunately, I don't know how to trace this. Could you please help me out?

**Comment by tobes** [comment]
I think the reason is because run() needs calling on the module for it to update.

See if changing here https://github.com/ultrabug/py3status/blob/master/py3status/core.py#L329 fixes things

```
    def clear_modules_cache(self):
        """
        For every module, reset the 'cached_until' of all its methods.
        """
        for module in self.modules.values():
            module.clear_cache()
```

change to

```
    def clear_modules_cache(self):
        """
        For every module, reset the 'cached_until' of all its methods.
        """
        for module in self.modules.values():
            module.clear_cache()
            module.run()
```

It's not the best place to fix the issue but should  show what's needed

**Comment by ultrabug** [comment]
Thanks for reporting @neutronst4r 

@tobes : wouldn't run() here be blocking py3status until all modules refreshed ?

**Comment by tobes** [comment]
> wouldn't run() here be blocking py3status until all modules refreshed ?

Good question.

I think we need a method that just sets a timer for the modules run().  I'll have a think of a nice solution and do some testing.
