### ISSUE TITLE
battery_level is not shown

### ISSUE THREAD

**Issue by MaxNoe** [ultrabug/py3status#258]
The `battery_level` module does not work for me.

With this `.i3status.conf`
```
general {
        output_format = "i3bar"
        colors = true
        interval = 5
}

order += "battery_level"

battery_level {
	format = "{status} {icon}"
}

```

I get the error: `your 'order' array is empty`

**Comment by tobes** [comment]
Thanks for reporting this.

There are a couple of issues:

first

```
format = "{status} {icon}"
```

`{status}` is not a valid placeholder see https://github.com/ultrabug/py3status/tree/master/py3status/modules#battery_level

>Format of status string placeholders:

>    {ascii_bar} - a string of ascii characters representing the battery level, an alternative visualization to '{icon}' option
    {icon} - a character representing the battery level, as defined by the 'blocks' and 'charging_character' parameters
    {percent} - the remaining battery percentage (previously '{}')
    {time_remaining} - the remaining time until the battery is empty

Second it seems that currently py3status needs either at least one i3status module in the config, or to be run with the `-s` option so in the i3 config 
```
status_command py3status -s -c ~/.i3/i3status.conf
```

Looks like you are running py3status version 2.9 but the issue exists in master too.

**Comment by MaxNoe** [comment]
Ok, i added an ethernet i3status, to get rid of  the empty array error and changed the `battery_level` config to just '{icon}'

There is still nothing shown for the battery. This is the json output of `py3status`.  My version is the latest version on PyPi.

```{json}
{"version": 1, "click_events": true}
[
[
    {"name":"ethernet","instance":"eth0","color":"#FF0000","markup":"none","full_text":"E"}
],
[
    {"markup": "none", "color": "#FF0000", "name": "ethernet", "instance": "eth0", "full_text": "E"},
    {"name": "battery_level", "full_text": ""}
]
```
```

**Comment by tobes** [comment]
Interesting,

That is some sort of python2 unicode issue.  If it was running under python3 you should get the actual icon.

So for now you need to either run it under python3, set `blocks` to some non-unicode chars, or just not use the `{icon}`

So that at least 2 new bugs you've uncovered.

**Comment by MaxNoe** [comment]
it runs under python3, python 3.5.1 to be exact

**Comment by MaxNoe** [comment]
The values is also empty when I just  use something like `format = "Hello World"`.

However, running the module manually with

```
python battery_level.py
```
works fine.

**Comment by tobes** [comment]
> The values is also empty

the initial `full_text` is `""` but subsequent ones appear to work fine for me.

```

general {
        output_format = "i3bar"
        colors = true
        interval = 5
}


order += "battery_level"
order += "ipv6"


battery_level {
    format = "hello world"
}
```

```
{"click_events": true, "version": 1}
[
[{"name":"ipv6","color":"#FF0000","full_text":"no IPv6"}]
,[{"name": "battery_level", "full_text": ""}, {"color": "#FF0000", "name": "ipv6", "full_text": "no IPv6"}]
,[{"color": "#00FF00", "instance": "", "name": "battery_level", "full_text": "hello world", "cached_until": 1460307666.351128}, {"color": "#FF0000", "name": "ipv6", "full_text": "no IPv6"}]
```

**Comment by MaxNoe** [comment]
Mhh, I don't know what I did wrong. Works now.

**Comment by MaxNoe** [comment]
Thanks for your help!

**Comment by ultrabug** [comment]
Thx for the report and nice debug guys, I guess this module still needs some py2 care
