### ISSUE TITLE
Module Proliferation

### ISSUE THREAD

**Issue by pydsigner** [ultrabug/py3status#285]
Py3status is accumulating quite an impressive collection of modules, which is great — we have a vibrant community around this project. However, I'm beginning to wonder if we should identify a more limited group of core modules and split others off into a pystatus-modules-extra package or something similar.

**Comment by tobes** [comment]
Would you keep them in tree (as in part of this repo) and package separately on pypi?  Or are you suggesting more of a split than that?

We also have some duplicates like `window_title` and `window_title_async`.

**Comment by pydsigner** [comment]
@tobes I think it'd probably make the most sense for them to be separate repos.

**Comment by cornerman** [comment]
@tobes there are some duplicate modules (scratchpad and window_title), because they use different ipc libraries (https://github.com/acrisci/i3ipc-python and https://github.com/ziberna/i3-py). The latter seems to be unmainted and does not support all event types (also see https://github.com/ultrabug/py3status/pull/135). Might be a good idea to deprecate the old ones?

**Comment by tobes** [comment]
> separate repos

I think this can make it hard to keep everything in sync as the user may use old py3status with new modules etc.  Having them updated at the same time is helpful for allowing us to change stuff.  Yes we should have a stable api but if we rely on new features eg py3 learns new tricks, it could bite us.

> The latter seems to be unmaintained ... Might be a good idea to deprecate the old ones?

I agree but breaking things for users is nasty. Maybe we can notify them that they should switch for a few releases, just try to not make it too annoying.

@ultrabug seems to like things not breaking for users and I'm inclined that way myself.

**Comment by pydsigner** [comment]
@tobes I think mainly the issue would be with packaging, as anyone going straight to git should be able to keep them in sync, while packages have means to ensure correct versioning. Perhaps though this is not as easy on Arch?

**Comment by tobes** [comment]
@pydsigner I'd like to think that keeping things in sync is easy, but bitter experience tells me even git sub-modules are very hard.

I think keeping the vibrant community is about low barriers to entry.  I'd be happy with a core (true and tested) lot of modules and a more experimental (here are some more) but that creates a whole bunch of issues. How do we decide on which is which?  What if we want to move one?

I'm not saying I disagree with your sentiment, it is very valid.  I'm just not sure it is an easy issue to solve.  I think a graceful  way to depreciate modules (or their defaults) would be good.  Having them all in tree has advantages, if nothing else I can grep them all.  If they are out of tree will I even know they exist or care about them?

Thankfully I've not been directly involved with packaging anything for a several years, but dependency conflicts kept me awake at night when I did.  We should probably deal with issues like running in a virtual env long before breaking ourself into more than one module.

**Comment by ultrabug** [comment]
I realise I never discussed this topic and I'm sorry about that.

My point of view for now is to remain as it is:
- I like the low entry barrier and the fact that a lot of contributed modules come from first timers to PR (I treasure it tbh) and I'm ready to accept different modules' maturity in the code base to preserve that
- As a packager, I would dislike having to keep two separate packages for a such small project.

Would you guys agree for a stall on this matter for the time being ?

**Comment by pydsigner** [comment]
@ultrabug That's fine.
