### ISSUE TITLE
no module named 'py3status.modules.fedora_updates'

### ISSUE THREAD

**Issue by OfficerHalf** [ultrabug/py3status#286]
Not sure if this is a Fedora package issue or a py3status issue. With v2.9 (from F23 updates-testing, actually packaged for python3 now), trying to add the fedora_updates module fails, and the nagbar gives the error in the title.

I'm submitting here first - it seems somewhat unlikely that the Fedora package would be missing the only Fedora specific module, but stranger things have happened. If it's a Fedora problem, I'll submit a bug there.

**Comment by jakubjedelsky** [comment]
Hi,

fedora maintainer here, thanks for submitting the issue. I didn't test the
module. I'll check it tomorrow (haven't my laptop today) and send some
update here.

so 23. 4. 2016 v 7:40 odesílatel Nathan <notifications@github.com> napsal:

**Comment by tobes** [comment]
@OfficerHalf fedora_updates was only added recently and will be available in the next release.

**Comment by jakubjedelsky** [comment]
fair enough.

@OfficerHalf I like that module, I'll add it to new build of package

**Comment by ultrabug** [comment]
Closing, hopefully 3.0 will be released soon :)
