### ISSUE TITLE
wish list

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#29]
* add some -v parameter to see the version (**done in v1.5**)

**Comment by ultrabug** [comment]
Friendly ping @t0m5k1 to let you know that what we've talked about here came true with py3status 2 released a few days ago.

**Comment by t0m5k1** [comment]
:O ooooh that is nice, I just checked.
will have to implement this.
thanks again

**Comment by guiniol** [comment]
Allow modules to change the output of other modules. For example, we could use the standard net_rate module and then have a color_output module which could be configured to change the color of the net_rate output depending on the traffic speed. This would be better than copying and modifying the net_rate module because the net_rate module could be updated without having to re-copy and re-modify it. The color_output module could also be distributed with py3status, and configured in i3status.conf.

**Comment by t0m5k1** [comment]
that would be handy as a separate request guiniol

**Comment by guiniol** [comment]
@t0m5k1 The way I understood it, this is a wish list thread, that's why I put it there. However, I do agree that it would be easier to track if there were one request per issue.

**Comment by ultrabug** [comment]
You're right guys, sorry @guiniol (it's me who asked him to put it here). Feel free to open a new one for this if you feel like it, else I won't forget it here anyways ;)

**Comment by guiniol** [comment]
@ultrabug Either we put one request per issue, or we put all requests in this issue, it's up to you and how you are used to working.

**Comment by ultrabug** [comment]
Let's keep this here for now, I'll split on the next one and close this one then. Cheers mates.

**Comment by habash1986** [comment]
that's should be simple, add the swaps status to the Sysdata model.

**Comment by vandr0iy** [comment]
Probably it may not be easy to implement, but could it be possible to change panel background for every plugin? I wished to make something like
https://camo.githubusercontent.com/8653749fc1a61456f6e498c5cac6f0befe1f7db6/687474703a2f2f646f7473686172652e69742f7075626c69632f696d616765732f75706c6f6164732f3634392e706e67
(powerline-style bar with every element colored differently)
but with your bar's features @ultrabug

**Comment by ultrabug** [comment]
@vandr0iy it is indeed a great idea. Unfortunately, py3status is not responsible for rendering the bar itself and thus respects the i3bar protocol : http://i3wm.org/docs/i3bar-protocol.html

AFAIK the i3bar protocol does not support background color per module, so maybe you could ask them for it and then it will be directly available through py3status ;)

Sorry I can't do more about it.

**Comment by ultrabug** [comment]
I'm closing my oldest issue, it makes no sense any more.
