### ISSUE TITLE
Default Color

### ISSUE THREAD

**Issue by OfficerHalf** [ultrabug/py3status#322]
The config (and i3status) allows for three colors: color_good, color_bad, color_degraded. However, some default modules (TzTime and Disk, for example) have a _fourth_ color (white, by default).

You can set that color not in i3status.conf, but [in the main i3 config file](http://unix.stackexchange.com/questions/131778/how-do-you-change-the-color-for-all-the-items-in-the-status-bar-in-the-i3-wm) with the statusline color setting - though that seems to be absent from the official docs. We can use this color by omitting the color key of the response dictionary or setting it to None, but this seems less than ideal.

I'm not sure how, but I'd like some way to do one of the following:
1. Explicitly use the color as defined in the main i3 config
2. Define a default color in i3status.conf and use it in modules

Or state clearly in the docs somewhere how to use the color.

**Comment by tobes** [comment]
https://github.com/ultrabug/py3status/pull/279 adds color as an option to all modues

**Comment by OfficerHalf** [comment]
Aha, so just passing 'color' is the default?

**Comment by tobes** [comment]
Color options are now in master and will be in the 3.1 release. 

Documentation https://github.com/ultrabug/py3status/blob/master/doc/README.md#configuring_color
