### ISSUE TITLE
Separator in Pomodoro Module

### ISSUE THREAD

**Issue by ben-e-whitney** [ultrabug/py3status#332]
The `pomodoro` module uses a hyphen as a separator between the minutes and seconds left in a timer. The documentation contradicts itself, saying in one place that a hyphen is used and in another that a colon is used. I think a colon makes more sense here. Should I submit a PR changing the default behavior, or maybe instead add a parameter allowing the user to choose the separator?

**Comment by tobes** [comment]
https://github.com/ultrabug/py3status/pull/330 adds a `format_separator` and is just merged.

The documentation could probably do with a tweak

**Comment by pydsigner** [comment]
I think that the default should change here, if anyone actually prefers the old behavior, which I think unlikely, they are now able to get it back. It's even possible that the original hyphen was a typo IMO.

**Comment by tobes** [comment]
> I think that the default should change here

Looks like the default was a `-` a `:` might be nicer but the user can set this now.  I'm not too fussed.

**Comment by egeskow** [comment]
I believe it should be ":" by default. 
There is [ISO 8061](https://en.wikipedia.org/wiki/ISO_8601) standard to time formats
Which [says](https://www.w3.org/TR/NOTE-datetime): 

```
   Complete date plus hours and minutes:
      YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
```
We can see "-" separator between year-month-date and ":" between others.

Also there is already [xkcd comics](https://xkcd.com/1179/)

**Comment by ultrabug** [comment]
Fixed thanks to @egeskow !
