### ISSUE TITLE
external_script: Trailing spaces are stripped from output

### ISSUE THREAD

**Issue by NickVst** [ultrabug/py3status#346]
When echoing out values with trailing spaces into the external_script module, trailing spaces are stripped from the output aswell. 

### Example

Given the simple script, underscores representing spaces:
 `echo "_ _ _Hello,_spaces!_ _ _" `
 the module outputs this to the bar:
`_ _ _Hello,_spaces!`  

The trailing spaces are not passed to the bar because of the code inside the external_script module.

### Issue

The issue is [at this line](https://github.com/ultrabug/py3status/blob/6e67f7be233a9c7a76938fc4ab9515a631eb283f/py3status/modules/external_script.py#L52) ( [Thanks Vorsorken for highlighting this](https://www.reddit.com/r/i3wm/comments/4pmvqt/py3status_trailing_spaces_not_showing_up/d4melly) ). Stripping characters from the output (apart from the final linebreak character) should be left up to the script writer.

**Comment by ultrabug** [comment]
Thanks for this report @NickVst ! please check the referenced commit here on issue346 branch, would that work for you ?

Cheers

**Comment by NickVst** [comment]
@ultrabug This definitely did the trick; spaces are showing up as they are supposed to do. Thanks!
