### ISSUE TITLE
Duplicate modules in conf file

### ISSUE THREAD

**Issue by Q3CPMA** [ultrabug/py3status#355]
Hello, I have
```
...
order += "sysdata ram"
order += "sysdata cpu"
...
sysdata ram
{
    cache_timeout = 1
    format = "RAM: {mem_used} / {mem_total}"
    high_treshold = "75"
    mid_treshold = "50"
}

sysdata cpu
{
    cache_timeout = 1
    format = "CPU: {cpu_usage}"
    high_treshold = "75"
    mid_treshold = "50"
}
```
in my .i3status.conf and everything works, except the colours. Basically, both sysdatas have the same colour at any moment, even if only one reaches a threshold. I'm doing something wrong, right?

**Comment by tobes** [comment]
It looks like the logic here is a bit broken.

It does do what the documentation states but that is not what the user expects.  I'll see how easy the fix is.

**Comment by ultrabug** [comment]
please @Q3CPMA could you check with the code from #356 ? Thanks @tobes !

**Comment by ultrabug** [comment]
ping, are we good here now ?

**Comment by Q3CPMA** [comment]
Nah. Retested with a git clone and two yes in parallel `..."},{"name": "sysdata", "full_text": "RAM: 0.51 / 15.57", "cached_until": 1468402349.8992772, "instance": "ram", "color": "#FF0000"},{"name": "sysdata", "full_text": "CPU: 75.32", "cached_until": 1468402349.9012043, "instance": "cpu", "color": "#FF0000"}...`

**Comment by tobes** [comment]
@Q3CPMA do you still experience this with the current master?

**Comment by Q3CPMA** [comment]
Yep. Tested with the simple conf in the pull request:
```
python py3status/__init__.py -c test.conf
...
,[{"cached_until": 1472934928.0277882, "instance": "ram", "name": "sysdata", "color": "#00FF00", "full_text": "RAM: 1.04 / 15.57"},{"cached_until": 1472934928.0292194, "instance": "cpu", "name": "sysdata", "color": "#00FF00", "full_text": "CPU: 20.49"}]
,[{"cached_until": 1472934929.0284672, "instance": "ram", "name": "sysdata", "color": "#FFFF00", "full_text": "RAM: 1.04 / 15.57"},{"cached_until": 1472934929.0297072, "instance": "cpu", "name": "sysdata", "color": "#FFFF00", "full_text": "CPU: 57.66"}]
,[{"cached_until": 1472934930.0292819, "instance": "ram", "name": "sysdata", "color": "#FF0000", "full_text": "RAM: 1.04 / 15.57"},{"cached_until": 1472934930.0304258, "instance": "cpu", "name": "sysdata", "color": "#FF0000", "full_text": "CPU: 79.00"}]
...
```

**Comment by ultrabug** [comment]
Thanks to you both for reporting & testing :+1:
