### ISSUE TITLE
Proposal: highlighting items on mouse over

### ISSUE THREAD

**Issue by chezstov** [ultrabug/py3status#358]
Is it possible to change module color if I mouse over it?

If u like this idea, i can write code to realize it.

**Comment by tobes** [comment]
Currently this is not possible.  The only events that are processed are click events.

If you have a magic way to do this I'd love to see how you manage it.

**Comment by chezstov** [comment]
Oh, i read about i3bar protocol and now i see that its have only click events.

I think I need to contact the i3wm developers and to implement other event types.

**Comment by ultrabug** [comment]
Yep sorry @chezstov but py3status is dependent on the i3bar protocol features and this one is not supported yet.
