### ISSUE TITLE
FileNotFoundError upon i3wm restart

### ISSUE THREAD

**Issue by c0m3tx** [ultrabug/py3status#367]
Whenever I restart i3wm, I get 

```py3status: (FileNotFoundError) i3status.py line 587. Please try to fix this and reload i3wm```

this message in the top part of the screen. However, py3status seems to work fine.

I would like to debug it but I must admit I have absolutely no idea where to start from, but if you need any more informations just ask me and I'll do my best to help.

Arch linux x64, downloaded git version from AUR

#### Update
Here is a small log
```
2016-07-13 15:05:11 INFO i3status spawned using config file /tmp/py3status_sf9n6n7y
2016-07-13 15:05:11 INFO loading module "sysdata" from py3status.modules.sysdata
2016-07-13 15:05:12 WARNING  (FileNotFoundError) i3status.py line 587.
2016-07-13 15:05:12 INFO Traceback
FileNotFoundError: [Errno 2] File o directory non esistente: '/tmp/py3status_sf9n6n7y'
  File "/usr/lib/python3.5/site-packages/py3status/i3status.py", line 587, in spawn_i3status
    self.py3_wrapper.log(err, 'error')
  File "/usr/lib/python3.5/tempfile.py", line 502, in __exit__
    self.close()
  File "/usr/lib/python3.5/tempfile.py", line 509, in close
    self._closer.close()
  File "/usr/lib/python3.5/tempfile.py", line 446, in close
    unlink(self.name)
```
This happens when I try to close the program, which in turn happens when i3 restarts. That file seems to contain i3status configuration but gets deleted just before raising error. Any idea?

**Comment by tobes** [comment]
do you get this using a minimal config?

```
general {
        colors = true
        interval = 5
        output_format = i3bar
}

order += "time"
```

If so what filesystem are you using for tmp?

**Comment by c0m3tx** [comment]
It happens even with the minimal config you suggested.

My `tmp` folder is on tmpfs
```none			/tmp		tmpfs		nodev,nosuid,noatime,size=1500M,mode=1777	0 0```

Can that be an issue?

**Comment by tobes** [comment]
> Can this be an issue?

I'm not sure, but something made me think that the filesystem might be involved.  It may well be a red herring.

When py3status is running do the i3status modules work eg `time`?

**Comment by c0m3tx** [comment]
> When py3status is running do the i3status modules work eg `time`?

Yes, all modules work fine. The error appears upon i3 restarting, which kills and restarts py3status, and also if I manually start py3status and then try to stop it via CTRL+C.

**Comment by tobes** [comment]
Since it's harmless. Maybe we should just catch the exception silently.

I'd still like to understand what exactly is going on.  I've looked online but can't find anything relevant :(

**Comment by RouxAntoine** [comment]
Hello i have the same problems with archlinux package but it seem not appear with pip installed version.

**Comment by RouxAntoine** [comment]
problem solve for me line 589 in file i3status.py replace : 
except Exception:
            err = sys.exc_info()[1]
            self.error = err
            self.py3_wrapper.log(err, 'error')
        self.i3status_pipe = None

by :

except Exception:
       self.py3_wrapper.report_exception('', notify_user=True)
       self.i3status_pipe = None

**Comment by tobes** [comment]
This just suppresses the error but we want other ones to be reported.

Does something like this work?  Yes it looks horrible.

```
except OSError as e:
    from errno import ENOENT
    if e.errno == ENOENT:
       self.py3_wrapper.report_exception('', notify_user=False)
   else:
       self.py3_wrapper.report_exception('', notify_user=True)
except Exception:
       self.py3_wrapper.report_exception('', notify_user=True)
self.i3status_pipe = None
```

**Comment by tobes** [comment]
@RouxAntoine what filesystem is your /tmp ?

**Comment by RouxAntoine** [comment]
My file system is ext4

**Comment by c0m3tx** [comment]
@RouxAntoine seems like the missing file is a copy of the configuration file which is created upon startup. It crashes on exit, and while I'm unable to understand what's going on, it looks like it is trying to unlink the file twice or maybe it's trying to write on the file after closing it. I'll try proposed solutions asap. Thank you all

**Comment by RouxAntoine** [comment]
thanks you to

**Comment by tobes** [comment]
> @tobes on your computer you don't have any problem with missing /tmp/file ?

Nopes, for me it's good.  I also did the commit that hit you (to improve our logging of errors).  I really don't understand the reason., we are using `tempfile` and it is within a `with` so python should behave. 

We can always stop it notifying the user and just log the exception, but I want to understand the issue first.

**Comment by RouxAntoine** [comment]
For my part i try to load "static_string" module but due to the tempfile error the module isn't load correctly. The format and color specify into config file is skip.

**Comment by ultrabug** [comment]
I found out the issue to be on a redundant cleanup of the py3status tmpfile for i3status. Since we're using a context manager we don't have to try and delete the file when reloading/exiting !

**Comment by Cypher1** [comment]
I'm getting the following error

py3status: None Please try to fix this and reload i3wm (Mod+Shift+R)
py3status: (FileNotFoundError) i3status.py line 341. Please try to fix this and reload (Mod+Shift+R)

Is this the same issue? I can open a new one if not.
Thanks

**Comment by tobes** [comment]
@Cypher1 what is your output for `py3status -v`

**Comment by Cypher1** [comment]
Output is:
```
py3status version 3.5 (python 3.5.2)
```

I think I worked out the issue though:
https://github.com/ultrabug/py3status/issues/948

Thanks
