### ISSUE TITLE
Crash on full screen

### ISSUE THREAD

**Issue by noisypixy** [ultrabug/py3status#370]
Whenever I make a window full-screen, `py3status` crashes.

```
AttributeError: 'I3status' object has no attribute 'i3status_pipe'
  File "/home/shiro/.i3/external/py3status/build/lib/py3status/__init__.py", line 26, in main
    py3.run()
  File "/home/shiro/.i3/external/py3status/build/lib/py3status/core.py", line 648, in run
    time.sleep(0.1)
  File "/home/shiro/.i3/external/py3status/build/lib/py3status/core.py", line 547, in i3bar_stop
    self.i3status_thread.suspend_i3status()
  File "/home/shiro/.i3/external/py3status/build/lib/py3status/i3status.py", line 519, in suspend_i3status
    if self.i3status_pipe:
```

I'm using `py3status` directly from the `master` branch of this repository; did a `git pull` just before creating this issue, and it was up to date.

**Comment by noisypixy** [comment]
This fixed it for me:

```diff
519c519
<         if self.i3status_pipe:
---
>         if 'i3status_pipe' in dir(self) and self.i3status_pipe:
```

**Comment by ultrabug** [comment]
Thanks a lot for reporting this and for this proposed fix @noisypixy !

I'm very surprised a full screen of a window can affect i3status (and then py3status), would you mind telling me if you're using `hide` mode on your bar ?

**Comment by noisypixy** [comment]
Nope, I'm using the "default" settings; I only changed the `status_command` (I started using i3wm yesterday, so I'm still learning).

```
bar {
        status_command ~/.i3/scripts/py3status.sh
        tray_output primary
}
```

... where `~/.i3/scripts/py3status.sh` contains:

```bash
#!/bin/bash

export PYTHONPATH="$HOME/.i3/external/py3status/build/lib"
python3 "$HOME/.i3/external/py3status/build/lib/py3status/__init__.py" -c ~/.i3/i3status.conf
```

`$HOME/.i3/external/py3status` is this repository, and I run `python3 setup.py build` to generate the `build` directory.

`~/.i3/i3status.conf` contains:

```
order += "clock"

general {
  interval = 1
}
```

... and `~/.i3/py3status/clock.py` (the only file in that directory) contains:

```python
# vim: set et ts=4 sw=4 :

import time

class Py3status:

    def clock(self):
        return {
            'full_text': time.strftime('%Y-%m-%d %H:%M:%S'),
            'cached_until': time.time() + 1,
        }
```

---

My OS is Ubuntu 16.04, up to date.

**Comment by tobes** [comment]
Ok, the reason this is happening is because `i3status_pipe` was being initialised in the wrong place.  I've added PR #371 which fixes this.

@noisypixy thanks for the excellent bug report which made finding the fix really easy.

**Comment by ultrabug** [comment]
Thanks @tobes 

@noisypixy can you confirm this works for you now ?

**Comment by noisypixy** [comment]
Yup, seems to be working fine now.

Thanks ^^

**Comment by ultrabug** [comment]
Great, thanks guys !
