### ISSUE TITLE
UnboundLocalError: local variable 'py3' referenced before assignment

### ISSUE THREAD

**Issue by aDrz** [ultrabug/py3status#373]
Hello!

After a upgrade of debian, py3status seems to be slightly unhappy. I tried to reinstall it, however I still have this error when I try to launch it:

`dude@dudladly:~$ py3status 
Traceback (most recent call last):
  File "/usr/bin/py3status", line 9, in <module>
    load_entry_point('py3status==3.0', 'console_scripts', 'py3status')()
  File "/usr/lib/python2.7/dist-packages/py3status/__init__.py", line 22, in main
    py3.report_exception('Setup error')
UnboundLocalError: local variable 'py3' referenced before assignment`

Thank you in advance for any help ! Have a good day.

**Comment by tobes** [comment]
Thanks for reporting this.

Unfortunately this error is not the actual cause of the problem.

do you have a locale set?

```
$  locale
```

**Comment by aDrz** [comment]
mhmh i see, i see... 

`locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
`

**Comment by aDrz** [comment]
Thank you, indeed it is due to my shitty locale variables...
