### ISSUE TITLE
How can I get mem_used in MB?

### ISSUE THREAD

**Issue by Rapiz1** [ultrabug/py3status#401]
How can I get mem_used in MB?

**Comment by tobes** [comment]
Unfortunately the sysdata module currently only gives memory sizes in GB.

 The code would be easy enough to change https://github.com/ultrabug/py3status/blob/master/py3status/modules/sysdata.py#L72 is where the conversion to GB happens (1 << 10) would give it in MB.

**Comment by ritze** [comment]
Maybe this can be a little bit more intuitively? When you have only 256 MB than MB is shown as unit. If you have 2 GB, than GB is shown as unit and so on…

**Comment by pferate** [comment]
I submitted a PR (#520) that will report mem_used in MB if total_mem is less than 1GB.  Otherwise, it gets reported in GB.

It would be trivial to add an option to force it to a certain unit.
