### ISSUE TITLE
Run modules in a queue

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#421]
This is a thought for a later version.

Currently each module updates itself using a Timer.   This is actually quite intensive as that is a large part of the time taken up inside module.py from what I can see from the profiling.

The suggestion is to instead run the modules from a queue.  So the modules update time would be added to a single queue managed in core.  In the main loop we would check the queue for any due updates and run them.

I think this would simplify things and reduce our running overheads.

This is just a heads up on the idea.  Feel free to shoot it down in flames.

**Comment by tobes** [comment]
actually this does no favours

**Comment by ultrabug** [comment]
Before you implemented Timers I had Queues in mind.

Mind sharing why it does no favour ?

**Comment by tobes** [comment]
Well mainly it was a bug so I was running too many things and it was slow to show the bar initially.

But you still need to have the modules run as Threads so I had little threads that I created that ran a module as needed.  But it was using more cpu (not by that much)  I've got the code so maybe in future we do something like this.

**Comment by ultrabug** [comment]
ok thanks

**Comment by tobes** [comment]
it is here as you can see it is a total work in progress type thing

https://github.com/ultrabug/py3status/compare/master...tobes:queue
