### ISSUE TITLE
[RFC] Configuration handling for modules

### ISSUE THREAD

**Issue by tablet-mode** [ultrabug/py3status#44]
So right now if you want to make your py3status modules configurable you have to handle everything in the module itself. I think it would be really nice if py3status would provide some kind of framework for that. 
It could expose some default settings to each module (e.g. the title) and if the module needs more settings it might extend the configuration. 
Maybe it could also be used to control which modules should actually be used instead of just loading everything in the py3status folder.

I think the format should be mirroring the format used for i3status.conf. It would probably make sense to place the config somewhere in either the .i3 or the py3status folder.

What are your thoughts on this?

**Comment by ultrabug** [comment]
Well mate, after a long work and testing, all our ideas have come true !

**Thank you** so much @tablet-mode for your insight, help and confidence.

Release post : http://www.ultrabug.fr/py3status-v2-0/

**Comment by tablet-mode** [comment]
Haha, my pleasure. Thank you for listening and implementing this so quickly.
