### ISSUE TITLE
"workspace_buttons no" will disable on_click AFFAIR

### ISSUE THREAD

**Issue by sphinx-wang** [ultrabug/py3status#45]
Many thanks for Ultrabug's warmly help. This issue was lighted by Ultrabug.

When "workspace_button" is set to no, the on_click function will not be triggered.

Why not keep click events when this option is enabled? Someone like me may need this feature.

Thanks.

**Comment by ultrabug** [comment]
i3 v4.9 fixed this !

  • i3bar: make click events on status blocks work with 'workspace_buttons no'
