### ISSUE TITLE
Thresholds

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#451]
Several modules have threshold and I think we should look at trying to standardize how these are treated. 

__names__

Sometime they are things like `critical`, `high_threshold`, `threshold_high`.  I think we should look at unifying them as  `threshold_xxx`

Alternatively we could fully switch to the `thresholds = {..}` approach see later

Sometime they are things like `threshold_high` other times `threshold_bad` I prefer the more descriptive names  `threshold_high`

__showing thresholds__

Currently there is no system for this that I can see. Options could be

* set `threshold_xxx = None` to disable (this would mean changing all modules)

*  Use `colors` parameter that is applied in core that strips any added colors from a modules output.  This could be added to any module or on the general section. it would work as it does for i3status. This would be my preference.

__custom thresholds__

vnstat allows fully customized thresholds which is an interesting idea as it give the user full flexibility
`coloring = { 800: "#dddd00", 900: "#dd0000", }` 

I think this is an interesting idea that we should look into more (maybe allowing named colors) eg
`thresholds = { 800: "good", 900: "degraded", 1000: '#FF00FF' }` 

__multiple thresholds__

sysdata has thresholds that it uses for more than one use cpu/memory and realistically is missing ones for cpu temp. options are

* multiple params - `threshold_cpu_high`

* using a dict `thresholds = {'cpu': {'high': 95, 'low': 50 }, 'memory': {...}}`

* split dicts `thresholds_cpu = {'high': 95, 'low': 50 }` or even `thresholds_cpu = {'high': (95, 'bad'), 'low': (50, '#FFFF00') }`

Currently there is a problem about which value to care about PR #449, #439 try to solve this by adding `threshold_value` parameter to say which is to be used.  To me this feels the wrong solution as we should just use the components functionality to allow cpu/memory/cpu temp to be colored independently. 

__helpers__

It might well be that adding some helpers into py3 would help keep consistency between modules and potentially allow us to deal with the above issues in more than one way eg

```
module {
    thresholds_cpu = {'high': (95, 'bad'), 'low': (50, 'good') }
}
```
would be the same as
```
module {
    thresholds_cpu_high = 95
    thresholds_cpu_low = 50
    color_thresholds_cpu_high = 'bad'
    color_thresholds_cpu_low = 'good'
}
```

Anyway the main thing is getting a consistent approach that we can use across all relevant modules.  We can start small and increase the features/flexibility as we go.

**Comment by tobes** [comment]
Revisiting this issue.

If we take the sysdata module as an example.  Currently it can only show one overall threshold, it picks the worst one and colors the output accordingly.

Really we want it to output something like

`sysdata <red>Mem 95%</red> <green>CPU 10%</green>`

Currently we don't have a recommended way to do this. We could do some thing around setting vars in the module say `color_cpu` and `color_mem` and then doing. 

`format = 'sysdata [\?color=mem Mem {mem_used_percent}%] [\?color=cpu CPU {cpu_usage}%]'`

Because of how the get color logic works we need to have the `color_` prefix on the modules attribute.

To me this makes sense as a way to do things, what do others think?

I'm still keen to have a more unified way of doing the thresholds.  I've got some code that moves the threshold processing into Module and Py3 so that we can do the thresholds consistently across modules but first it would be good to decide how we will make the thresholds available to users.

There is also the issue of how we inform the users of the options. @guiniol has come up with this

```
Color conditionals:
    cpu: change color based on the value of cpu_usage
    load: change color based on the value of load1
```

I prefer `Format color options:` but I think adding a new section for this is a good idea.

Another option would be a threshold section

```
Thresholds:
    cpu: percentage cpu usage
    load: percentage load
```
I think that this would have more flexibility as we need to explain what the threshold is based on as some modules may want non-percent values eg temperature.


As far as defining thresholds I'm in favor of

```
module_single_threshold {
    thresholds = [(95, 'bad'), (50, 'good')]
}

module_many_thresholds {
    thresholds = {
             'cpu: [(95, 'bad'), (50, 'good')],
             'mem: [(90, 'bad'), (60, '#f0f')],
    }
}
```

No module currently uses thresholds as a config option a module expecting multiple thresholds could still accept the list and use it for all threshold.  We could then look at deprecating/renaming the old config options, which I think we can do at least initially without users needing to change their configs.

**Comment by guiniol** [comment]
> ```
> module_single_threshold {
>         thresholds = [(95, 'bad'), (50, 'good')]
> }
> 
> module_many_thresholds {
>         thresholds = {
>                 'cpu: [(95, 'bad'), (50, 'good')],
>                 'mem: [(90, 'bad'), (60, '#f0f')],
>         }
> }
> ```

I like that. It allows for custom thresholds, it's not hard to define for users and with the proper `safe_format`, there's nothing to do in modules. There is one point to make very clear: the value has to be over the threshold to use the color. It doesn't matter if I define the threshold as `thresholds = [(95, 'bad'), (50, 'good')]` or `thresholds = [(50, 'good'), (95, 'bad')]` or even `thresholds = [(95, 'bad'), (25, 'very_good'), (50, 'good'), (75, 'degraded')]`. The thresholds are reordered and the value must be above the threshold. The default color can be defined with `(0, '#f0f')` ( or maybe `(None, '#f0f')`?).

**Comment by tobes** [comment]
Closing as threshold branch merged
