### ISSUE TITLE
netdata module uses fixed eth0 as default

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#457]
It should probably try to discover one if the system has no eth0 defined

**Comment by Battleroid** [comment]
It'd probably be possible (and best) to use something cross platform like [netifaces](https://pypi.python.org/pypi/netifaces) to get the default nic instead.

**Comment by tobes** [comment]
`cat /sys/class/net` gives them too and has no dependencies.  Seeing as we are then looking in `/proc` for the data it is probably not a huge issue if it is *nix specific (we can also add different methods like we have recently in volume_status)

`ip address show` is another option and might help finding one that is in use

**Comment by Battleroid** [comment]
I didn't think about that. Going through the interfaces in `/sys/class/net/...` would be pretty straightforward.
