### ISSUE TITLE
Module spaceapi is not python2 compatible

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#459]
No module named urllib.request in python2

**Comment by HoratioZEDU** [comment]
Perhaps doing `import six.moves.urllib.request` instead of `import urllib.request` would work. `six.moves` is cross-compatible between python 2 and python 3.

**Comment by tobes** [comment]
But that is an extra dependancy to be honest I think we should move it to use requests

**Comment by pferate** [comment]
I created #522 to resolve this using requests

**Comment by tobes** [comment]
this was fixed by #778
