### ISSUE TITLE
General color cannot be overridden in module config

### ISSUE THREAD

**Issue by Markus00000** [ultrabug/py3status#465]
In this example, `color_bad = "#ff0000"` in the `general` block cannot be overridden by `color_bad = "#ffffff"` in the `ethernet _first_` block:

    general {
            color_bad = "#ff0000"
    }
    
    ethernet _first_ {
            color_bad = "#ffffff"
    }

py3status versions:

    py3status version 3.1rc0 (python 3.5.2) => affected
    py3status version 3.0 (python 3.5.2)    => unaffected

**Comment by tobes** [comment]
@Markus00000 Thanks for finding this

**Comment by ultrabug** [comment]
Thanks @Markus00000 for reporting and @tobes for the fix !
