### ISSUE TITLE
300th star wish

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#481]
Hi @sanderboom !

You're the 300th star of `py3status` thank you very much and I hope you enjoy it :)

I wanted to celebrate this by asking you about the py3status module or feature of your dream ?
I'll be glad to do my best to make it happen for you ;)

There's no rush here, if you have none yet just leave this issue open. If you don't want this, feel free to close this issue too.

Cheers :+1:

**Comment by jakubjedelsky** [comment]
:tada::birthday::metal:

**Comment by sanderboom** [comment]
Haha great! Little did I know when I pressed the :star:! Awesome. 

To be honest I've just started out with i3, coming from Compiz. I'm very happy with i3 and trying to bend it to my wishes and needs. It seems I came to the right WM. 

I filed this feature request a couple of days ago that was immediately declined: 
https://github.com/i3/i3status/issues/161

This led me to `py3status`. I like your philosophy and the extensive docs. It made me install the Arch package `py3status-git` right away and played around with the modules.

I'm not yet in the position to have a special request. I'm still exploring the possibilities of `py3status` and i3 in general. Are there any high requested features from others? Maybe we can have a poll? :)

BTW congratulations with your 300th star :wink:

**Comment by ultrabug** [comment]
> Haha great! Little did I know when I pressed the :star:! Awesome.

Unexpected, that's the spirit :)

> This led me to py3status. I like your philosophy and the extensive docs. It made me install the Arch package py3status-git right away and played around with the modules.

Thanks, I hope you'll find it useful and fun to use !

> I'm not yet in the position to have a special request. I'm still exploring the possibilities of py3status and i3 in general. Are there any high requested features from others? Maybe we can have a poll? :)

There's absolutely no rush here, leave this issue open as long as you wish :) I've not seen any highly requested feature anyway.

Cheers

**Comment by lasers** [comment]
@sanderboom Absolutely no rush here. _[itching neck]_... No rush...

Do you have anything in mind?

If not, may I suggest a `stopwatch`? It allows people to track things... like how long you can run i3wm for... without using `i3-msg restart`... or maybe we should see if we can avoid that stopwatch reset too. I don't know. Just tossing this idea out.

stopwatch says it has been 4 months 17 days 59 minutes 37 seconds since this post. 👍

**Comment by sanderboom** [comment]
@lasers haha, fair enough! 
@ultrabug what do you think of this suggestion? Any other populair requests around? Can I make my 300star-wish into a poll?

**Comment by sanderboom** [comment]
Actually I do have a wish. This is probably a bit ambitious for a `py3status`-module, but the following would very useful to me in my daily `i3` usage: switching windows based on **most-recently-used**-data. 

The _most-recently-used_ paradigm is AFAIK in `i3` only available for switching workspaces and not for switching windows.

Suggestion on how this could be implemented in a `py3status` module:

- The module would show the number of windows on the current workspace. 
- When activated (mouse-click/shortcut) it would show a list of the window-titles in _most-recently-used-order_. 
- The on activation automatically selected option not be the currently focused window, but the most-recently-used before the current.
- Using keyboard/mouse it would be possible to select one of the windows and this window will be activated.

Interaction using keyboard (suggestion):
- Show when `Alt-Tab` is pressed;
- Keep activated as long `Alt` is down;
- Pressing `Tab` will move to the next option (`Alt` is still pressed);
- Pressing `Shift-Tab` will move to the previous option (`Alt` is still pressed);
- Release of `Alt` will activate the selected window.

You might see resemblance to elsewhere-seen WM functionality ;) 

I think this can be a very popular feature!

@ultrabug What do you think? :)

**Comment by tobes** [comment]
Your windows module sounds interesting. The keyboard stuff is currently
difficult but possible with dbus (as on occasion I have a branch that
allows this but needs work)

But the non keyboard stuff is doable but would need some thought.

I think you've got you 300 star wish

**Comment by sanderboom** [comment]
@tobes great! Really looking forward to this. If I can be of any help, please let me know (unfortunately, I'm not the most proficient in Python).

**Comment by tobes** [comment]
Hmm,

So the basics are quite easy.  We can know which windows have focus and sort of good enough work out the most recently used on a workspace.

The problem is with keyboard controls and most specifically I cannot tell when the Alt key is released if another key has fired.  I'm not sure if this should be seen as a bug in i3.

So anyhow this makes the module quite clunky/unusable.  Swapping to the last focused window on a workspace on Alt-Tab is easy the issue is anything nicer.

I'll have a think a bit more about this and maybe try to see if i3 can be patched as I think it should be seen as a bug.

**Comment by tobes** [comment]
@sanderboom 

how about 

* apps names in module (in last used order)

* `alt-tab` `shift-alt-tab` select an app in the module

* press `alt` or some other key to focus the app.

* mouse click on module focuses app

It's not quite as nice as it could be but I think that could be done.

**Comment by sanderboom** [comment]
@tobes This sounds great. 

> It's not quite as nice as it could be but I think that could be done.

I guess that you are referring to 'focus-on-release-of-alt'? Maybe this is something that is possible in a later phase?

Thanks for working on this, highly appreciated! :)

**Comment by lasers** [comment]
@sanderboom Have you found a solution to your wish?  If not, what about those?
* `rofi` https://wiki.archlinux.org/index.php/Rofi
* `sxhkd` https://wiki.archlinux.org/index.php/Sxhkd

**Comment by sanderboom** [comment]
I have to admit that currently I work with a full KDE + Plasma installation. I might return to i3 + py3status at a later moment though!

@ultrabug Congrats with the 512 :star:'s for py3status! Did you hand out more star wishes? ;)

Mine goes to whatever is now the feature in highest demand, have fun!

**Comment by ultrabug** [comment]
Hey @sanderboom thanks for replying, indeed you may come back to the light someday. If you do, you know where home is ;)

Thanks for the congratulation, it is important to mention that it is greatly more thanks to the amazing engagement of @lasers and @tobes that py3status evolves nowadays!

Since I like to keep my promises and I had to face the fact that I had a hard time to keep up to even yours at the time, I didn't pursue this tradition I'm afraid. I still feel like it was a fun idea but I don't want to have others working on something I initiated and can't keep up.

I wish you all the best and to have fun in whatever your endeavours will lead you to, thanks once again for your support !
