### ISSUE TITLE
Module imports (dependencies)

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#482]
For testing purposes it would be good if modules could be loaded even if they do not have their dependencies installed.  Doing this could also allow us to provide better information to the user on why the module cannot be run etc.

eg. `aws_bill` uses the `boto` library

We could do something like (my preference)
```
try:
    import boto
except ImportError:
    boto = None
```

or
```
def post_config_hook(self):
    import boto
```

I would also like to alter the modules method output to allow a response like
```
{'error': 'Dependency', 'requires': [{'name': 'boto', 'url': 'https://pypi.python.org/pypi/boto'}]}
```

**Comment by ultrabug** [comment]
I like the idea of course this would be better than the current "crash".

I'm not sure about the import in the post_config_hook but maybe we could enforce the check in this very function

```python
try:
    import boto
except ImportError:
    boto = None

def post_config_hook(self):
    if boto is None:
        raise bla
```

**Comment by tobes** [comment]
> ```
def post_config_hook(self):
    if boto is None:
        raise bla
```

I'm not convinced by raising an exception here.  I was looking at this and to me `self.py3.disable()` or some similarly named method could be used to prevent the module running/displaying output.

**Comment by pydsigner** [comment]
@tobes I think an exception with a good message is the best way to go, but it could be something like `raise self.py3.MissingDependencyException('The epic foobar module requires pyfoobar to be installed!')`.

**Comment by tobes** [comment]
@pydsigner ok this now makes sense to me.  It's better for py3status to decide what to do about the module, rather than each module deciding.  It's a nice and simple approach.

**Comment by tobes** [comment]
I'm going to close this as I can do the testing I wanted via ast which actually makes more sense
