### ISSUE TITLE
How to copy printed value when clicking on it ?

### ISSUE THREAD

**Issue by Spheerys** [ultrabug/py3status#502]
I'm looking for a way to copy the printed value with a left click on it.
What is the best way to do this ?

**Comment by tobes** [comment]
Currently there is no method for doing this.

A basic solution could be added without too much work but I wonder if there are other similar use cases eg sending output to other commands that would benefit from a more flexible solution.

**Comment by Spheerys** [comment]
Thanks for your answer.

My use case is the following : I'm printing an OTP auth code on the bar, which is refresh each 30 seconds. 
It could be useful for me to copy this value easily with a mouse click to past it on my website

**Comment by tobes** [comment]
now #504 is in master you can now do this.

```
my module {
    on_click 1 = 'exec echo $OUTPUT | xclip -i'
}
```

**Comment by Spheerys** [comment]
:+1:
