### ISSUE TITLE
Missing attribute in pomodoro module

### ISSUE THREAD

**Issue by promaq** [ultrabug/py3status#53]
When I was traying to run the pomodoro module i got the following error:

![pomodoro_issue](https://cloud.githubusercontent.com/assets/2600816/5696247/5c5a8f08-99c8-11e4-8562-1bbe729e5c38.png)

Placing `timer_pomodoro = 25 * 60` after [line 12](https://github.com/ultrabug/py3status/blob/master/py3status/modules/pomodoro.py#L12) in module code fixed this. But maybe there is something else worth checking.

Anyway, thanks for interesting stuff.

**Comment by ultrabug** [comment]
Hi @promaq 

Yes indeed I didn't think about letting the `timer_promodoro` be configurable and you demonstrate that I should have :) So I will correct it along with the other time related parameters of the pomodoro module.

Thanks for your feedback, and I'm glad you're enjoying py3status

**Comment by ultrabug** [comment]
done, cheers mate
