### ISSUE TITLE
Mpris: on_click error when no player

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#534]
If there is no player running and the user clicks on mpris an error occurs.  This only happens if no player is run between py3status starting and mpris being clicked

@ritze do you want to look at this it should be an easy fix.

```
AttributeError: Py3status instance has no attribute '_control_states'
  File "/home/toby/dev/py3status/py3status/module.py", line 401, in click_event
    click_method(event)
  File "/home/toby/dev/py3status/py3status/modules/mpris.py", line 541, in on_click
    if index not in self._control_states.keys():
```

**Comment by chinmaya1011** [comment]
![image](https://user-images.githubusercontent.com/36993291/87882450-b0f61100-ca1d-11ea-8e2e-7ebba8dd6c74.png)

Still happens on the current Arch package

**Comment by chinmaya1011** [comment]
Never mind, was a problem with my the service enabling mpris support for mpd. Sorry!
