### ISSUE TITLE
Multiple module instances

### ISSUE THREAD

**Issue by wlcx** [ultrabug/py3status#57]
Apologies if I'm wrong, but AFAICT there isn't a way to have multiple instances of py3status modules, like for example the stock i3status disk module:
```
order += "disk /"
order += "disk /home"

disk "/" {
        format = "%used/%total"
}

disk "/home" {
        format = "%used/%total"
}
```
I have tried configuring multiple instances of my own module, a mumble server monitor:
```
order += "mumble c"
mumble "c"{
        display_name = "foo"
        host = "bar.org.uk"
}
```
But this just results in the module not loading and the error ```py3status: loading mumble c failed (No module named 'py3status.modules.mumble')```

This ability would be nice, as it encourages reusable, modular, erm, modules.

**Comment by ultrabug** [comment]
It should work @wlcx but indeed I think we're facing a bug here. I'll extensively check this out and find a proper fix ASAP.

I'll update here when it's properly done, please bear with me, shouldn't take too long.

Thanks for reporting the issue.

**Comment by ultrabug** [comment]
Hi @wlcx, can you please test with the code at branch `issue57` as mentioned above ? I'm confident that it should fix this issue mate :)

**Comment by wlcx** [comment]
Looking great from my end! :) Thanks for a very fast fix!

**Comment by ultrabug** [comment]
Great, thanks for your feedback ! I'm waiting a bit for @Zopieux to let me know if this fixes another issue of his too and then I'll merge it to master.

**Comment by ultrabug** [comment]
I merged the branch to master, this will soon become py3status v2.2. Thanks a lot again mate.
