### ISSUE TITLE
xrandr _pos does not work with dashes in output names

### ISSUE THREAD

**Issue by mridcully** [ultrabug/py3status#593]
My outputs are named "DP-0", ..

This is my config:

xrandr {
  DP-4_pos = "right-of DP-0"
}

This does not work. I think the problem is in line 257 of xrandr.py. If I change it to remove the dashes, and update my config accordingly, it works.

pos = getattr(self, '{}_pos'.format(output.replace('-','')), '0x0')

**Comment by tobes** [comment]
This is actually looks fixed in master and 3.2

https://github.com/ultrabug/py3status/blob/3.2/py3status/modules/xrandr.py#L255

it looks like you version is out of sync for some reason

**Comment by mridcully** [comment]
The line I posted is actually the fix I made to get it to work. master and 3.2 do not work for me. Sorry for the confusion.

**Comment by tobes** [comment]
> The line I posted is actually the fix I made to get it to work.

ok, out of interest what distro are you using?

A PR would be great but if not I'll look at creating one

**Comment by mridcully** [comment]
i am using arch linux.

i am sure there is a better solution than the hack i posted before. is it possible to escape the name of the argument, e.g. "DP-4_pos" in the configuration file?

**Comment by tobes** [comment]
how does xrandr call the outputs?

can't you just do 
```
xrandr {
DP4_pos = "right-of DP-0"
}
```

xrandr sometimes has a hyphen in the name so replacing it could well break things for other users.

**Comment by mridcully** [comment]
I surrounded the output name in the config with quotes and now it works.. Without quotes it does not work because of the hyphen in the output name. Thanks!

xrandr {
  'DP-4_pos' = "right-of DP-0"
}
