### ISSUE TITLE
MPRIS: won't catch the player if the module is launched before any player

### ISSUE THREAD

**Issue by raspbeguy** [ultrabug/py3status#595]
Hi,

There is an annoying bug in the MPRIS module:

When I start (or restart) i3 and no MPRIS player is launched, then it won't catch any player. So I have to launch my player and then restart i3 in order for the player to be recognized.

I gave a look to the code and I believe that the function listing the running MPRIS players is launched in the `post_config_hook`, that would explain this behavior. I would gladly fix it in a PR, but I don't understand everything in this module and maybe there is a reason for that.

**Comment by tobes** [comment]
Yeah the starting things in post config hook probably shouldn't be
happening. I'm not sure this actually causes your problems but you may be
right.

I'm out so can't look at the code

**Comment by tobes** [comment]
@raspbeguy I think you'll need to do some debugging on this.  I think maybe you don't have pydbus or gi.repository installed right

@ritze have you any thoughts.  With the post_config_hook() stuff don't worry to much as this needs a good solution for a few other modules too.

**Comment by ritze** [comment]
I know this bug. I already mentioned it in #354 at the end. It always happens when you start a new player after launching the module started. I think the problem was starting a new thread with a dbus listener for the new player.

**Comment by tobes** [comment]
@ritze thanks for replying I can find this in #354 but that sounds a different issue to what @raspbeguy is having.

There are still two issues:

 *   Running a player with a high priority and starting a second player with a lower priority the module do nothing until the second player is closed.
*    Sometimes the module freezes.

**Comment by raspbeguy** [comment]
@tobes I have all the requirements installed.

**Comment by ritze** [comment]
I think we should rewrite the mpris module in the future™. Finding this bug cost me at least three hours. This is a typical example for grown source code.

**Comment by tobes** [comment]
this should now be fixed in master
