### ISSUE TITLE
Install fail - could not find any downloads...

### ISSUE THREAD

**Issue by erralb** [ultrabug/py3status#6]
Hi,
I am using ubuntu 12.04, and pip seems to work fine, as i successfully installed other packages, but when I try yours:

pip install py3status
Downloading/unpacking py3status
  Could not find any downloads that satisfy the requirement py3status
No distributions at all found for py3status

**Comment by XenHat** [comment]
It seems to be happening again:
````
Could not find any downloads that satisfy the requirement py3ststus
Cleaning up...
No distributions at all found for py3ststus
````
````
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
````
