### ISSUE TITLE
TypeError in PrivateBase64(Private) after recent Python update

### ISSUE THREAD

**Issue by green-tea** [ultrabug/py3status#606]
Hi,

I've been running py3status for some time on two Arch machines here, with identical configurations. After a recent update on one of the machines, which seems to have brought in Python 3.6 and a host of related updated packages, I get this error when running py3status (either the Arch packaged py3status 3.3-1 or a build of py3status-git):

> TypeError: _catch() missing 1 required positional argument: 's'

The other machine is running fine with the same configuration, and I've tested the latest git checkout there as well.

Full output:

> $ py3status__ 
> Traceback (most recent call last):
>   File "/usr/bin/py3status", line 11, in <module>
>     load_entry_point('py3status==3.3', 'console_scripts', 'py3status')()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
>     return self.resolve()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3.6/site-packages/py3status/__init__.py", line 4, in <module>
>     from py3status.core import Py3statusWrapper
>   File "/usr/lib/python3.6/site-packages/py3status/core.py", line 22, in <module>
>     from py3status.parse_config import process_config
>   File "/usr/lib/python3.6/site-packages/py3status/parse_config.py", line 23, in <module>
>     from py3status.private import PrivateHide, PrivateBase64
>   File "/usr/lib/python3.6/site-packages/py3status/private.py", line 124, in <module>
>     class PrivateBase64(Private):
> TypeError: _catch() missing 1 required positional argument: 's'

**Comment by onny** [comment]
I also have this issue, thanks for reporting it!

**Comment by tobes** [comment]
Thanks for reporting this. I'll look at fixing it as soon as I get my interweb back and can get a copy of 3.6

I think Unicode may have a new method, maybe around the format strings that is causing this.

**Comment by tobes** [comment]
@green-tea @onny 

Assuming you are not using obfuscation https://github.com/ultrabug/py3status/blob/master/doc/README.md#obfuscation can you confirm that this patch fixes the issue for you.  It is just a temp fix as I need to get 3.6 installed to do it properly and it is not yet in my distros repo

Anyhow if this works I can do a quick patch to prevent the problem you're having and then do the real fix later

```
diff --git a/py3status/parse_config.py b/py3status/parse_config.py
index 33b77c0..75b3fe1 100644
--- a/py3status/parse_config.py
+++ b/py3status/parse_config.py
@@ -20,7 +20,10 @@ from py3status.constants import (
     TZTIME_FORMAT,
 )
 
-from py3status.private import PrivateHide, PrivateBase64
+try:
+    from py3status.private import PrivateHide, PrivateBase64
+except:
+    pass
```

**Comment by tobes** [comment]
Ok, so I was able to check this using travis #610 should fix this issue but it is possible there are others further down the stack.  for some reason `dir(u'')` is very different to what you see in 3.5 no `__init__` etc.

Anyhow if you could try test that branch and let us know that would be great.

**Comment by onny** [comment]
Yep this seems to work for me, thanks!

**Comment by ultrabug** [comment]
Thanks for reporting, testing and fixing guys !
