### ISSUE TITLE
clock: Add option to display time-lessformal

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#616]
https://www.englishclub.com/vocabulary/time-telling-time.htm

```
#!/usr/bin/env bash

# I made this. meme.
# -lasers 12/23/2016

DATE="$(date '+%H%M%p')"
H="${DATE:0:2}"
M="${DATE:2:2}"
H="${H#0}"
M="${M#0}"
CH=''
CM=''

declare -a NUM=([oclock]="o'clock" [oh]='oh' [1]='one' [2]='two' [3]='three'
[4]='four' [5]='five' [6]='six' [7]='seven' [8]='eight' [9]='nine' [10]='ten'
[11]='eleven' [12]='twelve' [13]='thirteen' [14]='fourteen' [15]='fifteen'
[16]='sixteen' [17]='seventeen' [18]='eighteen' [19]='ninteen' [20]='twenty'
[30]='thirty' [40]='fourty' [50]='fifty')

addDigit(){ [[ $1 -ne 0 ]] && CM+=-${NUM[$1]} ; }

case $M in
    [1-9]) CM=${NUM[oh]} ; addDigit ${M} ;;
    1[0-9]) CM=${NUM[$M]} ;;
    2[0-9]) CM=${NUM[20]} ; addDigit ${M#2} ;;
    3[0-9]) CM=${NUM[30]} ; addDigit ${M#3} ;;
    4[0-9]) CM=${NUM[40]} ; addDigit ${M#4} ;;
    5[0-9]) CM=${NUM[50]} ; addDigit ${M#5} ;;
    0) CM=${NUM[oclock]} ;;
esac
case $H in
    [1-9]|1[0-2]) CH=${NUM[$H]} ;;
    1[3-9]|2[0-3]) CH=${NUM[$H-12]} ;;
    0) CH=${NUM[12]} ;;
esac
case $DATE in
    '1200AM') echo 'midnight' ;;
    '1200PM') echo 'afternoon' ;;
    *) echo "$CH $CM"
esac
```
EDIT: `oclock = ""`(Default) /`oclock = "o'clock"` because this script is slightly different.

**Comment by tobes** [comment]
This is very English specific.  Personally I'd like to see py3status move into a more translation friendly direction eg user errors in users language etc.

So I'd not add this sort of stuff to the clock module but that may just be my view and not shared by others

**Comment by lasers** [comment]
No problem. Feel free to close. I can stay with external_script. It would be very neat to see that along with cycling timezones. five-thirteen, three-thirteen, etc.

**Comment by tobes** [comment]
I'd not object to you creating it as a new module just not adding it to the clock one.  I think the idea is a nice one.  I also like the idea of a clock that has varying accuracy  that the user can switch between  12:37 > half past twelve > around one > lunchtime etc
