### ISSUE TITLE
dpms: Missing default format

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#617]
Missing default `format = "DPMS"`
```
Configuration parameters:
    format_off: string to display when DPMS is disabled (default 'DPMS')
    format_on: string to display when DPMS is enabled (default 'DPMS')
```
This is similar to what I was trying to muck around with `arch_updates` using...
~~`format_full`  -> `UDP: 0/0`~~
`format`  -> `UDP: 0/0`
`format_pacman` -> `UDP: 0`
`format_aur` -> `UDP: 0`

This script is missing default `format = "DPMS"`. I'm making this issue to see how it should be done with two different variables (using "DPMS: ON" and "DPMS: OFF" as example).

**Comment by tobes** [comment]
yeah this is something that needs fixing.  All modules should have `format` for their main output.  We may need to do some work in core first to make it easy to do.

**Comment by ultrabug** [comment]
My first take would be to use the deprecation feature to rename the `format_` options to `icon_on / icon_off`. Then I'd use a `format = '{icon}'` default and set the icon based on the status of DPMS

But my second take would be to use our magic formatter to handle this for us while deprecating the two options which would be better
