### ISSUE TITLE
rainbow: Add option to rainbow the modules

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#618]
If I were to do something most pointless yet most exciting thing I can imagine, I would like to rainbow the modules. Add an option to correctly split the code based on the number of contained modules in the list.... That way, each modules will start off at different color and they all cycle beautifully  like a rainbow.
```
order += "rainbow"
rainbow {
    external_script { script_path = "~/.local/bin/time-lessformal" }
    load {}
    dpms {}
    example1{}
    example2{}
}
```
As of right now, this will cycle all contained modules with same color. Not fun. :-( 

![2017-01-07__01 43 52](https://cloud.githubusercontent.com/assets/852504/21740286/e05880c8-d47a-11e6-8fd5-668715f3bf01.png)

**Comment by tobes** [comment]
I think this is a good plan.  It should be easy to do.  I'll take a look at it over then next few days.

**Comment by ultrabug** [comment]
lol I never expected a rainbow feature request :D

**Comment by lasers** [comment]
Close this?

**Comment by tobes** [comment]
thanks
