### ISSUE TITLE
screenshot: Does not always work out of the box correctly

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#625]
If you're using py3status, then the chance is that you're using i3wm. You also might be using non-gnome/non-de tools to take screenshots.

I pointed this out mainly because I had troubles with `screenshot` out of the box with no options / default screenshot options.

I tried to take my first screenshot only to be trapped in black screen (?!?). I killed9 `gnome-screenshot` in TTY to get my i3wm back.

Running this manually briefly flashes a black screen.
```
lasers~ gnome-screenshot
** Message: Unable to use GNOME Shell's builtin screenshot interface, resorting \
to fallback X11.
```

I think what happened was that `screenshot` script kept running gnome-screenshot or something else (Gnome)... Either way, it left me with a black screen. I suggest that we change default `screenshot_command` to something simple, non-gnome/non-de/non-gui... like scrot or maim.

EDIT: Need to test scrot / maim / others first too. Just a heads up.

Can use maim like... 
`save_path = "/tmp/"`
`screenshot_command = "maim"`
-> `/tmp/hz9q.jpg`

Cannot use maim like...
`# save_path = "/tmp/"`
`screenshot_command = "maim /tmp/$(date +%F-%T).png"`

EDIT: I can get screenshots appearing in ~/Pictures with `gnome-screenshot` but when `gnome-screenshot` is running (in bg), it's just freezing up everything. I then can't move and do anything until I kill `gnome-screenshot` first. Bad `gnome-screenshot` and/or xorg-related issues, I guess.

**Comment by pydsigner** [comment]
scrot would be a decent default; xfce4-screenshooter would at least be better than gnome-screenshot IMO.

**Comment by lasers** [comment]
@tobes. I would like to close this issue tonight. `scrot`?
https://wiki.archlinux.org/index.php/taking_a_screenshot

Can use `import -window root screenshot.png` instead.

**Comment by tobes** [comment]
1) can you not do
```
screenshot {
    screenshot_command = 'scrot'
}
```

2) A small change like 
```
diff --git a/py3status/modules/screenshot.py b/py3status/modules/screenshot.py
index 89c3aa4..0b811b8 100644
--- a/py3status/modules/screenshot.py
+++ b/py3status/modules/screenshot.py
@@ -32,6 +32,11 @@ import string
 import subprocess
 
 
+COMMANDS = {
+    'gnome-screenshot': 'gnome-screenshot -f',
+    'scrot': 'scrot',
+}
+
 class Py3status:
     """
     """
@@ -45,8 +50,13 @@ class Py3status:
     upload_server = 'puzzledge.org'
     upload_user = 'erol'
 
-    def __init__(self):
+    def post_config_hook(self):
         self.full_text = ''
+        if not self.screenshot_command:
+            cmd = self.py3.check_commands(COMMANDS.keys())
+            if cmd:
+                self.screenshot_command = COMMANDS[cmd]
+
 
     def on_click(self, event):
```

might meet your needs.

3) We should probably not have taken #225 as it actually makes it hard to go forward from here

4) there are 2 pending PRs regarding this module #594 and #642 both are massive and conflict with each other.  As I said before I'd like to get #592 sorted first.

**Comment by lasers** [comment]
1. I did that. This is more about picking a default/sensible screenshot tool for everybody.

    If I used `python-netifaces` to find nic card, you may suggest not to do that and instead, to get it via `/proc/something`. This is same thing... to use no (or very small) dependencies.

    When running `gnome-screenshot -f`, I didn't see any window appearing and got a screenshot in my directory. It was done in the background. So why gnome-screenshot?

    To use this module, we have to install `gnome-screenshot` which may come with lot of dependencies.

    ```
    gnome-screenshot depends on dconf, gtk3, libcanberra (may be some more...)
    Installed Size: 862.00 KiB

    scrot dpeneds on giblib
    Installed Size  : 36.00 KiB
    ```

>Longer version:
I do not use Gnome, and gnome-screenshot was not working for me when using the plugin. I like the idea behind the plugin, so I thought I would extend it to allow the screenshot command to be configurable.

Same problem I had.

Both commands does the same thing. I can stay with `screenshot_command`. I open this issue to make screenshot suck less out of the box for i3wm users, not GNOME users.

2. Sure. That will be sensible. Make the PR please? 👍
    (I already default scrot in my PR. Looking forward to that first PR sorted out first)
