### ISSUE TITLE
Nagbar appearing when receiving SIGUSR1

### ISSUE THREAD

**Issue by abello** [ultrabug/py3status#63]
Hello, 

The nagbar is showing up for me when py3status receives two consecurive (very close time-wise) SIGUSR1-s. 

For example, when I run:
killall -s SIGUSR1 py3status && killall -s SIGUSR1 py3status
the nagbar appears, with the text: "py3status: SIGUSR1 (received USR1, forcing refresh), please try to fix this and reload i3wm".

Could this be happening due to self.clear_modules_cache() raising an exception when it's called concurrently? The problem doesn't seem to happen if I comment out that line.

**Comment by Anon1234** [comment]
Yeah, it's especially annoying when i'm trying to do something like:
```
volume master {
        on_click 4 = "exec pactl -- set-sink-volume 0 +2%  && killall -USR1 py3status"
        on_click 5 = "exec pactl -- set-sink-volume 0 -2% && killall -USR1 py3status"
}
```
And result is  (when scrolling on audio status block):
![screenshot from 2015-02-09 19 33 21](https://cloud.githubusercontent.com/assets/1951834/6111580/9cd88e64-b092-11e4-93d8-cd4bd7cfc078.png)

**Comment by ultrabug** [comment]
Thanks @abello for reporting this, I think it shouldn't be too hard to fix.

@Anon1234, please note that you should not be doing this because **py3status already sends a SIGUSR1 to i3status for you upon click event** (which explains what you experience) !

**Comment by ultrabug** [comment]
Just as a heads up, I've sorted out a nice fix for this behavior which will land in py3status v2.3 later this week along with some other improvements.

Stay tuned.

**Comment by ultrabug** [comment]
Hi again @abello and @Anon1234,

I'm glad to tell you that I fixed this issue on **issue59_bis** branch, would you care to test it and report back please ?

I'll release this soon :) thanks

**Comment by abello** [comment]
Both this and issue 59 seem fixed for me!

Thanks a lot

**Comment by ultrabug** [comment]
Thx @abello, I hope you can also see a clear improvement of i3bar refresh speed upon click events ;)

**Comment by ultrabug** [comment]
Merged into master as of now, will soon become 2.3 unless I hear anything :)

**Comment by ultrabug** [comment]
py3status v2.3 has been released and fixes this issue ! :) enjoy !
