### ISSUE TITLE
Skip last separator | ""

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#632]
Example. If you put `order += "static_string"` at the end of the list, you'll get this.
`...three|DPMS| (ICONS)` MEH.

No empty format = "" at end of the list gets you this.
`...three|DPMS (ICONS)` OK.

This likely happen with all modules that can hide. It's smart enough to skip unnecessary `|` for empty formats... so we avoid `Mail: 2||9:53||`, but not at the end if "".

EDIT: I discovered this by putting `scratchpad_async` at end. I get forever `|  (ICONS`.

**Comment by tobes** [comment]
This is about how i3bar handles its input.  It adds the separator and then ignores 'empty' items.  We could look at changing what we give it as input to prevent this.

**Comment by lasers** [comment]
Can you look into this today? 👍
