### ISSUE TITLE
Module xrandr does not display correct mode at startup

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#633]
`man xrandr: If invoked without any option, it will dump the state of the outputs, showing the existing modes for each of them, with a '+' after the preferred modes and a '*' after the current .`

```
lasers~ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1200, maximum 8192 x 8192
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected primary (normal left inverted right x axis y axis)
   1920x1200     59.95 +
   1920x1080     60.00
   ...
DP-3 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+  (See this starrrr!)
   1920x1080     60.00
    ...
```
Current on `DP-3` (right monitor after using xrandr).
Prints `DP-2+DP-3`  (left+right monitor after restart).

**Comment by tobes** [comment]
So are you saying that we are not showing the correct mode?

**Comment by lasers** [comment]
Yes. Change a mode. `i3-msg restart` and it'll print initial mode, not current mode.

**Comment by lasers** [comment]
Duplicate https://github.com/ultrabug/py3status/issues/623. Closing.
