### ISSUE TITLE
whatismyip: Clickevent and online status don't work

### ISSUE THREAD

**Issue by MAGICCC** [ultrabug/py3status#635]
Hi,
when I use the ```whatismyip``` module, then I can't click on it to get the IP/online status and while in online status the bullet is staying red even when I am connected to the internet

Used adapters: wifi, lan

**Comment by levihemphill** [comment]
Can you post your i3status config?

**Comment by lasers** [comment]
I tested `whoismyip` on my end with nm-applet. No issue.

Could be a problem with device name since you mentioned adapters.
Could be a problem with firewall if you can't get an URL.
Could be a problem with missing libs, Is python-urllib at least installed?

**Comment by MAGICCC** [comment]
I just checked my config and indeed it was a config error on my side.
Cheers
