### ISSUE TITLE
mpd_status' max_width bogus?

### ISSUE THREAD

**Issue by girst** [ultrabug/py3status#636]
`max_width` doesn't seem to do what it is supposed to do. 

When displaying a long title (like `Georg Danzer - Ballade von verstecken Tschurifetzen - Re-Mastered`), the title gets _longer_, the _smaller_ the value is.

**Comment by lasers** [comment]
Can you share your `mpd status {}` section?

Just in case you did this... Use `= 10`, and not `= "10"`.

**Comment by girst** [comment]
```
mpd_status {
	hide_when_stopped = true
	state_play = ">"
	state_pause = "||"
	state_stop = "::"
	format = "%state% [[[$artist% - ]%title%]|[%file%]]"
	color_pause = "#ffffff"
	color_play = "#ffffff"
	color_stop = "#ffffff"
	max_width = 32 # inverse of length?
	cache_timeout = 0
	host = "localhost"
	port = 6900
}
```

thanks! I am using plain numbers.

**Comment by tobes** [comment]
looks like line 223 `text = text[:-self.max_width - 3] + '...'` should be `text = text[:self.max_width - 3] + '...'`

**Comment by lasers** [comment]
That works for me. `|| Musi...` Make a PR? 

If I don't have mpd running, I get `"Failed to connect to mpd!"` We may want a `format_mpd_not_running = ""`, `format_offline = ""` for this one.

There is also `text = "Failed to authenticate to mpd!"` in the code. Untested.

**Comment by girst** [comment]
> We may want a [...] format_offline = "" for this one.

that'd be great! (as someone who manually runs mpd/mopidy only occasionally, that message is rather annoying).
