### ISSUE TITLE
Not able to change i3-nagbar font as calls to it are hardcoded

### ISSUE THREAD

**Issue by randomguy** [ultrabug/py3status#665]
A quick grep through the py3status source show that there currently is no way of setting a font for calls to i3-nagbar. I see no trivial way to add a configuration option as the config file has to be compatible to i3status. Maybe it could be added as an command line option to py3status? I'll gladly try my hands on it as soon as I have some feedback as to whether such a feature is desired.

https://github.com/ultrabug/py3status/blob/master/py3status/core.py#L411

**Comment by tobes** [comment]
In theory not a problem as seems useful.

Getting the info is more of an issue.

I'd like to allow this sort of stuff via the config

```
general {
    i3_nagbar_font = ....
}

# or maybe a 
py3status {
    ...
}
```

@ultrabug what are your thoughts, adding command line options for something like this just seems overkill

**Comment by randomguy** [comment]
> @ultrabug what are your thoughts, adding command line options for something like this just seems overkill

I agree, the config would be the appropriate place.
