### ISSUE TITLE
No output from: battery_level.py.

### ISSUE THREAD

**Issue by bolens1112** [ultrabug/py3status#73]
I bet I am missing something but when I type in:
python battery_level.py
There is no output whatsoever.

Whereas if I put in:
python bitcoin_price.py
I get:
{'full_text': 'btce: 246.90$, btcde: 223.50€', 'cached_until': 1425135433.2139943}

Could someone please point me in the right direction.

I am running Arch Linux.

**Comment by ultrabug** [comment]
Hi @bolens1112 

Yes indeed this module did not support direct testing before 6 days ago : https://github.com/ultrabug/py3status/commit/52ba20d9188241a3e3666247d6865b71daebbce9

Try using py3status-git in Arch Linux or copy over the git version. It will be available as-is in the upcoming py3status v2.4

**Comment by bolens1112** [comment]
That did it.  Thank you very much!  I really like the simplicity and power of py3status keep up the good work!
