### ISSUE TITLE
decode error on py3status modules list

### ISSUE THREAD

**Issue by Philz69** [ultrabug/py3status#738]
I get `Setup Error (UnicodeDecodeError) docstrings.py line 70` everytime i use py3status modules list

Changing `with open(path) as f: ` to `with open(path, encoding='utf-8')` on line 69 of docstrings.py fixed the issue

**Comment by tobes** [comment]
@Philz69 thanks for reporting this.  Which version of py3status/python are you running?  Please post  the output of  `py3status -v`

**Comment by lasers** [comment]
Not experiencing this w/ Debian 8.7 (jessie). `py3status version 3.4 (python 2.7.9)`
Could be older version, still supported Wheezy or something else.
Please let us know. Thanks. @Philz69

**Comment by Philz69** [comment]
the output of `py3status -v` is `py3status version 3.4 ( pyhton 3.6.0 )`

**Comment by lasers** [comment]
@tobes My notes.

(P3) Not experiencing this `py3status modules list` issue w/ Arch Linux.
(P3) `py3status version 3.5rc0 (python 3.6.0)`

(P2) Not experiencing this `py3status2 modules list` issue w/ Arch Linux.
(P2) `py3status2 version 3.5rc0 (python 2.7.13)`

**Comment by tobes** [comment]
what if you `git checkout 3.4`?

**Comment by lasers** [comment]
(3.4) Same. Everything looks okay here.
(3.3) Okay on P2. Broken on P3. (Just for fun)

**Comment by tobes** [comment]
@lasers maybe it's something about installing via the aur rather than git

**Comment by Philz69** [comment]
I will try installing from git instead of the AUR

**Comment by lasers** [comment]
@tobes I tried `aur/py3status` and `aur/py3status-git`. Can't reproduce this.
@Philz69 Everything okay on `py3status-git`?

**Comment by Philz69** [comment]
You can close the issue, i havent been able to reproduce it since then, seems to have been an issue with my particular install.

**Comment by tobes** [comment]
cool, thanks for raising this issue and I'm glad it is all working now
