### ISSUE TITLE
clock: Keyboard Interrupt exception (post_config_hook)

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#744]
>py3status: post_config_hook in `clock _anon_module_6` raised an exception (KeyboardInterrupt) core.py line 481. Please try to fix this and reload i3wm (Mod+Shift+R)

... No log. I was doing `Mod+Shift+R` or something like that.

**Comment by tobes** [comment]
This is interesting.  We can probably prevent it happening.  Yeah you will have been killing py3status

**Comment by tobes** [comment]
#734 should prevent this error from being displayed to the user.  It may still appear in the logs due to the timing of processes exiting.
