### ISSUE TITLE
Add the ability to externally reload one module rather than whole status

### ISSUE THREAD

**Issue by ShareDVI** [ultrabug/py3status#745]
Keybinding some commands to sending usr1 works, but it reloads the whole bar. This leads to undesirable behavior if there are long-polled heavy modules like external scripts or net requests. Things like volume keys get pushed multiple times per second, so reloading the whole bar is a bad option.

I don't have many experience with linux programming, but perhaps a simple socket listener can be implemented, if this feature isn't considered out of scope for this project

**Comment by tobes** [comment]
I agree that this would be a useful feature.

The way I see it there are 3 options

* i3-ipc and keybindings - This would allow us to listen to bound events. It is a bit messy but we could do something like `bindsym <key> nop py3status update volume_status` It adds a dependency of i3ipc python module.  It is also unavailable except via i3 config.

* dbus - This would add another python dependency but would allow `bindsym <key> py3status-command update volume_status` as well as running directly from the cli.

* sockets - This could be done without adding any dependencies and would have the similar usage as in the dbus example but we would need to specify a port and that starts making the whole thing more complicated.  `bindsym <key> py3status-command --port 1234 update volume_status` would be a pain although having a default port might help in most cases.

* some sort of shared file - This would have similar issues to sockets how do we choose which file to use.

The last 2 options also only work for a single instance of py3status and it is possible users may want more than one instance running in multiple bars.  So I think that the dbus approach is probably the usable one.  I have an old branch that adds this but it needs some work to make it compatible with the latest changes to py3status.  It is actually for a different feature but adds what you want as a side-effect.

**Comment by ccryx** [comment]
I think just using UNIX sockets would be fine.
Each py3status instance could create a socket in $XDG_RUNTIME_DIR/py3status or some other place and py3status-cmd could send the commands it receives to each one.
The py3status instances can then decide to use ore ignore the commands.
(Not sure how well this would scale to large numbers of instances though)

**Comment by tobes** [comment]
@ccryx you're right unix domain sockets seem a good fiti and no new dependencies.

I've got a working prototype, but it'll have to wait for 3.6 as we are in feature freeze on 3.5

**Comment by lasers** [comment]
@tobes We should close this to take another step toward 100% clean roadmap.

**Comment by tobes** [comment]
Closing as now available via `py3-cmd` http://py3status.readthedocs.io/en/latest/py3-cmd.html

**Comment by ShareDVI** [comment]
@tobes You're awesome, thank you!
