### ISSUE TITLE
frame: pls expose urgent modules

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#750]
Using `github` under frame.

Display `py3status 30/32|-` in open state.
Display `+` in closed state.
Receives urgency in closed state. Still hidden.

Goal: Expose urgent module(s). `Github N1|+` ?

**Comment by tobes** [comment]
I'm not sure what we should do here

* open when some content becomes urgent.

* just show urgent content (I think this is what you are suggesting) but still be 'closed'

* make closed frame urgent till it is opened?  Would also need to watch for urgent stopping.

* something else

group also suffers from this issue so really we want something that makes sense there too.  Do we need user config of this?

**Comment by lasers** [comment]
>I'm not sure what we should do here

Let the users decide or is it too much?
```
expose_urgency = 1  # default
expose_urgency = 2  # my suggestion
expose_urgency = 3  # may require icon_urgency = "!" or "ATTN!" 
expose_urgency = 4  # something else
```
... And to deprecate _not-format_ formats.

`format_button_closed` -> `icon_closed`
`format_button_open` -> `icon_open`
`format_separator` -> `icon_separator`
`NEW?`.......................... -> `icon_urgency`

**Comment by tobes** [comment]
perhaps.

`expose_urgency` options should be strings in my opinion, `none`, `open`, `icon` etc ... I think we can get better names

I think it is good to let the user have options as long as it doesn't tie us up in knots.  From my point of view I'd like options that make sense for all containers.  currently these are `group`, `frame`, `rainbow` although these options don't really make sense for rainbow, but it ignoring them feels ok, unless we have a `suppress` option that stops content being urgent (I don't think we would want such an option anyhow as better to have the module suppress itself)

yeah the formats do need updating (group too) but again I'm not sure what we should call them `icon_button_open`? maybe `icon_open` is better.  Names is hard.

**Comment by tobes** [comment]
#799 should meet this need even if slightly different

**Comment by lasers** [comment]
I don't know what it is, but I have received several false positives for some time since we include `urgent` in the frame. Could be because `group` (inside frame) cycled urgent modules so I missed them or it's something else...

Maybe it had to do more with me opening applications instead of clicking on modules (in which the module then leave urgent alone until clicked).

**Comment by tobes** [comment]
ok, well if you can find a test case that would be great.

**Comment by lasers** [comment]
Should `group` stop cycling when there is an urgent? I think that might be it... especially when you're using `group` inside `frame`.
