### ISSUE TITLE
[clock] It is more intuitive to round clock emoji to the nearest 15 or 45 minutes

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#820]
The emoji clock is being used in many apps these days, and I noticed that py3status implementation is not consistent with the rest and is less intuitive to me.

Currently the clock emoji is not being updated until the hour exactly reaches the next step, so for example:
- 14:59 🕝

Instead, it is more intuitive to choose icon for the time rounded to the nearest 15 or 45 minutes, that is:

- 14:01 🕑
- 14:14 🕑
- 14:15 🕝
- 14:44 🕝
- 14:45 🕒
- 14:59 🕒

/cc @tobes as you created this module.

**Comment by tobes** [comment]
I'm quite happy for you to make this change, it makes sense to be consistent
