### ISSUE TITLE
xrandr_rotate: Does not always display orientation correctly

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#837]
I'm only using this module to test `use post_config_hook` PR https://github.com/ultrabug/py3status/pull/836. I ran into a bug immediately.

Module `xrandr_rotate` does not always display orientation correctly at startup.

I expected green `H` for using landscape monitor.
I received green `V` instead.

The right monitor is connected, but not in use at this moment. I get this.
```
lasers~/src/py3status/py3status/modules git:(psc-xrandr-rotate✗) python2 xrandr_rotate.py 
xrandr: Output DP-3 is not disconnected but has no modes
xrandr: Output DP-3 is not disconnected but has no modes
xrandr: Output DP-3 is not disconnected but has no modes
{'color': '#00FF00', 'full_text': u'V', 'cached_until': 1490387276.0}
```

I'm able to switch between `H` and `V` without any problem.
It's not perfect. Just a heads up.

**Comment by tobes** [comment]
@lasers this is a late reply but could you paste the output of `xrandr -q` when this problem occurs as I'd like to really understand the issue.  I think that #1105 will likely break things for some users even if it fixes it for others.

**Comment by lasers** [comment]
I hadn't run into this problem as I don't use `xrandr_rotate` regularly. I also changed graphic card going from `4` monitors to `2` monitors so it's not likely that I run into this again. I was lucky enough to face this issue and fortunate enough to log this.... so I can file a minor bug report.

1105 shouldn't break things. That `(` startswith is not correct because it'll give me horizontal when `xrandr` prints `(left...` 1105 looks okay as it loops through...
```
DP-2 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) ...
```
My `xrandr -q` during that time.. is possibly empty lines... or rather... lines not including `normal` and `inverted`... so biased if statement gives me `vertical.`

**Comment by lasers** [comment]
Instead of making a new issue, I'm reporting a bug here.

**xrandr_rotate: Does not always display orientation _correctly**

I'm only using this module to fix bugs... I ran into a bug immediately.

Module `xrandr_rotate` does not always display orientation correctly at startup.

I expected green `H` for using landscape monitor.
I received green `V` instead.

Both monitors are connected and in use at this moment. I get this.
```
DP-2 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis)...
DP-3 connected 1920x1200+1920+0 (normal left inverted right x axis y axis)...
```

I'm able to switch between `H` and `V` without any problem.
It's not perfect. Just a heads up.

-------
The bug? `xrandr_rotate` does not work correctly with `primary` due to `cut -d " " -f4'` (wrong place) and the python codes does the same thing... `[x.split()[3]` (wrong place).

I missed this bug when I was fixing up the module nicely. The `fix orien` PR works fine here post-fix. This is simply here to point out the hidden bug. Thanks. 👍
