### ISSUE TITLE
get_placeholders_list: Does not always return positions correctly

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#850]
Returning `self.py3.get_placeholders_list` gets you different positions between versions.

~~Python2 always returns positions correctly... following the placeholders.~~
Python2 always shuffles positions somewhere... not following the placeholders.
Python3 always shuffles positions somewhere... not following the placeholders.

```
# Python2 
lasers~/src/py3status/py3status/modules git:(master ✗) python2 test.py
{'color': '#00FF00', 'full_text': [u'58, 54, 255, 201'], 'cached_until': 1490494960.0}
```
```
# Python3
lasers~/src/py3status/py3status/modules git:(master ✗) python3 test.py
{'cached_until': 1490494964.0, 'color': '#00FF00', 'full_text': ['255, 58, 54, 201']}
```

Second round. Positions shuffled.

```
# Python2
lasers~/src/py3status/py3status/modules git:(master ✗) python2 test.py
{'color': '#00FF00', 'full_text': [u'57, 57, 255, 198'], 'cached_until': 1490495450.0}
```
```
# Python3
lasers~/src/py3status/py3status/modules git:(master ✗) python3 test.py 
{'cached_until': 1490495454.0, 'color': '#00FF00', 'full_text': ['198, 255, 57, 57']}
```
Third round. Positions shuffled.

```
# Python2
lasers~/src/py3status/py3status/modules git:(master ✗) python2 test.py
{'color': '#00FF00', 'full_text': [u'57, 57, 255, 198'], 'cached_until': 1490496231.0}
```
```
# Python3
lasers~/src/py3status/py3status/modules git:(master ✗) python3 test.py
{'cached_until': 1490496216.0, 'color': '#00FF00', 'full_text': ['57, 198, 58, 255']}
```
Please fix this. :-(

**Comment by tobes** [comment]
@lasers 

can you add your test.py?

**Comment by lasers** [comment]
There's no `test.py`. I'm experimenting with `nvidia_temp` module using better way to query NVIDIA properties without using RE... and with over 100+ placeholders. 😄 
Module: [nvidia-gpu-wip/modules/nvidia_temp.py](https://github.com/lasers/py3status/blob/nvidia-gpu-wip/py3status/modules/nvidia_temp.py)

**Comment by tobes** [comment]
ok, looking at things you are expecting `get_placeholders_list()` to return a list of placeholders that are in the order of the format.  This is not what it does because it only returns each placeholder once even if they are used in multiple places.  Also because we use a set in that logic there is no actual order.  I can make it return a sorted list so it is consistent and improve the docs.

For your problem you want to `fmt = self.py3.safe_format(self.format_nvidia,  info)` where info is a dict of `{placeholder_name: value}` does that help

**Comment by lasers** [comment]
We likely need this fixed first before I can whip out another `deadbeef` PR.
Can't mix placeholders with hidden placeholders.
* Duplicate `title` right away. Stuck.
* Possible duplicate `isplaying` if users customize that into their format.

Alternative choice: Run `deadbeef` command twice every loop. Ugly and not efficient.
* Run format placeholders first.
* Run `%title%ÐÉÅÐƁÊËF%isplaying` second.

**Comment by lasers** [comment]
From what I understand, this occurs because I'm returning dict directly in the terminal... often for testing purposes to make sure things works okay as expected.

This shouldn't be an issue for the working modules where values out of jumbled blob will get assigned correctly at the end. Feel free to prune this issue. Thanks.

**Comment by lasers** [comment]
This issue is very minor and non-crucial. I'm closing this one.

**Comment by tobes** [comment]
For what it's worth `py3.get_placeholder_formats_list()` returns placeholders in order.  However using this in a module where their order is important will almost always be the wrong thing to do (as explained above).  It gives the impression of being useful but actually creates a false sense of things.

So although you can now do what you wanted. Please never do as it will always be logically broken.
