### ISSUE TITLE
Time module does not accept colors in format

### ISSUE THREAD

**Issue by Zetaphor** [ultrabug/py3status#851]
`time {
	format = "[\?color=#FFFFFF \uf073 %A %B %e %Y \uf017 %l:%M:%S %p]"
}`

Attempting to use colors in the formatting of the time module result in the color tags being output directly to the modules display.

![image](https://cloud.githubusercontent.com/assets/3112763/24366444/2adb292a-12e7-11e7-8873-d9f7a12128f0.png)

Version: py3status version 3.5rc0 (python 2.7.12)

**Comment by tobes** [comment]
unfortunately the formatter so things like `[\?color=...]` is not supported in i3status modules

```
time {
    format = "\uf073 %A %B %e %Y \uf017 %l:%M:%S %p]"
    color = "#FFFFFF"
}
```
will work in this instance

**Comment by Zetaphor** [comment]
Ah, that's unfortunate :-( So I'm guessing there's no way to color only those FontAwesome icons? That's what I originally set out to do, but I wanted to make my example simpler.

**Comment by tobes** [comment]
I'd like to do that, and I think it should be possible, but it needs quite a bit of work hopefully we can get this in the 3.6 release

**Comment by lasers** [comment]
@tobes Voicing my suggestions to deal with `formatter`.

1) Make `i3status.py` module similar to `i3blocks.py` and `i3pystatus.py`.
   1) Run `i3status` process per module (or... see `ii.`).
   2) The modules goes inside `i3status` container. Use module names as placeholders.
      1) One process to rule them all.
      2) I question its useful. Is it even worth doing this for i3status?
   3) This would kill/simplify so many things in core/modules/etc.
      1) True minimal py3status code.
      2) More clean code not having to deal with i3status code.
      3) Not a i3status wrapper anymore, but more honest.
         1) Support i3status, i3block, i3pystatus, other statuses, conky, etc.
2) Redirect i3status modules to py3status modules.
   1) Use `class Meta` or post_config_hook to deal with i3status placeholders.
   2) Identical formats (?) or users can use py3status format.
   3) i3status does not have that many modules.

    ```
    order += "ipv6"               # net_iplist?
    order += "disk /"             # diskdata?
    order += "run_watch DHCP"     # file_process?
    order += "run_watch VPNC"     # file_process?
    order += "path_exists VPN"    # file_process?
    order += "wireless wlan0"     # net_iplist?
    order += "ethernet eth0"      # net_iplist?
    order += "battery 0"          # battery_status?
    order += "cpu_temperature 0"  # lm_sensors? sysdata?
    order += "cpu_usage 0"        # sysdata?
    order += "load"               # loadavg? sysdata?
    order += "time"               # clock?
    order += "tztime local"       # clock?
    ```
   4) Make `i3status.py` seems more reasonable than redirecting.

**Comment by ultrabug** [comment]
Closing, too late to be relevant now
