### ISSUE TITLE
py3status 3.5 release

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#874]
@ultrabug I think we should look at releasing 3.5 soon.

Ideally we would have finished all the format updates for this release however

* screenshot - currently no format and needs quite a bit of work due to complexities etc

* pomodoro - currently no format, #755 exists but will take a lot of time to review/cleanup and is likely to introduce bugs imho

* wifi - currently has 2 formats #863 fixes this but does not do proper deprecation currently

* wwan_status - currently has multiple formats (hard to test)

Although we could push these last modules through we would likely introduce bugs.

Also i3status modules do not use the formatter rules (I think we could allow this but it needs some core changes to avoid extra code duplication) as well as finding the pain points in doing this.

3.5 includes a number of bug fixes as well as new modules, improvements, and of course the new documentation so it would be good to get it into the hands of our users.

~~#844 should get merged as currently `deadbeef` it is reported dead~~

I'd like to fix #859 once I can reproduce the issue

[current milestone issues/PRs](https://github.com/ultrabug/py3status/milestone/4)

**Comment by maximbaz** [comment]
Let's get the plugin updates merged before the release, pretty please? 😄 
#819 (and two more will follow, that cannot be sent before this is merged), #822, #875.

I want to get back to the official build 🙂

**Comment by tobes** [comment]
They seem reasonable

**Comment by ultrabug** [comment]
I agree, and the changelog is amazingly large already. Users should benefit from 3.5 ASAP now.

I'd like your go on #820 as it LGTM. Then we'll release 3.5 as it is.

**Comment by maximbaz** [comment]
Hey guys, could you please have a look at #883 and #884 first? Especially #883, it has functional improvements and I'd love to have it in the release 🙂

**Comment by maximbaz** [comment]
All the goodies are merged, thanks guys 🎉
