### ISSUE TITLE
Multi-line format improvement

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#895]
I think if we want to win the hearts and minds of other people with this new formatter thing, we should try and remedy this cosmetic issue first.

```
# purrrrty
    uptime {
        format = '[\?if=weeks {weeks} weeks ][\?if=days {days} days ]
            [\?if=hours {hours} hours ][\?if=minutes {minutes} minutes]'
    }
```
```
# uggggh
    uptime {
        format = '[\?if=weeks {weeks} weeks ][\?if=days {days} days ]'
        format += '[\?if=hours {hours} hours ][\?if=minutes {minutes} minutes]'
    }
```
With `purrrrty`, we get `\n` in the status making it `uggggh`. We should strip them.

This makes it easy for copypasta too with longer formats. Let's imagine we have lot of `[\?color]` in this particular `mpd_status` config... maybe along with other things like `[\?width]` and `[\?soft -]`. Who know?
```
# purrrrty
    mpd_status {
        cache_timeout = 5
        format = '[\?if=weeks {weeks} weeks ][\?if=days {days} days ]
            [\?if=hours {hours} hours ][\?if=minutes {minutes} minutes]
            [\?if=hours {hours} hours ][\?if=minutes {minutes} minutes]
            [\?if=hours {hours} hours ][\?if=minutes {minutes} minutes]
            [\?if=hours {hours} hours ][\?if=minutes {minutes} minutes]'
        hide_when_stopped = True
        hide_when_paused = False
    }
```
... And is more `purrrrty` than using several `format+=`. 🐱

**Comment by tobes** [comment]
whilst I agree that the `format +=` is not the most beautiful thing in the world

a) it works at the moment 🎉 

b) with the multi-line approach we have the issue of which spaces are wanted or not.

maybe something like
```
module {
    format = 'la la la' \
             'here we keep going' \
             '  I wanted these spaces'
    param = 42
}
```
I really hate the whole `\` line continuation style in general but because we can do
```
module {
    format = 'la la la' 
    'param' = 42
}
```

we sort of need to know we are a continuation not a new config setting

**Comment by lasers** [comment]
I should put this in `formatter new feature` issue. Oh well.

I'd like to go through my formatted `whatismyip` to see what need to be changed so we can get that in asap... then I will have a good idea of how to work with other modules better.

Right now, I'm looking at `gmpdp` right now... New `flatten_dict` works okay with `_` delimiter. Am in process of merging formats, but will need `Control` placeholders to dictate if it's playing or paused... and you saw how that looks right now in `whatismyip`... It is `purrrrty uggggh` with the use of `' '` and `''`.

**Comment by tobes** [comment]
> I should put this in formatter new feature issue. Oh well.

well the multi-line stuff is about the config parser so can stay here.

> I'd like to go through my formatted whatismyip

links help so I know what you are referring to (I found it eventually)

> need Control placeholders

Well they really need #887 to fix one issue and maybe even a new bit of functionality, It is about finding a nice solution, which isn't always the first we come to and often someone looking from the outside can help point out the obvious.

Anyway I know the pace of things being done sometimes seems a bit slow but often there are dependencies or just things need to be mulled over for a while.

What was your view on the `\` approach?

**Comment by lasers** [comment]
I don't like `\` or `+\`. It feels somewhat hassle and I think we wouldn't want that for the users... We want them to set things and forget instead of programming the format.

That's why I tried the format above. `format +=` works as you said here and (days) earlier. 

Something I want to mention. If we start expose (or already expose) variables so users can do `{cache_timeout}` and stuffs, we would have to try and use same variables... which kinda can be tricky because we sometimes come up with better ones... or to make things less murky in the code.

Almost done with `gpmdp` thing, but for sake of simplicity, I included all control placeholders out of simplicity / sheer laziness as I couldn't get the last `G` to appear.

**Comment by tobes** [comment]
> Something I want to mention. If we start expose 

This is true and users should only do this at their own peril.  We should actually document them for modules that support them.  I think I may have been drinking when I added the feature...

But this is why it is good to try to find the best solution rather than just doing the dirty hack that works today.  We are getting there...

> Almost done with gpmdp thing,

you keep changing the code but line 109 looks wrong to me

**Comment by lasers** [comment]
>you keep changing the code but line 109 looks wrong to me

Heh. Cleaning up a bit, but is pretty done. I agree. It looks horrible. I finished the format merge. We need to find something better than this... What do you suggest? It is easier for me to just use `\?if=is_playing` than to figure out the `|[|[]]` thing... which I pulled it off in `whatismyip`.

**Comment by lasers** [comment]
Revisiting `\` thing... It's not a terrible idea. Shows that it's still connecting.

**Comment by lasers** [comment]
Bunch of `format +=` would just work fine and is very readable using `kdeconnector` as an example.
```
    kdeconnector {
	allow_urgent = False
	button_browse = 3
        device = 'Samsung Galaxy S6'
	format =  '[\?if=name SGS6 ]'
        format += '[\?if=is_reachable [\?if=is_trusted [\?not_zero ✉ {count} ]'
        format += '[[\?if=is_full |[\?if=is_charging ⬆|⬇][ {percent}%]]]]]'
        format += '[\?if=is_error KDEConnect|[\?if=!is_trusted (not paired)]'
        format += '[\?if=!is_reachable (not reachable)]]'
	cache_timeout = 60
    }
```
