### ISSUE TITLE
external_script broke

### ISSUE THREAD

**Issue by dakra** [ultrabug/py3status#909]
[This commit](https://github.com/ultrabug/py3status/commit/060bbaa2a41013ec6014ecfe1b4872e49800ef3c#diff-bc7ae0f900203121d70b8f1d06fc190b) broke the `external_script` module for me.

My config was:

```
format = "{output}"
script_path = "emacsclient --eval '(dakra/org-pomodoro-i3-bar-time)'"
```

When printing the exception it said `Command 'emacsclient' returned non-zero exit status 1`
but running this command itself works fine.

**Comment by lasers** [comment]
Hi there. Does it work under `master` branch with `shell=True` bit?
https://github.com/ultrabug/py3status/blob/master/py3status/modules/external_script.py
```
        output = self.py3.command_output(self.script_path, shell=True)
```

**Comment by dakra** [comment]
I used `py3status version 3.5 (python 3.6.0)` (using fish shell, if that matters)
and there the `shell=True` argument was already set and didn't work.

I can checkout the git version and see if it works there if that helps in case in any other file something changed?!

**Comment by lasers** [comment]
Do `... $(dakra/stuffs)` work there instead of `...(dakra/stuffs)`?

If that does not work, I went back to subprocess. The code is here: https://github.com/lasers/py3status/blob/subprocess-check-output/py3status/modules/external_script.py since I don't see `subprocess.check_output` bit in the code for `self.py3_command_output`.

Will wait for @tobes to resolve this.

**Comment by tobes** [comment]
@dakra thanks for reporting this issue.

A temporary solution (works for bash but fish should fine) would be to create a script that returns a successful return code and then run that.

eg
```
emacsclient --eval '(dakra/org-pomodoro-i3-bar-time)'
exit 0
```

**Comment by tobes** [comment]
This is now fixed in master
