### ISSUE TITLE
cached_until not working when testing module

### ISSUE THREAD

**Issue by pydo** [ultrabug/py3status#916]
I'm testing a simple module I wrote but the `cached_until` value doesn't seem to be respected. The public method gets called every second.

    import requests

    class Py3status:
        _api_url = 'https://min-api.cryptocompare.com/data/price?fsym={CRYPTO}&tsyms={CURRENCY}'
        pretty_format = '{CRYPTO}: {PRICE}$'
        cache_timeout = 60

        def _get_rate(self):
            resp = requests.get(self._api_url.format(CURRENCY=self.currency, CRYPTO=self.crypto))
            return resp.json()

        def display_price(self):
            data = self._get_rate()
            return {
                # 'cached_until': self.py3.time_in(self.cache_timeout),
                'cached_until': self.py3.CACHE_FOREVER,
                'full_text': self.pretty_format.format(CRYPTO=self.crypto,
                                                       PRICE=data[self.currency])
           }

    if __name__ == "__main__":
        """
        Run module in test mode.
        """
            config = {
            'always_show': True,
            'currency': 'CAD',
            'crypto': 'ETH'
        }
        from py3status.module_test import module_test
       module_test(Py3status, config=config)

Is the cached_until ignored in testing mode?

**Comment by lasers** [comment]
As far as I know, yes. Good for terminals and testing stuffs.

You can try `py3status --debug --log-file /tmp/py3status_bottom.log` in your i3 config and put this in: `self.py3.log('----- Hi there -----')` right before the return to test to see if `cache_timeout` is working correctly for you (live) using `tail -f /tmp/py3status_bottom.log`.

**Comment by pydo** [comment]
@lasers Thanks for the debugging technique, it will definitely save me time. I was able to quickly confirm that the cache was working.
