### ISSUE TITLE
[Disk module] Doesn't work with my home

### ISSUE THREAD

**Issue by FlorentDancy** [ultrabug/py3status#925]
Hi,

I'm trying to use the "Disk" module, but it doesn't seem to be documented, so here's my problem.

This works perfectly well:

```
disk "/home" {
    format = "/home : %avail / %total"
    low_threshold = "5"
    threshold_type = "gbytes_avail"
    prefix_type = "binary"
}
```

But if I replace `/home` by `/home/fld` (name of my user), it doesn't work anymore: nothing displays in my bar.
I can't find anything in the logs throwing an error, so I'm kinda clueless...

Any idea of where it could come from?
Permissions of `/home/fld`?

Thanks in advance!

**Comment by tobes** [comment]
@FlorentDancy 

The reason for this is that `/home` is the name of a mountpoint but `/home/fld` is a directory.  The disk module is actually a native i3status one rather than a py3status one.

If you `df -h` you'll see the mountpoints on your system.  As `/home/fld` is in `/home` then the data for that drive/partition will be correct as it is the same drive so same free space etc.

I hope that helps

**Comment by AnwariasEu** [comment]
You can view the source code of the module at its installation directory.
For me its /usr/lib/python3.6/site-packages/py3status/modules.
There is also an example given and all possible configuration options are listed.

You can specify a disk with the 'disk' option, but not a directory as you tried.
I suspect your '/home' is a seperate partition, this is why the module is able to print its usage.

**Comment by FlorentDancy** [comment]
Thank you both for your answers!

@tobes I understand perfectly your point, it makes sense. What I don't understand, is that I swear it used to work at some point, and now it doesn't anymore. 
So the real mystery is: how could this have been working before...? I guess we'll never know :)

@AnwariasEu unfortunately, since it's not a py3status module (as @tobes pointed out), it doesn't exist in the folder you've provided. But indeed you're right, `/home` is on a specific partition in my case.

Final question (even though I doubt it's possible): is there a way to display the usage of a certain folder compared to the disk it's onto?
My disk being `/home`, and the folder I'd like to monitor being `/home/fld` for instance.

**Comment by lasers** [comment]
>Final question (even though I doubt it's possible): is there a way to display the usage of a certain folder compared to the disk it's onto?


Inside `du-home.sh` script:
```
# ~/bin/du-home.sh
------------------------------------
#!/bin/sh
du -hs /home/fld 2>/dev/null | cut -f1
```
Inside `py3status` config:
```
external_script du {
	format = 'Home {output}'
        script_path = '~/bin/du-home.sh'
	cache_timeout = 3600  
}
order += "external_script du"
```

**Comment by FlorentDancy** [comment]
Thanks @lasers! :)

**Comment by ultrabug** [comment]
Thanks guys, closing
