### ISSUE TITLE
amixer need args

### ISSUE THREAD

**Issue by zhenyangze** [ultrabug/py3status#927]
hi.
In this file:volume_status.py, Call amixer command need with '-c1' arg in my computer.
In : `amixer -D default sget Master`
Out: `amixer: Unable to find simple control 'Master',0`

In: `amixer -D default -c1 sget Master`
Out: 
```
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 61 [70%] [-19.50dB] [on]
```

**Comment by tobes** [comment]
@zhenyangze Thanks for reporting this issue.  It looks like we need to add a way to choose the card to use.

It would be nice if it could set the correct card for output.  What is your output if you just run `amixer`  for me I get

```
$ amixer
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65532 [100%] [on]
  Front Right: Playback 65532 [100%] [on]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 65536
  Front Left: Capture 16461 [25%] [on]
  Front Right: Capture 16461 [25%] [on]
```

**Comment by zhenyangze** [comment]
I'll send it to you after I go to the office tomorrow

**Comment by zhenyangze** [comment]
```shell
$ amixer
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',1
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',2
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]

```

**Comment by lasers** [comment]
I wonder if the proper solution is to create a configuration file `~/.asoundrc` with few things so `amixer` and other `alsa` utilities tools would know what to use. It might look something like this.

```
~/.asoundrc
--------------------
pcm.!default {
        type hw
        card __ <----------- ??
        device __ <---------- ??
}
```
There is a GUI tool too if you want to try that. https://bitbucket.org/stativ/asoundconf

**Comment by zhenyangze** [comment]
Maybe, but i dont have idea why it diff from yours.
