### ISSUE TITLE
monitor dbus to autoreload modules

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#928]
Just had this idea so writing this down.

Maybe we could monitor some dbus events and automatically refresh certain modules upon them.

Like jac plug/unplug or brightness change from keyboard would directly update the affected modules.

**Comment by tobes** [comment]
This is something that I've also considered.  My thoughts.

* Do we just choose a single dbus library or do we try to support more than one?  I think just using pydbus would be easier but this might affect some users if we switch some existing dbus modules.

* I think having all dbus controlled by Py3 would allow us to provide a better user experience, make writing new modules easier, no need to run dbus thread etc.  It would probably have a more limited interface (query, run method, subscribe)

* I think a fairly simple interface could be created, but it'd need some thought.

**Comment by ultrabug** [comment]
We have that on some modules, closing
