### ISSUE TITLE
Module 'net_rate' should respect 'unit' with 'hide_if_zero = true' and in thresholds

### ISSUE THREAD

**Issue by maximbaz** [ultrabug/py3status#935]
Set the following config:

```
net_rate {
  format = '[\?color=total {total}]'
  thresholds = {'total': [(0, 'good'), (1048576, 'degraded'), (10485760, 'bad')]} # 1 MB/s, 10 MB/s
  hide_if_zero = true
  unit = 'MB/s'
}
```

----------------

1. Observe that even though the `hide_if_zero = true`, the module prints `0.0 MB/s`. This happens because the code is using the absolute rate, in bytes, not in the unit defined:

```
# if there is no rate - show last active interface, or hide
if deltas[interface]['total'] == 0:    <-------------- here
    interface = self.last_interface
    hide = self.hide_if_zero
```

The value of `deltas[interface]['total']` is maybe `309.25828642304896` (bytes) which is non-zero.

A naive fix to format with the units would be like this:

```
# if there is no rate - show last active interface, or hide
total, _ = self.py3.format_units(deltas[interface]['total'], unit=self.unit, si=self.si_units)
if total == 0:
    interface = self.last_interface
    hide = self.hide_if_zero
```

However it doesn't help, because now the total contains `0.000309` for the same value, and it is still non-zero. The reason we see `0.0 MB/s` in the output is because the value `0.000309` is then additionally formatted with the formatter `{value:.1f}`.

The desired behavior is to synchronize what I see in the bar (`0.0 MB/s`) with the behavior of `hide_if_zero = true`, so that I don't ever see module in the bar with the value of `0.0 MB/s`.

-----------

2. Notice how I had to define thresholds:

```
thresholds = {'total': [(0, 'good'), (1048576, 'degraded'), (10485760, 'bad')]} # 1 MB/s, 10 MB/s
```

Less important, but ideally this would also respect the unit and allow me to set thresholds in megabytes, like this:

```
thresholds = {'total': [(0, 'good'), (1, 'degraded'), (10, 'bad')]} # 1 MB/s, 10 MB/s
unit = 'MB/s'
```

----

It's a part of my attempts to clean the bar from non-important information 🙂. May be relevant to #934.

**Comment by tobes** [comment]
So I was looking at this and I agree the showing `0.0MB/s` is the wrong behavior here.

The problem as you point out, is that we do not have easy access to the format of the placeholder.  This is easy to add to a helper to `Py3` I did look at expanding `Py3.get_placeholders_list()` but it gets messy quickly.  So I think we want a new function to do this.  If format is `{placeholder} {placeholder:.1f} {placeholder:.2f}` what do we want to get back I'm thinking `[('placeholder', None), ('placeholder', '.1f'), ('placeholder', '.2f')]`

So I'm thinking we would need a `get_placeholder_formats_list()` can we think of a better name?

**Comment by maximbaz** [comment]
The function itself and its name make sense to me 👍

**Comment by tobes** [comment]
@maximbaz  #962 fixes the `hide_if_zero` it would be great if you could review/test that.
