### ISSUE TITLE
Sysdata model is not displaying ram usage correctly

### ISSUE THREAD

**Issue by habash1986** [ultrabug/py3status#94]
Greating from the middle east! I want to say thanks for your awesome project, and please keep up it :)

So as you can see in this ![screenshot](https://cloud.githubusercontent.com/assets/9447447/6993396/9626b940-dafb-11e4-98c1-b85a317ed21b.png), the used ram is being shown as 0.00, I tried to check the model's code, since I have a little experience in coding myself, I wasn't able to see what's wrong, the model is using the "free" command, and return the used, free, and percentage, everything seems to be working fine to me.

Here's my [i3status.conf](http://pastebin.com/eVhNu2XC) file just in case.

**Comment by ultrabug** [comment]
Hello @habash1986, I'm glad you enjoy py3status :)

This is strange indeed, would you please share your py3status and python versions (using py3status -v) ? I'll test the module once again and let you know if I have any idea.

**Comment by habash1986** [comment]
@ultrabug :)
Python version is 3.4.3-2
py3status version is 2.4
I'm using Arch as well

**Comment by ultrabug** [comment]
@habash1986, indeed there was an error in the module. It was looking for the wrong index position and was giving the used SWAP instead of RAM.

As you can see in the commit referenced above, I have fixed the issue now. Please use the module from the master branch until the next release !

Thanks

**Comment by gerritwalther** [comment]
This issue occurred to me in the last 2 weeks. I also have py3status 2.4. Unfortunately I'm on Debian and am using pypi-install and there is no option to install packages that are not from PyPI (according to the man page). Do you already have any plans to publish a new release?

**Comment by ultrabug** [comment]
@gerritwalther well I was rly busy the last couple of weeks so this delayed my plans for the 2.5 release which I'd like to contain the issue #98 RFC.

For now, I would recommend copying the fixed module file from the sources to your local import folder (default `~/.i3/py3status/`) and it will override the distribution's one with nothing to change on your side.

Would this work for you ?

**Comment by gerritwalther** [comment]
@ultrabug Awesome. Haven't thought of that :)
