### ISSUE TITLE
py3status depends on i3status

### ISSUE THREAD

**Issue by Cypher1** [ultrabug/py3status#948]
Why does py3status need i3status installed? Can we remove this dependency or at least fix the error message which currently gives: (FileNoteFound) i3status.py (line 341).

Thanks

**Comment by tobes** [comment]
i3status should only be needed if you are using one of it's modules.  Do you have any i3status modules defined in your config?

**Comment by Cypher1** [comment]
Bingo! I didn't realise that we hadn't re-implemented the "time" module.
Can we get a better error message for it still?

**Comment by tobes** [comment]
yeah, there is no reason that we can't handle this more gracefully.  Thanks for reporting it.

There is the `clock` module that may help

**Comment by Cypher1** [comment]
Thanks I'm trying to fix my preferred formatting with it now.
Cheers

**Comment by ultrabug** [comment]
Hi @Cypher1 

> Bingo! I didn't realise that we hadn't re-implemented the "time" module.
I like that you say **WE** 👍 

What message would you propose for this mate? Your user experience would be of great help in providing the best message for this case!

**Comment by Cypher1** [comment]
Hi @ultrabug 

I'm thinking something like "Error: Dependency i3bar not installed. Please install it." is all that is needed. 

If I'm not busy tomorrow morning I'll see if I can put together a pull request for it.

_Sent from my Sony F8331 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ultrabug** [comment]
Thanks @Cypher1 , please check https://github.com/ultrabug/py3status/pull/953 for this

**Comment by Cypher1** [comment]
Ack. Thanks

**Comment by tobes** [comment]
fix now in master
