### ISSUE TITLE
Lag on keyboard_layout

### ISSUE THREAD

**Issue by gideonite** [ultrabug/py3status#97]
I'm using the `keyboard_layout` module and I'm wondering why there is a lag of over five seconds when I change the keyboard layout.

I know that five seconds doesn't sound like a lot but my goal in using this module is to always know what keyboard layout I'm using. One of the reasons for this is because my i3 keybindings only work in one keyboard =(

**Comment by ultrabug** [comment]
Hello @gideonite 

As a matter a fact there is a `cache_timeout` setting in the keyboard_layout module which defaults to **10 seconds** and is responsible for the behaviour you're encountering.

In your i3status.conf, you can change this parameter to a lower value fitting your needs (2s for example) by doing :

```
keyboard_layout {
    cache_timeout = 2
}
```

However, if you want a real time update I suggest you instead use USR1 signal mechanism of py3status to force a refresh only when you actually change your keyboard layout. It will save your the command to be run in background every 2 seconds.

For this, use something like : `setxkbmap fr && killall -s USR1 py3status` on your key binding.

Hope this helps.

PS: I still need to add a note about this parameter on the keyboard_layout module docstring as mentioned by @Horgix who reported the same problem as you...

**Comment by gideonite** [comment]
@ultrabug Yes, later I found where that the `cache_timeout` was being set but I still didn't know the proper name for the property to override it. In any case, `setxkbmap fr && killall -s USR1 py3status` worked like a charm.

Along this vein though, I'm wondering in general how property names are documented. It'd be nice to be able to auto-generate documentation, or for the time being, just maintain more documentation about all the possible knobs to turn.

Thanks for help.

**Comment by ultrabug** [comment]
Yes you're right @gideonite I need to better demonstrate the CLI and document the modules options, it's in my TODO :)

FYI : `py3status modules details` from the command line will show you the details and parameters of all available modules.

**Comment by Horgix** [comment]
ultrabug wrote:
> PS: I still need to add a note about this parameter on the keyboard_layout module docstring as mentioned by @Horgix who reported the same problem as you...

I'm on the way of writing documentation for that kind of things, but am still getting a better hand on the existing code and defaults. If you already have a list of stuff that needs to be documented, maybe it's time to create a TODO file ;)

**Comment by ultrabug** [comment]
Thanks guys, just as a heads-up I've added the missing dosctring on the module ;)
