### ISSUE TITLE
external_script does not run at startup (but runs after reloading config)

### ISSUE THREAD

**Issue by jmburgos** [ultrabug/py3status#977]
Hello,

I have a call to the external_script module like this:

external_script { 
   format = "{output}"
    script_path = "/home/julian/.emacs.d/org-pomodoro-for-i3bar.sh"
    cache_timeout = 5
}

When I start i3, the bar appears but without the output of this script.  All the other modules run fine, and their output shows on the bar.  But if I reload i3's configuration (doing $mod+Shift+c), then the module runs and the output appears in the bar as it should.  Other than manually reloading the configuration every time I start i3, do you know what I could do?

Many thanks

**Comment by jmburgos** [comment]
I think I figured out.  My script makes a call to emacs to run a function.  I run emacs in daemon mode, which is started when i3 loads with the following line in the i3 configuration file:

exec --no-startup-id /opt/emacs/25.2/bin/emacs-25.2 --daemon

My script does not play nicely (gets an error) if run before the daemon is started, and I think py3status sets up the bar (and therefore runs the script) before the daemon is started.  If I reload i3's configuration file, then the scrip runs when the daemon is running and everything is fine.

**Comment by ultrabug** [comment]
Saying py3status is too fast ? ;) hehe

Glad you figured it out mate, okay for you that I close this issue ?

**Comment by jmburgos** [comment]
Yes, and sorry for the noise.  :)

**Comment by ultrabug** [comment]
No worries @jmburgos, you're home here! Thanks.
