### ISSUE TITLE
Uniformize and standardize 'format' option

### ISSUE THREAD

**Issue by Horgix** [ultrabug/py3status#98]
Looking at the current modules, I found that the option allowing users
to define a custom output format is not consistent or not present. One
thing that made me like i3status was the idea that no matter the module,
it is the `format` option that is used to customize its output. I
think it would be nice to uniformize existant modules around this idea
and to document this as the way to go for future modules.

Beside the uniformization, it offers more flexibility for users : take
for example a simple module like
[whoami](https://github.com/Ultrabug/py3status/blob/master/py3status/modules/whoami.py).
It actually only offers the possibility to display the username of the
user running py3status. No formatting of the output is possible.
Wouldn't it be nice if it defined a `format = "{username}"` in the
configuration ? It would allow the following :
- Still the same default behavior
- Definable by users in i3status.conf, to add simple things sur as
  prefix or suffix (which are definitely handy and pretty when used with
  UTF8 icons)
- By using directly `{username}` and making it available to the user,
  there isn't more parsing to do on the module side. Just return
  `format.format(username = username)` as response and it's done and
  working for both default value and possible user custom values

Details for existing modules (OK means it does it the way I described as
ideal; KO means the output is absolutely not configurable atm; links are
on the concerned lines) :
- [aws_bill](https://github.com/Horgix/py3status/blob/master/py3status/modules/aws_bill.py#L38)
  : KO; no output customization available
- [battery_level](https://github.com/Horgix/py3status/blob/master/py3status/modules/battery_level.py#L40)
  has a `format` option but with unamed parameters, which is probably
  not intuitive for users that would want to redefine it themselves
- [bitcoin_price](https://github.com/Horgix/py3status/blob/master/py3status/modules/bitcoin_price.py#L38)
  KO; doesn't have any output configuration
- [bluetooth](https://github.com/Horgix/py3status/blob/master/py3status/modules/bluetooth.py#L38)
  **OK**
- [clementine](https://github.com/Horgix/py3status/blob/master/py3status/modules/clementine.py#L16)
  KO; offers absolutely no output costomization, would probably greatly
  benefit from it and would be easily adaptable
- [dpms](https://github.com/Horgix/py3status/blob/master/py3status/modules/dpms.py#L16)
  : KO; no customization, easy to add
- [glpi](https://github.com/Horgix/py3status/blob/master/py3status/modules/glpi.py#L24)
  KO; would benefit from it
- [imap](https://github.com/Horgix/py3status/blob/master/py3status/modules/imap.py#L33)
  **OK**
- [keyboard_layout](https://github.com/Horgix/py3status/blob/master/py3status/modules/keyboard_layout.py#L54)
  KO; has no output config
- [mpd_status](https://github.com/Ultrabug/py3status/blob/master/py3status/modules/mpd_status.py#L47)
  **OK**
- [net_rate](https://github.com/Horgix/py3status/blob/master/py3status/modules/net_rate.py#L40)
  **OK**
- [netdata](https://github.com/Horgix/py3status/blob/master/py3status/modules/netdata.py#L49)
  doesn't have a configurable output but already uses .format strings
- [ns_checker](https://github.com/Horgix/py3status/blob/master/py3status/modules/ns_checker.py#L27)
  KO; satisfies itself by only displaying a defined output with "NOK" or
  "OK", and would benefit from this uniformization
- [nvidia_temp](https://github.com/Horgix/py3status/blob/master/py3status/modules/nvidia_temp.py#L35)
  offers customization of prefix and units (suffix) : would benefit from
  this standardization
- [online_status](https://github.com/Horgix/py3status/blob/master/py3status/modules/online_status.py#L29)
  allows output customization with `format_offline` and `format_online`
  as options. Having the `format_online` named `format` would be more
  intuitive and consistent
- [pingdom](https://github.com/Horgix/py3status/blob/master/py3status/modules/pingdom.py#L29)
  KO; doesn't allow any output customization and would benefit from a
  `format` option
- [player_control](https://github.com/Horgix/py3status/blob/master/py3status/modules/player_control.py#L40)
  already have customizable icons, but would probably be improved by a
  `format` for people who want to add a prefix such as an UTF8 music
  note or that kind of stuff
- [pomodoro](https://github.com/Horgix/py3status/blob/master/py3status/modules/pomodoro.py#L36)
  looks a bit tricky to adapt to this suggestion
- [rate_counter](https://github.com/Horgix/py3status/blob/master/py3status/modules/rate_counter.py#L20)
  KO; has a completely hardcoded output
- [scratchpad_counter](https://github.com/Horgix/py3status/blob/master/py3status/modules/scratchpad_counter.py#L29)
  uses a .format string and document what `{}` will be replaced for, but
  a named argument would make it uniformized with the other modules
- [screenshot](https://github.com/Horgix/py3status/blob/master/py3status/modules/screenshot.py#L31)
  KO but seems to have a really variable output depending on clicks,
  maybe not adaptable
- [spaceapi](https://github.com/Horgix/py3status/blob/master/py3status/modules/spaceapi.py#L33)
  has a partially customizable output, but would need a renaming. The
  `%H` instead of strings formatted with `{x}` is probably a limitation
  imposed by datetime
- [spotify](https://github.com/Horgix/py3status/blob/master/py3status/modules/spotify.py#L34)
  **OK**; does everything right
- [sysdata](https://github.com/Horgix/py3status/blob/master/py3status/modules/sysdata.py#L77)
  KO
- [vnstat](https://github.com/Horgix/py3status/blob/master/py3status/modules/vnstat.py#L65)
  **OK** : does it exactly as suggested
- [weather_yahoo](https://github.com/Horgix/py3status/blob/master/py3status/modules/weather_yahoo.py#L26)
  KO
- [whatismyip](https://github.com/Horgix/py3status/blob/master/py3status/modules/whatismyip.py#L30)
  looks **OK**
- [whoami](https://github.com/Ultrabug/py3status/blob/master/py3status/modules/whoami.py#L16)
  doesn't offer any way to customize the output
- [window_title](https://github.com/Horgix/py3status/blob/master/py3status/modules/window_title.py#L38)
  KO; but seems tricky to adapt
- [xrandr](https://github.com/Horgix/py3status/blob/master/py3status/modules/xrandr.py#L62)
  KO

I took the time to write such a enhancement suggestion because it
involves changing parameter names for several modules, which would not
be compatible with existing configurations. I guess it needs discussion,
and will depend on what @Ultrabug wants for this project :)

**Comment by ultrabug** [comment]
I think it's a very good idea and proposition. I agree with your points and I'm all for normalization !

I see a few key points here just like you :
* we need to preserve existing configurations for now
* some modules (and it's true for i3status too) have more than one format parameter (format_up and format_down for example)

That being said, I guess we could proceed in this order :
* start by adding a `format` parameter on all the modules you listed here where it could have no direct effect and where they have only one possible output (whoami, dpms, glpi ...)
* continue by looking at the tricky modules where some could have multiple format parameters
* finish by the modules where a user configuration breakage could happen

Would you be up to help for this big job ? If so, please limit to one PR per module and don't forget to document on the docstring (should be visible from a `py3status modules details` command)

Thanks !

**Comment by Horgix** [comment]
> I think it's a very good idea and proposition. I agree with your points and I'm all for normalization !

Glad you like it :)

> some modules (and it's true for i3status too) have more than one format parameter (format_up and format_down for example)

I think that even in these cases, there is always a predominant one (generally format_up or format_ok or whatever). We could : 1. keep format_up and format_down or 2. consider format_up is the standard, and just define format and format_down.

> That being said, I guess we could proceed in this order :

This order looks perfectly fine to me !

> Would you be up to help for this big job ?

Yeah sure, I already offered my help for this task on IRC.

> If so, please limit to one PR per module and don't forget to document on the docstring (should be visible from a py3status modules details command)

That's what I planned to do. Feel free to comment on the PR that would need modifications, I'll do my best to get it right on the first try for each module.

**Comment by Horgix** [comment]
Since Github has a markdown syntax for checklists, I'll keep track of what have been done here :

* [ ] [aws_bill](https://github.com/Horgix/py3status/blob/master/py3status/modules/aws_bill.py#L38)
  : KO; no output customization available
* [ ] [battery_level](https://github.com/Horgix/py3status/blob/master/py3status/modules/battery_level.py#L40)
  has a `format` option but with unamed parameters, which is probably
  not intuitive for users that would want to redefine it themselves
* [ ] [bitcoin_price](https://github.com/Horgix/py3status/blob/master/py3status/modules/bitcoin_price.py#L38)
  KO; doesn't have any output configuration
* [X] [bluetooth](https://github.com/Horgix/py3status/blob/master/py3status/modules/bluetooth.py#L38)
  **OK**
* [ ] [clementine](https://github.com/Horgix/py3status/blob/master/py3status/modules/clementine.py#L16)
  KO; offers absolutely no output costomization, would probably greatly
  benefit from it and would be easily adaptable
* [ ] [dpms](https://github.com/Horgix/py3status/blob/master/py3status/modules/dpms.py#L16)
  : KO; no customization, easy to add
* [ ] [glpi](https://github.com/Horgix/py3status/blob/master/py3status/modules/glpi.py#L24)
  KO; would benefit from it
* [X] [imap](https://github.com/Horgix/py3status/blob/master/py3status/modules/imap.py#L33)
  **OK**
* [ ] [keyboard_layout](https://github.com/Horgix/py3status/blob/master/py3status/modules/keyboard_layout.py#L54)
  KO; has no output config
* [X] [mpd_status](https://github.com/Ultrabug/py3status/blob/master/py3status/modules/mpd_status.py#L47)
  **OK**
* [X] [net_rate](https://github.com/Horgix/py3status/blob/master/py3status/modules/net_rate.py#L40)
  **OK**
* [ ] [netdata](https://github.com/Horgix/py3status/blob/master/py3status/modules/netdata.py#L49)
  doesn't have a configurable output but already uses .format strings
* [ ] [ns_checker](https://github.com/Horgix/py3status/blob/master/py3status/modules/ns_checker.py#L27)
  KO; satisfies itself by only displaying a defined output with "NOK" or
  "OK", and would benefit from this uniformization
* [ ] [nvidia_temp](https://github.com/Horgix/py3status/blob/master/py3status/modules/nvidia_temp.py#L35)
  offers customization of prefix and units (suffix) : would benefit from
  this standardization
* [ ] [online_status](https://github.com/Horgix/py3status/blob/master/py3status/modules/online_status.py#L29)
  allows output customization with `format_offline` and `format_online`
  as options. Having the `format_online` named `format` would be more
  intuitive and consistent
* [ ] [pingdom](https://github.com/Horgix/py3status/blob/master/py3status/modules/pingdom.py#L29)
  KO; doesn't allow any output customization and would benefit from a
  `format` option
* [ ] [player_control](https://github.com/Horgix/py3status/blob/master/py3status/modules/player_control.py#L40)
  already have customizable icons, but would probably be improved by a
  `format` for people who want to add a prefix such as an UTF8 music
  note or that kind of stuff
* [ ] [pomodoro](https://github.com/Horgix/py3status/blob/master/py3status/modules/pomodoro.py#L36)
  looks a bit tricky to adapt to this suggestion
* [ ] [rate_counter](https://github.com/Horgix/py3status/blob/master/py3status/modules/rate_counter.py#L20)
  KO; has a completely hardcoded output
* [ ] [scratchpad_counter](https://github.com/Horgix/py3status/blob/master/py3status/modules/scratchpad_counter.py#L29)
  uses a .format string and document what `{}` will be replaced for, but
  a named argument would make it uniformized with the other modules
* [ ] [screenshot](https://github.com/Horgix/py3status/blob/master/py3status/modules/screenshot.py#L31)
  KO but seems to have a really variable output depending on clicks,
  maybe not adaptable
* [ ] [spaceapi](https://github.com/Horgix/py3status/blob/master/py3status/modules/spaceapi.py#L33)
  has a partially customizable output, but would need a renaming. The
  `%H` instead of strings formatted with `{x}` is probably a limitation
  imposed by datetime
* [X] [spotify](https://github.com/Horgix/py3status/blob/master/py3status/modules/spotify.py#L34)
  **OK**; does everything right
* [ ] [sysdata](https://github.com/Horgix/py3status/blob/master/py3status/modules/sysdata.py#L77)
  KO
* [X] [vnstat](https://github.com/Horgix/py3status/blob/master/py3status/modules/vnstat.py#L65)
  **OK** : does it exactly as suggested
* [ ] [weather_yahoo](https://github.com/Horgix/py3status/blob/master/py3status/modules/weather_yahoo.py#L26)
  KO
* [ ] [whatismyip](https://github.com/Horgix/py3status/blob/master/py3status/modules/whatismyip.py#L30)
  looks **OK**
* [ ] [whoami](https://github.com/Ultrabug/py3status/blob/master/py3status/modules/whoami.py#L16)
  doesn't offer any way to customize the output
* [ ] [window_title](https://github.com/Horgix/py3status/blob/master/py3status/modules/window_title.py#L38)
  KO; but seems tricky to adapt
* [ ] [xrandr](https://github.com/Horgix/py3status/blob/master/py3status/modules/xrandr.py#L62)
  KO

**Comment by Horgix** [comment]
@ultrabug : is it possible to assign the issue to me since I'm taking care of it, or is it only for project collaborators on Gibhut ?

Also, I just checked sysdata as OK since df16bcbfacafa1b3f4d3f4cbde45262b72d61751 added what  I suggested

**Comment by ultrabug** [comment]
@Horgix no I cannot assign to anyone else (yes must be for collaborators) sorry.

Thx for updating the list wrt sysdata.

**Comment by ultrabug** [comment]
pomodoro module OK thanks to @schober-ch !

**Comment by ultrabug** [comment]
keyboard_layout module OK

**Comment by Horgix** [comment]
Checked up in the list :

- pomodoro
- keyboard_layout
- dpms

I supposed that new modules were compliant thanks to @ultrabug vigilance :)

**Comment by ChoiZ** [comment]
I'll update clementine in few days ;-)

**Comment by lasers** [comment]
What do you think about using `{current}` to almost everything (well, not everything), but if it's possible... We use it just the same way we do with `format = ""`

DPMS could use it.  `{state}`
Taskwarrior could use it. `{task}`
window_title `{title}`
window_title_async `{title}`
scratchpad_counter `{}` or `{counter}`
scratchpad_async `{}` or `{counter}`
etc....

I put one in Clementine just now. `N/A`... now `{current}`
Hamster uses `{current}` already.
gpmdp uses `{current}` already.

I admit I like this one. Thoughts?

**Comment by lasers** [comment]
Gah. Pomodoro module technically not OK.

`format = "Poo / {bar} / {ss} / {mm} / {mmss}"`
`Pomodoro (Poo / ▉▉▉▉▉ / 1499 / 25 / 24:59)`

**Comment by tobes** [comment]
> I admit I like this one. Thoughts?

Thanks for all your efforts with pushing this forward.

As I've said before the main thing is that any changes should be transparent to all users.  So basically if the default is nasty we are sort of stuck with that.  The same with placeholders (yes we can rename them etc but that starts a world of pain)

`{current}` makes sense for media players as it is the currently playing track, and hamster is current task or some such.

Really the placeholders should make sense to the user without reading the documentation

> Gah. Pomodoro module technically not OK.

Pomodoro is fun but probably one of the last to fix up

**Comment by lasers** [comment]
I see `timer` "...is more of a demo of a composite. This is not format friendly. I was wondering if you want to update `timer.py` to show others how to use composite and format together.

It might look something like...
```
format = 'Timer {timer}'
format_timer = '{hh}:{mm}:{ss}'
color = '#CCCCCC'
```
Changes color for everything here. Seeing how we're using `composite` here, information does not go inside `full_text`. If we do, we get this...
```
2017-03-04 06:25:56 INFO Traceback
Exception: conflicting "full_text" and "composite" in response
  File "/usr/lib/python3.6/site-packages/py3status-3.5rc0-py3.6.egg/py3status/module.py", line 685, in run
    self.process_composite(response)
  File "/usr/lib/python3.6/site-packages/py3status-3.5rc0-py3.6.egg/py3status/module.py", line 314, in process_composite
    raise Exception(err)
```
This is a nice clash. Poking you for a solution.
Should be able to customize/omit `Timer` and colons.

**Comment by tobes** [comment]
@lasers Thanks for the report.

I think that maybe we should close this issue and start a new one as we have made quite a lot of progress since this was first opened and it might be good to have a fresh review of outstanding modules etc.  If you create a new one then I'll close this.

Once again thanks for your help and of course @Horgix for doing the initial push on this herculean effort

**Comment by lasers** [comment]
Do @Horgix want to review all modules again? 👍 

I would like to focus on getting most of pending PRs such as...
* `pomodoro` (This!) 
* revised `bitcoin_price`
* new `bluetooth` dbus goes in first, then I fix new `bluetooth` format
* etc...
... in before somebody go through the review process again.

Fo sho, we got this in the bag. More than enough modules has been made format-friendly. Bugs/exceptions has been ran into... which some of them has been fixed too. 🥂 

I could make a new list. Wanted to see status on `bluetooth` and to keep everything here.

**Comment by tobes** [comment]
> I could make a new list. 

this would be great

I've got the following but I suspect there are more where the format needs improving but this is what I'm aware off.

`bitcoin_price` - no format

`mpd_status` - has format but does not use py3.safe_format() - complexity due to '%' formatting issue

`netdata`- no format - currently 2 methods should be combined into one imho

`pingdom` - no format

`rainbow` - no format

`screenshot` - no format - needs though due to conflicting needs (backward compatibility/usability)

`spaceapi` - no format

`timer` - no format - needs some thought

`wifi` - no format - has alternatives

`wwan_status` - no format - has alternatives

`xsel` - no format

others that might need some work

`pomodoro` - much is hardwired

`bluetooth` - needs cleanup

Do we have any others?

**Comment by schober-ch** [comment]
Hey. I'm not really up-to-date with format changes in py3status and only using the pomodoro timer as some kind of nice-to-be-there-thing, but as @tobes commented:

> Pomodoro is fun but probably one of the last to fix up

I can look into the module, but due to usual time constraints it won't be soon.

**Comment by ultrabug** [comment]
A long work went on, @lasers did a great job, thanks!
