### ISSUE TITLE
Missing left curly bracket with existing config

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#987]
**Missing right curly bracket**

```
    static_string {


order += static_string
```
🍏 👍 *CONFIG ERROR*
🍏 👍 **OK!**

```
    static_string {
        button_fake = 1

order += static_string
```
🍏 👍 *CONFIG ERROR*
🍏 👍 **OK!**

**Missing left curly bracket**

 ```
    static_string

    }
order += static_string
```
🍏 👍 *CONFIG ERROR*
🍏 👍 **OK!**
```
static_string
    button_example = 1
}
order += static_string
```
🍎 👎 *Error: status_command process exited unexpectedly (exit 1)*
🍎 👎 **NOT OK!**

I accidentally this bug when I accidentally the bracket.
EDIT: Fixed examples.

**Comment by tobes** [comment]
thanks for reporting this.

In future can you add complete examples that cause the issue rather than pseudo examples as that saves time.  A working example config that triggers the bug is
```
order += static_string

static_string 
    format = 'py3status test'
}
```

**Comment by lasers** [comment]
Fixed via https://github.com/ultrabug/py3status/pull/990
