### ISSUE TITLE
Documentation should be easier to find

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#992]
currently finding the docs involves scrolling down the main landing page for py3status it would be good to have a link to https://py3status.readthedocs.io/ similar to done at https://github.com/acrisci/i3ipc-python

**Comment by lasers** [comment]
@ultrabug This sounds like a good plan. Maybe link to Github version too, but I think some links are just going to redirect to `ReadtheDocs`... Anyhow, we should get this done soon.

@tobes  http://py3status.readthedocs.io sends people to `3.5` right now.
Use http://py3status.readthedocs.io/en/latest or update the `readthedocs` default version (?)

**Comment by tobes** [comment]
> @tobes http://py3status.readthedocs.io sends people to 3.5 right now.

thanks, now points to 3.6

**Comment by lasers** [comment]
@ultrabug Pinging for attention on this issue.

**Comment by ultrabug** [comment]
done! thx

**Comment by lasers** [comment]
@tobes  http://py3status.readthedocs.io sends people to `3.6` right now.
Use http://py3status.readthedocs.io/en/latest or update the `readthedocs` default version (?)
